; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27054.0 

	TITLE	D:\repo\MSX-master\MSX\blueMSX-DPI\Src\Board\Coleco.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	??_C@_05IEEKDPFI@V9938@				; `string'
PUBLIC	??_C@_05IAMHEDOK@V9958@				; `string'
PUBLIC	??_C@_08IBFDMDNO@TMS9929A@			; `string'
PUBLIC	??_C@_08HEDIBBLA@TMS99x8A@			; `string'
;	COMDAT ??_C@_08HEDIBBLA@TMS99x8A@
CONST	SEGMENT
??_C@_08HEDIBBLA@TMS99x8A@ DB 'TMS99x8A', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_08IBFDMDNO@TMS9929A@
CONST	SEGMENT
??_C@_08IBFDMDNO@TMS9929A@ DB 'TMS9929A', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_05IAMHEDOK@V9958@
CONST	SEGMENT
??_C@_05IAMHEDOK@V9958@ DB 'V9958', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_05IEEKDPFI@V9938@
CONST	SEGMENT
??_C@_05IEEKDPFI@V9938@ DB 'V9938', 00H			; `string'
CONST	ENDS
PUBLIC	_colecoCreate
PUBLIC	??_C@_0M@NIMHLJHA@colecoJoyIo@			; `string'
PUBLIC	??_C@_0L@KJCEGGJD@sliderVal0@			; `string'
PUBLIC	??_C@_0L@LADPFHNC@sliderVal1@			; `string'
PUBLIC	??_C@_0M@GOOIHBOG@joyIntState@			; `string'
EXTRN	_vdpCreate:PROC
EXTRN	_vdpGetRefreshRate:PROC
EXTRN	_mixerReset:PROC
EXTRN	_machineInitialize:PROC
EXTRN	_boardInit:PROC
EXTRN	_boardCaptureUInt8:PROC
EXTRN	_boardGetMixer:PROC
EXTRN	_boardTimerCreate:PROC
EXTRN	_boardTimerDestroy:PROC
EXTRN	_boardTimerAdd:PROC
EXTRN	_boardTimerCheckTimeout:PROC
EXTRN	_boardInsertExternalDevices:PROC
EXTRN	_boardRemoveExternalDevices:PROC
EXTRN	_r800Create:PROC
EXTRN	_r800Destroy:PROC
EXTRN	_r800SetFrequency:PROC
EXTRN	_r800Reset:PROC
EXTRN	_r800SetInt:PROC
EXTRN	_r800ClearInt:PROC
EXTRN	_r800SetNmi:PROC
EXTRN	_r800ClearNmi:PROC
EXTRN	_r800SetDataBus:PROC
EXTRN	_r800Execute:PROC
EXTRN	_r800StopExecution:PROC
EXTRN	_r800SetTimeoutAt:PROC
EXTRN	_r800SetBreakpoint:PROC
EXTRN	_r800ClearBreakpoint:PROC
EXTRN	_r800GetTimeTrace:PROC
EXTRN	_r800LoadState:PROC
EXTRN	_r800SaveState:PROC
EXTRN	_r800DebugCreate:PROC
EXTRN	_r800DebugDestroy:PROC
EXTRN	_sn76489Create:PROC
EXTRN	_sn76489Destroy:PROC
EXTRN	_sn76489Reset:PROC
EXTRN	_sn76489WriteData:PROC
EXTRN	_sn76489LoadState:PROC
EXTRN	_sn76489SaveState:PROC
EXTRN	_deviceManagerCreate:PROC
EXTRN	_deviceManagerDestroy:PROC
EXTRN	_deviceManagerReset:PROC
EXTRN	_deviceManagerLoadState:PROC
EXTRN	_deviceManagerSaveState:PROC
EXTRN	_deviceManagerRegister:PROC
EXTRN	_deviceManagerUnregister:PROC
EXTRN	_saveStateOpenForRead:PROC
EXTRN	_saveStateOpenForWrite:PROC
EXTRN	_saveStateClose:PROC
EXTRN	_saveStateGet:PROC
EXTRN	_saveStateSet:PROC
EXTRN	_slotManagerCreate:PROC
EXTRN	_slotManagerDestroy:PROC
EXTRN	_slotManagerReset:PROC
EXTRN	_slotLoadState:PROC
EXTRN	_slotSaveState:PROC
EXTRN	_slotWrite:PROC
EXTRN	_slotRead:PROC
EXTRN	_slotMapRamPage:PROC
EXTRN	_slotSetSubslotted:PROC
EXTRN	_ledSetCapslock:PROC
EXTRN	_ioPortRegister:PROC
EXTRN	_ioPortUnregister:PROC
EXTRN	_ioPortReset:PROC
EXTRN	_ioPortRead:PROC
EXTRN	_ioPortWrite:PROC
EXTRN	_cartridgeSetSlotInfo:PROC
EXTRN	_joystickPortUpdateHandlerRegister:PROC
EXTRN	_joystickPortUpdateHandlerUnregister:PROC
EXTRN	_colecoJoystickCreate:PROC
EXTRN	_colecoSuperActionCreate:PROC
EXTRN	_colecoSteeringWheelCreate:PROC
EXTRN	_boardSysTime:DWORD
EXTRN	_eventMap:BYTE
_BSS	SEGMENT
_sn76489 DD	01H DUP (?)
_r800	DD	01H DUP (?)
_joyDevice DD	02H DUP (?)
_joyDeviceHandle DD 01H DUP (?)
_joyMode DD	01H DUP (?)
_rollerTimer DD	01H DUP (?)
_joyIntState DD	01H DUP (?)
_BSS	ENDS
;	COMDAT ??_C@_0M@GOOIHBOG@joyIntState@
CONST	SEGMENT
??_C@_0M@GOOIHBOG@joyIntState@ DB 'joyIntState', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0L@LADPFHNC@sliderVal1@
CONST	SEGMENT
??_C@_0L@LADPFHNC@sliderVal1@ DB 'sliderVal1', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0L@KJCEGGJD@sliderVal0@
CONST	SEGMENT
??_C@_0L@KJCEGGJD@sliderVal0@ DB 'sliderVal0', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0M@NIMHLJHA@colecoJoyIo@
CONST	SEGMENT
??_C@_0M@NIMHLJHA@colecoJoyIo@ DB 'colecoJoyIo', 00H	; `string'
CONST	ENDS
_DATA	SEGMENT
_sliderVal DB	030H
	DB	030H
_DATA	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\board\coleco.c
;	COMDAT _getTimeTrace
_TEXT	SEGMENT
_offset$ = 8						; size = 4
_getTimeTrace PROC					; COMDAT

; 344  :     return r800GetTimeTrace(r800, offset);

	push	DWORD PTR _offset$[esp-4]
	push	DWORD PTR _r800
	call	_r800GetTimeTrace
	add	esp, 8

; 345  : }

	ret	0
_getTimeTrace ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\board\coleco.c
;	COMDAT _loadState
_TEXT	SEGMENT
_loadState PROC						; COMDAT

; 336  :     r800LoadState(r800);

	push	DWORD PTR _r800
	call	_r800LoadState

; 337  :     boardInit(&r800->systemTime);

	push	DWORD PTR _r800
	call	_boardInit

; 338  :     deviceManagerLoadState();

	call	_deviceManagerLoadState

; 339  :     slotLoadState();

	call	_slotLoadState

; 340  :     sn76489LoadState(sn76489);

	push	DWORD PTR _sn76489
	call	_sn76489LoadState
	add	esp, 12					; 0000000cH

; 341  : }

	ret	0
_loadState ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\board\coleco.c
;	COMDAT _saveState
_TEXT	SEGMENT
_saveState PROC						; COMDAT

; 328  :     r800SaveState(r800);

	push	DWORD PTR _r800
	call	_r800SaveState

; 329  :     sn76489SaveState(sn76489);

	push	DWORD PTR _sn76489
	call	_sn76489SaveState
	add	esp, 8

; 330  :     deviceManagerSaveState();

	call	_deviceManagerSaveState

; 331  :     slotSaveState();

	jmp	_slotSaveState
_saveState ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\board\coleco.c
;	COMDAT _getRefreshRate
_TEXT	SEGMENT
_getRefreshRate PROC					; COMDAT

; 323  :     return vdpGetRefreshRate();

	jmp	_vdpGetRefreshRate
_getRefreshRate ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\board\coleco.c
;	COMDAT _destroy
_TEXT	SEGMENT
_destroy PROC						; COMDAT

; 312  :     boardRemoveExternalDevices();

	call	_boardRemoveExternalDevices

; 313  : 
; 314  :     sn76489Destroy(sn76489);

	push	DWORD PTR _sn76489
	call	_sn76489Destroy

; 315  :     r800DebugDestroy();

	call	_r800DebugDestroy

; 316  :     slotManagerDestroy();

	call	_slotManagerDestroy

; 317  :     deviceManagerDestroy();

	call	_deviceManagerDestroy

; 318  :     r800Destroy(r800);

	push	DWORD PTR _r800
	call	_r800Destroy
	add	esp, 8

; 319  : }

	ret	0
_destroy ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\board\coleco.c
; File d:\repo\msx-master\msx\bluemsx-dpi\src\board\board.h
; File d:\repo\msx-master\msx\bluemsx-dpi\src\board\coleco.c
; File d:\repo\msx-master\msx\bluemsx-dpi\src\board\board.h
; File d:\repo\msx-master\msx\bluemsx-dpi\src\board\coleco.c
;	COMDAT _reset
_TEXT	SEGMENT
_reset	PROC						; COMDAT
; File d:\repo\msx-master\msx\bluemsx-dpi\src\board\board.h

; 165  :     return *boardSysTime;

	mov	eax, DWORD PTR _boardSysTime
; File d:\repo\msx-master\msx\bluemsx-dpi\src\board\coleco.c

; 292  : {

	push	esi
; File d:\repo\msx-master\msx\bluemsx-dpi\src\board\board.h

; 165  :     return *boardSysTime;

	mov	esi, DWORD PTR [eax]
; File d:\repo\msx-master\msx\bluemsx-dpi\src\board\coleco.c

; 295  :     slotManagerReset();

	call	_slotManagerReset

; 296  : 
; 297  :     if (r800 != NULL) {

	mov	eax, DWORD PTR _r800
	test	eax, eax
	je	SHORT $LN2@reset

; 298  :         r800Reset(r800, systemTime);

	push	esi
	push	eax
	call	_r800Reset
	add	esp, 8
$LN2@reset:

; 299  :     }
; 300  : 
; 301  :     if (sn76489 != NULL) {

	mov	eax, DWORD PTR _sn76489
	pop	esi
	test	eax, eax
	je	SHORT $LN3@reset

; 302  :         sn76489Reset(sn76489);

	push	eax
	call	_sn76489Reset
	add	esp, 4
$LN3@reset:

; 303  :     }
; 304  :     
; 305  :     ledSetCapslock(0);

	push	0
	call	_ledSetCapslock
	add	esp, 4

; 306  : 
; 307  :     deviceManagerReset();

	jmp	_deviceManagerReset
_reset	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\board\coleco.c
;	COMDAT _colecoJoyIoCreate
_TEXT	SEGMENT
_callbacks$ = -16					; size = 16
_colecoJoyIoCreate PROC					; COMDAT

; 264  : {

	sub	esp, 16					; 00000010H
	push	esi

; 265  :     DeviceCallbacks callbacks = { colecoJoyIoDestroy,   colecoJoyIoReset, 

	mov	DWORD PTR _callbacks$[esp+20], OFFSET _colecoJoyIoDestroy
	mov	esi, 224				; 000000e0H
	mov	DWORD PTR _callbacks$[esp+24], OFFSET _colecoJoyIoReset
	mov	DWORD PTR _callbacks$[esp+28], OFFSET _colecoJoyIoSaveState
	mov	DWORD PTR _callbacks$[esp+32], OFFSET _colecoJoyIoLoadState

; 266  :                                   colecoJoyIoSaveState, colecoJoyIoLoadState };
; 267  : 
; 268  :     int i;
; 269  :     
; 270  :     // Initialize joyMode
; 271  :     joyMode = 1;

	mov	DWORD PTR _joyMode, 1
$LL4@colecoJoyI:

; 272  : 
; 273  :     for (i = 0xe0; i <= 0xff; i++) {
; 274  :         ioPortRegister(i, colecoJoyIoRead, colecoSN76489Write, NULL);

	push	0
	push	OFFSET _colecoSN76489Write
	push	OFFSET _colecoJoyIoRead
	push	esi
	call	_ioPortRegister
	inc	esi
	add	esp, 16					; 00000010H
	cmp	esi, 255				; 000000ffH
	jle	SHORT $LL4@colecoJoyI

; 275  :     }
; 276  :     for (i = 0x80; i <= 0x9f; i++) {

	mov	esi, 128				; 00000080H
$LL7@colecoJoyI:

; 277  :         ioPortRegister(i, NULL, colecoJoyIoWrite, NULL);

	push	0
	push	OFFSET _colecoJoyIoWrite
	push	0
	push	esi
	call	_ioPortRegister
	inc	esi
	add	esp, 16					; 00000010H
	cmp	esi, 159				; 0000009fH
	jle	SHORT $LL7@colecoJoyI

; 278  :     }
; 279  :     for (i = 0xc0; i <= 0xdf; i++) {

	mov	esi, 192				; 000000c0H
$LL10@colecoJoyI:

; 280  :         ioPortRegister(i, NULL, colecoJoyIoWrite, NULL);

	push	0
	push	OFFSET _colecoJoyIoWrite
	push	0
	push	esi
	call	_ioPortRegister
	inc	esi
	add	esp, 16					; 00000010H
	cmp	esi, 223				; 000000dfH
	jle	SHORT $LL10@colecoJoyI

; 281  :     }
; 282  :     
; 283  :     joystickPortUpdateHandlerRegister(colecoJoyIoHandler, NULL);

	push	0
	push	OFFSET _colecoJoyIoHandler
	call	_joystickPortUpdateHandlerRegister

; 284  :     joyDeviceHandle = deviceManagerRegister(ROM_UNKNOWN, &callbacks, NULL);

	push	0
	lea	eax, DWORD PTR _callbacks$[esp+32]
	push	eax
	push	0
	call	_deviceManagerRegister

; 285  : 
; 286  :     rollerTimer = boardTimerCreate(onRollerPoll, NULL);

	push	0
	push	OFFSET _onRollerPoll
	mov	DWORD PTR _joyDeviceHandle, eax
	call	_boardTimerCreate

; 287  :         
; 288  :     boardTimerAdd(rollerTimer, boardSystemTime() + boardFrequency() / 200);

	mov	ecx, DWORD PTR _boardSysTime
	mov	DWORD PTR _rollerTimer, eax
	mov	ecx, DWORD PTR [ecx]
	add	ecx, 107386				; 0001a37aH
	push	ecx
	push	eax
	call	_boardTimerAdd
	add	esp, 36					; 00000024H
	pop	esi

; 289  : }

	add	esp, 16					; 00000010H
	ret	0
_colecoJoyIoCreate ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\board\coleco.c
;	COMDAT _colecoJoyIoDestroy
_TEXT	SEGMENT
_dummy$ = 8						; size = 4
_colecoJoyIoDestroy PROC				; COMDAT

; 243  : {

	push	esi

; 244  :     int i;
; 245  :     for (i = 0xe0; i <= 0xff; i++) {

	mov	esi, 224				; 000000e0H
$LL4@colecoJoyI:

; 246  :         ioPortUnregister(i);

	push	esi
	call	_ioPortUnregister
	inc	esi
	add	esp, 4
	cmp	esi, 255				; 000000ffH
	jle	SHORT $LL4@colecoJoyI

; 247  :     }
; 248  :     
; 249  :     if (joyDevice[0] != NULL && joyDevice[0]->destroy != NULL) {

	mov	eax, DWORD PTR _joyDevice
	pop	esi
	test	eax, eax
	je	SHORT $LN5@colecoJoyI
	mov	ecx, DWORD PTR [eax+8]
	test	ecx, ecx
	je	SHORT $LN5@colecoJoyI

; 250  :         joyDevice[0]->destroy(joyDevice[0]);

	push	eax
	call	ecx
	add	esp, 4
$LN5@colecoJoyI:

; 251  :     }
; 252  :     if (joyDevice[1] != NULL && joyDevice[1]->destroy != NULL) {

	mov	eax, DWORD PTR _joyDevice+4
	test	eax, eax
	je	SHORT $LN6@colecoJoyI
	mov	ecx, DWORD PTR [eax+8]
	test	ecx, ecx
	je	SHORT $LN6@colecoJoyI

; 253  :         joyDevice[1]->destroy(joyDevice[1]);

	push	eax
	call	ecx
	add	esp, 4
$LN6@colecoJoyI:

; 254  :     }
; 255  :     
; 256  :     joystickPortUpdateHandlerUnregister();

	call	_joystickPortUpdateHandlerUnregister

; 257  : 
; 258  :     deviceManagerUnregister(joyDeviceHandle);

	push	DWORD PTR _joyDeviceHandle
	call	_deviceManagerUnregister

; 259  : 
; 260  :     boardTimerDestroy(rollerTimer);

	push	DWORD PTR _rollerTimer
	call	_boardTimerDestroy
	add	esp, 8

; 261  : }

	ret	0
_colecoJoyIoDestroy ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\board\coleco.c
;	COMDAT _colecoJoyIoReset
_TEXT	SEGMENT
_dummy$ = 8						; size = 4
_colecoJoyIoReset PROC					; COMDAT

; 230  :     sliderVal[0] = 0x30;
; 231  :     sliderVal[1] = 0x30;
; 232  :     joyIntState = 0;
; 233  : 
; 234  :     if (joyDevice[0] != NULL && joyDevice[0]->reset != NULL) {

	mov	eax, DWORD PTR _joyDevice
	mov	WORD PTR _sliderVal, 12336		; 00003030H
	mov	DWORD PTR _joyIntState, 0
	test	eax, eax
	je	SHORT $LN2@colecoJoyI
	mov	ecx, DWORD PTR [eax+12]
	test	ecx, ecx
	je	SHORT $LN2@colecoJoyI

; 235  :         joyDevice[0]->reset(joyDevice[0]);

	push	eax
	call	ecx
	add	esp, 4
$LN2@colecoJoyI:

; 236  :     }
; 237  :     if (joyDevice[1] != NULL && joyDevice[1]->reset != NULL) {

	mov	eax, DWORD PTR _joyDevice+4
	test	eax, eax
	je	SHORT $LN3@colecoJoyI
	mov	ecx, DWORD PTR [eax+12]
	test	ecx, ecx
	je	SHORT $LN3@colecoJoyI

; 238  :         joyDevice[1]->reset(joyDevice[1]);

	mov	DWORD PTR _dummy$[esp-4], eax
	jmp	ecx
$LN3@colecoJoyI:

; 239  :     }
; 240  : }

	ret	0
_colecoJoyIoReset ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\board\coleco.c
;	COMDAT _colecoJoyIoSaveState
_TEXT	SEGMENT
_dummy$ = 8						; size = 4
_colecoJoyIoSaveState PROC				; COMDAT

; 213  : {

	push	esi

; 214  :     SaveState* state = saveStateOpenForWrite("colecoJoyIo");

	push	OFFSET ??_C@_0M@NIMHLJHA@colecoJoyIo@
	call	_saveStateOpenForWrite

; 215  :     saveStateSet(state, "sliderVal0", sliderVal[0]);

	movzx	ecx, BYTE PTR _sliderVal
	mov	esi, eax
	push	ecx
	push	OFFSET ??_C@_0L@KJCEGGJD@sliderVal0@
	push	esi
	call	_saveStateSet

; 216  :     saveStateSet(state, "sliderVal1", sliderVal[1]);

	movzx	ecx, BYTE PTR _sliderVal+1
	push	ecx
	push	OFFSET ??_C@_0L@LADPFHNC@sliderVal1@
	push	esi
	call	_saveStateSet

; 217  :     saveStateSet(state, "joyIntState", joyIntState);

	push	DWORD PTR _joyIntState
	push	OFFSET ??_C@_0M@GOOIHBOG@joyIntState@
	push	esi
	call	_saveStateSet

; 218  :     saveStateClose(state);

	push	esi
	call	_saveStateClose

; 219  : 
; 220  :     if (joyDevice[0] != NULL && joyDevice[0]->saveState != NULL) {

	mov	eax, DWORD PTR _joyDevice
	add	esp, 44					; 0000002cH
	pop	esi
	test	eax, eax
	je	SHORT $LN2@colecoJoyI
	mov	ecx, DWORD PTR [eax+16]
	test	ecx, ecx
	je	SHORT $LN2@colecoJoyI

; 221  :         joyDevice[0]->saveState(joyDevice[0]);

	push	eax
	call	ecx
	add	esp, 4
$LN2@colecoJoyI:

; 222  :     }
; 223  :     if (joyDevice[1] != NULL && joyDevice[1]->saveState != NULL) {

	mov	eax, DWORD PTR _joyDevice+4
	test	eax, eax
	je	SHORT $LN3@colecoJoyI
	mov	ecx, DWORD PTR [eax+16]
	test	ecx, ecx
	je	SHORT $LN3@colecoJoyI

; 224  :         joyDevice[1]->saveState(joyDevice[1]);

	mov	DWORD PTR _dummy$[esp-4], eax
	jmp	ecx
$LN3@colecoJoyI:

; 225  :     }
; 226  : }

	ret	0
_colecoJoyIoSaveState ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\board\coleco.c
;	COMDAT _colecoJoyIoLoadState
_TEXT	SEGMENT
_dummy$ = 8						; size = 4
_colecoJoyIoLoadState PROC				; COMDAT

; 197  : {

	push	esi

; 198  :     SaveState* state = saveStateOpenForRead("colecoJoyIo");

	push	OFFSET ??_C@_0M@NIMHLJHA@colecoJoyIo@
	call	_saveStateOpenForRead

; 199  :     sliderVal[0] = (UInt8)saveStateGet(state, "sliderVal0", 0);

	push	0
	mov	esi, eax
	push	OFFSET ??_C@_0L@KJCEGGJD@sliderVal0@
	push	esi
	call	_saveStateGet

; 200  :     sliderVal[1] = (UInt8)saveStateGet(state, "sliderVal1", 0);

	push	0
	push	OFFSET ??_C@_0L@LADPFHNC@sliderVal1@
	push	esi
	mov	BYTE PTR _sliderVal, al
	call	_saveStateGet

; 201  :     joyIntState  =        saveStateGet(state, "joyIntState", 0);

	push	0
	push	OFFSET ??_C@_0M@GOOIHBOG@joyIntState@
	push	esi
	mov	BYTE PTR _sliderVal+1, al
	call	_saveStateGet

; 202  :     saveStateClose(state);

	push	esi
	mov	DWORD PTR _joyIntState, eax
	call	_saveStateClose

; 203  : 
; 204  :     if (joyDevice[0] != NULL && joyDevice[0]->loadState != NULL) {

	mov	eax, DWORD PTR _joyDevice
	add	esp, 44					; 0000002cH
	pop	esi
	test	eax, eax
	je	SHORT $LN2@colecoJoyI
	mov	ecx, DWORD PTR [eax+20]
	test	ecx, ecx
	je	SHORT $LN2@colecoJoyI

; 205  :         joyDevice[0]->loadState(joyDevice[0]);

	push	eax
	call	ecx
	add	esp, 4
$LN2@colecoJoyI:

; 206  :     }
; 207  :     if (joyDevice[1] != NULL && joyDevice[1]->loadState != NULL) {

	mov	eax, DWORD PTR _joyDevice+4
	test	eax, eax
	je	SHORT $LN3@colecoJoyI
	mov	ecx, DWORD PTR [eax+20]
	test	ecx, ecx
	je	SHORT $LN3@colecoJoyI

; 208  :         joyDevice[1]->loadState(joyDevice[1]);

	mov	DWORD PTR _dummy$[esp-4], eax
	jmp	ecx
$LN3@colecoJoyI:

; 209  :     }
; 210  : }

	ret	0
_colecoJoyIoLoadState ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\board\coleco.c
;	COMDAT _onRollerPoll
_TEXT	SEGMENT
_ref$ = 8						; size = 4
_time$ = 12						; size = 4
_onRollerPoll PROC					; COMDAT

; 176  : {

	push	esi

; 177  :     int devNo;
; 178  : 
; 179  :     for (devNo = 0; devNo < 2; devNo++) {

	xor	esi, esi
$LL4@onRollerPo:

; 180  :         ColecoJoystickDevice* device = joyDevice[devNo];

	mov	eax, DWORD PTR _joyDevice[esi*4]

; 181  :         if (device != NULL && device->read != NULL) {

	test	eax, eax
	je	SHORT $LN2@onRollerPo
	mov	ecx, DWORD PTR [eax]
	test	ecx, ecx
	je	SHORT $LN2@onRollerPo

; 182  :             UInt8 val = (UInt8)(device->read(device) >> 4) & 0x30;

	push	eax
	call	ecx
	mov	cx, ax
	add	esp, 4
	shr	cx, 4
	and	cl, 48					; 00000030H

; 183  :             if ((sliderVal[devNo] & 0x10) != 0 && (val & 0x10) == 0) {

	test	BYTE PTR _sliderVal[esi], 16		; 00000010H
	je	SHORT $LN15@onRollerPo
	test	cl, 16					; 00000010H
	jne	SHORT $LN15@onRollerPo

; 184  :                 joyIntState |= 1 << devNo;

	mov	eax, DWORD PTR _joyIntState
	bts	eax, esi
	mov	DWORD PTR _joyIntState, eax
$LN15@onRollerPo:

; 185  :             }
; 186  :             sliderVal[devNo] =  val;

	mov	BYTE PTR _sliderVal[esi], cl
$LN2@onRollerPo:

; 177  :     int devNo;
; 178  : 
; 179  :     for (devNo = 0; devNo < 2; devNo++) {

	inc	esi
	cmp	esi, 2
	jl	SHORT $LL4@onRollerPo

; 187  :         }
; 188  :     }
; 189  :     if (joyIntState != 0) {

	cmp	DWORD PTR _joyIntState, 0
	pop	esi
	je	SHORT $LN7@onRollerPo

; 190  :         r800SetInt(r800);

	push	DWORD PTR _r800
	call	_r800SetInt
	add	esp, 4
$LN7@onRollerPo:

; 191  :     }
; 192  :     
; 193  :     boardTimerAdd(rollerTimer, boardSystemTime() + boardFrequency() / 1000);

	mov	eax, DWORD PTR _boardSysTime
	mov	eax, DWORD PTR [eax]
	add	eax, 21477				; 000053e5H
	push	eax
	push	DWORD PTR _rollerTimer
	call	_boardTimerAdd
	add	esp, 8

; 194  : }

	ret	0
_onRollerPoll ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\board\coleco.c
;	COMDAT _colecoJoyIoHandler
_TEXT	SEGMENT
_dummy$ = 8						; size = 4
_port$ = 12						; size = 4
_type$ = 16						; size = 4
_colecoJoyIoHandler PROC				; COMDAT

; 149  : {

	push	esi

; 150  :     if (port >= 2) {

	mov	esi, DWORD PTR _port$[esp]
	cmp	esi, 2
	jge	SHORT $LN2@colecoJoyI

; 151  :         return;
; 152  :     }
; 153  : 
; 154  :     if (joyDevice[port] != NULL && joyDevice[port]->destroy != NULL) {

	mov	eax, DWORD PTR _joyDevice[esi*4]
	test	eax, eax
	je	SHORT $LN5@colecoJoyI
	mov	ecx, DWORD PTR [eax+8]
	test	ecx, ecx
	je	SHORT $LN5@colecoJoyI

; 155  :         joyDevice[port]->destroy(joyDevice[port]);

	push	eax
	call	ecx
	add	esp, 4
$LN5@colecoJoyI:

; 156  :     }
; 157  :     
; 158  :     switch (type) {

	mov	eax, DWORD PTR _type$[esp]
	sub	eax, 5
	je	SHORT $LN7@colecoJoyI
	sub	eax, 4
	je	SHORT $LN8@colecoJoyI
	sub	eax, 1
	je	SHORT $LN9@colecoJoyI

; 159  :     default:
; 160  :     case JOYSTICK_PORT_NONE:
; 161  :         joyDevice[port] = NULL;

	mov	DWORD PTR _joyDevice[esi*4], 0
	pop	esi

; 171  :         break;
; 172  :     }
; 173  : }

	ret	0
$LN9@colecoJoyI:

; 168  :         break;
; 169  :     case JOYSTICK_PORT_STEERINGWHEEL:
; 170  :         joyDevice[port] = colecoSteeringWheelCreate(port);

	push	esi
	call	_colecoSteeringWheelCreate

; 171  :         break;
; 172  :     }
; 173  : }

	add	esp, 4
	mov	DWORD PTR _joyDevice[esi*4], eax
	pop	esi
	ret	0
$LN8@colecoJoyI:

; 165  :         break;
; 166  :     case JOYSTICK_PORT_SUPERACTION:
; 167  :         joyDevice[port] = colecoSuperActionCreate(port);

	push	esi
	call	_colecoSuperActionCreate

; 171  :         break;
; 172  :     }
; 173  : }

	add	esp, 4
	mov	DWORD PTR _joyDevice[esi*4], eax
	pop	esi
	ret	0
$LN7@colecoJoyI:

; 162  :         break;
; 163  :     case JOYSTICK_PORT_COLECOJOYSTICK:
; 164  :         joyDevice[port] = colecoJoystickCreate(port);

	push	esi
	call	_colecoJoystickCreate

; 171  :         break;
; 172  :     }
; 173  : }

	add	esp, 4
	mov	DWORD PTR _joyDevice[esi*4], eax
$LN2@colecoJoyI:
	pop	esi
	ret	0
_colecoJoyIoHandler ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\board\coleco.c
;	COMDAT _colecoJoyIoRead
_TEXT	SEGMENT
tv762 = -8						; size = 4
_joyState$1$ = -8					; size = 4
$T1 = -8						; size = 1
tv767 = -4						; size = 4
$T2 = -4						; size = 1
_dummy$ = 8						; size = 4
tv781 = 12						; size = 1
_ioPort$ = 12						; size = 2
_colecoJoyIoRead PROC					; COMDAT

; 82   : {

	sub	esp, 8

; 83   :     int devNo = (ioPort >> 1) & 1;

	mov	eax, DWORD PTR _ioPort$[esp+4]

; 84   :     ColecoJoystickDevice* device = joyDevice[devNo];
; 85   :     UInt16 joyState = 0xffff;

	mov	edx, 65535				; 0000ffffH
	shr	eax, 1
	and	eax, 1
	mov	DWORD PTR _joyState$1$[esp+8], edx
	mov	DWORD PTR _ioPort$[esp+4], eax
	mov	ecx, DWORD PTR _joyDevice[eax*4]

; 86   :     static UInt8 oldValue[2] = { 0, 0 };
; 87   :     UInt8 value;
; 88   : 
; 89   :     if (device != NULL && device->read != NULL) {

	test	ecx, ecx
	je	SHORT $LN2@colecoJoyI
	push	esi
	mov	esi, DWORD PTR [ecx]
	test	esi, esi
	je	SHORT $LN38@colecoJoyI

; 90   :         joyState = device->read(device);

	push	ecx
	call	esi
	movzx	edx, ax
	add	esp, 4
	mov	eax, DWORD PTR _ioPort$[esp+8]
	mov	DWORD PTR _joyState$1$[esp+12], edx
$LN38@colecoJoyI:
	pop	esi
$LN2@colecoJoyI:

; 91   :     }
; 92   : 
; 93   :     if (joyMode != 0) {

	cmp	DWORD PTR _joyMode, 0
	mov	ch, BYTE PTR _sliderVal[eax]
	push	ebx
	je	SHORT $LN3@colecoJoyI

; 94   :         value =  boardCaptureUInt8(2 * devNo, sliderVal[devNo] |
; 95   :                                               ((joyState & 0x001) ? 0x01 : 0) |
; 96   :                                               ((joyState & 0x008) ? 0x02 : 0) |
; 97   :                                               ((joyState & 0x002) ? 0x04 : 0) |
; 98   :                                               ((joyState & 0x004) ? 0x08 : 0) |
; 99   :                                               ((joyState & 0x010) ? 0x40 : 0));
; 100  :     }

	mov	ebx, DWORD PTR _ioPort$[esp+8]
	add	al, al
	mov	BYTE PTR $T2[esp+12], al
	mov	cl, dl
	and	cl, 16					; 00000010H
	mov	al, dl
	add	cl, cl
	and	al, 6
	or	cl, al
	mov	al, dl
	shr	al, 2
	add	cl, cl
	and	al, 2
	and	dl, 1
	or	cl, al
	or	cl, dl
	or	cl, ch
	mov	BYTE PTR $T1[esp+12], cl
	jmp	$LN4@colecoJoyI
$LN3@colecoJoyI:

; 101  :     else {
; 102  :         value = sliderVal[devNo] | ((joyState & 0x020) ? 0x40 : 0) | 0x0f;

	mov	bl, dl
	and	bl, 32					; 00000020H
	add	bl, bl
	or	bl, ch
	or	bl, 15					; 0000000fH

; 103  : 
; 104  : 	    if (devNo == 1) {

	test	eax, eax
	je	$LN5@colecoJoyI

; 105  : 		    if (inputEventGetState(EC_COLECO2_0))    value &= 0xFA;

	cmp	DWORD PTR _eventMap+560, 0
	je	SHORT $LN7@colecoJoyI
	and	bl, 250					; 000000faH
$LN7@colecoJoyI:

; 106  : 		    if (inputEventGetState(EC_COLECO2_1))    value &= 0xFD;

	cmp	DWORD PTR _eventMap+564, 0
	je	SHORT $LN8@colecoJoyI
	and	bl, 253					; 000000fdH
$LN8@colecoJoyI:

; 107  : 		    if (inputEventGetState(EC_COLECO2_2))    value &= 0xF7;

	cmp	DWORD PTR _eventMap+568, 0
	je	SHORT $LN9@colecoJoyI
	and	bl, 247					; 000000f7H
$LN9@colecoJoyI:

; 108  : 		    if (inputEventGetState(EC_COLECO2_3))    value &= 0xFC;

	cmp	DWORD PTR _eventMap+572, 0
	je	SHORT $LN10@colecoJoyI
	and	bl, 252					; 000000fcH
$LN10@colecoJoyI:

; 109  : 		    if (inputEventGetState(EC_COLECO2_4))    value &= 0xF2;

	cmp	DWORD PTR _eventMap+576, 0
	je	SHORT $LN11@colecoJoyI
	and	bl, 242					; 000000f2H
$LN11@colecoJoyI:

; 110  : 		    if (inputEventGetState(EC_COLECO2_5))    value &= 0xF3;

	cmp	DWORD PTR _eventMap+580, 0
	je	SHORT $LN12@colecoJoyI
	and	bl, 243					; 000000f3H
$LN12@colecoJoyI:

; 111  : 		    if (inputEventGetState(EC_COLECO2_6))    value &= 0xFE;

	cmp	DWORD PTR _eventMap+584, 0
	je	SHORT $LN13@colecoJoyI
	and	bl, 254					; 000000feH
$LN13@colecoJoyI:

; 112  : 		    if (inputEventGetState(EC_COLECO2_7))    value &= 0xF5;

	cmp	DWORD PTR _eventMap+588, 0
	je	SHORT $LN14@colecoJoyI
	and	bl, 245					; 000000f5H
$LN14@colecoJoyI:

; 113  : 		    if (inputEventGetState(EC_COLECO2_8))    value &= 0xF1;

	cmp	DWORD PTR _eventMap+592, 0
	je	SHORT $LN15@colecoJoyI
	and	bl, 241					; 000000f1H
$LN15@colecoJoyI:

; 114  : 		    if (inputEventGetState(EC_COLECO2_9))    value &= 0xFB;

	cmp	DWORD PTR _eventMap+596, 0
	je	SHORT $LN16@colecoJoyI
	and	bl, 251					; 000000fbH
$LN16@colecoJoyI:

; 115  : 		    if (inputEventGetState(EC_COLECO2_STAR)) value &= 0xF9;

	cmp	DWORD PTR _eventMap+600, 0
	je	SHORT $LN17@colecoJoyI
	and	bl, 249					; 000000f9H
$LN17@colecoJoyI:

; 116  : 		    if (inputEventGetState(EC_COLECO2_HASH)) value &= 0xF6;

	cmp	DWORD PTR _eventMap+604, 0
	je	SHORT $LN18@colecoJoyI
	and	bl, 246					; 000000f6H
$LN18@colecoJoyI:

; 117  : 		    if ((joyState & 0x040) == 0)             value &= 0xF8;
; 118  : 		    if ((joyState & 0x080) == 0)             value &= 0xF4;

	mov	al, bl
	mov	cl, dl
	and	al, 248					; 000000f8H
	and	cl, 64					; 00000040H
	mov	ecx, DWORD PTR _joyState$1$[esp+12]
	movzx	edx, al
	movzx	eax, bl
	cmovne	edx, eax

; 119  :         }

	mov	al, dl
	and	al, 244					; 000000f4H
	and	cl, 128					; 00000080H
	movzx	ebx, al
	movzx	eax, dl
	cmovne	ebx, eax
	mov	DWORD PTR tv762[esp+12], ebx
	jmp	$LN34@colecoJoyI
$LN5@colecoJoyI:

; 120  :         else {
; 121  : 		    if (inputEventGetState(EC_COLECO1_0))    value &= 0xFA;

	cmp	DWORD PTR _eventMap+480, 0
	je	SHORT $LN21@colecoJoyI
	and	bl, 250					; 000000faH
$LN21@colecoJoyI:

; 122  : 		    if (inputEventGetState(EC_COLECO1_1))    value &= 0xFD;

	cmp	DWORD PTR _eventMap+484, 0
	je	SHORT $LN22@colecoJoyI
	and	bl, 253					; 000000fdH
$LN22@colecoJoyI:

; 123  : 		    if (inputEventGetState(EC_COLECO1_2))    value &= 0xF7;

	cmp	DWORD PTR _eventMap+488, 0
	je	SHORT $LN23@colecoJoyI
	and	bl, 247					; 000000f7H
$LN23@colecoJoyI:

; 124  : 		    if (inputEventGetState(EC_COLECO1_3))    value &= 0xFC;

	cmp	DWORD PTR _eventMap+492, 0
	je	SHORT $LN24@colecoJoyI
	and	bl, 252					; 000000fcH
$LN24@colecoJoyI:

; 125  : 		    if (inputEventGetState(EC_COLECO1_4))    value &= 0xF2;

	cmp	DWORD PTR _eventMap+496, 0
	je	SHORT $LN25@colecoJoyI
	and	bl, 242					; 000000f2H
$LN25@colecoJoyI:

; 126  : 		    if (inputEventGetState(EC_COLECO1_5))    value &= 0xF3;

	cmp	DWORD PTR _eventMap+500, 0
	je	SHORT $LN26@colecoJoyI
	and	bl, 243					; 000000f3H
$LN26@colecoJoyI:

; 127  : 		    if (inputEventGetState(EC_COLECO1_6))    value &= 0xFE;

	cmp	DWORD PTR _eventMap+504, 0
	je	SHORT $LN27@colecoJoyI
	and	bl, 254					; 000000feH
$LN27@colecoJoyI:

; 128  : 		    if (inputEventGetState(EC_COLECO1_7))    value &= 0xF5;

	cmp	DWORD PTR _eventMap+508, 0
	je	SHORT $LN28@colecoJoyI
	and	bl, 245					; 000000f5H
$LN28@colecoJoyI:

; 129  : 		    if (inputEventGetState(EC_COLECO1_8))    value &= 0xF1;

	cmp	DWORD PTR _eventMap+512, 0
	je	SHORT $LN29@colecoJoyI
	and	bl, 241					; 000000f1H
$LN29@colecoJoyI:

; 130  : 		    if (inputEventGetState(EC_COLECO1_9))    value &= 0xFB;

	cmp	DWORD PTR _eventMap+516, 0
	je	SHORT $LN30@colecoJoyI
	and	bl, 251					; 000000fbH
$LN30@colecoJoyI:

; 131  : 		    if (inputEventGetState(EC_COLECO1_STAR)) value &= 0xF9;

	cmp	DWORD PTR _eventMap+520, 0
	je	SHORT $LN31@colecoJoyI
	and	bl, 249					; 000000f9H
$LN31@colecoJoyI:

; 132  : 		    if (inputEventGetState(EC_COLECO1_HASH)) value &= 0xF6;

	cmp	DWORD PTR _eventMap+524, 0
	je	SHORT $LN32@colecoJoyI
	and	bl, 246					; 000000f6H
$LN32@colecoJoyI:

; 133  : 		    if ((joyState & 0x040) == 0)             value &= 0xF8;
; 134  : 		    if ((joyState & 0x080) == 0)             value &= 0xF4;

	mov	al, bl
	mov	cl, dl
	and	al, 248					; 000000f8H
	and	cl, 64					; 00000040H
	movzx	eax, al
	mov	DWORD PTR tv767[esp+12], eax
	mov	ecx, eax
	movzx	eax, bl
	cmovne	ecx, eax
	mov	BYTE PTR tv762[esp+12], cl
	test	dl, dl
	js	SHORT $LN34@colecoJoyI
	and	cl, 244					; 000000f4H
	mov	BYTE PTR tv762[esp+12], cl
$LN34@colecoJoyI:

; 135  : 	    }
; 136  : 
; 137  :         value = boardCaptureUInt8(4 + 2 * devNo, value);

	mov	ebx, DWORD PTR _ioPort$[esp+8]
	mov	al, bl
	add	al, 2
	add	al, al
	mov	BYTE PTR $T2[esp+12], al
	mov	eax, DWORD PTR tv762[esp+12]
	mov	BYTE PTR $T1[esp+12], al
$LN4@colecoJoyI:

; 138  :     }
; 139  : 
; 140  :     joyIntState &= ~(1 << devNo);

	push	DWORD PTR $T1[esp+12]
	push	DWORD PTR $T2[esp+16]
	call	_boardCaptureUInt8
	mov	ecx, DWORD PTR _joyIntState
	add	esp, 8
	btr	ecx, ebx
	mov	BYTE PTR tv781[esp+8], al
	mov	DWORD PTR _joyIntState, ecx
	pop	ebx
	test	ecx, ecx

; 141  :     if (joyIntState == 0) {

	jne	SHORT $LN35@colecoJoyI

; 142  :         r800ClearInt(r800);

	push	DWORD PTR _r800
	call	_r800ClearInt

; 143  :     }
; 144  : 
; 145  :     return value;

	mov	al, BYTE PTR tv781[esp+8]
	add	esp, 4
$LN35@colecoJoyI:

; 146  : }

	add	esp, 8
	ret	0
_colecoJoyIoRead ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\board\coleco.c
;	COMDAT _colecoJoyIoWrite
_TEXT	SEGMENT
_dummy$ = 8						; size = 4
_ioPort$ = 12						; size = 2
_value$ = 16						; size = 1
_colecoJoyIoWrite PROC					; COMDAT

; 78   : 	joyMode = (ioPort >> 6) & 1;

	mov	eax, DWORD PTR _ioPort$[esp-4]
	shr	eax, 6
	and	eax, 1
	mov	DWORD PTR _joyMode, eax

; 79   : }

	ret	0
_colecoJoyIoWrite ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\board\coleco.c
;	COMDAT _colecoSN76489Write
_TEXT	SEGMENT
_dummy$ = 8						; size = 4
_ioPort$ = 12						; size = 2
_value$ = 16						; size = 1
_colecoSN76489Write PROC				; COMDAT

; 73   :     sn76489WriteData(sn76489, ioPort, value);

	push	DWORD PTR _value$[esp-4]
	push	DWORD PTR _ioPort$[esp]
	push	DWORD PTR _sn76489
	call	_sn76489WriteData
	add	esp, 12					; 0000000cH

; 74   : }

	ret	0
_colecoSN76489Write ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\board\coleco.c
;	COMDAT _colecoCreate
_TEXT	SEGMENT
_callbacks$1 = -16					; size = 16
_machine$ = 8						; size = 4
_vdpSyncMode$ = 12					; size = 4
_boardInfo$ = 16					; size = 4
_colecoCreate PROC					; COMDAT

; 350  : {

	sub	esp, 16					; 00000010H
	push	ebx
	push	esi
	push	edi

; 351  :     int success;
; 352  :     int i;
; 353  : 
; 354  :     r800 = r800Create(CPU_ENABLE_M1, slotRead, slotWrite, ioPortRead, ioPortWrite, NULL, boardTimerCheckTimeout, NULL, NULL, NULL, NULL, NULL, NULL);

	push	0
	push	0
	push	0
	push	0
	push	0
	push	0
	push	OFFSET _boardTimerCheckTimeout
	push	0
	push	OFFSET _ioPortWrite
	push	OFFSET _ioPortRead
	push	OFFSET _slotWrite
	push	OFFSET _slotRead
	push	2
	call	_r800Create

; 355  : 
; 356  :     boardInfo->cartridgeCount   = 1;

	mov	ecx, DWORD PTR _boardInfo$[esp+76]
	mov	DWORD PTR _r800, eax
	mov	DWORD PTR [ecx], 1

; 357  :     boardInfo->diskdriveCount   = 0;

	mov	DWORD PTR [ecx+4], 0

; 358  :     boardInfo->casetteCount     = 0;

	mov	DWORD PTR [ecx+8], 0

; 359  :     boardInfo->cpuRef           = r800;

	mov	DWORD PTR [ecx+12], eax

; 360  : 
; 361  :     boardInfo->destroy          = destroy;

	mov	DWORD PTR [ecx+16], OFFSET _destroy

; 362  :     boardInfo->softReset        = reset;

	mov	DWORD PTR [ecx+20], OFFSET _reset

; 363  :     boardInfo->loadState        = loadState;

	mov	DWORD PTR [ecx+24], OFFSET _loadState

; 364  :     boardInfo->saveState        = saveState;

	mov	DWORD PTR [ecx+28], OFFSET _saveState

; 365  :     boardInfo->getRefreshRate   = getRefreshRate;

	mov	DWORD PTR [ecx+32], OFFSET _getRefreshRate

; 366  :     boardInfo->getRamPage       = NULL;

	mov	DWORD PTR [ecx+36], 0

; 367  : 
; 368  :     boardInfo->run              = r800Execute;

	mov	DWORD PTR [ecx+44], OFFSET _r800Execute

; 369  :     boardInfo->stop             = r800StopExecution;

	mov	DWORD PTR [ecx+48], OFFSET _r800StopExecution

; 370  :     boardInfo->setInt           = r800SetNmi;

	mov	DWORD PTR [ecx+52], OFFSET _r800SetNmi

; 371  :     boardInfo->clearInt         = r800ClearNmi;

	mov	DWORD PTR [ecx+56], OFFSET _r800ClearNmi

; 372  :     boardInfo->setCpuTimeout    = r800SetTimeoutAt;

	mov	DWORD PTR [ecx+60], OFFSET _r800SetTimeoutAt

; 373  :     boardInfo->setBreakpoint    = r800SetBreakpoint;

	mov	DWORD PTR [ecx+64], OFFSET _r800SetBreakpoint

; 374  :     boardInfo->clearBreakpoint  = r800ClearBreakpoint;

	mov	DWORD PTR [ecx+68], OFFSET _r800ClearBreakpoint

; 375  :     boardInfo->setDataBus       = r800SetDataBus;

	mov	DWORD PTR [ecx+40], OFFSET _r800SetDataBus

; 376  :     
; 377  :     boardInfo->getTimeTrace     = getTimeTrace;

	mov	DWORD PTR [ecx+76], OFFSET _getTimeTrace

; 378  : 
; 379  :     deviceManagerCreate();

	call	_deviceManagerCreate

; 380  : 
; 381  :     boardInit(&r800->systemTime);

	push	DWORD PTR _r800
	call	_boardInit

; 382  :     ioPortReset();

	call	_ioPortReset

; 383  : 
; 384  :     r800Reset(r800, 0);

	push	0
	push	DWORD PTR _r800
	call	_r800Reset
	add	esp, 64					; 00000040H

; 385  :     mixerReset(boardGetMixer());

	call	_boardGetMixer
	push	eax
	call	_mixerReset

; 386  : 
; 387  :     r800DebugCreate(r800);

	push	DWORD PTR _r800
	call	_r800DebugCreate

; 388  : 
; 389  :     sn76489 = sn76489Create(boardGetMixer());

	call	_boardGetMixer
	push	eax
	call	_sn76489Create
	mov	DWORD PTR _sn76489, eax

; 390  : 
; 391  :     slotManagerCreate();

	call	_slotManagerCreate

; 392  :     
; 393  :     if (vdpSyncMode == VDP_SYNC_AUTO) {
; 394  :         vdpSyncMode = VDP_SYNC_60HZ;
; 395  :     }
; 396  :     vdpCreate(VDP_COLECO, machine->video.vdpVersion, vdpSyncMode, machine->video.vramSize / 0x4000);

	mov	ebx, DWORD PTR _machine$[esp+36]
	mov	ecx, 2
	mov	eax, DWORD PTR [ebx+104]
	cdq
	and	edx, 16383				; 00003fffH
	add	eax, edx
	sar	eax, 14					; 0000000eH
	push	eax
	mov	eax, DWORD PTR _vdpSyncMode$[esp+40]
	test	eax, eax
	cmovne	ecx, eax
	push	ecx
	push	DWORD PTR [ebx+100]
	push	2
	call	_vdpCreate
	add	esp, 28					; 0000001cH

; 265  :     DeviceCallbacks callbacks = { colecoJoyIoDestroy,   colecoJoyIoReset, 

	mov	DWORD PTR _callbacks$1[esp+28], OFFSET _colecoJoyIoDestroy
	mov	DWORD PTR _callbacks$1[esp+32], OFFSET _colecoJoyIoReset

; 392  :     
; 393  :     if (vdpSyncMode == VDP_SYNC_AUTO) {
; 394  :         vdpSyncMode = VDP_SYNC_60HZ;
; 395  :     }
; 396  :     vdpCreate(VDP_COLECO, machine->video.vdpVersion, vdpSyncMode, machine->video.vramSize / 0x4000);

	mov	esi, 224				; 000000e0H

; 265  :     DeviceCallbacks callbacks = { colecoJoyIoDestroy,   colecoJoyIoReset, 

	mov	DWORD PTR _callbacks$1[esp+36], OFFSET _colecoJoyIoSaveState
	mov	DWORD PTR _callbacks$1[esp+40], OFFSET _colecoJoyIoLoadState

; 266  :                                   colecoJoyIoSaveState, colecoJoyIoLoadState };
; 267  : 
; 268  :     int i;
; 269  :     
; 270  :     // Initialize joyMode
; 271  :     joyMode = 1;

	mov	DWORD PTR _joyMode, 1
	npad	4
$LL18@colecoCrea:

; 272  : 
; 273  :     for (i = 0xe0; i <= 0xff; i++) {
; 274  :         ioPortRegister(i, colecoJoyIoRead, colecoSN76489Write, NULL);

	push	0
	push	OFFSET _colecoSN76489Write
	push	OFFSET _colecoJoyIoRead
	push	esi
	call	_ioPortRegister
	inc	esi
	add	esp, 16					; 00000010H
	cmp	esi, 255				; 000000ffH
	jle	SHORT $LL18@colecoCrea

; 275  :     }
; 276  :     for (i = 0x80; i <= 0x9f; i++) {

	mov	esi, 128				; 00000080H
$LL21@colecoCrea:

; 277  :         ioPortRegister(i, NULL, colecoJoyIoWrite, NULL);

	push	0
	push	OFFSET _colecoJoyIoWrite
	push	0
	push	esi
	call	_ioPortRegister
	inc	esi
	add	esp, 16					; 00000010H
	cmp	esi, 159				; 0000009fH
	jle	SHORT $LL21@colecoCrea

; 278  :     }
; 279  :     for (i = 0xc0; i <= 0xdf; i++) {

	mov	esi, 192				; 000000c0H
$LL24@colecoCrea:

; 280  :         ioPortRegister(i, NULL, colecoJoyIoWrite, NULL);

	push	0
	push	OFFSET _colecoJoyIoWrite
	push	0
	push	esi
	call	_ioPortRegister
	inc	esi
	add	esp, 16					; 00000010H
	cmp	esi, 223				; 000000dfH
	jle	SHORT $LL24@colecoCrea

; 281  :     }
; 282  :     
; 283  :     joystickPortUpdateHandlerRegister(colecoJoyIoHandler, NULL);

	push	0
	push	OFFSET _colecoJoyIoHandler
	call	_joystickPortUpdateHandlerRegister

; 284  :     joyDeviceHandle = deviceManagerRegister(ROM_UNKNOWN, &callbacks, NULL);

	push	0
	lea	eax, DWORD PTR _callbacks$1[esp+40]
	push	eax
	push	0
	call	_deviceManagerRegister

; 285  : 
; 286  :     rollerTimer = boardTimerCreate(onRollerPoll, NULL);

	push	0
	push	OFFSET _onRollerPoll
	mov	DWORD PTR _joyDeviceHandle, eax
	call	_boardTimerCreate

; 287  :         
; 288  :     boardTimerAdd(rollerTimer, boardSystemTime() + boardFrequency() / 200);

	mov	ecx, DWORD PTR _boardSysTime
	mov	DWORD PTR _rollerTimer, eax
	mov	ecx, DWORD PTR [ecx]
	add	ecx, 107386				; 0001a37aH
	push	ecx
	push	eax
	call	_boardTimerAdd

; 397  : 
; 398  :     colecoJoyIoCreate();
; 399  : 
; 400  :     ledSetCapslock(0);

	push	0
	call	_ledSetCapslock
	add	esp, 40					; 00000028H

; 283  :     joystickPortUpdateHandlerRegister(colecoJoyIoHandler, NULL);

	xor	esi, esi
	npad	1
$LL4@colecoCrea:

; 401  : 
; 402  :     for (i = 0; i < 4; i++) {
; 403  :         slotSetSubslotted(i, 0);

	push	0
	push	esi
	call	_slotSetSubslotted
	inc	esi
	add	esp, 8
	cmp	esi, 4
	jl	SHORT $LL4@colecoCrea

; 404  :     }
; 405  :     for (i = 0; i < 2; i++) {

	xor	esi, esi
	lea	edi, DWORD PTR [ebx+84]
$LL7@colecoCrea:

; 406  :         cartridgeSetSlotInfo(i, machine->cart[i].slot, 0);

	push	0
	push	DWORD PTR [edi]
	push	esi
	call	_cartridgeSetSlotInfo
	inc	esi
	lea	edi, DWORD PTR [edi+8]
	add	esp, 12					; 0000000cH
	cmp	esi, 2
	jl	SHORT $LL7@colecoCrea

; 407  :     }
; 408  : 
; 409  :     success = machineInitialize(machine, NULL, NULL, NULL);

	push	0
	push	0
	push	0
	push	ebx
	call	_machineInitialize
	add	esp, 16					; 00000010H
	mov	edi, eax
	xor	esi, esi
	npad	1
$LL10@colecoCrea:

; 410  : 
; 411  :     for (i = 0; i < 8; i++) {
; 412  :         slotMapRamPage(0, 0, i);

	push	esi
	push	0
	push	0
	call	_slotMapRamPage
	inc	esi
	add	esp, 12					; 0000000cH
	cmp	esi, 8
	jl	SHORT $LL10@colecoCrea

; 413  :     }
; 414  : 
; 415  :     if (success) {

	test	edi, edi
	je	SHORT $LN12@colecoCrea

; 416  :         success = boardInsertExternalDevices();

	call	_boardInsertExternalDevices
	mov	edi, eax
$LN12@colecoCrea:

; 417  :     }
; 418  : 
; 419  :     r800SetFrequency(r800, CPU_Z80,  machine->cpu.freqZ80);

	push	DWORD PTR [ebx+136]
	push	0
	push	DWORD PTR _r800
	call	_r800SetFrequency

; 420  :     r800SetFrequency(r800, CPU_R800, machine->cpu.freqR800);

	push	DWORD PTR [ebx+140]
	push	1
	push	DWORD PTR _r800
	call	_r800SetFrequency
	add	esp, 24					; 00000018H

; 421  : 
; 422  :     if (!success) {

	test	edi, edi
	jne	SHORT $LN54@colecoCrea

; 312  :     boardRemoveExternalDevices();

	call	_boardRemoveExternalDevices

; 313  : 
; 314  :     sn76489Destroy(sn76489);

	push	DWORD PTR _sn76489
	call	_sn76489Destroy

; 315  :     r800DebugDestroy();

	call	_r800DebugDestroy

; 316  :     slotManagerDestroy();

	call	_slotManagerDestroy

; 317  :     deviceManagerDestroy();

	call	_deviceManagerDestroy

; 318  :     r800Destroy(r800);

	push	DWORD PTR _r800
	call	_r800Destroy
	add	esp, 8
$LN54@colecoCrea:

; 423  :         destroy();
; 424  :     }
; 425  : 
; 426  :     return success;
; 427  : }

	mov	eax, edi
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 16					; 00000010H
	ret	0
_colecoCreate ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\board\board.h
;	COMDAT _boardSystemTime
_TEXT	SEGMENT
_boardSystemTime PROC					; COMDAT

; 164  :     extern UInt32* boardSysTime;
; 165  :     return *boardSysTime;

	mov	eax, DWORD PTR _boardSysTime
	mov	eax, DWORD PTR [eax]

; 166  : }

	ret	0
_boardSystemTime ENDP
_TEXT	ENDS
END
