; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27054.0 

	TITLE	D:\repo\MSX-master\MSX\blueMSX-DPI\Src\Debugger\Debugger.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	??_C@_05IEEKDPFI@V9938@				; `string'
PUBLIC	??_C@_05IAMHEDOK@V9958@				; `string'
PUBLIC	??_C@_08IBFDMDNO@TMS9929A@			; `string'
PUBLIC	??_C@_08HEDIBBLA@TMS99x8A@			; `string'
;	COMDAT ??_C@_08HEDIBBLA@TMS99x8A@
CONST	SEGMENT
??_C@_08HEDIBBLA@TMS99x8A@ DB 'TMS99x8A', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_08IBFDMDNO@TMS9929A@
CONST	SEGMENT
??_C@_08IBFDMDNO@TMS9929A@ DB 'TMS9929A', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_05IAMHEDOK@V9958@
CONST	SEGMENT
??_C@_05IAMHEDOK@V9958@ DB 'V9958', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_05IEEKDPFI@V9938@
CONST	SEGMENT
??_C@_05IEEKDPFI@V9938@ DB 'V9938', 00H			; `string'
CONST	ENDS
PUBLIC	_debuggerCreate
PUBLIC	_debuggerDestroy
PUBLIC	_dbgSnapshotCreate
PUBLIC	_dbgSnapshotDestroy
PUBLIC	_dbgGetState
PUBLIC	_dbgSnapshotGetDeviceCount
PUBLIC	_dbgSnapshotGetDevice
PUBLIC	_dbgDeviceGetMemoryBlockCount
PUBLIC	_dbgDeviceGetMemoryBlock
PUBLIC	_dbgDeviceGetRegisterBankCount
PUBLIC	_dbgDeviceGetRegisterBank
PUBLIC	_dbgDeviceGetCallstackCount
PUBLIC	_dbgDeviceGetCallstack
PUBLIC	_dbgDeviceGetIoPortsCount
PUBLIC	_dbgDeviceGetIoPorts
PUBLIC	_dbgDeviceWriteMemory
PUBLIC	_dbgDeviceWriteRegister
PUBLIC	_dbgDeviceWriteIoPort
PUBLIC	_dbgRun
PUBLIC	_dbgStop
PUBLIC	_dbgPause
PUBLIC	_dbgStep
PUBLIC	_dbgStepBack
PUBLIC	_dbgSetBreakpoint
PUBLIC	_dbgClearBreakpoint
PUBLIC	_dbgSetWatchpoint
PUBLIC	_dbgClearWatchpoint
PUBLIC	_debuggerCheckVramAccess
PUBLIC	_dbgEnableVramAccessCheck
PUBLIC	_debuggerNotifyEmulatorStart
PUBLIC	_debuggerNotifyEmulatorStop
PUBLIC	_debuggerNotifyEmulatorPause
PUBLIC	_debuggerNotifyEmulatorResume
PUBLIC	_debuggerNotifyEmulatorReset
PUBLIC	_debuggerTrace
PUBLIC	_debuggerSetBreakpoint
EXTRN	_debugDeviceGetSnapshot:PROC
EXTRN	_debugDeviceWriteMemory:PROC
EXTRN	_debugDeviceWriteRegister:PROC
EXTRN	_debugDeviceWriteIoPort:PROC
EXTRN	_debugDeviceSetMemoryWatchpoint:PROC
EXTRN	_debugDeviceClearMemoryWatchpoint:PROC
EXTRN	_emulatorStop:PROC
EXTRN	_emulatorGetState:PROC
EXTRN	_actionEmuTogglePause:PROC
EXTRN	_actionEmuStep:PROC
EXTRN	_actionEmuStepBack:PROC
EXTRN	_boardSetBreakpoint:PROC
EXTRN	_boardClearBreakpoint:PROC
EXTRN	_free:PROC
EXTRN	_malloc:PROC
_BSS	SEGMENT
_debuggerList DD 08H DUP (?)
_dbgState DD	01H DUP (?)
_debuggerVramAccessEnable DD 01H DUP (?)
_BSS	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\debugger\debugger.c
;	COMDAT _onDefSetBp
_TEXT	SEGMENT
_ref$ = 8						; size = 4
_d1$ = 12						; size = 2
_d2$ = 16						; size = 2
_d3$ = 20						; size = 2
_onDefSetBp PROC					; COMDAT

; 66   : }

	ret	0
_onDefSetBp ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\debugger\debugger.c
;	COMDAT _onDefTrace
_TEXT	SEGMENT
_ref$ = 8						; size = 4
_dummy$ = 12						; size = 4
_onDefTrace PROC					; COMDAT

; 63   : }

	ret	0
_onDefTrace ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\debugger\debugger.c
;	COMDAT _onDefault
_TEXT	SEGMENT
_ref$ = 8						; size = 4
_onDefault PROC						; COMDAT

; 60   : }

	ret	0
_onDefault ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\debugger\debugger.c
;	COMDAT _debuggerSetBreakpoint
_TEXT	SEGMENT
_slot$ = 8						; size = 2
_page$ = 12						; size = 2
_address$ = 16						; size = 2
_debuggerSetBreakpoint PROC				; COMDAT

; 196  : {

	push	ebx

; 197  :     int i;
; 198  : 
; 199  :     for (i = 0; i < MAX_DEBUGGERS; i++) {

	mov	ebx, DWORD PTR _page$[esp]
	push	ebp
	mov	ebp, DWORD PTR _address$[esp+4]
	push	esi
	push	edi
	mov	edi, DWORD PTR _slot$[esp+12]
	mov	esi, OFFSET _debuggerList
$LL4@debuggerSe:

; 200  :         if (debuggerList[i] != NULL) {

	mov	eax, DWORD PTR [esi]
	test	eax, eax
	je	SHORT $LN2@debuggerSe

; 201  :             debuggerList[i]->onDebugSetBp(debuggerList[i]->ref, slot, page, address);

	push	ebp
	push	ebx
	push	edi
	push	DWORD PTR [eax+28]
	mov	eax, DWORD PTR [eax+24]
	call	eax
	add	esp, 16					; 00000010H
$LN2@debuggerSe:

; 197  :     int i;
; 198  : 
; 199  :     for (i = 0; i < MAX_DEBUGGERS; i++) {

	add	esi, 4
	cmp	esi, OFFSET _debuggerList+32
	jl	SHORT $LL4@debuggerSe

; 202  :         }
; 203  :     }
; 204  : }

	pop	edi
	pop	esi
	pop	ebp
	pop	ebx
	ret	0
_debuggerSetBreakpoint ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\debugger\debugger.c
;	COMDAT _debuggerTrace
_TEXT	SEGMENT
_str$ = 8						; size = 4
_debuggerTrace PROC					; COMDAT

; 185  : {

	push	esi
	push	edi

; 186  :     int i;
; 187  : 
; 188  :     for (i = 0; i < MAX_DEBUGGERS; i++) {

	mov	edi, DWORD PTR _str$[esp+4]
	mov	esi, OFFSET _debuggerList
	npad	5
$LL4@debuggerTr:

; 189  :         if (debuggerList[i] != NULL) {

	mov	eax, DWORD PTR [esi]
	test	eax, eax
	je	SHORT $LN2@debuggerTr

; 190  :             debuggerList[i]->onDebugTrace(debuggerList[i]->ref, str);

	push	edi
	push	DWORD PTR [eax+28]
	mov	eax, DWORD PTR [eax+20]
	call	eax
	add	esp, 8
$LN2@debuggerTr:

; 186  :     int i;
; 187  : 
; 188  :     for (i = 0; i < MAX_DEBUGGERS; i++) {

	add	esi, 4
	cmp	esi, OFFSET _debuggerList+32
	jl	SHORT $LL4@debuggerTr

; 191  :         }
; 192  :     }
; 193  : }

	pop	edi
	pop	esi
	ret	0
_debuggerTrace ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\debugger\debugger.c
;	COMDAT _debuggerNotifyEmulatorReset
_TEXT	SEGMENT
_debuggerNotifyEmulatorReset PROC			; COMDAT

; 172  : {

	push	esi

; 173  :     int i;
; 174  :     
; 175  :     dbgState = DBG_RUNNING;

	mov	DWORD PTR _dbgState, 2
	mov	esi, OFFSET _debuggerList
$LL4@debuggerNo:

; 178  :         if (debuggerList[i] != NULL) {

	mov	eax, DWORD PTR [esi]
	test	eax, eax
	je	SHORT $LN2@debuggerNo

; 179  :             debuggerList[i]->onEmulatorReset(debuggerList[i]->ref);

	push	DWORD PTR [eax+28]
	mov	eax, DWORD PTR [eax+16]
	call	eax
	add	esp, 4
$LN2@debuggerNo:

; 176  : 
; 177  :     for (i = 0; i < MAX_DEBUGGERS; i++) {

	add	esi, 4
	cmp	esi, OFFSET _debuggerList+32
	jl	SHORT $LL4@debuggerNo

; 180  :         }
; 181  :     }
; 182  : }

	pop	esi
	ret	0
_debuggerNotifyEmulatorReset ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\debugger\debugger.c
;	COMDAT _debuggerNotifyEmulatorResume
_TEXT	SEGMENT
_debuggerNotifyEmulatorResume PROC			; COMDAT

; 159  : {

	push	esi

; 160  :     int i;
; 161  :     
; 162  :     dbgState = DBG_RUNNING;

	mov	DWORD PTR _dbgState, 2
	mov	esi, OFFSET _debuggerList
$LL4@debuggerNo:

; 165  :         if (debuggerList[i] != NULL) {

	mov	eax, DWORD PTR [esi]
	test	eax, eax
	je	SHORT $LN2@debuggerNo

; 166  :             debuggerList[i]->onEmulatorResume(debuggerList[i]->ref);

	push	DWORD PTR [eax+28]
	mov	eax, DWORD PTR [eax+12]
	call	eax
	add	esp, 4
$LN2@debuggerNo:

; 163  : 
; 164  :     for (i = 0; i < MAX_DEBUGGERS; i++) {

	add	esi, 4
	cmp	esi, OFFSET _debuggerList+32
	jl	SHORT $LL4@debuggerNo

; 167  :         }
; 168  :     }
; 169  : }

	pop	esi
	ret	0
_debuggerNotifyEmulatorResume ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\debugger\debugger.c
;	COMDAT _debuggerNotifyEmulatorPause
_TEXT	SEGMENT
_debuggerNotifyEmulatorPause PROC			; COMDAT

; 146  : {

	push	esi

; 147  :     int i;
; 148  :     
; 149  :     dbgState = DBG_PAUSED;

	mov	DWORD PTR _dbgState, 1
	mov	esi, OFFSET _debuggerList
$LL4@debuggerNo:

; 152  :         if (debuggerList[i] != NULL) {

	mov	eax, DWORD PTR [esi]
	test	eax, eax
	je	SHORT $LN2@debuggerNo

; 153  :             debuggerList[i]->onEmulatorPause(debuggerList[i]->ref);

	push	DWORD PTR [eax+28]
	mov	eax, DWORD PTR [eax+8]
	call	eax
	add	esp, 4
$LN2@debuggerNo:

; 150  : 
; 151  :     for (i = 0; i < MAX_DEBUGGERS; i++) {

	add	esi, 4
	cmp	esi, OFFSET _debuggerList+32
	jl	SHORT $LL4@debuggerNo

; 154  :         }
; 155  :     }
; 156  : }

	pop	esi
	ret	0
_debuggerNotifyEmulatorPause ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\debugger\debugger.c
;	COMDAT _debuggerNotifyEmulatorStop
_TEXT	SEGMENT
_debuggerNotifyEmulatorStop PROC			; COMDAT

; 133  : {

	push	esi

; 134  :     int i;
; 135  : 
; 136  :     dbgState = DBG_STOPPED;

	mov	DWORD PTR _dbgState, 0
	mov	esi, OFFSET _debuggerList
$LL4@debuggerNo:

; 139  :         if (debuggerList[i] != NULL) {

	mov	eax, DWORD PTR [esi]
	test	eax, eax
	je	SHORT $LN2@debuggerNo

; 140  :             debuggerList[i]->onEmulatorStop(debuggerList[i]->ref);

	push	DWORD PTR [eax+28]
	mov	eax, DWORD PTR [eax+4]
	call	eax
	add	esp, 4
$LN2@debuggerNo:

; 137  : 
; 138  :     for (i = 0; i < MAX_DEBUGGERS; i++) {

	add	esi, 4
	cmp	esi, OFFSET _debuggerList+32
	jl	SHORT $LL4@debuggerNo

; 141  :         }
; 142  :     }
; 143  : }

	pop	esi
	ret	0
_debuggerNotifyEmulatorStop ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\debugger\debugger.c
;	COMDAT _debuggerNotifyEmulatorStart
_TEXT	SEGMENT
_debuggerNotifyEmulatorStart PROC			; COMDAT

; 120  : {

	push	esi

; 121  :     int i;
; 122  :     
; 123  :     dbgState = DBG_RUNNING;

	mov	DWORD PTR _dbgState, 2
	mov	esi, OFFSET _debuggerList
$LL4@debuggerNo:

; 126  :         if (debuggerList[i] != NULL) {

	mov	eax, DWORD PTR [esi]
	test	eax, eax
	je	SHORT $LN2@debuggerNo

; 127  :             debuggerList[i]->onEmulatorStart(debuggerList[i]->ref);

	push	DWORD PTR [eax+28]
	mov	eax, DWORD PTR [eax]
	call	eax
	add	esp, 4
$LN2@debuggerNo:

; 124  : 
; 125  :     for (i = 0; i < MAX_DEBUGGERS; i++) {

	add	esi, 4
	cmp	esi, OFFSET _debuggerList+32
	jl	SHORT $LL4@debuggerNo

; 128  :         }
; 129  :     }
; 130  : }

	pop	esi
	ret	0
_debuggerNotifyEmulatorStart ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\debugger\debugger.c
;	COMDAT _dbgEnableVramAccessCheck
_TEXT	SEGMENT
_enable$ = 8						; size = 4
_dbgEnableVramAccessCheck PROC				; COMDAT

; 375  :     if (enable) {

	cmp	DWORD PTR _enable$[esp-4], 0
	je	SHORT $LN2@dbgEnableV

; 376  :         debuggerVramAccessEnable++;

	inc	DWORD PTR _debuggerVramAccessEnable

; 380  :     }
; 381  : }    

	ret	0
$LN2@dbgEnableV:

; 377  :     }
; 378  :     else {
; 379  :         debuggerVramAccessEnable--;

	dec	DWORD PTR _debuggerVramAccessEnable

; 380  :     }
; 381  : }    

	ret	0
_dbgEnableVramAccessCheck ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\debugger\debugger.c
;	COMDAT _debuggerCheckVramAccess
_TEXT	SEGMENT
_debuggerCheckVramAccess PROC				; COMDAT

; 116  :     return debuggerVramAccessEnable > 0;

	xor	eax, eax
	cmp	DWORD PTR _debuggerVramAccessEnable, eax
	setg	al

; 117  : }

	ret	0
_debuggerCheckVramAccess ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\debugger\debugger.c
;	COMDAT _dbgClearWatchpoint
_TEXT	SEGMENT
_devType$ = 8						; size = 4
_address$ = 12						; size = 4
_dbgClearWatchpoint PROC				; COMDAT

; 390  :     debugDeviceClearMemoryWatchpoint(devType, address);

	jmp	_debugDeviceClearMemoryWatchpoint
_dbgClearWatchpoint ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\debugger\debugger.c
;	COMDAT _dbgSetWatchpoint
_TEXT	SEGMENT
_devType$ = 8						; size = 4
_address$ = 12						; size = 4
_condition$ = 16					; size = 4
_referenceValue$ = 20					; size = 4
_size$ = 24						; size = 4
_dbgSetWatchpoint PROC					; COMDAT

; 385  :     debugDeviceSetMemoryWatchpoint(devType, address, condition, referenceValue, size);

	jmp	_debugDeviceSetMemoryWatchpoint
_dbgSetWatchpoint ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\debugger\debugger.c
;	COMDAT _dbgClearBreakpoint
_TEXT	SEGMENT
_address$ = 8						; size = 2
_dbgClearBreakpoint PROC				; COMDAT

; 370  :     boardClearBreakpoint(address);

	jmp	_boardClearBreakpoint
_dbgClearBreakpoint ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\debugger\debugger.c
;	COMDAT _dbgSetBreakpoint
_TEXT	SEGMENT
_address$ = 8						; size = 2
_dbgSetBreakpoint PROC					; COMDAT

; 365  :     boardSetBreakpoint(address);

	jmp	_boardSetBreakpoint
_dbgSetBreakpoint ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\debugger\debugger.c
;	COMDAT _dbgStepBack
_TEXT	SEGMENT
_dbgStepBack PROC					; COMDAT

; 358  :     if (emulatorGetState() == EMU_PAUSED) {

	call	_emulatorGetState
	cmp	eax, 1
	je	_actionEmuStepBack

; 359  :         actionEmuStepBack();
; 360  :     }
; 361  : }

	ret	0
_dbgStepBack ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\debugger\debugger.c
;	COMDAT _dbgStep
_TEXT	SEGMENT
_dbgStep PROC						; COMDAT

; 351  :     if (emulatorGetState() == EMU_PAUSED) {

	call	_emulatorGetState
	cmp	eax, 1
	je	_actionEmuStep

; 352  :         actionEmuStep();
; 353  :     }
; 354  : }

	ret	0
_dbgStep ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\debugger\debugger.c
;	COMDAT _dbgPause
_TEXT	SEGMENT
_dbgPause PROC						; COMDAT

; 344  :     if (emulatorGetState() == EMU_RUNNING) {

	call	_emulatorGetState
	test	eax, eax
	je	_actionEmuTogglePause

; 345  :         actionEmuTogglePause();
; 346  :     }
; 347  : }

	ret	0
_dbgPause ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\debugger\debugger.c
;	COMDAT _dbgStop
_TEXT	SEGMENT
_dbgStop PROC						; COMDAT

; 339  :     emulatorStop();

	jmp	_emulatorStop
_dbgStop ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\debugger\debugger.c
;	COMDAT _dbgRun
_TEXT	SEGMENT
_dbgRun	PROC						; COMDAT

; 332  :     if (emulatorGetState() != EMU_RUNNING) {

	call	_emulatorGetState
	test	eax, eax
	jne	_actionEmuTogglePause

; 333  :         actionEmuTogglePause();
; 334  :     }
; 335  : }

	ret	0
_dbgRun	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\debugger\debugger.c
;	COMDAT _dbgDeviceWriteIoPort
_TEXT	SEGMENT
_ioPorts$ = 8						; size = 4
_portIndex$ = 12					; size = 4
_value$ = 16						; size = 4
_dbgDeviceWriteIoPort PROC				; COMDAT

; 233  :     return debugDeviceWriteIoPort(ioPorts, portIndex, value);

	jmp	_debugDeviceWriteIoPort
_dbgDeviceWriteIoPort ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\debugger\debugger.c
;	COMDAT _dbgDeviceWriteRegister
_TEXT	SEGMENT
_regBank$ = 8						; size = 4
_regIndex$ = 12						; size = 4
_value$ = 16						; size = 4
_dbgDeviceWriteRegister PROC				; COMDAT

; 228  :     return debugDeviceWriteRegister(regBank, regIndex, value);

	jmp	_debugDeviceWriteRegister
_dbgDeviceWriteRegister ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\debugger\debugger.c
;	COMDAT _dbgDeviceWriteMemory
_TEXT	SEGMENT
_memoryBlock$ = 8					; size = 4
_data$ = 12						; size = 4
_startAddr$ = 16					; size = 4
_size$ = 20						; size = 4
_dbgDeviceWriteMemory PROC				; COMDAT

; 223  :     return debugDeviceWriteMemory(memoryBlock, data, startAddr, size);

	jmp	_debugDeviceWriteMemory
_dbgDeviceWriteMemory ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\debugger\debugger.c
;	COMDAT _dbgDeviceGetIoPorts
_TEXT	SEGMENT
_dbgDevice$ = 8						; size = 4
_index$ = 12						; size = 4
_dbgDeviceGetIoPorts PROC				; COMDAT

; 324  :     if (index >= dbgDevice->ioPortsCount) {

	mov	ecx, DWORD PTR _dbgDevice$[esp-4]
	mov	eax, DWORD PTR _index$[esp-4]
	cmp	eax, DWORD PTR [ecx+80]
	jl	SHORT $LN2@dbgDeviceG

; 325  :         return NULL;

	xor	eax, eax

; 328  : }

	ret	0
$LN2@dbgDeviceG:

; 326  :     }
; 327  :     return dbgDevice->ioPorts[index];

	mov	eax, DWORD PTR [ecx+eax*4+212]

; 328  : }

	ret	0
_dbgDeviceGetIoPorts ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\debugger\debugger.c
;	COMDAT _dbgDeviceGetIoPortsCount
_TEXT	SEGMENT
_dbgDevice$ = 8						; size = 4
_dbgDeviceGetIoPortsCount PROC				; COMDAT

; 319  :     return dbgDevice->ioPortsCount;

	mov	eax, DWORD PTR _dbgDevice$[esp-4]
	mov	eax, DWORD PTR [eax+80]

; 320  : }

	ret	0
_dbgDeviceGetIoPortsCount ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\debugger\debugger.c
;	COMDAT _dbgDeviceGetCallstack
_TEXT	SEGMENT
_dbgDevice$ = 8						; size = 4
_index$ = 12						; size = 4
_dbgDeviceGetCallstack PROC				; COMDAT

; 306  :     return dbgDevice->callstack != NULL ? 1 : 0;

	mov	eax, DWORD PTR _dbgDevice$[esp-4]
	xor	ecx, ecx
	mov	eax, DWORD PTR [eax+276]
	test	eax, eax
	setne	cl

; 311  :     if (index >= dbgDeviceGetCallstackCount(dbgDevice)) {

	xor	edx, edx
	cmp	DWORD PTR _index$[esp-4], ecx
	cmovge	eax, edx

; 312  :         return NULL;
; 313  :     }
; 314  :     return dbgDevice->callstack;
; 315  : }

	ret	0
_dbgDeviceGetCallstack ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\debugger\debugger.c
;	COMDAT _dbgDeviceGetCallstackCount
_TEXT	SEGMENT
_dbgDevice$ = 8						; size = 4
_dbgDeviceGetCallstackCount PROC			; COMDAT

; 306  :     return dbgDevice->callstack != NULL ? 1 : 0;

	mov	ecx, DWORD PTR _dbgDevice$[esp-4]
	xor	eax, eax
	cmp	DWORD PTR [ecx+276], eax
	setne	al

; 307  : }

	ret	0
_dbgDeviceGetCallstackCount ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\debugger\debugger.c
;	COMDAT _dbgDeviceGetRegisterBank
_TEXT	SEGMENT
_dbgDevice$ = 8						; size = 4
_index$ = 12						; size = 4
_dbgDeviceGetRegisterBank PROC				; COMDAT

; 298  :     if (index >= dbgDevice->registerBankCount) {

	mov	ecx, DWORD PTR _dbgDevice$[esp-4]
	mov	eax, DWORD PTR _index$[esp-4]
	cmp	eax, DWORD PTR [ecx+76]
	jl	SHORT $LN2@dbgDeviceG

; 299  :         return NULL;

	xor	eax, eax

; 302  : }

	ret	0
$LN2@dbgDeviceG:

; 300  :     }
; 301  :     return dbgDevice->registerBank[index];

	mov	eax, DWORD PTR [ecx+eax*4+148]

; 302  : }

	ret	0
_dbgDeviceGetRegisterBank ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\debugger\debugger.c
;	COMDAT _dbgDeviceGetRegisterBankCount
_TEXT	SEGMENT
_dbgDevice$ = 8						; size = 4
_dbgDeviceGetRegisterBankCount PROC			; COMDAT

; 293  :     return dbgDevice->registerBankCount;

	mov	eax, DWORD PTR _dbgDevice$[esp-4]
	mov	eax, DWORD PTR [eax+76]

; 294  : }

	ret	0
_dbgDeviceGetRegisterBankCount ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\debugger\debugger.c
;	COMDAT _dbgDeviceGetMemoryBlock
_TEXT	SEGMENT
_dbgDevice$ = 8						; size = 4
_index$ = 12						; size = 4
_dbgDeviceGetMemoryBlock PROC				; COMDAT

; 285  :     if (index >= dbgDevice->memoryBlockCount) {

	mov	ecx, DWORD PTR _dbgDevice$[esp-4]
	mov	eax, DWORD PTR _index$[esp-4]
	cmp	eax, DWORD PTR [ecx+72]
	jl	SHORT $LN2@dbgDeviceG

; 286  :         return NULL;

	xor	eax, eax

; 289  : }

	ret	0
$LN2@dbgDeviceG:

; 287  :     }
; 288  :     return dbgDevice->memoryBlock[index];

	mov	eax, DWORD PTR [ecx+eax*4+84]

; 289  : }

	ret	0
_dbgDeviceGetMemoryBlock ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\debugger\debugger.c
;	COMDAT _dbgDeviceGetMemoryBlockCount
_TEXT	SEGMENT
_dbgDevice$ = 8						; size = 4
_dbgDeviceGetMemoryBlockCount PROC			; COMDAT

; 280  :     return dbgDevice->memoryBlockCount;

	mov	eax, DWORD PTR _dbgDevice$[esp-4]
	mov	eax, DWORD PTR [eax+72]

; 281  : }

	ret	0
_dbgDeviceGetMemoryBlockCount ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\debugger\debugger.c
;	COMDAT _dbgSnapshotGetDevice
_TEXT	SEGMENT
_dbgSnapshot$ = 8					; size = 4
_index$ = 12						; size = 4
_dbgSnapshotGetDevice PROC				; COMDAT

; 272  :     if (index >= dbgSnapshot->count) {

	mov	ecx, DWORD PTR _dbgSnapshot$[esp-4]
	mov	eax, DWORD PTR _index$[esp-4]
	cmp	eax, DWORD PTR [ecx]
	jl	SHORT $LN2@dbgSnapsho

; 273  :         return NULL;

	xor	eax, eax

; 276  : }

	ret	0
$LN2@dbgSnapsho:

; 274  :     }
; 275  :     return dbgSnapshot->dbgDevice[index];

	mov	eax, DWORD PTR [ecx+eax*4+4]

; 276  : }

	ret	0
_dbgSnapshotGetDevice ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\debugger\debugger.c
;	COMDAT _dbgSnapshotGetDeviceCount
_TEXT	SEGMENT
_dbgSnapshot$ = 8					; size = 4
_dbgSnapshotGetDeviceCount PROC				; COMDAT

; 267  :     return dbgSnapshot->count;

	mov	eax, DWORD PTR _dbgSnapshot$[esp-4]
	mov	eax, DWORD PTR [eax]

; 268  : }

	ret	0
_dbgSnapshotGetDeviceCount ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\debugger\debugger.c
;	COMDAT _dbgGetState
_TEXT	SEGMENT
_dbgGetState PROC					; COMDAT

; 262  :     return dbgState;

	mov	eax, DWORD PTR _dbgState

; 263  : }

	ret	0
_dbgGetState ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\debugger\debugger.c
;	COMDAT _dbgSnapshotDestroy
_TEXT	SEGMENT
_dbgDevice$1$ = -4					; size = 4
_dbgSnapshot$ = 8					; size = 4
_dbgSnapshotDestroy PROC				; COMDAT

; 237  : {

	push	ecx

; 238  :     int i;
; 239  : 
; 240  :     for (i = 0; i < dbgSnapshot->count; i++) {

	mov	eax, DWORD PTR _dbgSnapshot$[esp]
	push	ebx
	xor	ebx, ebx
	cmp	DWORD PTR [eax], ebx
	jle	SHORT $LN3@dbgSnapsho
	push	ebp
	push	esi
	push	edi
	lea	ebp, DWORD PTR [eax+4]
$LL4@dbgSnapsho:

; 241  :         DbgDevice* dbgDevice = dbgSnapshot->dbgDevice[i];

	mov	eax, DWORD PTR [ebp]
	mov	edi, 16					; 00000010H
	mov	DWORD PTR _dbgDevice$1$[esp+20], eax
	lea	esi, DWORD PTR [eax+148]
$LL7@dbgSnapsho:

; 244  :             if (dbgDevice->memoryBlock[j] != NULL) {

	mov	eax, DWORD PTR [esi-64]
	test	eax, eax
	je	SHORT $LN8@dbgSnapsho

; 245  :                 free(dbgDevice->memoryBlock[j]);

	push	eax
	call	_free
	add	esp, 4
$LN8@dbgSnapsho:

; 246  :             }
; 247  :             if (dbgDevice->registerBank[j] != NULL) {

	mov	eax, DWORD PTR [esi]
	test	eax, eax
	je	SHORT $LN9@dbgSnapsho

; 248  :                 free(dbgDevice->registerBank[j]);

	push	eax
	call	_free
	add	esp, 4
$LN9@dbgSnapsho:

; 249  :             }
; 250  :             if (dbgDevice->ioPorts[j] != NULL) {

	mov	eax, DWORD PTR [esi+64]
	test	eax, eax
	je	SHORT $LN5@dbgSnapsho

; 251  :                 free(dbgDevice->ioPorts[j]);

	push	eax
	call	_free
	add	esp, 4
$LN5@dbgSnapsho:

; 242  :         int j;
; 243  :         for (j = 0; j < MAX_DBG_COMPONENTS; j++) {

	add	esi, 4
	sub	edi, 1
	jne	SHORT $LL7@dbgSnapsho

; 252  :             }
; 253  :         }
; 254  : 
; 255  :         free(dbgDevice);

	push	DWORD PTR _dbgDevice$1$[esp+20]
	call	_free
	mov	eax, DWORD PTR _dbgSnapshot$[esp+20]
	inc	ebx
	add	esp, 4
	add	ebp, 4
	cmp	ebx, DWORD PTR [eax]
	jl	SHORT $LL4@dbgSnapsho
	pop	edi
	pop	esi
	pop	ebp
$LN3@dbgSnapsho:

; 256  :     }
; 257  :     free(dbgSnapshot);

	pop	ebx

; 258  : }

	add	esp, 4

; 256  :     }
; 257  :     free(dbgSnapshot);

	mov	DWORD PTR _dbgSnapshot$[esp-4], eax
	jmp	_free
_dbgSnapshotDestroy ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\debugger\debugger.c
;	COMDAT _dbgSnapshotCreate
_TEXT	SEGMENT
_dbgSnapshotCreate PROC					; COMDAT

; 208  :     DbgSnapshot* dbgSnapshot;
; 209  :     
; 210  :     if (dbgState != DBG_PAUSED) {

	cmp	DWORD PTR _dbgState, 1
	je	SHORT $LN2@dbgSnapsho

; 211  :         return NULL;

	xor	eax, eax

; 219  : }

	ret	0
$LN2@dbgSnapsho:
	push	esi

; 212  :     }
; 213  : 
; 214  :     dbgSnapshot = malloc(sizeof(DbgSnapshot));

	push	260					; 00000104H
	call	_malloc
	mov	esi, eax

; 215  : 
; 216  :     debugDeviceGetSnapshot(dbgSnapshot->dbgDevice, &dbgSnapshot->count);

	push	esi
	lea	ecx, DWORD PTR [esi+4]
	push	ecx
	call	_debugDeviceGetSnapshot
	add	esp, 12					; 0000000cH

; 217  : 
; 218  :     return dbgSnapshot;

	mov	eax, esi
	pop	esi

; 219  : }

	ret	0
_dbgSnapshotCreate ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\debugger\debugger.c
;	COMDAT _debuggerDestroy
_TEXT	SEGMENT
_debugger$ = 8						; size = 4
_debuggerDestroy PROC					; COMDAT

; 102  :     int i;
; 103  : 
; 104  :     for (i = 0; i < MAX_DEBUGGERS; i++) {

	mov	ecx, DWORD PTR _debugger$[esp-4]
	xor	eax, eax
$LL4@debuggerDe:

; 105  :         if (debuggerList[i] == debugger) {

	cmp	DWORD PTR _debuggerList[eax*4], ecx
	je	SHORT $LN8@debuggerDe

; 102  :     int i;
; 103  : 
; 104  :     for (i = 0; i < MAX_DEBUGGERS; i++) {

	inc	eax
	cmp	eax, 8
	jl	SHORT $LL4@debuggerDe

; 107  :             break;
; 108  :         }
; 109  :     }
; 110  : 
; 111  :     free(debugger);

	mov	DWORD PTR _debugger$[esp-4], ecx
	jmp	_free
$LN8@debuggerDe:

; 106  :             debuggerList[i] = NULL;

	mov	DWORD PTR _debuggerList[eax*4], 0

; 107  :             break;
; 108  :         }
; 109  :     }
; 110  : 
; 111  :     free(debugger);

	mov	DWORD PTR _debugger$[esp-4], ecx
	jmp	_free
_debuggerDestroy ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\debugger\debugger.c
;	COMDAT _debuggerCreate
_TEXT	SEGMENT
_onEmulatorStart$ = 8					; size = 4
_onEmulatorStop$ = 12					; size = 4
_onEmulatorPause$ = 16					; size = 4
_onEmulatorResume$ = 20					; size = 4
_onEmulatorReset$ = 24					; size = 4
_onDebugTrace$ = 28					; size = 4
_onDebugSetBp$ = 32					; size = 4
_ref$ = 36						; size = 4
_debuggerCreate PROC					; COMDAT

; 76   : {

	push	esi
	push	edi

; 77   :     BlueDebugger* debugger = malloc(sizeof(BlueDebugger));

	push	32					; 00000020H
	call	_malloc

; 78   :     int i;
; 79   : 
; 80   :     debugger->onEmulatorStart  = onEmulatorStart  ? onEmulatorStart  : onDefault;

	mov	ecx, DWORD PTR _onEmulatorStart$[esp+8]
	mov	edi, eax

; 81   :     debugger->onEmulatorStop   = onEmulatorStop   ? onEmulatorStop   : onDefault;
; 82   :     debugger->onEmulatorPause  = onEmulatorPause  ? onEmulatorPause  : onDefault;

	mov	eax, DWORD PTR _onEmulatorPause$[esp+8]
	add	esp, 4
	test	ecx, ecx
	mov	esi, OFFSET _onDefault
	mov	edx, esi
	cmovne	edx, ecx
	mov	ecx, DWORD PTR _onEmulatorStop$[esp+4]
	test	ecx, ecx
	mov	DWORD PTR [edi], edx
	mov	edx, esi
	cmovne	edx, ecx
	test	eax, eax
	mov	ecx, esi
	mov	DWORD PTR [edi+4], edx
	cmovne	ecx, eax

; 83   :     debugger->onEmulatorResume = onEmulatorResume ? onEmulatorResume : onDefault;

	mov	eax, DWORD PTR _onEmulatorResume$[esp+4]
	test	eax, eax
	mov	DWORD PTR [edi+8], ecx
	mov	ecx, esi
	cmovne	ecx, eax

; 84   :     debugger->onEmulatorReset  = onEmulatorReset  ? onEmulatorReset  : onDefault;

	mov	eax, DWORD PTR _onEmulatorReset$[esp+4]
	test	eax, eax
	mov	DWORD PTR [edi+12], ecx

; 85   :     debugger->onDebugTrace     = onDebugTrace     ? onDebugTrace     : onDefTrace;

	mov	ecx, OFFSET _onDefTrace
	cmovne	esi, eax
	mov	eax, DWORD PTR _onDebugTrace$[esp+4]
	test	eax, eax
	mov	DWORD PTR [edi+16], esi
	cmovne	ecx, eax

; 86   :     debugger->onDebugSetBp     = onDebugSetBp     ? onDebugSetBp     : onDefSetBp;

	mov	eax, DWORD PTR _onDebugSetBp$[esp+4]
	test	eax, eax
	mov	DWORD PTR [edi+20], ecx
	mov	ecx, OFFSET _onDefSetBp
	cmovne	ecx, eax

; 87   :     debugger->ref = ref;

	mov	eax, DWORD PTR _ref$[esp+4]
	mov	DWORD PTR [edi+28], eax

; 88   : 
; 89   :     for (i = 0; i < MAX_DEBUGGERS; i++) {

	xor	eax, eax
	mov	DWORD PTR [edi+24], ecx
$LL4@debuggerCr:

; 90   :         if (debuggerList[i] == NULL) {

	cmp	DWORD PTR _debuggerList[eax*4], 0
	je	SHORT $LN8@debuggerCr

; 88   : 
; 89   :     for (i = 0; i < MAX_DEBUGGERS; i++) {

	inc	eax
	cmp	eax, 8
	jl	SHORT $LL4@debuggerCr

; 92   :             break;
; 93   :         }
; 94   :     }
; 95   : 
; 96   :     return debugger;
; 97   : }

	mov	eax, edi
	pop	edi
	pop	esi
	ret	0
$LN8@debuggerCr:

; 91   :             debuggerList[i] = debugger;

	mov	DWORD PTR _debuggerList[eax*4], edi

; 92   :             break;
; 93   :         }
; 94   :     }
; 95   : 
; 96   :     return debugger;
; 97   : }

	mov	eax, edi
	pop	edi
	pop	esi
	ret	0
_debuggerCreate ENDP
_TEXT	ENDS
END
