; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27054.0 

	TITLE	D:\repo\MSX-master\MSX\blueMSX-DPI\Src\Input\MsxJoystick.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_msxJoystickCreate
PUBLIC	_destroy
EXTRN	_calloc:PROC
EXTRN	_free:PROC
EXTRN	_eventMap:BYTE
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\input\msxjoystick.c
;	COMDAT _destroy
_TEXT	SEGMENT
_joystick$ = 8						; size = 4
_destroy PROC						; COMDAT

; 63   :     free(joystick);

	jmp	_free
_destroy ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\input\msxjoystick.c
;	COMDAT _read
_TEXT	SEGMENT
_joystick$ = 8						; size = 4
_read	PROC						; COMDAT

; 39   :     UInt8 state;
; 40   : 
; 41   :     if (joystick->controller == 0) {

	mov	eax, DWORD PTR _joystick$[esp-4]
	cmp	DWORD PTR [eax+24], 0
	jne	SHORT $LN2@read

; 42   :         state = (inputEventGetState(EC_JOY1_UP)      << 0) |

	mov	al, BYTE PTR _eventMap+420
	add	al, al
	or	al, BYTE PTR _eventMap+416
	add	al, al
	or	al, BYTE PTR _eventMap+412
	add	al, al
	or	al, BYTE PTR _eventMap+408
	add	al, al
	or	al, BYTE PTR _eventMap+404
	add	al, al
	or	al, BYTE PTR _eventMap+400

; 51   :                 (inputEventGetState(EC_JOY2_DOWN)    << 1) |
; 52   :                 (inputEventGetState(EC_JOY2_LEFT)    << 2) |
; 53   :                 (inputEventGetState(EC_JOY2_RIGHT)   << 3) |
; 54   :                 (inputEventGetState(EC_JOY2_BUTTON1) << 4) |
; 55   :                 (inputEventGetState(EC_JOY2_BUTTON2) << 5);
; 56   :     }
; 57   : 
; 58   :     return ~state & 0x3f;

	not	al
	and	al, 63					; 0000003fH

; 59   : }

	ret	0
$LN2@read:

; 43   :                 (inputEventGetState(EC_JOY1_DOWN)    << 1) |
; 44   :                 (inputEventGetState(EC_JOY1_LEFT)    << 2) |
; 45   :                 (inputEventGetState(EC_JOY1_RIGHT)   << 3) |
; 46   :                 (inputEventGetState(EC_JOY1_BUTTON1) << 4) |
; 47   :                 (inputEventGetState(EC_JOY1_BUTTON2) << 5);
; 48   :     }
; 49   :     else {
; 50   :         state = (inputEventGetState(EC_JOY2_UP)      << 0) |

	mov	al, BYTE PTR _eventMap+460
	add	al, al
	or	al, BYTE PTR _eventMap+456
	add	al, al
	or	al, BYTE PTR _eventMap+452
	add	al, al
	or	al, BYTE PTR _eventMap+448
	add	al, al
	or	al, BYTE PTR _eventMap+444
	add	al, al
	or	al, BYTE PTR _eventMap+440

; 51   :                 (inputEventGetState(EC_JOY2_DOWN)    << 1) |
; 52   :                 (inputEventGetState(EC_JOY2_LEFT)    << 2) |
; 53   :                 (inputEventGetState(EC_JOY2_RIGHT)   << 3) |
; 54   :                 (inputEventGetState(EC_JOY2_BUTTON1) << 4) |
; 55   :                 (inputEventGetState(EC_JOY2_BUTTON2) << 5);
; 56   :     }
; 57   : 
; 58   :     return ~state & 0x3f;

	not	al
	and	al, 63					; 0000003fH

; 59   : }

	ret	0
_read	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\input\msxjoystick.c
;	COMDAT _msxJoystickCreate
_TEXT	SEGMENT
_controller$ = 8					; size = 4
_msxJoystickCreate PROC					; COMDAT

; 68   :     MsxJoystick* joystick = (MsxJoystick*)calloc(1, sizeof(MsxJoystick));

	push	28					; 0000001cH
	push	1
	call	_calloc

; 69   :     joystick->joyDevice.read    = read;
; 70   :     joystick->joyDevice.destroy = destroy;
; 71   :     joystick->controller        = controller;

	mov	ecx, DWORD PTR _controller$[esp+4]
	add	esp, 8
	mov	DWORD PTR [eax], OFFSET _read
	mov	DWORD PTR [eax+8], OFFSET _destroy
	mov	DWORD PTR [eax+24], ecx

; 72   :     
; 73   :     return (MsxJoystickDevice*)joystick;
; 74   : }

	ret	0
_msxJoystickCreate ENDP
_TEXT	ENDS
END
