; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27054.0 

	TITLE	D:\repo\MSX-master\MSX\blueMSX-DPI\Src\IoDevice\MSXMidi.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	??_C@_05IEEKDPFI@V9938@				; `string'
PUBLIC	??_C@_05IAMHEDOK@V9958@				; `string'
PUBLIC	??_C@_08IBFDMDNO@TMS9929A@			; `string'
PUBLIC	??_C@_08HEDIBBLA@TMS99x8A@			; `string'
;	COMDAT ??_C@_08HEDIBBLA@TMS99x8A@
CONST	SEGMENT
??_C@_08HEDIBBLA@TMS99x8A@ DB 'TMS99x8A', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_08IBFDMDNO@TMS9929A@
CONST	SEGMENT
??_C@_08IBFDMDNO@TMS9929A@ DB 'TMS9929A', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_05IAMHEDOK@V9958@
CONST	SEGMENT
??_C@_05IAMHEDOK@V9958@ DB 'V9958', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_05IEEKDPFI@V9938@
CONST	SEGMENT
??_C@_05IEEKDPFI@V9938@ DB 'V9938', 00H			; `string'
CONST	ENDS
PUBLIC	_MSXMidiCreate
PUBLIC	??_C@_07MHAJBJHJ@MSXMidi@			; `string'
PUBLIC	??_C@_0O@JDPPJMM@timerIRQlatch@			; `string'
PUBLIC	??_C@_0BA@OELNDKKA@timerIRQenabled@		; `string'
PUBLIC	??_C@_0O@NPIOJLJP@rxrdyIRQlatch@		; `string'
PUBLIC	??_C@_0BA@NGJHOCPC@rxrdyIRQenabled@		; `string'
PUBLIC	??_C@_07DBHDALPG@ioStart@			; `string'
EXTRN	_midiIoCreate:PROC
EXTRN	_midiIoDestroy:PROC
EXTRN	_midiIoTransmit:PROC
EXTRN	_deviceManagerRegister:PROC
EXTRN	_deviceManagerUnregister:PROC
EXTRN	_debugDeviceRegister:PROC
EXTRN	_debugDeviceUnregister:PROC
EXTRN	_dbgDeviceAddIoPorts:PROC
EXTRN	_dbgIoPortsAddPort:PROC
EXTRN	_saveStateOpenForRead:PROC
EXTRN	_saveStateOpenForWrite:PROC
EXTRN	_saveStateClose:PROC
EXTRN	_saveStateGet:PROC
EXTRN	_saveStateSet:PROC
EXTRN	_boardSetInt:PROC
EXTRN	_boardClearInt:PROC
EXTRN	_boardGetInt:PROC
EXTRN	_ioPortRegister:PROC
EXTRN	_ioPortUnregister:PROC
EXTRN	_archMidiLoadState:PROC
EXTRN	_archMidiSaveState:PROC
EXTRN	_langDbgDevMsxMidi:PROC
EXTRN	_i8251Peek:PROC
EXTRN	_i8251Read:PROC
EXTRN	_i8251Write:PROC
EXTRN	_i8251RxData:PROC
EXTRN	_i8251LoadState:PROC
EXTRN	_i8251SaveState:PROC
EXTRN	_i8251Reset:PROC
EXTRN	_i8251Destroy:PROC
EXTRN	_i8251Create:PROC
EXTRN	_i8254Peek:PROC
EXTRN	_i8254Read:PROC
EXTRN	_i8254Write:PROC
EXTRN	_i8254LoadState:PROC
EXTRN	_i8254SaveState:PROC
EXTRN	_i8254Reset:PROC
EXTRN	_i8254Destroy:PROC
EXTRN	_i8254SetGate:PROC
EXTRN	_i8254Create:PROC
EXTRN	_free:PROC
EXTRN	_malloc:PROC
;	COMDAT ??_C@_07DBHDALPG@ioStart@
CONST	SEGMENT
??_C@_07DBHDALPG@ioStart@ DB 'ioStart', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_0BA@NGJHOCPC@rxrdyIRQenabled@
CONST	SEGMENT
??_C@_0BA@NGJHOCPC@rxrdyIRQenabled@ DB 'rxrdyIRQenabled', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0O@NPIOJLJP@rxrdyIRQlatch@
CONST	SEGMENT
??_C@_0O@NPIOJLJP@rxrdyIRQlatch@ DB 'rxrdyIRQlatch', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BA@OELNDKKA@timerIRQenabled@
CONST	SEGMENT
??_C@_0BA@OELNDKKA@timerIRQenabled@ DB 'timerIRQenabled', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0O@JDPPJMM@timerIRQlatch@
CONST	SEGMENT
??_C@_0O@JDPPJMM@timerIRQlatch@ DB 'timerIRQlatch', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_07MHAJBJHJ@MSXMidi@
CONST	SEGMENT
??_C@_07MHAJBJHJ@MSXMidi@ DB 'MSXMidi', 00H		; `string'
CONST	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\iodevice\msxmidi.c
;	COMDAT _midiInCallback
_TEXT	SEGMENT
_msxMidi$ = 8						; size = 4
_buffer$ = 12						; size = 4
_length$ = 16						; size = 4
_midiInCallback PROC					; COMDAT

; 409  : {

	push	esi

; 410  :     while (length--) {

	mov	esi, DWORD PTR _length$[esp]
	test	esi, esi
	je	SHORT $LN6@midiInCall
	push	ebx
	mov	ebx, DWORD PTR _msxMidi$[esp+4]
	push	edi
	mov	edi, DWORD PTR _buffer$[esp+8]
$LL2@midiInCall:

; 411  :         i8251RxData(msxMidi->i8251, *buffer++);

	movzx	eax, BYTE PTR [edi]
	push	eax
	push	DWORD PTR [ebx+12]
	call	_i8251RxData
	add	esp, 8
	lea	edi, DWORD PTR [edi+1]
	sub	esi, 1
	jne	SHORT $LL2@midiInCall
	pop	edi
	pop	ebx
$LN6@midiInCall:
	pop	esi

; 412  :     }
; 413  : }

	ret	0
_midiInCallback ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\iodevice\msxmidi.c
;	COMDAT _getDebugInfo
_TEXT	SEGMENT
_ioPorts$1$ = -4					; size = 4
$T1 = 8							; size = 1
_msxMidi$ = 8						; size = 4
_dbgDevice$ = 12					; size = 4
_getDebugInfo PROC					; COMDAT

; 388  : {

	push	ecx
	push	ebx
	push	ebp
	push	esi

; 389  :     DbgIoPorts* ioPorts;
; 390  :     int i;
; 391  :     int externalPorts = msxMidi->isExternal ? 1 : 0;

	mov	esi, DWORD PTR _msxMidi$[esp+12]
	xor	eax, eax
	push	edi
	mov	edi, DWORD PTR [esi+24]
	test	edi, edi

; 392  :     int mappedPorts = 0;
; 393  : 
; 394  :     if (msxMidi->ioStart != 0) {

	mov	ecx, DWORD PTR [esi+20]
	setne	al
	xor	ebp, ebp
	test	ecx, ecx
	je	SHORT $LN5@getDebugIn

; 395  :         mappedPorts = (msxMidi->ioStart == 0xe0 ? 2 : 8);

	cmp	ecx, 224				; 000000e0H
	mov	ebp, 8
	mov	edx, 2
	cmove	ebp, edx
$LN5@getDebugIn:

; 396  :     }
; 397  :     ioPorts = dbgDeviceAddIoPorts(dbgDevice, langDbgDevMsxMidi(), externalPorts + mappedPorts);

	add	eax, ebp
	push	eax
	call	_langDbgDevMsxMidi
	push	eax
	push	DWORD PTR _dbgDevice$[esp+24]
	call	_dbgDeviceAddIoPorts
	add	esp, 12					; 0000000cH
	mov	ebx, eax
	mov	DWORD PTR _ioPorts$1$[esp+20], ebx

; 398  : 
; 399  :     if (externalPorts != 0) {

	test	edi, edi
	je	SHORT $LN6@getDebugIn

; 400  :         dbgIoPortsAddPort(ioPorts, mappedPorts, 0xe2, DBG_IO_READWRITE, peekIo(msxMidi, 0xe2));

	push	226					; 000000e2H
	push	esi
	call	_peekIo
	movzx	ecx, al
	push	ecx
	push	3
	push	226					; 000000e2H
	push	ebp
	push	ebx
	call	_dbgIoPortsAddPort
	add	esp, 28					; 0000001cH
$LN6@getDebugIn:

; 401  :     }
; 402  : 
; 403  :     for (i = 0; i < mappedPorts; i++) {

	xor	edi, edi
	test	ebp, ebp
	je	SHORT $LN3@getDebugIn
$LL4@getDebugIn:

; 404  :         dbgIoPortsAddPort(ioPorts, i, msxMidi->ioStart + i, DBG_IO_READWRITE, peekIo(msxMidi, msxMidi->ioStart + i));

	mov	ax, WORD PTR [esi+20]
	movzx	ebx, di
	add	ax, bx
	movzx	ecx, ax

; 313  : 	switch (ioPort & 7) {

	mov	eax, ecx
	and	eax, 7
	jmp	DWORD PTR $LN21@getDebugIn[eax*4]
$LN11@getDebugIn:

; 314  : 		case 0: // UART data register
; 315  : 		case 1: // UART status register
; 316  : 			return i8251Peek(msxMidi->i8251, ioPort & 3);

	and	ecx, 3
	push	ecx
	push	DWORD PTR [esi+12]
	call	_i8251Peek

; 404  :         dbgIoPortsAddPort(ioPorts, i, msxMidi->ioStart + i, DBG_IO_READWRITE, peekIo(msxMidi, msxMidi->ioStart + i));

	mov	BYTE PTR $T1[esp+24], al
	add	esp, 8
	jmp	SHORT $LN8@getDebugIn
$LN13@getDebugIn:

; 325  : 			return i8254Peek(msxMidi->i8254, ioPort & 3);

	and	ecx, 3
	push	ecx
	push	DWORD PTR [esi+16]
	call	_i8254Peek

; 404  :         dbgIoPortsAddPort(ioPorts, i, msxMidi->ioStart + i, DBG_IO_READWRITE, peekIo(msxMidi, msxMidi->ioStart + i));

	mov	BYTE PTR $T1[esp+24], al
	add	esp, 8
	jmp	SHORT $LN8@getDebugIn
$LN9@getDebugIn:
	mov	BYTE PTR $T1[esp+16], 255		; 000000ffH
$LN8@getDebugIn:
	push	DWORD PTR $T1[esp+16]
	mov	ax, WORD PTR [esi+20]
	add	ax, bx
	push	3
	movzx	eax, ax
	push	eax
	push	edi
	push	DWORD PTR _ioPorts$1$[esp+36]
	call	_dbgIoPortsAddPort
	inc	edi
	add	esp, 20					; 00000014H
	cmp	edi, ebp
	jl	SHORT $LL4@getDebugIn
$LN3@getDebugIn:
	pop	edi

; 405  :     }
; 406  : }

	pop	esi
	pop	ebp
	pop	ebx
	pop	ecx
	ret	0
	npad	3
$LN21@getDebugIn:
	DD	$LN11@getDebugIn
	DD	$LN11@getDebugIn
	DD	$LN9@getDebugIn
	DD	$LN9@getDebugIn
	DD	$LN13@getDebugIn
	DD	$LN13@getDebugIn
	DD	$LN13@getDebugIn
	DD	$LN13@getDebugIn
_getDebugInfo ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\iodevice\msxmidi.c
;	COMDAT _peekIo
_TEXT	SEGMENT
_msxMidi$ = 8						; size = 4
_ioPort$ = 12						; size = 2
_peekIo	PROC						; COMDAT

; 313  : 	switch (ioPort & 7) {

	mov	ecx, DWORD PTR _ioPort$[esp-4]
	mov	eax, ecx
	and	eax, 7
	jmp	DWORD PTR $LN9@peekIo[eax*4]
$LN4@peekIo:

; 314  : 		case 0: // UART data register
; 315  : 		case 1: // UART status register
; 316  : 			return i8251Peek(msxMidi->i8251, ioPort & 3);

	mov	eax, DWORD PTR _msxMidi$[esp-4]
	and	ecx, 3
	push	ecx
	push	DWORD PTR [eax+12]
	call	_i8251Peek
	add	esp, 8

; 328  : }

	ret	0
$LN6@peekIo:

; 317  : 			break;
; 318  : 		case 2: // timer interrupt flag off
; 319  : 		case 3: // no function
; 320  : 			return 0xff;
; 321  : 		case 4: // counter 0 data port
; 322  : 		case 5: // counter 1 data port
; 323  : 		case 6: // counter 2 data port
; 324  : 		case 7: // timer command register
; 325  : 			return i8254Peek(msxMidi->i8254, ioPort & 3);

	mov	eax, DWORD PTR _msxMidi$[esp-4]
	and	ecx, 3
	push	ecx
	push	DWORD PTR [eax+16]
	call	_i8254Peek
	add	esp, 8

; 328  : }

	ret	0
$LN2@peekIo:

; 326  : 	}
; 327  : 	return 0xff;

	or	al, 255					; 000000ffH

; 328  : }

	ret	0
	npad	1
$LN9@peekIo:
	DD	$LN4@peekIo
	DD	$LN4@peekIo
	DD	$LN2@peekIo
	DD	$LN2@peekIo
	DD	$LN6@peekIo
	DD	$LN6@peekIo
	DD	$LN6@peekIo
	DD	$LN6@peekIo
_peekIo	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\iodevice\msxmidi.c
;	COMDAT _registerIoPorts
_TEXT	SEGMENT
_msxMidi$ = 8						; size = 4
_ioStart$ = 12						; size = 4
_registerIoPorts PROC					; COMDAT

; 288  : static void registerIoPorts(MSXMidi* msxMidi, int ioStart) {

	push	ebx

; 289  :     int i;
; 290  : 
; 291  :     if (msxMidi->ioStart == ioStart) {

	mov	ebx, DWORD PTR _ioStart$[esp]
	push	edi
	mov	edi, DWORD PTR _msxMidi$[esp+4]
	mov	eax, DWORD PTR [edi+20]
	cmp	eax, ebx
	je	SHORT $LN8@registerIo

; 292  :         return;
; 293  :     }
; 294  : 
; 295  :     if (msxMidi->ioStart != 0) {

	test	eax, eax
	je	SHORT $LN5@registerIo

; 296  :         unregisterIoPorts(msxMidi);

	push	edi
	call	_unregisterIoPorts
	add	esp, 4
$LN5@registerIo:

; 297  :     }
; 298  : 
; 299  :     msxMidi->ioStart = ioStart;
; 300  : 
; 301  :     i = msxMidi->ioStart == 0xe0 ? 2 : 8;

	push	esi
	cmp	ebx, 224				; 000000e0H
	mov	DWORD PTR [edi+20], ebx
	mov	esi, 8
	mov	eax, 2
	cmove	esi, eax
$LL10@registerIo:

; 302  :     while (i--) {
; 303  :         ioPortRegister(ioStart + i, readIo, writeIo, msxMidi);

	push	edi
	dec	esi
	push	OFFSET _writeIo
	push	OFFSET _readIo
	lea	eax, DWORD PTR [esi+ebx]
	push	eax
	call	_ioPortRegister
	add	esp, 16					; 00000010H
	test	esi, esi
	jne	SHORT $LL10@registerIo
	pop	esi
$LN8@registerIo:
	pop	edi

; 304  :     }
; 305  : }

	pop	ebx
	ret	0
_registerIoPorts ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\iodevice\msxmidi.c
;	COMDAT _pitOut2
_TEXT	SEGMENT
_msxMidi$ = 8						; size = 4
_state$ = 12						; size = 4
_pitOut2 PROC						; COMDAT

; 266  : {

	push	esi

; 145  : 	if (msxMidi->timerIRQlatch != status) {

	mov	esi, DWORD PTR _msxMidi$[esp]
	cmp	DWORD PTR [esi+28], 1
	je	SHORT $LN4@pitOut2

; 146  : 		msxMidi->timerIRQlatch = status;
; 147  : 		if (msxMidi->timerIRQenabled) {

	mov	eax, DWORD PTR [esi+32]
	mov	DWORD PTR [esi+28], 1
	test	eax, eax
	je	SHORT $LN9@pitOut2

; 148  : 			if (msxMidi->timerIRQlatch) {
; 149  :                 boardSetInt(INT_TMR);

	push	256					; 00000100H
	call	_boardSetInt
	mov	eax, DWORD PTR [esi+32]
	add	esp, 4

; 150  : 			} 
; 151  :             else {
; 152  :                 boardClearInt(INT_TMR);
; 153  : 			}
; 154  : 		}
; 155  : 
; 156  :         i8254SetGate(msxMidi->i8254, 2, msxMidi->timerIRQenabled && !msxMidi->timerIRQlatch);

	test	eax, eax
	je	SHORT $LN9@pitOut2
	cmp	DWORD PTR [esi+28], 0
	jne	SHORT $LN9@pitOut2
	mov	eax, 1
	push	eax
	push	2
	push	DWORD PTR [esi+16]
	call	_i8254SetGate
	add	esp, 12					; 0000000cH
	pop	esi

; 267  :     setTimerIRQ(msxMidi, 1);
; 268  : }

	ret	0
$LN9@pitOut2:

; 156  :         i8254SetGate(msxMidi->i8254, 2, msxMidi->timerIRQenabled && !msxMidi->timerIRQlatch);

	xor	eax, eax
	push	eax
	push	2
	push	DWORD PTR [esi+16]
	call	_i8254SetGate
	add	esp, 12					; 0000000cH
$LN4@pitOut2:
	pop	esi

; 267  :     setTimerIRQ(msxMidi, 1);
; 268  : }

	ret	0
_pitOut2 ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\iodevice\msxmidi.c
;	COMDAT _pitOut1
_TEXT	SEGMENT
_msxMidi$ = 8						; size = 4
_state$ = 12						; size = 4
_pitOut1 PROC						; COMDAT

; 263  : }

	ret	0
_pitOut1 ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\iodevice\msxmidi.c
;	COMDAT _pitOut0
_TEXT	SEGMENT
_msxMidi$ = 8						; size = 4
_state$ = 12						; size = 4
_pitOut0 PROC						; COMDAT

; 259  : }

	ret	0
_pitOut0 ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\iodevice\msxmidi.c
;	COMDAT _getRts
_TEXT	SEGMENT
_msxMidi$ = 8						; size = 4
_getRts	PROC						; COMDAT

; 250  :     return 1;

	mov	eax, 1

; 251  : }

	ret	0
_getRts	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\iodevice\msxmidi.c
;	COMDAT _getDtr
_TEXT	SEGMENT
_msxMidi$ = 8						; size = 4
_getDtr	PROC						; COMDAT

; 245  :     return boardGetInt(INT_TMR) ? 1 : 0;

	push	256					; 00000100H
	call	_boardGetInt
	add	esp, 4
	neg	eax
	sbb	eax, eax
	neg	eax

; 246  : }

	ret	0
_getDtr	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\iodevice\msxmidi.c
;	COMDAT _setRts
_TEXT	SEGMENT
_msxMidi$ = 8						; size = 4
_status$ = 12						; size = 4
_setRts	PROC						; COMDAT

; 193  : 	if (msxMidi->rxrdyIRQenabled != enabled) {

	mov	eax, DWORD PTR _msxMidi$[esp-4]
	mov	ecx, DWORD PTR _status$[esp-4]
	cmp	DWORD PTR [eax+40], ecx
	je	SHORT $LN5@setRts

; 194  : 		msxMidi->rxrdyIRQenabled = enabled;

	mov	DWORD PTR [eax+40], ecx

; 195  : 		if (!msxMidi->rxrdyIRQenabled && msxMidi->rxrdyIRQlatch) {

	test	ecx, ecx
	jne	SHORT $LN5@setRts
	cmp	DWORD PTR [eax+36], ecx
	je	SHORT $LN5@setRts

; 196  :             boardClearInt(INT_RXRDY);

	push	512					; 00000200H
	call	_boardClearInt
	pop	ecx
$LN5@setRts:

; 240  :     enableRxRDYIRQ(msxMidi, status);
; 241  : }

	ret	0
_setRts	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\iodevice\msxmidi.c
;	COMDAT _setDtr
_TEXT	SEGMENT
_msxMidi$ = 8						; size = 4
_status$ = 12						; size = 4
_setDtr	PROC						; COMDAT

; 162  : 	if (msxMidi->timerIRQenabled != enabled) {

	mov	eax, DWORD PTR _status$[esp-4]

; 234  : {

	push	esi

; 162  : 	if (msxMidi->timerIRQenabled != enabled) {

	mov	esi, DWORD PTR _msxMidi$[esp]
	cmp	DWORD PTR [esi+32], eax
	je	SHORT $LN4@setDtr

; 163  : 		msxMidi->timerIRQenabled = enabled;
; 164  : 		if (msxMidi->timerIRQlatch) {

	cmp	DWORD PTR [esi+28], 0
	mov	DWORD PTR [esi+32], eax
	je	SHORT $LN7@setDtr

; 165  : 			if (msxMidi->timerIRQenabled) {

	push	256					; 00000100H
	test	eax, eax
	je	SHORT $LN6@setDtr

; 166  :                 boardSetInt(INT_TMR);

	call	_boardSetInt

; 167  : 			} 

	jmp	SHORT $LN11@setDtr
$LN6@setDtr:

; 168  :             else {
; 169  :                 boardClearInt(INT_TMR);

	call	_boardClearInt
$LN11@setDtr:

; 170  : 			}
; 171  : 		}
; 172  :         i8254SetGate(msxMidi->i8254, 2, msxMidi->timerIRQenabled && !msxMidi->timerIRQlatch);

	add	esp, 4
$LN7@setDtr:
	cmp	DWORD PTR [esi+32], 0
	je	SHORT $LN9@setDtr
	cmp	DWORD PTR [esi+28], 0
	jne	SHORT $LN9@setDtr
	mov	eax, 1
	push	eax
	push	2
	push	DWORD PTR [esi+16]
	call	_i8254SetGate
	add	esp, 12					; 0000000cH
	pop	esi

; 235  :     enableTimerIRQ(msxMidi, status);
; 236  : }

	ret	0
$LN9@setDtr:

; 172  :         i8254SetGate(msxMidi->i8254, 2, msxMidi->timerIRQenabled && !msxMidi->timerIRQlatch);

	xor	eax, eax
	push	eax
	push	2
	push	DWORD PTR [esi+16]
	call	_i8254SetGate
	add	esp, 12					; 0000000cH
$LN4@setDtr:
	pop	esi

; 235  :     enableTimerIRQ(msxMidi, status);
; 236  : }

	ret	0
_setDtr	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\iodevice\msxmidi.c
;	COMDAT _setRxReady
_TEXT	SEGMENT
_msxMidi$ = 8						; size = 4
_status$ = 12						; size = 4
_setRxReady PROC					; COMDAT

; 178  : 	if (msxMidi->rxrdyIRQlatch != status) {

	mov	ecx, DWORD PTR _msxMidi$[esp-4]
	mov	eax, DWORD PTR _status$[esp-4]
	cmp	DWORD PTR [ecx+36], eax
	je	SHORT $LN7@setRxReady

; 179  : 		msxMidi->rxrdyIRQlatch = status;
; 180  : 		if (msxMidi->rxrdyIRQenabled) {

	cmp	DWORD PTR [ecx+40], 0
	mov	DWORD PTR [ecx+36], eax
	je	SHORT $LN7@setRxReady

; 181  : 			if (msxMidi->rxrdyIRQlatch) {

	push	512					; 00000200H
	test	eax, eax
	je	SHORT $LN6@setRxReady

; 182  :                 boardSetInt(INT_RXRDY);

	call	_boardSetInt
	add	esp, 4

; 230  :     setRxRDYIRQ(msxMidi, status);
; 231  : }

	ret	0
$LN6@setRxReady:

; 185  :                 boardClearInt(INT_RXRDY);

	call	_boardClearInt
	pop	ecx
$LN7@setRxReady:

; 230  :     setRxRDYIRQ(msxMidi, status);
; 231  : }

	ret	0
_setRxReady ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\iodevice\msxmidi.c
;	COMDAT _setParity
_TEXT	SEGMENT
_msxMidi$ = 8						; size = 4
_value$ = 12						; size = 4
_setParity PROC						; COMDAT

; 226  : }

	ret	0
_setParity ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\iodevice\msxmidi.c
;	COMDAT _setStopBits
_TEXT	SEGMENT
_msxMidi$ = 8						; size = 4
_value$ = 12						; size = 4
_setStopBits PROC					; COMDAT

; 222  : }

	ret	0
_setStopBits ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\iodevice\msxmidi.c
;	COMDAT _setDataBits
_TEXT	SEGMENT
_msxMidi$ = 8						; size = 4
_value$ = 12						; size = 4
_setDataBits PROC					; COMDAT

; 218  : }

	ret	0
_setDataBits ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\iodevice\msxmidi.c
;	COMDAT _signal8251
_TEXT	SEGMENT
_msxMidi$ = 8						; size = 4
_signal8251 PROC					; COMDAT

; 213  :     return 0;

	xor	eax, eax

; 214  : }

	ret	0
_signal8251 ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\iodevice\msxmidi.c
;	COMDAT _transmit
_TEXT	SEGMENT
_msxMidi$ = 8						; size = 4
_value$ = 12						; size = 1
_transmit PROC						; COMDAT

; 207  :     midiIoTransmit(msxMidi->midiIo, value);

	mov	eax, DWORD PTR _msxMidi$[esp-4]
	push	DWORD PTR _value$[esp-4]
	push	DWORD PTR [eax+8]
	call	_midiIoTransmit
	add	esp, 8

; 208  :     return 1;

	mov	eax, 1

; 209  : }

	ret	0
_transmit ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\iodevice\msxmidi.c
;	COMDAT _enableRxRDYIRQ
_TEXT	SEGMENT
_msxMidi$ = 8						; size = 4
_enabled$ = 12						; size = 4
_enableRxRDYIRQ PROC					; COMDAT

; 193  : 	if (msxMidi->rxrdyIRQenabled != enabled) {

	mov	eax, DWORD PTR _msxMidi$[esp-4]
	mov	ecx, DWORD PTR _enabled$[esp-4]
	cmp	DWORD PTR [eax+40], ecx
	je	SHORT $LN3@enableRxRD

; 194  : 		msxMidi->rxrdyIRQenabled = enabled;

	mov	DWORD PTR [eax+40], ecx

; 195  : 		if (!msxMidi->rxrdyIRQenabled && msxMidi->rxrdyIRQlatch) {

	test	ecx, ecx
	jne	SHORT $LN3@enableRxRD
	cmp	DWORD PTR [eax+36], ecx
	je	SHORT $LN3@enableRxRD

; 196  :             boardClearInt(INT_RXRDY);

	push	512					; 00000200H
	call	_boardClearInt
	pop	ecx
$LN3@enableRxRD:

; 197  : 		}
; 198  : 	}
; 199  : }

	ret	0
_enableRxRDYIRQ ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\iodevice\msxmidi.c
;	COMDAT _setRxRDYIRQ
_TEXT	SEGMENT
_msxMidi$ = 8						; size = 4
_status$ = 12						; size = 4
_setRxRDYIRQ PROC					; COMDAT

; 178  : 	if (msxMidi->rxrdyIRQlatch != status) {

	mov	ecx, DWORD PTR _msxMidi$[esp-4]
	mov	eax, DWORD PTR _status$[esp-4]
	cmp	DWORD PTR [ecx+36], eax
	je	SHORT $LN5@setRxRDYIR

; 179  : 		msxMidi->rxrdyIRQlatch = status;
; 180  : 		if (msxMidi->rxrdyIRQenabled) {

	cmp	DWORD PTR [ecx+40], 0
	mov	DWORD PTR [ecx+36], eax
	je	SHORT $LN5@setRxRDYIR

; 181  : 			if (msxMidi->rxrdyIRQlatch) {

	push	512					; 00000200H
	test	eax, eax
	je	SHORT $LN4@setRxRDYIR

; 182  :                 boardSetInt(INT_RXRDY);

	call	_boardSetInt
	add	esp, 4

; 186  : 			}
; 187  : 		}
; 188  : 	}
; 189  : }

	ret	0
$LN4@setRxRDYIR:

; 183  : 			}
; 184  :             else {
; 185  :                 boardClearInt(INT_RXRDY);

	call	_boardClearInt
	pop	ecx
$LN5@setRxRDYIR:

; 186  : 			}
; 187  : 		}
; 188  : 	}
; 189  : }

	ret	0
_setRxRDYIRQ ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\iodevice\msxmidi.c
;	COMDAT _enableTimerIRQ
_TEXT	SEGMENT
_msxMidi$ = 8						; size = 4
_enabled$ = 12						; size = 4
_enableTimerIRQ PROC					; COMDAT

; 162  : 	if (msxMidi->timerIRQenabled != enabled) {

	mov	eax, DWORD PTR _enabled$[esp-4]
	push	esi
	mov	esi, DWORD PTR _msxMidi$[esp]
	cmp	DWORD PTR [esi+32], eax
	je	SHORT $LN2@enableTime

; 163  : 		msxMidi->timerIRQenabled = enabled;
; 164  : 		if (msxMidi->timerIRQlatch) {

	cmp	DWORD PTR [esi+28], 0
	mov	DWORD PTR [esi+32], eax
	je	SHORT $LN5@enableTime

; 165  : 			if (msxMidi->timerIRQenabled) {

	push	256					; 00000100H
	test	eax, eax
	je	SHORT $LN4@enableTime

; 166  :                 boardSetInt(INT_TMR);

	call	_boardSetInt

; 167  : 			} 

	jmp	SHORT $LN9@enableTime
$LN4@enableTime:

; 168  :             else {
; 169  :                 boardClearInt(INT_TMR);

	call	_boardClearInt
$LN9@enableTime:

; 170  : 			}
; 171  : 		}
; 172  :         i8254SetGate(msxMidi->i8254, 2, msxMidi->timerIRQenabled && !msxMidi->timerIRQlatch);

	add	esp, 4
$LN5@enableTime:
	cmp	DWORD PTR [esi+32], 0
	je	SHORT $LN7@enableTime
	cmp	DWORD PTR [esi+28], 0
	jne	SHORT $LN7@enableTime
	mov	eax, 1
	push	eax
	push	2
	push	DWORD PTR [esi+16]
	call	_i8254SetGate
	add	esp, 12					; 0000000cH
	pop	esi

; 173  : 	}
; 174  : }

	ret	0
$LN7@enableTime:

; 170  : 			}
; 171  : 		}
; 172  :         i8254SetGate(msxMidi->i8254, 2, msxMidi->timerIRQenabled && !msxMidi->timerIRQlatch);

	xor	eax, eax
	push	eax
	push	2
	push	DWORD PTR [esi+16]
	call	_i8254SetGate
	add	esp, 12					; 0000000cH
$LN2@enableTime:

; 173  : 	}
; 174  : }

	pop	esi
	ret	0
_enableTimerIRQ ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\iodevice\msxmidi.c
;	COMDAT _setTimerIRQ
_TEXT	SEGMENT
_msxMidi$ = 8						; size = 4
_status$ = 12						; size = 4
_setTimerIRQ PROC					; COMDAT

; 145  : 	if (msxMidi->timerIRQlatch != status) {

	mov	eax, DWORD PTR _status$[esp-4]
	push	esi
	mov	esi, DWORD PTR _msxMidi$[esp]
	cmp	DWORD PTR [esi+28], eax
	je	SHORT $LN2@setTimerIR

; 146  : 		msxMidi->timerIRQlatch = status;
; 147  : 		if (msxMidi->timerIRQenabled) {

	cmp	DWORD PTR [esi+32], 0
	mov	DWORD PTR [esi+28], eax
	je	SHORT $LN7@setTimerIR

; 148  : 			if (msxMidi->timerIRQlatch) {

	push	256					; 00000100H
	test	eax, eax
	je	SHORT $LN4@setTimerIR

; 149  :                 boardSetInt(INT_TMR);

	call	_boardSetInt

; 150  : 			} 

	jmp	SHORT $LN10@setTimerIR
$LN4@setTimerIR:

; 151  :             else {
; 152  :                 boardClearInt(INT_TMR);

	call	_boardClearInt
$LN10@setTimerIR:

; 153  : 			}
; 154  : 		}
; 155  : 
; 156  :         i8254SetGate(msxMidi->i8254, 2, msxMidi->timerIRQenabled && !msxMidi->timerIRQlatch);

	add	esp, 4
	cmp	DWORD PTR [esi+32], 0
	je	SHORT $LN7@setTimerIR
	cmp	DWORD PTR [esi+28], 0
	jne	SHORT $LN7@setTimerIR
	mov	eax, 1
	push	eax
	push	2
	push	DWORD PTR [esi+16]
	call	_i8254SetGate
	add	esp, 12					; 0000000cH
	pop	esi

; 157  : 	}
; 158  : }

	ret	0
$LN7@setTimerIR:

; 153  : 			}
; 154  : 		}
; 155  : 
; 156  :         i8254SetGate(msxMidi->i8254, 2, msxMidi->timerIRQenabled && !msxMidi->timerIRQlatch);

	xor	eax, eax
	push	eax
	push	2
	push	DWORD PTR [esi+16]
	call	_i8254SetGate
	add	esp, 12					; 0000000cH
$LN2@setTimerIR:

; 157  : 	}
; 158  : }

	pop	esi
	ret	0
_setTimerIRQ ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\iodevice\msxmidi.c
;	COMDAT _reset
_TEXT	SEGMENT
_msxMidi$ = 8						; size = 4
_reset	PROC						; COMDAT

; 125  : {

	push	esi

; 126  :     boardClearInt(INT_TMR);

	push	256					; 00000100H
	call	_boardClearInt

; 127  :     boardClearInt(INT_RXRDY);

	push	512					; 00000200H
	call	_boardClearInt

; 128  : 
; 129  : 	msxMidi->timerIRQlatch   = 0;

	mov	esi, DWORD PTR _msxMidi$[esp+8]
	add	esp, 8

; 130  : 	msxMidi->timerIRQenabled = 0;
; 131  : 	msxMidi->rxrdyIRQlatch   = 0;
; 132  : 	msxMidi->rxrdyIRQenabled = 0;
; 133  : 
; 134  :     if (msxMidi->isExternal) {

	cmp	DWORD PTR [esi+24], 0
	mov	DWORD PTR [esi+28], 0
	mov	DWORD PTR [esi+32], 0
	mov	DWORD PTR [esi+36], 0
	mov	DWORD PTR [esi+40], 0
	je	SHORT $LN2@reset

; 135  :         unregisterIoPorts(msxMidi);

	push	esi
	call	_unregisterIoPorts
	add	esp, 4
$LN2@reset:

; 136  :     }
; 137  : 
; 138  :     i8251Reset(msxMidi->i8251);

	push	DWORD PTR [esi+12]
	call	_i8251Reset

; 139  :     i8254Reset(msxMidi->i8254);

	push	DWORD PTR [esi+16]
	call	_i8254Reset
	add	esp, 8
	pop	esi

; 140  : }

	ret	0
_reset	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\iodevice\msxmidi.c
;	COMDAT _destroy
_TEXT	SEGMENT
_msxMidi$ = 8						; size = 4
_destroy PROC						; COMDAT

; 109  : {

	push	esi

; 110  :     ioPortUnregister(0xe2);

	push	226					; 000000e2H
	call	_ioPortUnregister

; 111  :     unregisterIoPorts(msxMidi);

	mov	esi, DWORD PTR _msxMidi$[esp+4]
	push	esi
	call	_unregisterIoPorts

; 112  : 
; 113  :     midiIoDestroy(msxMidi->midiIo);

	push	DWORD PTR [esi+8]
	call	_midiIoDestroy

; 114  :     
; 115  :     i8251Destroy(msxMidi->i8251);

	push	DWORD PTR [esi+12]
	call	_i8251Destroy

; 116  :     i8254Destroy(msxMidi->i8254);

	push	DWORD PTR [esi+16]
	call	_i8254Destroy

; 117  : 
; 118  :     deviceManagerUnregister(msxMidi->deviceHandle);

	push	DWORD PTR [esi]
	call	_deviceManagerUnregister

; 119  :     debugDeviceUnregister(msxMidi->debugHandle);

	push	DWORD PTR [esi+4]
	call	_debugDeviceUnregister

; 120  : 
; 121  :     free(msxMidi);

	push	esi
	call	_free
	add	esp, 32					; 00000020H
	pop	esi

; 122  : }

	ret	0
_destroy ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\iodevice\msxmidi.c
;	COMDAT _loadState
_TEXT	SEGMENT
_msxMidi$ = 8						; size = 4
_loadState PROC						; COMDAT

; 91   : {

	push	esi
	push	edi

; 92   :     SaveState* state = saveStateOpenForRead("MSXMidi");

	push	OFFSET ??_C@_07MHAJBJHJ@MSXMidi@
	call	_saveStateOpenForRead

; 93   : 
; 94   :     msxMidi->timerIRQlatch   = saveStateGet(state, "timerIRQlatch",    0);

	push	0
	mov	esi, eax
	push	OFFSET ??_C@_0O@JDPPJMM@timerIRQlatch@
	push	esi
	call	_saveStateGet
	mov	edi, DWORD PTR _msxMidi$[esp+20]

; 95   :     msxMidi->timerIRQenabled = saveStateGet(state, "timerIRQenabled",  0);

	push	0
	push	OFFSET ??_C@_0BA@OELNDKKA@timerIRQenabled@
	push	esi
	mov	DWORD PTR [edi+28], eax
	call	_saveStateGet

; 96   :     msxMidi->rxrdyIRQlatch   = saveStateGet(state, "rxrdyIRQlatch",    0);

	push	0
	push	OFFSET ??_C@_0O@NPIOJLJP@rxrdyIRQlatch@
	push	esi
	mov	DWORD PTR [edi+32], eax
	call	_saveStateGet

; 97   :     msxMidi->rxrdyIRQenabled = saveStateGet(state, "rxrdyIRQenabled",  0);

	push	0
	push	OFFSET ??_C@_0BA@NGJHOCPC@rxrdyIRQenabled@
	push	esi
	mov	DWORD PTR [edi+36], eax
	call	_saveStateGet

; 98   :     msxMidi->ioStart         = saveStateGet(state, "ioStart", 0);

	push	0
	push	OFFSET ??_C@_07DBHDALPG@ioStart@
	push	esi
	mov	DWORD PTR [edi+40], eax
	call	_saveStateGet
	add	esp, 64					; 00000040H
	mov	DWORD PTR [edi+20], eax

; 99   : 
; 100  :     saveStateClose(state);

	push	esi
	call	_saveStateClose

; 101  :     
; 102  :     i8251LoadState(msxMidi->i8251);

	push	DWORD PTR [edi+12]
	call	_i8251LoadState

; 103  :     i8254LoadState(msxMidi->i8254);

	push	DWORD PTR [edi+16]
	call	_i8254LoadState
	add	esp, 12					; 0000000cH

; 104  :     
; 105  :     archMidiLoadState();

	pop	edi
	pop	esi
	jmp	_archMidiLoadState
_loadState ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\iodevice\msxmidi.c
;	COMDAT _saveState
_TEXT	SEGMENT
_msxMidi$ = 8						; size = 4
_saveState PROC						; COMDAT

; 73   : {

	push	esi
	push	edi

; 74   :     SaveState* state = saveStateOpenForWrite("MSXMidi");

	push	OFFSET ??_C@_07MHAJBJHJ@MSXMidi@
	call	_saveStateOpenForWrite

; 75   :     
; 76   :     saveStateSet(state, "timerIRQlatch",    msxMidi->timerIRQlatch);

	mov	edi, DWORD PTR _msxMidi$[esp+8]
	mov	esi, eax
	push	DWORD PTR [edi+28]
	push	OFFSET ??_C@_0O@JDPPJMM@timerIRQlatch@
	push	esi
	call	_saveStateSet

; 77   :     saveStateSet(state, "timerIRQenabled",  msxMidi->timerIRQenabled);

	push	DWORD PTR [edi+32]
	push	OFFSET ??_C@_0BA@OELNDKKA@timerIRQenabled@
	push	esi
	call	_saveStateSet

; 78   :     saveStateSet(state, "rxrdyIRQlatch",    msxMidi->rxrdyIRQlatch);

	push	DWORD PTR [edi+36]
	push	OFFSET ??_C@_0O@NPIOJLJP@rxrdyIRQlatch@
	push	esi
	call	_saveStateSet

; 79   :     saveStateSet(state, "rxrdyIRQenabled",  msxMidi->rxrdyIRQenabled);

	push	DWORD PTR [edi+40]
	push	OFFSET ??_C@_0BA@NGJHOCPC@rxrdyIRQenabled@
	push	esi
	call	_saveStateSet

; 80   :     saveStateSet(state, "ioStart",          msxMidi->ioStart);

	push	DWORD PTR [edi+20]
	push	OFFSET ??_C@_07DBHDALPG@ioStart@
	push	esi
	call	_saveStateSet
	add	esp, 64					; 00000040H

; 81   : 
; 82   :     saveStateClose(state);

	push	esi
	call	_saveStateClose

; 83   : 
; 84   :     i8251SaveState(msxMidi->i8251);

	push	DWORD PTR [edi+12]
	call	_i8251SaveState

; 85   :     i8254SaveState(msxMidi->i8254);

	push	DWORD PTR [edi+16]
	call	_i8254SaveState
	add	esp, 12					; 0000000cH

; 86   : 
; 87   :     archMidiSaveState();

	pop	edi
	pop	esi
	jmp	_archMidiSaveState
_saveState ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\iodevice\msxmidi.c
;	COMDAT _unregisterIoPorts
_TEXT	SEGMENT
_msxMidi$ = 8						; size = 4
_unregisterIoPorts PROC					; COMDAT

; 275  : static void unregisterIoPorts(MSXMidi* msxMidi) {

	push	edi

; 276  :     int i;
; 277  :     if (msxMidi->ioStart == 0) {

	mov	edi, DWORD PTR _msxMidi$[esp]
	cmp	DWORD PTR [edi+20], 0
	je	SHORT $LN1@unregister

; 278  :         return;
; 279  :     }
; 280  :     
; 281  :     for (i = 0; i < (msxMidi->ioStart == 0xe0 ? 2 : 8); i++) {

	push	ebx
	push	esi
	xor	esi, esi
	lea	ebx, DWORD PTR [esi+2]
$LL4@unregister:

; 282  :         ioPortUnregister(msxMidi->ioStart + i);

	mov	eax, DWORD PTR [edi+20]
	add	eax, esi
	push	eax
	call	_ioPortUnregister
	add	esp, 4
	inc	esi
	cmp	DWORD PTR [edi+20], 224			; 000000e0H
	mov	eax, 8
	cmove	eax, ebx
	cmp	esi, eax
	jl	SHORT $LL4@unregister

; 283  :     }
; 284  : 
; 285  :     msxMidi->ioStart = 0;

	pop	esi
	mov	DWORD PTR [edi+20], 0
	pop	ebx
$LN1@unregister:

; 286  : }

	pop	edi
	ret	0
_unregisterIoPorts ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\iodevice\msxmidi.c
;	COMDAT _writeIo
_TEXT	SEGMENT
_msxMidi$ = 8						; size = 4
_ioPort$ = 12						; size = 2
_value$ = 16						; size = 1
_writeIo PROC						; COMDAT

; 351  :     if ((ioPort & 0xff) == 0xe2) {

	mov	ecx, DWORD PTR _ioPort$[esp-4]
	cmp	cl, 226					; 000000e2H
	jne	SHORT $LN4@writeIo

; 353  :         if (value & 0x80) {

	mov	eax, DWORD PTR _value$[esp-4]
	test	al, al
	jns	SHORT $LN5@writeIo

; 354  :             unregisterIoPorts(msxMidi);

	push	DWORD PTR _msxMidi$[esp-4]
	call	_unregisterIoPorts
	add	esp, 4

; 377  : 			break;
; 378  : 	}
; 379  : }

	ret	0
$LN5@writeIo:

; 352  :         int ioStart = (value & 1) ? 0xe0 : 0xe8;

	movzx	eax, al
	shl	eax, 3
	not	eax
	and	eax, 8
	or	eax, 224				; 000000e0H

; 355  :         }
; 356  :         else {
; 357  :             registerIoPorts(msxMidi, ioStart);

	push	eax
	push	DWORD PTR _msxMidi$[esp]
	call	_registerIoPorts
	add	esp, 8

; 377  : 			break;
; 378  : 	}
; 379  : }

	ret	0
$LN4@writeIo:

; 358  :         }
; 359  :         return;
; 360  :     }
; 361  : 
; 362  :     switch (ioPort & 7) {

	mov	eax, ecx
	and	eax, 7
	jmp	DWORD PTR $LN20@writeIo[eax*4]
$LN7@writeIo:

; 363  : 		case 0: // UART data register
; 364  : 		case 1: // UART command register
; 365  :             i8251Write(msxMidi->i8251, ioPort & 3, value);

	push	DWORD PTR _value$[esp-4]
	mov	eax, DWORD PTR _msxMidi$[esp]
	and	ecx, 3
	push	ecx
	push	DWORD PTR [eax+12]
	call	_i8251Write

; 377  : 			break;
; 378  : 	}
; 379  : }

	add	esp, 12					; 0000000cH
	ret	0
$LN8@writeIo:

; 366  : 			break;
; 367  : 		case 2: // timer interrupt flag off
; 368  : 			setTimerIRQ(msxMidi, 0);

	push	0
	push	DWORD PTR _msxMidi$[esp]
	call	_setTimerIRQ
	add	esp, 8

; 377  : 			break;
; 378  : 	}
; 379  : }

	ret	0
$LN10@writeIo:

; 369  : 			break;
; 370  : 		case 3: // no function
; 371  : 			break;
; 372  : 		case 4: // counter 0 data port
; 373  : 		case 5: // counter 1 data port
; 374  : 		case 6: // counter 2 data port
; 375  : 		case 7: // timer command register
; 376  :             i8254Write(msxMidi->i8254, ioPort & 3, value);

	push	DWORD PTR _value$[esp-4]
	mov	eax, DWORD PTR _msxMidi$[esp]
	and	ecx, 3
	push	ecx
	push	DWORD PTR [eax+16]
	call	_i8254Write

; 377  : 			break;
; 378  : 	}
; 379  : }

	add	esp, 12					; 0000000cH
$LN2@writeIo:
	ret	0
	npad	1
$LN20@writeIo:
	DD	$LN7@writeIo
	DD	$LN7@writeIo
	DD	$LN8@writeIo
	DD	$LN2@writeIo
	DD	$LN10@writeIo
	DD	$LN10@writeIo
	DD	$LN10@writeIo
	DD	$LN10@writeIo
_writeIo ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\iodevice\msxmidi.c
;	COMDAT _readIo
_TEXT	SEGMENT
_msxMidi$ = 8						; size = 4
_ioPort$ = 12						; size = 2
_readIo	PROC						; COMDAT

; 332  : 	switch (ioPort & 7) {

	mov	ecx, DWORD PTR _ioPort$[esp-4]
	mov	eax, ecx
	and	eax, 7
	jmp	DWORD PTR $LN9@readIo[eax*4]
$LN4@readIo:

; 333  : 		case 0: // UART data register
; 334  : 		case 1: // UART status register
; 335  : 			return i8251Read(msxMidi->i8251, ioPort & 3);

	mov	eax, DWORD PTR _msxMidi$[esp-4]
	and	ecx, 3
	push	ecx
	push	DWORD PTR [eax+12]
	call	_i8251Read
	add	esp, 8

; 347  : }

	ret	0
$LN6@readIo:

; 336  : 			break;
; 337  : 		case 2: // timer interrupt flag off
; 338  : 		case 3: // no function
; 339  : 			return 0xff;
; 340  : 		case 4: // counter 0 data port
; 341  : 		case 5: // counter 1 data port
; 342  : 		case 6: // counter 2 data port
; 343  : 		case 7: // timer command register
; 344  : 			return i8254Read(msxMidi->i8254, ioPort & 3);

	mov	eax, DWORD PTR _msxMidi$[esp-4]
	and	ecx, 3
	push	ecx
	push	DWORD PTR [eax+16]
	call	_i8254Read
	add	esp, 8

; 347  : }

	ret	0
$LN2@readIo:

; 345  : 	}
; 346  : 	return 0xff;

	or	al, 255					; 000000ffH

; 347  : }

	ret	0
	npad	1
$LN9@readIo:
	DD	$LN4@readIo
	DD	$LN4@readIo
	DD	$LN2@readIo
	DD	$LN2@readIo
	DD	$LN6@readIo
	DD	$LN6@readIo
	DD	$LN6@readIo
	DD	$LN6@readIo
_readIo	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\iodevice\msxmidi.c
;	COMDAT _MSXMidiCreate
_TEXT	SEGMENT
_callbacks$ = -32					; size = 16
_dbgCallbacks$ = -16					; size = 16
_isExternal$ = 8					; size = 4
_MSXMidiCreate PROC					; COMDAT

; 421  : {

	sub	esp, 32					; 00000020H
	push	esi
	push	edi

; 422  :     DeviceCallbacks callbacks = {destroy, reset, saveState, loadState};
; 423  :     DebugCallbacks dbgCallbacks = { getDebugInfo, NULL, NULL, NULL };
; 424  :     MSXMidi* msxMidi;
; 425  : 
; 426  :     msxMidi = malloc(sizeof(MSXMidi));

	push	44					; 0000002cH
	mov	DWORD PTR _callbacks$[esp+44], OFFSET _destroy
	mov	DWORD PTR _callbacks$[esp+48], OFFSET _reset
	mov	DWORD PTR _callbacks$[esp+52], OFFSET _saveState
	mov	DWORD PTR _callbacks$[esp+56], OFFSET _loadState
	mov	DWORD PTR _dbgCallbacks$[esp+44], OFFSET _getDebugInfo
	mov	DWORD PTR _dbgCallbacks$[esp+48], 0
	mov	DWORD PTR _dbgCallbacks$[esp+52], 0
	mov	DWORD PTR _dbgCallbacks$[esp+56], 0
	call	_malloc

; 427  :     
; 428  :     msxMidi->ioStart = 0;
; 429  :     msxMidi->deviceHandle = deviceManagerRegister(isExternal ? ROM_MSXMIDI_EXTERNAL : ROM_MSXMIDI, &callbacks, msxMidi);

	mov	esi, DWORD PTR _isExternal$[esp+40]
	mov	edi, eax
	push	edi
	lea	eax, DWORD PTR _callbacks$[esp+48]
	test	esi, esi
	push	eax
	mov	eax, 169				; 000000a9H
	mov	DWORD PTR [edi+20], 0
	mov	ecx, 88					; 00000058H
	cmovne	ecx, eax
	push	ecx
	call	_deviceManagerRegister
	add	esp, 16					; 00000010H
	mov	DWORD PTR [edi], eax

; 430  :     msxMidi->debugHandle = debugDeviceRegister(DBGTYPE_AUDIO, langDbgDevMsxMidi(), &dbgCallbacks, msxMidi);

	lea	eax, DWORD PTR _dbgCallbacks$[esp+40]
	push	edi
	push	eax
	call	_langDbgDevMsxMidi
	push	eax
	push	5
	call	_debugDeviceRegister

; 431  : 
; 432  :     msxMidi->i8254 = i8254Create(4000000, pitOut0, pitOut1, pitOut2, msxMidi);

	push	edi
	push	OFFSET _pitOut2
	push	OFFSET _pitOut1
	push	OFFSET _pitOut0
	push	4000000					; 003d0900H
	mov	DWORD PTR [edi+4], eax
	call	_i8254Create

; 433  :     msxMidi->i8251 = i8251Create(transmit, signal8251, setDataBits, setStopBits, setParity, 

	push	edi
	push	OFFSET _getRts
	push	OFFSET _getDtr
	push	OFFSET _setRts
	push	OFFSET _setDtr
	push	OFFSET _setRxReady
	push	OFFSET _setParity
	push	OFFSET _setStopBits
	push	OFFSET _setDataBits
	push	OFFSET _signal8251
	push	OFFSET _transmit
	mov	DWORD PTR [edi+16], eax
	call	_i8251Create
	add	esp, 80					; 00000050H
	mov	DWORD PTR [edi+12], eax

; 434  :                                  setRxReady, setDtr, setRts, getDtr, getRts, msxMidi);
; 435  :     msxMidi->isExternal = isExternal;

	mov	DWORD PTR [edi+24], esi

; 436  : 
; 437  :     if (isExternal) {

	test	esi, esi
	je	SHORT $LN2@MSXMidiCre

; 438  :         ioPortRegister(0xe2, NULL, writeIo, msxMidi);

	push	edi
	push	OFFSET _writeIo
	push	0
	push	226					; 000000e2H
	call	_ioPortRegister
	add	esp, 16					; 00000010H

; 439  :     }

	jmp	SHORT $LN12@MSXMidiCre
$LN2@MSXMidiCre:

; 291  :     if (msxMidi->ioStart == ioStart) {

	mov	eax, DWORD PTR [edi+20]
	cmp	eax, 232				; 000000e8H
	je	SHORT $LN12@MSXMidiCre

; 292  :         return;
; 293  :     }
; 294  : 
; 295  :     if (msxMidi->ioStart != 0) {

	test	eax, eax
	je	SHORT $LN9@MSXMidiCre

; 296  :         unregisterIoPorts(msxMidi);

	push	edi
	call	_unregisterIoPorts
	add	esp, 4
$LN9@MSXMidiCre:

; 297  :     }
; 298  : 
; 299  :     msxMidi->ioStart = ioStart;

	mov	DWORD PTR [edi+20], 232			; 000000e8H
	mov	esi, 8
	npad	5
$LL14@MSXMidiCre:

; 300  : 
; 301  :     i = msxMidi->ioStart == 0xe0 ? 2 : 8;
; 302  :     while (i--) {
; 303  :         ioPortRegister(ioStart + i, readIo, writeIo, msxMidi);

	push	edi
	dec	esi
	push	OFFSET _writeIo
	push	OFFSET _readIo
	lea	eax, DWORD PTR [esi+232]
	push	eax
	call	_ioPortRegister
	add	esp, 16					; 00000010H
	test	esi, esi
	jne	SHORT $LL14@MSXMidiCre
$LN12@MSXMidiCre:

; 440  :     else {
; 441  :         registerIoPorts(msxMidi, 0xe8);
; 442  :     }
; 443  : 
; 444  :     msxMidi->midiIo = midiIoCreate(midiInCallback, msxMidi);

	push	edi
	push	OFFSET _midiInCallback
	call	_midiIoCreate

; 445  : 
; 446  :     reset(msxMidi);

	push	edi
	mov	DWORD PTR [edi+8], eax
	call	_reset
	add	esp, 12					; 0000000cH

; 447  : 
; 448  :     return 1;

	mov	eax, 1
	pop	edi
	pop	esi

; 449  : }

	add	esp, 32					; 00000020H
	ret	0
_MSXMidiCreate ENDP
_TEXT	ENDS
END
