; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27054.0 

	TITLE	D:\repo\MSX-master\MSX\blueMSX-DPI\Src\Memory\romMapperMsxRs232.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	??_C@_05IEEKDPFI@V9938@				; `string'
PUBLIC	??_C@_05IAMHEDOK@V9958@				; `string'
PUBLIC	??_C@_08IBFDMDNO@TMS9929A@			; `string'
PUBLIC	??_C@_08HEDIBBLA@TMS99x8A@			; `string'
;	COMDAT ??_C@_08HEDIBBLA@TMS99x8A@
CONST	SEGMENT
??_C@_08HEDIBBLA@TMS99x8A@ DB 'TMS99x8A', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_08IBFDMDNO@TMS9929A@
CONST	SEGMENT
??_C@_08IBFDMDNO@TMS9929A@ DB 'TMS9929A', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_05IAMHEDOK@V9958@
CONST	SEGMENT
??_C@_05IAMHEDOK@V9958@ DB 'V9958', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_05IEEKDPFI@V9938@
CONST	SEGMENT
??_C@_05IEEKDPFI@V9938@ DB 'V9938', 00H			; `string'
CONST	ENDS
PUBLIC	_romMapperMsxRs232Create
PUBLIC	??_C@_08JDPDFAIF@MSXRs232@			; `string'
PUBLIC	??_C@_06DJIHEMFI@status@			; `string'
PUBLIC	??_C@_07CMMFKEJG@intmask@			; `string'
EXTRN	_ioPortRegister:PROC
EXTRN	_ioPortUnregister:PROC
EXTRN	_slotRegister:PROC
EXTRN	_slotUnregister:PROC
EXTRN	_slotMapPage:PROC
EXTRN	_deviceManagerRegister:PROC
EXTRN	_deviceManagerUnregister:PROC
EXTRN	_debugDeviceRegister:PROC
EXTRN	_debugDeviceUnregister:PROC
EXTRN	_dbgDeviceAddIoPorts:PROC
EXTRN	_dbgIoPortsAddPort:PROC
EXTRN	_saveStateOpenForRead:PROC
EXTRN	_saveStateOpenForWrite:PROC
EXTRN	_saveStateClose:PROC
EXTRN	_saveStateGet:PROC
EXTRN	_saveStateSet:PROC
EXTRN	_boardSetInt:PROC
EXTRN	_boardClearInt:PROC
EXTRN	_i8251Peek:PROC
EXTRN	_i8251Read:PROC
EXTRN	_i8251Write:PROC
EXTRN	_i8251RxData:PROC
EXTRN	_i8251LoadState:PROC
EXTRN	_i8251SaveState:PROC
EXTRN	_i8251Reset:PROC
EXTRN	_i8251Destroy:PROC
EXTRN	_i8251Create:PROC
EXTRN	_i8254Peek:PROC
EXTRN	_i8254Read:PROC
EXTRN	_i8254Write:PROC
EXTRN	_i8254LoadState:PROC
EXTRN	_i8254SaveState:PROC
EXTRN	_i8254Reset:PROC
EXTRN	_i8254Destroy:PROC
EXTRN	_i8254Create:PROC
EXTRN	_archUartCreate:PROC
EXTRN	_langDbgDevRs232:PROC
EXTRN	_free:PROC
EXTRN	_malloc:PROC
EXTRN	_memcpy:PROC
_BSS	SEGMENT
_msxRs232 DD	01H DUP (?)
_BSS	ENDS
;	COMDAT ??_C@_07CMMFKEJG@intmask@
CONST	SEGMENT
??_C@_07CMMFKEJG@intmask@ DB 'intmask', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_06DJIHEMFI@status@
CONST	SEGMENT
??_C@_06DJIHEMFI@status@ DB 'status', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_08JDPDFAIF@MSXRs232@
CONST	SEGMENT
??_C@_08JDPDFAIF@MSXRs232@ DB 'MSXRs232', 00H		; `string'
CONST	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommappermsxrs232.c
;	COMDAT _getDebugInfo
_TEXT	SEGMENT
_value$1 = -4						; size = 1
_msxRs232$ = 8						; size = 4
_dbgDevice$ = 12					; size = 4
_getDebugInfo PROC					; COMDAT

; 315  : {

	push	ecx
	push	ebx
	push	ebp
	push	esi
	push	edi

; 316  :     DbgIoPorts* ioPorts;
; 317  :     int i;
; 318  : 
; 319  :     ioPorts = dbgDeviceAddIoPorts(dbgDevice, langDbgDevRs232(), 8);

	push	8
	call	_langDbgDevRs232
	push	eax
	push	DWORD PTR _dbgDevice$[esp+24]
	call	_dbgDeviceAddIoPorts

; 320  :     for (i = 0; i < 7; i++) {

	mov	ebp, DWORD PTR _msxRs232$[esp+28]
	add	esp, 12					; 0000000cH
	mov	ebx, eax
	xor	esi, esi
$LL4@getDebugIn:

; 321  :         dbgIoPortsAddPort(ioPorts, i, 0x80 + i, DBG_IO_READWRITE, peekIo(msxRs232, 0x80 + i));

	lea	edi, DWORD PTR [esi+128]

; 168  :     UInt8 value = 0xff;

	mov	BYTE PTR _value$1[esp+20], 255		; 000000ffH

; 321  :         dbgIoPortsAddPort(ioPorts, i, 0x80 + i, DBG_IO_READWRITE, peekIo(msxRs232, 0x80 + i));

	movzx	edx, di

; 170  :     switch (ioPort) {

	lea	ecx, DWORD PTR [edx-128]
	cmp	ecx, 6
	ja	SHORT $LN7@getDebugIn
	jmp	DWORD PTR $LN20@getDebugIn[ecx*4]
$LN9@getDebugIn:

; 171  :     case 0x80:
; 172  :     case 0x81:
; 173  :         ioPort &= 0x01;

	and	edx, 1

; 174  :         value = i8251Peek(msxRs232->i8251, ioPort);

	push	edx
	push	DWORD PTR [ebp+28]
	call	_i8251Peek

; 175  :         break;

	jmp	SHORT $LN17@getDebugIn
$LN10@getDebugIn:

; 176  :     case 0x82:
; 177  :         value = msxRs232->status;

	mov	al, BYTE PTR [ebp+36]

; 178  :         break;

	jmp	SHORT $LN18@getDebugIn
$LN11@getDebugIn:

; 179  :     case 0x84:
; 180  :     case 0x85:
; 181  :     case 0x86:
; 182  :         ioPort &= 0x03;

	and	edx, 3

; 183  : 	    value = i8254Peek(msxRs232->i8254, ioPort);

	push	edx
	push	DWORD PTR [ebp+32]
	call	_i8254Peek
$LN17@getDebugIn:

; 321  :         dbgIoPortsAddPort(ioPorts, i, 0x80 + i, DBG_IO_READWRITE, peekIo(msxRs232, 0x80 + i));

	add	esp, 8
$LN18@getDebugIn:
	mov	BYTE PTR _value$1[esp+20], al
$LN7@getDebugIn:
	push	DWORD PTR _value$1[esp+20]
	push	3
	push	edi
	push	esi
	push	ebx
	call	_dbgIoPortsAddPort
	inc	esi
	add	esp, 20					; 00000014H
	cmp	esi, 7
	jl	SHORT $LL4@getDebugIn

; 322  :     }
; 323  :     dbgIoPortsAddPort(ioPorts, 1, 0x87, DBG_IO_WRITE, 0);

	push	0
	push	2
	push	135					; 00000087H
	push	1
	push	ebx
	call	_dbgIoPortsAddPort
	add	esp, 20					; 00000014H
	pop	edi
	pop	esi
	pop	ebp
	pop	ebx

; 324  : }

	pop	ecx
	ret	0
	npad	3
$LN20@getDebugIn:
	DD	$LN9@getDebugIn
	DD	$LN9@getDebugIn
	DD	$LN10@getDebugIn
	DD	$LN7@getDebugIn
	DD	$LN11@getDebugIn
	DD	$LN11@getDebugIn
	DD	$LN11@getDebugIn
_getDebugInfo ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommappermsxrs232.c
;	COMDAT _romMapperMsxRs232ReceiveCallback
_TEXT	SEGMENT
_value$ = 8						; size = 1
_romMapperMsxRs232ReceiveCallback PROC			; COMDAT

; 306  :     i8251RxData(msxRs232->i8251, value);

	mov	eax, DWORD PTR _msxRs232
	push	DWORD PTR _value$[esp-4]
	push	DWORD PTR [eax+28]
	call	_i8251RxData
	add	esp, 8

; 307  : }

	ret	0
_romMapperMsxRs232ReceiveCallback ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommappermsxrs232.c
;	COMDAT _pitOut2
_TEXT	SEGMENT
_msxRs232$ = 8						; size = 4
_state$ = 12						; size = 4
_pitOut2 PROC						; COMDAT

; 296  : {

	mov	edx, DWORD PTR _msxRs232$[esp-4]
	mov	cl, BYTE PTR [edx+36]

; 297  :     msxRs232->status = (state) ? msxRs232->status|STATUS_OUT2 : msxRs232->status&~STATUS_OUT2;

	mov	al, cl
	or	cl, 64					; 00000040H
	and	al, 191					; 000000bfH
	movzx	ecx, cl
	cmp	DWORD PTR _state$[esp-4], 0
	movzx	eax, al
	cmove	ecx, eax
	mov	BYTE PTR [edx+36], cl

; 298  : }

	ret	0
_pitOut2 ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommappermsxrs232.c
;	COMDAT _pitOut1
_TEXT	SEGMENT
_msxRs232$ = 8						; size = 4
_state$ = 12						; size = 4
_pitOut1 PROC						; COMDAT

; 292  :     //msxRs232->i8251->txClk(msxRs232, state);
; 293  : }

	ret	0
_pitOut1 ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommappermsxrs232.c
;	COMDAT _pitOut0
_TEXT	SEGMENT
_msxRs232$ = 8						; size = 4
_state$ = 12						; size = 4
_pitOut0 PROC						; COMDAT

; 288  :     //msxRs232->i8251->rxClk(msxRs232, state);
; 289  : }

	ret	0
_pitOut0 ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommappermsxrs232.c
;	COMDAT _getRts
_TEXT	SEGMENT
_msxRs232$ = 8						; size = 4
_getRts	PROC						; COMDAT

; 279  :     return 0;

	xor	eax, eax

; 280  : }

	ret	0
_getRts	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommappermsxrs232.c
;	COMDAT _getDtr
_TEXT	SEGMENT
_msxRs232$ = 8						; size = 4
_getDtr	PROC						; COMDAT

; 275  :     return 0;

	xor	eax, eax

; 276  : }

	ret	0
_getDtr	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommappermsxrs232.c
;	COMDAT _setRts
_TEXT	SEGMENT
_msxRs232$ = 8						; size = 4
_status$ = 12						; size = 4
_setRts	PROC						; COMDAT

; 272  : }

	ret	0
_setRts	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommappermsxrs232.c
;	COMDAT _setDtr
_TEXT	SEGMENT
_msxRs232$ = 8						; size = 4
_status$ = 12						; size = 4
_setDtr	PROC						; COMDAT

; 269  : }

	ret	0
_setDtr	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommappermsxrs232.c
;	COMDAT _setRxReady
_TEXT	SEGMENT
_msxRs232$ = 8						; size = 4
_status$ = 12						; size = 4
_setRxReady PROC					; COMDAT

; 260  :     if (~msxRs232->intmask & INTMASK_RXREADY) {

	mov	eax, DWORD PTR _msxRs232$[esp-4]
	movzx	eax, BYTE PTR [eax+37]
	not	eax
	test	al, 1
	je	SHORT $LN4@setRxReady

; 261  :         if (status)

	cmp	DWORD PTR _status$[esp-4], 0
	push	1
	je	SHORT $LN3@setRxReady

; 262  :             boardSetInt(1);

	call	_boardSetInt
	add	esp, 4

; 265  :     }
; 266  : }

	ret	0
$LN3@setRxReady:

; 263  :         else
; 264  :             boardClearInt(1);

	call	_boardClearInt
	pop	ecx
$LN4@setRxReady:

; 265  :     }
; 266  : }

	ret	0
_setRxReady ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommappermsxrs232.c
;	COMDAT _setParity
_TEXT	SEGMENT
_msxRs232$ = 8						; size = 4
_value$ = 12						; size = 4
_setParity PROC						; COMDAT

; 256  : }

	ret	0
_setParity ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommappermsxrs232.c
;	COMDAT _setStopBits
_TEXT	SEGMENT
_msxRs232$ = 8						; size = 4
_value$ = 12						; size = 4
_setStopBits PROC					; COMDAT

; 253  : }

	ret	0
_setStopBits ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommappermsxrs232.c
;	COMDAT _setDataBits
_TEXT	SEGMENT
_msxRs232$ = 8						; size = 4
_value$ = 12						; size = 4
_setDataBits PROC					; COMDAT

; 250  : }

	ret	0
_setDataBits ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommappermsxrs232.c
;	COMDAT _rs232signal
_TEXT	SEGMENT
_msxRs232$ = 8						; size = 4
_rs232signal PROC					; COMDAT

; 246  :     return 0;

	xor	eax, eax

; 247  : }

	ret	0
_rs232signal ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommappermsxrs232.c
;	COMDAT _rs232transmit
_TEXT	SEGMENT
_msxRs232$ = 8						; size = 4
_value$ = 12						; size = 1
_rs232transmit PROC					; COMDAT

; 242  :     return 0;

	xor	eax, eax

; 243  : }

	ret	0
_rs232transmit ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommappermsxrs232.c
;	COMDAT _writeIo
_TEXT	SEGMENT
_msxRs232$ = 8						; size = 4
_ioPort$ = 12						; size = 2
_value$ = 16						; size = 1
_writeIo PROC						; COMDAT

; 216  :     UInt16 baseAdr;
; 217  : 
; 218  :     switch (ioPort) {

	mov	ecx, DWORD PTR _ioPort$[esp-4]
	movzx	eax, cx
	add	eax, -128				; ffffff80H
	cmp	eax, 7
	ja	SHORT $LN2@writeIo
	jmp	DWORD PTR $LN10@writeIo[eax*4]
$LN4@writeIo:

; 219  :     case 0x80:
; 220  :     case 0x81:
; 221  :         baseAdr = ioPort - 0x80;
; 222  :         i8251Write(msxRs232->i8251, baseAdr, value);

	push	DWORD PTR _value$[esp-4]
	lea	eax, DWORD PTR [ecx-128]
	push	eax
	mov	eax, DWORD PTR _msxRs232$[esp+4]
	push	DWORD PTR [eax+28]
	call	_i8251Write

; 233  :         break;
; 234  :     }
; 235  : }

	add	esp, 12					; 0000000cH
	ret	0
$LN5@writeIo:

; 223  :         break;
; 224  :     case 0x82:
; 225  :         msxRs232->intmask = value & 0x0f;

	mov	eax, DWORD PTR _msxRs232$[esp-4]
	mov	cl, BYTE PTR _value$[esp-4]
	and	cl, 15					; 0000000fH
	mov	BYTE PTR [eax+37], cl

; 233  :         break;
; 234  :     }
; 235  : }

	ret	0
$LN6@writeIo:

; 226  :         break;
; 227  :     case 0x84:
; 228  :     case 0x85:
; 229  :     case 0x86:
; 230  :     case 0x87:
; 231  :         baseAdr = ioPort - 0x84;
; 232  :         i8254Write(msxRs232->i8254, baseAdr, value);

	push	DWORD PTR _value$[esp-4]
	lea	eax, DWORD PTR [ecx-132]
	push	eax
	mov	eax, DWORD PTR _msxRs232$[esp+4]
	push	DWORD PTR [eax+32]
	call	_i8254Write

; 233  :         break;
; 234  :     }
; 235  : }

	add	esp, 12					; 0000000cH
$LN2@writeIo:
	ret	0
$LN10@writeIo:
	DD	$LN4@writeIo
	DD	$LN4@writeIo
	DD	$LN5@writeIo
	DD	$LN2@writeIo
	DD	$LN6@writeIo
	DD	$LN6@writeIo
	DD	$LN6@writeIo
	DD	$LN6@writeIo
_writeIo ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommappermsxrs232.c
;	COMDAT _readIo
_TEXT	SEGMENT
_msxRs232$ = 8						; size = 4
_ioPort$ = 12						; size = 2
_readIo	PROC						; COMDAT

; 192  :     UInt8 value = 0xff;
; 193  : 
; 194  :     switch (ioPort) {

	mov	ecx, DWORD PTR _ioPort$[esp-4]
	or	dl, 255					; 000000ffH
	movzx	eax, cx
	add	eax, -128				; ffffff80H
	cmp	eax, 6
	ja	SHORT $LN2@readIo
	jmp	DWORD PTR $LN10@readIo[eax*4]
$LN4@readIo:

; 195  :     case 0x80:
; 196  :     case 0x81:
; 197  :         ioPort &= 0x01;
; 198  :         value = i8251Read(msxRs232->i8251, ioPort);

	mov	eax, DWORD PTR _msxRs232$[esp-4]
	and	ecx, 1
	push	ecx
	push	DWORD PTR [eax+28]
	call	_i8251Read

; 208  :         break;
; 209  :     }
; 210  : 
; 211  :     return value;

	mov	dl, al
	add	esp, 8

; 212  : }

	ret	0
$LN5@readIo:

; 199  :         break;
; 200  :     case 0x82:
; 201  :         value = msxRs232->status;

	mov	eax, DWORD PTR _msxRs232$[esp-4]
	mov	dl, BYTE PTR [eax+36]

; 208  :         break;
; 209  :     }
; 210  : 
; 211  :     return value;

	mov	al, dl

; 212  : }

	ret	0
$LN6@readIo:

; 202  :         break;
; 203  :     case 0x84:
; 204  :     case 0x85:
; 205  :     case 0x86:
; 206  :         ioPort &= 0x03;
; 207  : 	    value = i8254Read(msxRs232->i8254, ioPort);

	mov	eax, DWORD PTR _msxRs232$[esp-4]
	and	ecx, 3
	push	ecx
	push	DWORD PTR [eax+32]
	call	_i8254Read

; 208  :         break;
; 209  :     }
; 210  : 
; 211  :     return value;

	mov	dl, al
	add	esp, 8
$LN2@readIo:
	mov	al, dl

; 212  : }

	ret	0
	npad	3
$LN10@readIo:
	DD	$LN4@readIo
	DD	$LN4@readIo
	DD	$LN5@readIo
	DD	$LN2@readIo
	DD	$LN6@readIo
	DD	$LN6@readIo
	DD	$LN6@readIo
_readIo	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommappermsxrs232.c
;	COMDAT _peekIo
_TEXT	SEGMENT
_msxRs232$ = 8						; size = 4
_ioPort$ = 12						; size = 2
_peekIo	PROC						; COMDAT

; 168  :     UInt8 value = 0xff;
; 169  : 
; 170  :     switch (ioPort) {

	mov	ecx, DWORD PTR _ioPort$[esp-4]
	or	dl, 255					; 000000ffH
	movzx	eax, cx
	add	eax, -128				; ffffff80H
	cmp	eax, 6
	ja	SHORT $LN2@peekIo
	jmp	DWORD PTR $LN10@peekIo[eax*4]
$LN4@peekIo:

; 171  :     case 0x80:
; 172  :     case 0x81:
; 173  :         ioPort &= 0x01;
; 174  :         value = i8251Peek(msxRs232->i8251, ioPort);

	mov	eax, DWORD PTR _msxRs232$[esp-4]
	and	ecx, 1
	push	ecx
	push	DWORD PTR [eax+28]
	call	_i8251Peek

; 184  :         break;
; 185  :     }
; 186  : 
; 187  :     return value;

	mov	dl, al
	add	esp, 8

; 188  : }

	ret	0
$LN5@peekIo:

; 175  :         break;
; 176  :     case 0x82:
; 177  :         value = msxRs232->status;

	mov	eax, DWORD PTR _msxRs232$[esp-4]
	mov	dl, BYTE PTR [eax+36]

; 184  :         break;
; 185  :     }
; 186  : 
; 187  :     return value;

	mov	al, dl

; 188  : }

	ret	0
$LN6@peekIo:

; 178  :         break;
; 179  :     case 0x84:
; 180  :     case 0x85:
; 181  :     case 0x86:
; 182  :         ioPort &= 0x03;
; 183  : 	    value = i8254Peek(msxRs232->i8254, ioPort);

	mov	eax, DWORD PTR _msxRs232$[esp-4]
	and	ecx, 3
	push	ecx
	push	DWORD PTR [eax+32]
	call	_i8254Peek

; 184  :         break;
; 185  :     }
; 186  : 
; 187  :     return value;

	mov	dl, al
	add	esp, 8
$LN2@peekIo:
	mov	al, dl

; 188  : }

	ret	0
	npad	3
$LN10@peekIo:
	DD	$LN4@peekIo
	DD	$LN4@peekIo
	DD	$LN5@peekIo
	DD	$LN2@peekIo
	DD	$LN6@peekIo
	DD	$LN6@peekIo
	DD	$LN6@peekIo
_peekIo	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommappermsxrs232.c
;	COMDAT _write
_TEXT	SEGMENT
_msxRs232$ = 8						; size = 4
_address$ = 12						; size = 2
_value$ = 16						; size = 1
_write	PROC						; COMDAT

; 160  : }

	ret	0
_write	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommappermsxrs232.c
;	COMDAT _peek
_TEXT	SEGMENT
_msxRs232$ = 8						; size = 4
_address$ = 12						; size = 2
_peek	PROC						; COMDAT

; 155  :     return address < 0x4000 ? msxRs232->romData[address] : 0xff;

	mov	ax, WORD PTR _address$[esp-4]
	mov	ecx, 16384				; 00004000H
	cmp	ax, cx
	jae	SHORT $LN3@peek
	movzx	ecx, ax
	mov	eax, DWORD PTR _msxRs232$[esp-4]
	mov	eax, DWORD PTR [eax+24]
	mov	al, BYTE PTR [ecx+eax]

; 156  : }

	ret	0
$LN3@peek:

; 155  :     return address < 0x4000 ? msxRs232->romData[address] : 0xff;

	or	al, 255					; 000000ffH

; 156  : }

	ret	0
_peek	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommappermsxrs232.c
;	COMDAT _read
_TEXT	SEGMENT
_msxRs232$ = 8						; size = 4
_address$ = 12						; size = 2
_read	PROC						; COMDAT

; 150  :     return address < 0x4000 ? msxRs232->romData[address] : 0xff;

	mov	ax, WORD PTR _address$[esp-4]
	mov	ecx, 16384				; 00004000H
	cmp	ax, cx
	jae	SHORT $LN3@read
	movzx	ecx, ax
	mov	eax, DWORD PTR _msxRs232$[esp-4]
	mov	eax, DWORD PTR [eax+24]
	mov	al, BYTE PTR [ecx+eax]

; 151  : }

	ret	0
$LN3@read:

; 150  :     return address < 0x4000 ? msxRs232->romData[address] : 0xff;

	or	al, 255					; 000000ffH

; 151  : }

	ret	0
_read	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommappermsxrs232.c
;	COMDAT _reset
_TEXT	SEGMENT
_msxRs232$ = 8						; size = 4
_reset	PROC						; COMDAT

; 137  : {

	push	esi

; 138  :     i8251Reset(msxRs232->i8251);

	mov	esi, DWORD PTR _msxRs232$[esp]
	push	DWORD PTR [esi+28]
	call	_i8251Reset

; 139  :     i8254Reset(msxRs232->i8254);

	push	DWORD PTR [esi+32]
	call	_i8254Reset
	add	esp, 8

; 140  :     msxRs232->status = 0;

	mov	WORD PTR [esi+36], 0

; 141  :     msxRs232->intmask = 0;

	pop	esi

; 142  : }

	ret	0
_reset	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommappermsxrs232.c
;	COMDAT _destroy
_TEXT	SEGMENT
_msxRs232$ = 8						; size = 4
_destroy PROC						; COMDAT

; 116  : {

	push	esi

; 117  :     ioPortUnregister(0x80);

	push	128					; 00000080H
	call	_ioPortUnregister

; 118  :     ioPortUnregister(0x81);

	push	129					; 00000081H
	call	_ioPortUnregister

; 119  :     ioPortUnregister(0x82);

	push	130					; 00000082H
	call	_ioPortUnregister

; 120  :     ioPortUnregister(0x84);

	push	132					; 00000084H
	call	_ioPortUnregister

; 121  :     ioPortUnregister(0x85);

	push	133					; 00000085H
	call	_ioPortUnregister

; 122  :     ioPortUnregister(0x86);

	push	134					; 00000086H
	call	_ioPortUnregister

; 123  :     ioPortUnregister(0x87);

	push	135					; 00000087H
	call	_ioPortUnregister

; 124  :        
; 125  :     i8251Destroy(msxRs232->i8251);

	mov	esi, DWORD PTR _msxRs232$[esp+28]
	push	DWORD PTR [esi+28]
	call	_i8251Destroy

; 126  :     i8254Destroy(msxRs232->i8254);

	push	DWORD PTR [esi+32]
	call	_i8254Destroy

; 127  : 
; 128  :     slotUnregister(msxRs232->slot, msxRs232->sslot, msxRs232->startPage);

	push	DWORD PTR [esi+16]
	push	DWORD PTR [esi+12]
	push	DWORD PTR [esi+8]
	call	_slotUnregister

; 129  :     deviceManagerUnregister(msxRs232->deviceHandle);

	push	DWORD PTR [esi]
	call	_deviceManagerUnregister

; 130  :     debugDeviceUnregister(msxRs232->debugHandle);

	push	DWORD PTR [esi+4]
	call	_debugDeviceUnregister

; 131  : 
; 132  :     free(msxRs232->romData);

	push	DWORD PTR [esi+24]
	call	_free

; 133  :     free(msxRs232);

	push	esi
	call	_free
	add	esp, 64					; 00000040H
	pop	esi

; 134  : }

	ret	0
_destroy ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommappermsxrs232.c
;	COMDAT _loadState
_TEXT	SEGMENT
_msxRs232$ = 8						; size = 4
_loadState PROC						; COMDAT

; 103  : {

	push	esi
	push	edi

; 104  :     SaveState* state = saveStateOpenForRead("MSXRs232");

	push	OFFSET ??_C@_08JDPDFAIF@MSXRs232@
	call	_saveStateOpenForRead

; 105  : 
; 106  :     msxRs232->status  = (UInt8)saveStateGet(state, "status",  0);

	push	0
	mov	esi, eax
	push	OFFSET ??_C@_06DJIHEMFI@status@
	push	esi
	call	_saveStateGet
	mov	edi, DWORD PTR _msxRs232$[esp+20]

; 107  :     msxRs232->intmask  = (UInt8)saveStateGet(state, "intmask",  0);

	push	0
	push	OFFSET ??_C@_07CMMFKEJG@intmask@
	push	esi
	mov	BYTE PTR [edi+36], al
	call	_saveStateGet

; 108  : 
; 109  :     saveStateClose(state);

	push	esi
	mov	BYTE PTR [edi+37], al
	call	_saveStateClose

; 110  :     
; 111  :     i8251LoadState(msxRs232->i8251);

	push	DWORD PTR [edi+28]
	call	_i8251LoadState

; 112  :     i8254LoadState(msxRs232->i8254);

	push	DWORD PTR [edi+32]
	call	_i8254LoadState
	add	esp, 40					; 00000028H
	pop	edi
	pop	esi

; 113  : }

	ret	0
_loadState ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommappermsxrs232.c
;	COMDAT _saveState
_TEXT	SEGMENT
_msxRs232$ = 8						; size = 4
_saveState PROC						; COMDAT

; 90   : {

	push	esi
	push	edi

; 91   :     SaveState* state = saveStateOpenForWrite("MSXRs232");

	push	OFFSET ??_C@_08JDPDFAIF@MSXRs232@
	call	_saveStateOpenForWrite

; 92   : 
; 93   :     saveStateSet(state, "status",  msxRs232->status);

	mov	edi, DWORD PTR _msxRs232$[esp+8]
	mov	esi, eax
	movzx	ecx, BYTE PTR [edi+36]
	push	ecx
	push	OFFSET ??_C@_06DJIHEMFI@status@
	push	esi
	call	_saveStateSet

; 94   :     saveStateSet(state, "intmask",  msxRs232->intmask);

	movzx	ecx, BYTE PTR [edi+37]
	push	ecx
	push	OFFSET ??_C@_07CMMFKEJG@intmask@
	push	esi
	call	_saveStateSet

; 95   : 
; 96   :     saveStateClose(state);

	push	esi
	call	_saveStateClose

; 97   : 
; 98   :     i8251SaveState(msxRs232->i8251);

	push	DWORD PTR [edi+28]
	call	_i8251SaveState

; 99   :     i8254SaveState(msxRs232->i8254);

	push	DWORD PTR [edi+32]
	call	_i8254SaveState
	add	esp, 40					; 00000028H
	pop	edi
	pop	esi

; 100  : }

	ret	0
_saveState ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommappermsxrs232.c
;	COMDAT _romMapperMsxRs232Create
_TEXT	SEGMENT
_callbacks$ = -32					; size = 16
_dbgCallbacks$ = -16					; size = 16
_filename$ = 8						; size = 4
_romData$ = 12						; size = 4
_size$ = 16						; size = 4
_slot$ = 20						; size = 4
_sslot$ = 24						; size = 4
_startPage$ = 28					; size = 4
_romMapperMsxRs232Create PROC				; COMDAT

; 331  : {

	sub	esp, 32					; 00000020H
	push	ebx

; 332  :     DeviceCallbacks callbacks = {destroy, reset, saveState, loadState};
; 333  :     DebugCallbacks dbgCallbacks = { getDebugInfo, NULL, NULL, NULL };
; 334  :     int pages = 4;
; 335  :     int i;
; 336  : 
; 337  :     if ((startPage + pages) > 8) {

	mov	ebx, DWORD PTR _startPage$[esp+32]
	mov	DWORD PTR _callbacks$[esp+36], OFFSET _destroy
	mov	DWORD PTR _callbacks$[esp+40], OFFSET _reset
	mov	DWORD PTR _callbacks$[esp+44], OFFSET _saveState
	lea	eax, DWORD PTR [ebx+4]
	mov	DWORD PTR _callbacks$[esp+48], OFFSET _loadState
	mov	DWORD PTR _dbgCallbacks$[esp+36], OFFSET _getDebugInfo
	mov	DWORD PTR _dbgCallbacks$[esp+40], 0
	mov	DWORD PTR _dbgCallbacks$[esp+44], 0
	mov	DWORD PTR _dbgCallbacks$[esp+48], 0
	cmp	eax, 8
	jle	SHORT $LN5@romMapperM

; 338  :         return 0;

	xor	eax, eax
	pop	ebx

; 377  : }

	add	esp, 32					; 00000020H
	ret	0
$LN5@romMapperM:
	push	ebp
	push	esi
	push	edi

; 339  :     }
; 340  : 
; 341  :     msxRs232 = malloc(sizeof(MSXRs232));

	push	40					; 00000028H
	call	_malloc

; 342  :     
; 343  :     msxRs232->deviceHandle = deviceManagerRegister(ROM_MSXRS232, &callbacks, msxRs232);

	push	eax
	mov	DWORD PTR _msxRs232, eax
	lea	eax, DWORD PTR _callbacks$[esp+56]
	push	eax
	push	89					; 00000059H
	call	_deviceManagerRegister
	mov	ecx, DWORD PTR _msxRs232
	add	esp, 16					; 00000010H
	mov	DWORD PTR [ecx], eax

; 344  :     msxRs232->debugHandle = debugDeviceRegister(DBGTYPE_BIOS, langDbgDevRs232(), &dbgCallbacks, msxRs232);

	lea	eax, DWORD PTR _dbgCallbacks$[esp+48]
	push	ecx
	push	eax
	call	_langDbgDevRs232
	push	eax
	push	3
	call	_debugDeviceRegister
	mov	ecx, DWORD PTR _msxRs232

; 345  : 
; 346  :     slotRegister(slot, sslot, startPage, pages, read, peek, write, destroy, msxRs232);

	mov	ebp, DWORD PTR _sslot$[esp+60]
	push	ecx
	push	OFFSET _destroy
	push	OFFSET _write
	push	OFFSET _peek
	push	OFFSET _read
	push	4
	push	ebx
	push	ebp
	push	DWORD PTR _slot$[esp+92]
	mov	DWORD PTR [ecx+4], eax
	call	_slotRegister

; 347  : 
; 348  :     msxRs232->romData = malloc(size);

	mov	esi, DWORD PTR _size$[esp+96]
	push	esi
	call	_malloc
	mov	edi, DWORD PTR _msxRs232

; 349  :     memcpy(msxRs232->romData, romData, size);

	push	esi
	push	DWORD PTR _romData$[esp+104]
	push	eax
	mov	DWORD PTR [edi+24], eax
	call	_memcpy

; 350  :     
; 351  :     msxRs232->slot  = slot;

	mov	ecx, DWORD PTR _slot$[esp+112]
	add	esp, 68					; 00000044H
	mov	DWORD PTR [edi+8], ecx
	xor	esi, esi

; 352  :     msxRs232->sslot = sslot;

	mov	DWORD PTR [edi+12], ebp

; 353  :     msxRs232->startPage  = startPage;

	mov	DWORD PTR [edi+16], ebx
$LL4@romMapperM:

; 354  : 
; 355  :     for (i = 0; i < pages; i++) {
; 356  :         slotMapPage(slot, sslot, i + startPage, NULL, 0, 0);

	push	0
	push	0
	push	0
	lea	eax, DWORD PTR [esi+ebx]
	push	eax
	push	ebp
	push	ecx
	call	_slotMapPage
	mov	ecx, DWORD PTR _slot$[esp+68]
	inc	esi
	add	esp, 24					; 00000018H
	cmp	esi, 4
	jl	SHORT $LL4@romMapperM

; 357  :     }
; 358  : 
; 359  :     msxRs232->i8251 = i8251Create(rs232transmit, rs232signal, setDataBits, setStopBits, setParity, 

	push	DWORD PTR _msxRs232
	push	OFFSET _getRts
	push	OFFSET _getDtr
	push	OFFSET _setRts
	push	OFFSET _setDtr
	push	OFFSET _setRxReady
	push	OFFSET _setParity
	push	OFFSET _setStopBits
	push	OFFSET _setDataBits
	push	OFFSET _rs232signal
	push	OFFSET _rs232transmit
	call	_i8251Create
	mov	ecx, DWORD PTR _msxRs232

; 360  :                                  setRxReady, setDtr, setRts, getDtr, getRts, msxRs232);
; 361  : 
; 362  :     msxRs232->i8254 = i8254Create(1843200, pitOut0, pitOut1, pitOut2, msxRs232);

	push	ecx
	push	OFFSET _pitOut2
	push	OFFSET _pitOut1
	push	OFFSET _pitOut0
	push	1843200					; 001c2000H
	mov	DWORD PTR [ecx+28], eax
	call	_i8254Create
	mov	ecx, DWORD PTR _msxRs232
	add	esp, 64					; 00000040H

; 363  : 
; 364  :     msxRs232->serialLink = archUartCreate(romMapperMsxRs232ReceiveCallback);

	push	OFFSET _romMapperMsxRs232ReceiveCallback
	mov	DWORD PTR [ecx+32], eax
	call	_archUartCreate
	mov	ecx, DWORD PTR _msxRs232

; 365  : 
; 366  :     ioPortRegister(0x80, readIo, writeIo, msxRs232);

	push	ecx
	push	OFFSET _writeIo
	push	OFFSET _readIo
	push	128					; 00000080H
	mov	DWORD PTR [ecx+20], eax
	call	_ioPortRegister

; 367  :     ioPortRegister(0x81, readIo, writeIo, msxRs232);

	push	DWORD PTR _msxRs232
	push	OFFSET _writeIo
	push	OFFSET _readIo
	push	129					; 00000081H
	call	_ioPortRegister

; 368  :     ioPortRegister(0x82, readIo, writeIo, msxRs232);

	push	DWORD PTR _msxRs232
	push	OFFSET _writeIo
	push	OFFSET _readIo
	push	130					; 00000082H
	call	_ioPortRegister

; 369  :     ioPortRegister(0x84, readIo, writeIo, msxRs232);

	push	DWORD PTR _msxRs232
	push	OFFSET _writeIo
	push	OFFSET _readIo
	push	132					; 00000084H
	call	_ioPortRegister
	add	esp, 68					; 00000044H

; 370  :     ioPortRegister(0x85, readIo, writeIo, msxRs232);

	push	DWORD PTR _msxRs232
	push	OFFSET _writeIo
	push	OFFSET _readIo
	push	133					; 00000085H
	call	_ioPortRegister

; 371  :     ioPortRegister(0x86, readIo, writeIo, msxRs232);

	push	DWORD PTR _msxRs232
	push	OFFSET _writeIo
	push	OFFSET _readIo
	push	134					; 00000086H
	call	_ioPortRegister

; 372  :     ioPortRegister(0x87, NULL, writeIo, msxRs232);

	push	DWORD PTR _msxRs232
	push	OFFSET _writeIo
	push	0
	push	135					; 00000087H
	call	_ioPortRegister

; 373  : 
; 374  :     reset(msxRs232);

	mov	esi, DWORD PTR _msxRs232

; 138  :     i8251Reset(msxRs232->i8251);

	push	DWORD PTR [esi+28]
	call	_i8251Reset

; 139  :     i8254Reset(msxRs232->i8254);

	push	DWORD PTR [esi+32]
	call	_i8254Reset
	add	esp, 56					; 00000038H

; 140  :     msxRs232->status = 0;

	mov	WORD PTR [esi+36], 0

; 375  : 
; 376  :     return 1;

	mov	eax, 1
	pop	edi
	pop	esi
	pop	ebp
	pop	ebx

; 377  : }

	add	esp, 32					; 00000020H
	ret	0
_romMapperMsxRs232Create ENDP
_TEXT	ENDS
END
