; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27054.0 

	TITLE	D:\repo\MSX-master\MSX\blueMSX-DPI\Src\Memory\romMapperKanji12.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_romMapperKanji12Create
PUBLIC	??_C@_0O@MDEIHGIC@mapperKanji12@		; `string'
PUBLIC	??_C@_07LHEPONKL@address@			; `string'
EXTRN	_deviceManagerRegister:PROC
EXTRN	_deviceManagerUnregister:PROC
EXTRN	_debugDeviceRegister:PROC
EXTRN	_debugDeviceUnregister:PROC
EXTRN	_dbgDeviceAddIoPorts:PROC
EXTRN	_dbgIoPortsAddPort:PROC
EXTRN	_saveStateOpenForRead:PROC
EXTRN	_saveStateOpenForWrite:PROC
EXTRN	_saveStateClose:PROC
EXTRN	_saveStateGet:PROC
EXTRN	_saveStateSet:PROC
EXTRN	_ioPortUnregister:PROC
EXTRN	_ioPortRegisterSub:PROC
EXTRN	_ioPortCheckSub:PROC
EXTRN	_langDbgDevKanji12:PROC
EXTRN	_free:PROC
EXTRN	_malloc:PROC
EXTRN	_memcpy:PROC
;	COMDAT ??_C@_07LHEPONKL@address@
CONST	SEGMENT
??_C@_07LHEPONKL@address@ DB 'address', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_0O@MDEIHGIC@mapperKanji12@
CONST	SEGMENT
??_C@_0O@MDEIHGIC@mapperKanji12@ DB 'mapperKanji12', 00H ; `string'
CONST	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommapperkanji12.c
;	COMDAT _getDebugInfo
_TEXT	SEGMENT
_value$1 = -4						; size = 1
_rm$ = 8						; size = 4
_dbgDevice$ = 12					; size = 4
_getDebugInfo PROC					; COMDAT

; 140  : {

	push	ecx

; 141  :     if (ioPortCheckSub(0xf7)) {

	push	247					; 000000f7H
	call	_ioPortCheckSub
	add	esp, 4
	test	eax, eax
	je	SHORT $LN3@getDebugIn

; 142  :         DbgIoPorts* ioPorts;
; 143  :         int i;
; 144  : 
; 145  :         ioPorts = dbgDeviceAddIoPorts(dbgDevice, langDbgDevKanji12(), 2);

	push	ebx
	push	esi
	push	edi
	push	2
	call	_langDbgDevKanji12
	push	eax
	push	DWORD PTR _dbgDevice$[esp+20]
	call	_dbgDeviceAddIoPorts

; 146  : 
; 147  :         for (i = 0; i < 16; i++) {

	mov	edi, DWORD PTR _rm$[esp+24]
	add	esp, 12					; 0000000cH
	mov	ebx, eax
	xor	esi, esi
$LL4@getDebugIn:

; 82   :     UInt8 value = 0xff;

	movzx	edx, si

; 83   : 
; 84   : 	switch (ioPort & 0x0f) {

	mov	ecx, edx
	mov	BYTE PTR _value$1[esp+16], 255		; 000000ffH
	and	ecx, 15					; 0000000fH
	sub	ecx, 0
	je	SHORT $LN10@getDebugIn
	sub	ecx, 1
	je	SHORT $LN10@getDebugIn
	sub	ecx, 8
	jne	SHORT $LN14@getDebugIn

; 85   : 	case 0:
; 86   : 		value = ~0xf7;
; 87   : 		break;
; 88   : 	case 1:
; 89   : 		value = 0x08;
; 90   : 		break;
; 91   : 	case 9:
; 92   : 		if (rm->address < rm->size) {

	mov	ecx, DWORD PTR [edi+16]
	cmp	ecx, DWORD PTR [edi+12]
	jae	SHORT $LN13@getDebugIn

; 93   : 			value = rm->romData[rm->address];

	mov	eax, DWORD PTR [edi]
	mov	al, BYTE PTR [ecx+eax]
	mov	BYTE PTR _value$1[esp+16], al

; 94   : 		} else {

	jmp	SHORT $LN14@getDebugIn
$LN13@getDebugIn:

; 95   : 			value = 0xff;

	mov	BYTE PTR _value$1[esp+16], 255		; 000000ffH
	jmp	SHORT $LN14@getDebugIn
$LN10@getDebugIn:

; 148  :             dbgIoPortsAddPort(ioPorts, i, 0x40 + i, DBG_IO_READWRITE, peek(rm, i));

	mov	BYTE PTR _value$1[esp+16], 8
$LN14@getDebugIn:
	push	DWORD PTR _value$1[esp+16]
	lea	eax, DWORD PTR [edx+64]
	push	3
	push	eax
	push	esi
	push	ebx
	call	_dbgIoPortsAddPort
	inc	esi
	add	esp, 20					; 00000014H
	cmp	esi, 16					; 00000010H
	jl	SHORT $LL4@getDebugIn
	pop	edi
	pop	esi
	pop	ebx
$LN3@getDebugIn:

; 149  :         }
; 150  :     }
; 151  : }

	pop	ecx
	ret	0
_getDebugInfo ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommapperkanji12.c
;	COMDAT _write
_TEXT	SEGMENT
_rm$ = 8						; size = 4
_ioPort$ = 12						; size = 2
_value$ = 16						; size = 1
_write	PROC						; COMDAT

; 129  : 	switch (ioPort & 0x0f) {

	mov	eax, DWORD PTR _ioPort$[esp-4]
	and	eax, 15					; 0000000fH
	push	esi
	sub	eax, 7
	je	SHORT $LN4@write
	sub	eax, 1
	jne	SHORT $LN2@write

; 132  : 		break;
; 133  : 	case 8: 
; 134  : 		rm->address = 0x800 + (((rm->address - 0x800) / (18 * 192)) * 192 + value) * 18;

	mov	esi, DWORD PTR _rm$[esp]
	mov	eax, 795364315				; 2f684bdbH
	mov	ecx, DWORD PTR [esi+16]
	sub	ecx, 2048				; 00000800H
	mul	ecx
	movzx	eax, BYTE PTR _value$[esp]
	sub	ecx, edx
	shr	ecx, 1
	add	ecx, edx
	shr	ecx, 11					; 0000000bH
	lea	ecx, DWORD PTR [ecx+ecx*2]
	shl	ecx, 6
	add	ecx, eax
	lea	eax, DWORD PTR [ecx+ecx*8]

; 135  : 		break;
; 136  : 	}
; 137  : }

	lea	eax, DWORD PTR [eax*2+2048]
	mov	DWORD PTR [esi+16], eax
	pop	esi
	ret	0
$LN4@write:

; 130  : 	case 7: 
; 131  : 		rm->address = 0x800 + (value * 192 + ((rm->address - 0x800) / 18) % 192) * 18;

	mov	esi, DWORD PTR _rm$[esp]
	mov	eax, 954437177				; 38e38e39H
	mov	ecx, DWORD PTR [esi+16]
	sub	ecx, 2048				; 00000800H
	mul	ecx
	mov	ecx, 192				; 000000c0H
	shr	edx, 2
	mov	eax, edx
	xor	edx, edx
	div	ecx
	movzx	eax, BYTE PTR _value$[esp]
	lea	eax, DWORD PTR [eax+eax*2]
	shl	eax, 6
	add	edx, eax
	lea	eax, DWORD PTR [edx+edx*8]

; 135  : 		break;
; 136  : 	}
; 137  : }

	lea	eax, DWORD PTR [eax*2+2048]
	mov	DWORD PTR [esi+16], eax
$LN2@write:
	pop	esi
	ret	0
_write	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommapperkanji12.c
;	COMDAT _read
_TEXT	SEGMENT
_rm$ = 8						; size = 4
_ioPort$ = 12						; size = 2
_read	PROC						; COMDAT

; 105  :     UInt8 value = 0xff;
; 106  : 
; 107  : 	switch (ioPort & 0x0f) {

	mov	eax, DWORD PTR _ioPort$[esp-4]
	or	cl, 255					; 000000ffH
	and	eax, 15					; 0000000fH
	sub	eax, 0
	je	SHORT $LN4@read
	sub	eax, 1
	je	SHORT $LN4@read
	sub	eax, 8
	jne	SHORT $LN10@read

; 108  : 	case 0:
; 109  : 		value = ~0xf7;
; 110  : 		break;
; 111  : 	case 1:
; 112  : 		value = 0x08;
; 113  : 		break;
; 114  : 	case 9:
; 115  : 		if (rm->address < rm->size) {

	mov	ecx, DWORD PTR _rm$[esp-4]
	push	ebx
	mov	edx, DWORD PTR [ecx+16]
	cmp	edx, DWORD PTR [ecx+12]
	jae	SHORT $LN7@read

; 116  : 			value = rm->romData[rm->address];

	mov	eax, DWORD PTR [ecx]
	mov	bl, BYTE PTR [edx+eax]

; 117  : 		} else {
; 118  : 			value = 0xff;
; 119  : 		}
; 120  : 		rm->address++;

	lea	eax, DWORD PTR [edx+1]
	mov	DWORD PTR [ecx+16], eax

; 121  : 		break;
; 122  : 	}
; 123  : 
; 124  : 	return value;

	mov	al, bl
	pop	ebx

; 125  : }

	ret	0
$LN7@read:

; 117  : 		} else {
; 118  : 			value = 0xff;
; 119  : 		}
; 120  : 		rm->address++;

	lea	eax, DWORD PTR [edx+1]
	or	bl, 255					; 000000ffH
	mov	DWORD PTR [ecx+16], eax

; 121  : 		break;
; 122  : 	}
; 123  : 
; 124  : 	return value;

	mov	al, bl
	pop	ebx

; 125  : }

	ret	0
$LN10@read:

; 121  : 		break;
; 122  : 	}
; 123  : 
; 124  : 	return value;

	mov	al, cl

; 125  : }

	ret	0
$LN4@read:
	mov	al, 8
	ret	0
_read	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommapperkanji12.c
;	COMDAT _peek
_TEXT	SEGMENT
_rm$ = 8						; size = 4
_ioPort$ = 12						; size = 2
_peek	PROC						; COMDAT

; 82   :     UInt8 value = 0xff;
; 83   : 
; 84   : 	switch (ioPort & 0x0f) {

	mov	eax, DWORD PTR _ioPort$[esp-4]
	or	cl, 255					; 000000ffH
	and	eax, 15					; 0000000fH
	sub	eax, 0
	je	SHORT $LN4@peek
	sub	eax, 1
	je	SHORT $LN4@peek
	sub	eax, 8
	jne	SHORT $LN10@peek

; 85   : 	case 0:
; 86   : 		value = ~0xf7;
; 87   : 		break;
; 88   : 	case 1:
; 89   : 		value = 0x08;
; 90   : 		break;
; 91   : 	case 9:
; 92   : 		if (rm->address < rm->size) {

	mov	eax, DWORD PTR _rm$[esp-4]
	mov	ecx, DWORD PTR [eax+16]
	cmp	ecx, DWORD PTR [eax+12]
	jae	SHORT $LN7@peek

; 93   : 			value = rm->romData[rm->address];

	mov	eax, DWORD PTR [eax]
	mov	al, BYTE PTR [ecx+eax]

; 101  : }

	ret	0
$LN7@peek:

; 94   : 		} else {
; 95   : 			value = 0xff;

	or	al, 255					; 000000ffH

; 101  : }

	ret	0
$LN10@peek:

; 96   : 		}
; 97   : 		break;
; 98   : 	}
; 99   : 
; 100  : 	return value;

	mov	al, cl

; 101  : }

	ret	0
$LN4@peek:
	mov	al, 8
	ret	0
_peek	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommapperkanji12.c
;	COMDAT _destroy
_TEXT	SEGMENT
_rm$ = 8						; size = 4
_destroy PROC						; COMDAT

; 67   : {

	push	esi

; 68   :     deviceManagerUnregister(rm->deviceHandle);

	mov	esi, DWORD PTR _rm$[esp]
	push	DWORD PTR [esi+4]
	call	_deviceManagerUnregister

; 69   :     debugDeviceUnregister(rm->debugHandle);

	push	DWORD PTR [esi+8]
	call	_debugDeviceUnregister

; 70   : 
; 71   :     ioPortUnregister(0xd9);

	push	217					; 000000d9H
	call	_ioPortUnregister

; 72   :     ioPortUnregister(0xd8);

	push	216					; 000000d8H
	call	_ioPortUnregister

; 73   :     ioPortUnregister(0xda);

	push	218					; 000000daH
	call	_ioPortUnregister

; 74   :     ioPortUnregister(0xdb);

	push	219					; 000000dbH
	call	_ioPortUnregister

; 75   : 
; 76   :     free(rm->romData);

	push	DWORD PTR [esi]
	call	_free

; 77   :     free(rm);

	push	esi
	call	_free
	add	esp, 32					; 00000020H
	pop	esi

; 78   : }

	ret	0
_destroy ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommapperkanji12.c
;	COMDAT _loadState
_TEXT	SEGMENT
_rm$ = 8						; size = 4
_loadState PROC						; COMDAT

; 58   : {

	push	esi

; 59   :     SaveState* state = saveStateOpenForRead("mapperKanji12");

	push	OFFSET ??_C@_0O@MDEIHGIC@mapperKanji12@
	call	_saveStateOpenForRead

; 60   : 
; 61   :     rm->address = saveStateGet(state, "address", 0);

	push	0
	mov	esi, eax
	push	OFFSET ??_C@_07LHEPONKL@address@
	push	esi
	call	_saveStateGet
	mov	ecx, DWORD PTR _rm$[esp+16]

; 62   : 
; 63   :     saveStateClose(state);

	push	esi
	mov	DWORD PTR [ecx+16], eax
	call	_saveStateClose
	add	esp, 20					; 00000014H
	pop	esi

; 64   : }

	ret	0
_loadState ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommapperkanji12.c
;	COMDAT _saveState
_TEXT	SEGMENT
_rm$ = 8						; size = 4
_saveState PROC						; COMDAT

; 49   : {

	push	esi

; 50   :     SaveState* state = saveStateOpenForWrite("mapperKanji12");

	push	OFFSET ??_C@_0O@MDEIHGIC@mapperKanji12@
	call	_saveStateOpenForWrite

; 51   : 
; 52   :     saveStateSet(state, "address", rm->address);

	mov	ecx, DWORD PTR _rm$[esp+4]
	mov	esi, eax
	push	DWORD PTR [ecx+16]
	push	OFFSET ??_C@_07LHEPONKL@address@
	push	esi
	call	_saveStateSet

; 53   :     
; 54   :     saveStateClose(state);

	push	esi
	call	_saveStateClose
	add	esp, 20					; 00000014H
	pop	esi

; 55   : }

	ret	0
_saveState ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommapperkanji12.c
;	COMDAT _romMapperKanji12Create
_TEXT	SEGMENT
_callbacks$ = -32					; size = 16
_dbgCallbacks$ = -16					; size = 16
_romData$ = 8						; size = 4
_size$ = 12						; size = 4
_romMapperKanji12Create PROC				; COMDAT

; 154  : {

	sub	esp, 32					; 00000020H
	push	edi

; 155  :     DeviceCallbacks callbacks = { destroy, NULL, saveState, loadState };
; 156  :     DebugCallbacks dbgCallbacks = { getDebugInfo, NULL, NULL, NULL };
; 157  :     RomMapperKanji12* rm;
; 158  : 
; 159  : 	if (size != 0x20000 && size != 0x40000) {

	mov	edi, DWORD PTR _size$[esp+32]
	mov	DWORD PTR _callbacks$[esp+36], OFFSET _destroy
	mov	DWORD PTR _callbacks$[esp+40], 0
	mov	DWORD PTR _callbacks$[esp+44], OFFSET _saveState
	mov	DWORD PTR _callbacks$[esp+48], OFFSET _loadState
	mov	DWORD PTR _dbgCallbacks$[esp+36], OFFSET _getDebugInfo
	mov	DWORD PTR _dbgCallbacks$[esp+40], 0
	mov	DWORD PTR _dbgCallbacks$[esp+44], 0
	mov	DWORD PTR _dbgCallbacks$[esp+48], 0
	cmp	edi, 131072				; 00020000H
	je	SHORT $LN2@romMapperK
	cmp	edi, 262144				; 00040000H
	je	SHORT $LN2@romMapperK

; 160  :         return 0;

	xor	eax, eax
	pop	edi

; 177  : }

	add	esp, 32					; 00000020H
	ret	0
$LN2@romMapperK:
	push	esi

; 161  :     }
; 162  : 
; 163  :     rm = malloc(sizeof(RomMapperKanji12));

	push	20					; 00000014H
	call	_malloc
	mov	esi, eax

; 164  : 
; 165  :     rm->size = size;
; 166  :     rm->address = 0;
; 167  : 
; 168  :     rm->deviceHandle = deviceManagerRegister(ROM_KANJI12, &callbacks, rm);

	lea	eax, DWORD PTR _callbacks$[esp+44]
	push	esi
	push	eax
	push	30					; 0000001eH
	mov	DWORD PTR [esi+12], edi
	mov	DWORD PTR [esi+16], 0
	call	_deviceManagerRegister
	add	esp, 16					; 00000010H
	mov	DWORD PTR [esi+4], eax

; 169  :     rm->debugHandle = debugDeviceRegister(DBGTYPE_CART, langDbgDevKanji12(), &dbgCallbacks, rm);

	lea	eax, DWORD PTR _dbgCallbacks$[esp+40]
	push	esi
	push	eax
	call	_langDbgDevKanji12
	push	eax
	push	2
	call	_debugDeviceRegister

; 170  : 
; 171  :     rm->romData = malloc(size);

	push	edi
	mov	DWORD PTR [esi+8], eax
	call	_malloc

; 172  :     memcpy(rm->romData, romData, size);

	push	edi
	push	DWORD PTR _romData$[esp+60]
	mov	DWORD PTR [esi], eax
	push	eax
	call	_memcpy

; 173  :     
; 174  :     ioPortRegisterSub(0xf7, read, write, rm);

	push	esi
	push	OFFSET _write
	push	OFFSET _read
	push	247					; 000000f7H
	call	_ioPortRegisterSub
	add	esp, 48					; 00000030H

; 175  : 
; 176  :     return 1;

	mov	eax, 1
	pop	esi
	pop	edi

; 177  : }

	add	esp, 32					; 00000020H
	ret	0
_romMapperKanji12Create ENDP
_TEXT	ENDS
END
