; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27054.0 

	TITLE	D:\repo\MSX-master\MSX\blueMSX-DPI\Src\Memory\romMapperKorean126.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_romMapperKorean126Create
PUBLIC	___local_stdio_printf_options
PUBLIC	_sprintf
PUBLIC	??_C@_0BA@EPBLLHIF@mapperKorean126@		; `string'
PUBLIC	??_C@_0M@NAELOINI@romMapper?$CFd@		; `string'
EXTRN	_slotRegister:PROC
EXTRN	_slotUnregister:PROC
EXTRN	_slotMapPage:PROC
EXTRN	_deviceManagerRegister:PROC
EXTRN	_deviceManagerUnregister:PROC
EXTRN	_saveStateOpenForRead:PROC
EXTRN	_saveStateOpenForWrite:PROC
EXTRN	_saveStateClose:PROC
EXTRN	_saveStateGet:PROC
EXTRN	_saveStateSet:PROC
EXTRN	_free:PROC
EXTRN	_malloc:PROC
EXTRN	___stdio_common_vsprintf:PROC
EXTRN	@__security_check_cookie@4:PROC
EXTRN	_memcpy:PROC
EXTRN	___security_cookie:DWORD
_DATA	SEGMENT
COMM	?_OptionsStorage@?1??__local_stdio_printf_options@@9@9:QWORD							; `__local_stdio_printf_options'::`2'::_OptionsStorage
_DATA	ENDS
;	COMDAT ??_C@_0M@NAELOINI@romMapper?$CFd@
CONST	SEGMENT
??_C@_0M@NAELOINI@romMapper?$CFd@ DB 'romMapper%d', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0BA@EPBLLHIF@mapperKorean126@
CONST	SEGMENT
??_C@_0BA@EPBLLHIF@mapperKorean126@ DB 'mapperKorean126', 00H ; `string'
CONST	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommapperkorean126.c
;	COMDAT _write
_TEXT	SEGMENT
_rm$ = 8						; size = 4
_address$ = 12						; size = 2
_value$ = 16						; size = 1
_write	PROC						; COMDAT

; 92   : {

	push	ebx

; 93   :     UInt8* bankData;
; 94   :     int bank;
; 95   : 
; 96   :     address += 0x4000;

	mov	ebx, DWORD PTR _address$[esp]

; 97   :     
; 98   :     // $4000-$7FFF: bit 0=bank
; 99   :     if (address>0x7fff) return;

	mov	eax, 32767				; 00007fffH
	add	ebx, 16384				; 00004000H
	cmp	bx, ax
	ja	SHORT $LN1@write

; 100  :     bank=address<<1&2;
; 101  : 
; 102  :     bankData = rm->romData + ((int)value << 14);

	movzx	eax, BYTE PTR _value$[esp]
	and	ebx, 1
	push	esi
	push	edi
	mov	edi, DWORD PTR _rm$[esp+8]
	mov	esi, eax
	add	ebx, ebx
	shl	esi, 14					; 0000000eH

; 103  : 
; 104  :     rm->romMapper[bank] = value;
; 105  :     
; 106  :     slotMapPage(rm->slot, rm->sslot, rm->startPage + bank, bankData, 1, 0);

	push	0
	push	1
	add	esi, DWORD PTR [edi+4]
	mov	DWORD PTR [edi+ebx*4+24], eax
	mov	eax, DWORD PTR [edi+16]
	push	esi
	add	eax, ebx
	push	eax
	push	DWORD PTR [edi+12]
	push	DWORD PTR [edi+8]
	call	_slotMapPage

; 107  :     slotMapPage(rm->slot, rm->sslot, rm->startPage + bank + 1, bankData + 0x2000, 1, 0);

	push	0
	push	1
	lea	eax, DWORD PTR [esi+8192]
	push	eax
	mov	eax, DWORD PTR [edi+16]
	inc	eax
	add	eax, ebx
	push	eax
	push	DWORD PTR [edi+12]
	push	DWORD PTR [edi+8]
	call	_slotMapPage
	add	esp, 48					; 00000030H
	pop	edi
	pop	esi
$LN1@write:

; 108  : }

	pop	ebx
	ret	0
_write	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommapperkorean126.c
;	COMDAT _destroy
_TEXT	SEGMENT
_rm$ = 8						; size = 4
_destroy PROC						; COMDAT

; 83   : {

	push	esi

; 84   :     slotUnregister(rm->slot, rm->sslot, rm->startPage);

	mov	esi, DWORD PTR _rm$[esp]
	push	DWORD PTR [esi+16]
	push	DWORD PTR [esi+12]
	push	DWORD PTR [esi+8]
	call	_slotUnregister

; 85   :     deviceManagerUnregister(rm->deviceHandle);

	push	DWORD PTR [esi]
	call	_deviceManagerUnregister

; 86   : 
; 87   :     free(rm->romData);

	push	DWORD PTR [esi+4]
	call	_free

; 88   :     free(rm);

	push	esi
	call	_free
	add	esp, 24					; 00000018H
	pop	esi

; 89   : }

	ret	0
_destroy ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommapperkorean126.c
;	COMDAT _loadState
_TEXT	SEGMENT
_tag$ = -20						; size = 16
__$ArrayPad$ = -4					; size = 4
_rm$ = 8						; size = 4
_loadState PROC						; COMDAT

; 63   : {

	sub	esp, 20					; 00000014H
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, esp
	mov	DWORD PTR __$ArrayPad$[esp+20], eax
	push	ebx
	mov	ebx, DWORD PTR _rm$[esp+20]
	push	ebp
	push	esi
	push	edi

; 64   :     SaveState* state = saveStateOpenForRead("mapperKorean126");

	push	OFFSET ??_C@_0BA@EPBLLHIF@mapperKorean126@
	call	_saveStateOpenForRead
	add	esp, 4
	lea	edi, DWORD PTR [ebx+24]
	mov	ebp, eax
	xor	esi, esi
	npad	6
$LL4@loadState:

; 65   :     char tag[16];
; 66   :     int i;
; 67   : 
; 68   :     for (i = 0; i < 4; i++) {
; 69   :         sprintf(tag, "romMapper%d", i);

	push	esi
	lea	eax, DWORD PTR _tag$[esp+40]
	push	OFFSET ??_C@_0M@NAELOINI@romMapper?$CFd@
	push	eax
	call	_sprintf

; 70   :         rm->romMapper[i] = saveStateGet(state, tag, 0);

	push	0
	lea	eax, DWORD PTR _tag$[esp+52]
	push	eax
	push	ebp
	call	_saveStateGet
	inc	esi
	mov	DWORD PTR [edi], eax
	add	esp, 24					; 00000018H
	lea	edi, DWORD PTR [edi+4]
	cmp	esi, 4
	jl	SHORT $LL4@loadState

; 71   :     }
; 72   : 
; 73   :     saveStateClose(state);

	push	ebp
	call	_saveStateClose
	add	esp, 4
	lea	ebp, DWORD PTR [ebx+24]
	xor	edi, edi
	npad	7
$LL7@loadState:

; 74   : 
; 75   :     for (i = 0; i < 4; i += 2) {
; 76   :         UInt8* bankData = rm->romData + (rm->romMapper[i] << 14);

	mov	esi, DWORD PTR [ebp]

; 77   :         slotMapPage(rm->slot, rm->sslot, rm->startPage + i,     bankData, 1, 0);

	mov	eax, DWORD PTR [ebx+16]
	push	0
	push	1
	shl	esi, 14					; 0000000eH
	add	eax, edi
	add	esi, DWORD PTR [ebx+4]
	push	esi
	push	eax
	push	DWORD PTR [ebx+12]
	push	DWORD PTR [ebx+8]
	call	_slotMapPage

; 78   :         slotMapPage(rm->slot, rm->sslot, rm->startPage + i + 1, bankData + 0x2000, 1, 0);

	push	0
	push	1
	lea	eax, DWORD PTR [esi+8192]
	push	eax
	mov	eax, DWORD PTR [ebx+16]
	inc	eax
	add	eax, edi
	push	eax
	push	DWORD PTR [ebx+12]
	push	DWORD PTR [ebx+8]
	call	_slotMapPage
	add	edi, 2
	lea	ebp, DWORD PTR [ebp+8]
	add	esp, 48					; 00000030H
	cmp	edi, 4
	jl	SHORT $LL7@loadState

; 79   :     }
; 80   : }

	mov	ecx, DWORD PTR __$ArrayPad$[esp+36]
	pop	edi
	pop	esi
	pop	ebp
	pop	ebx
	xor	ecx, esp
	call	@__security_check_cookie@4
	add	esp, 20					; 00000014H
	ret	0
_loadState ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommapperkorean126.c
;	COMDAT _saveState
_TEXT	SEGMENT
_tag$ = -20						; size = 16
__$ArrayPad$ = -4					; size = 4
_rm$ = 8						; size = 4
_saveState PROC						; COMDAT

; 49   : {

	sub	esp, 20					; 00000014H
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, esp
	mov	DWORD PTR __$ArrayPad$[esp+20], eax
	push	ebx
	push	esi
	mov	esi, DWORD PTR _rm$[esp+24]
	push	edi

; 50   :     SaveState* state = saveStateOpenForWrite("mapperKorean126");

	push	OFFSET ??_C@_0BA@EPBLLHIF@mapperKorean126@
	call	_saveStateOpenForWrite
	add	esp, 4
	xor	edi, edi
	mov	ebx, eax
	add	esi, 24					; 00000018H
	npad	7
$LL4@saveState:

; 51   :     char tag[16];
; 52   :     int i;
; 53   : 
; 54   :     for (i = 0; i < 4; i++) {
; 55   :         sprintf(tag, "romMapper%d", i);

	push	edi
	lea	eax, DWORD PTR _tag$[esp+36]
	push	OFFSET ??_C@_0M@NAELOINI@romMapper?$CFd@
	push	eax
	call	_sprintf

; 56   :         saveStateSet(state, tag, rm->romMapper[i]);

	push	DWORD PTR [esi]
	lea	eax, DWORD PTR _tag$[esp+48]
	push	eax
	push	ebx
	call	_saveStateSet
	inc	edi
	lea	esi, DWORD PTR [esi+4]
	add	esp, 24					; 00000018H
	cmp	edi, 4
	jl	SHORT $LL4@saveState

; 57   :     }
; 58   : 
; 59   :     saveStateClose(state);

	push	ebx
	call	_saveStateClose

; 60   : }

	mov	ecx, DWORD PTR __$ArrayPad$[esp+36]
	add	esp, 4
	pop	edi
	pop	esi
	pop	ebx
	xor	ecx, esp
	call	@__security_check_cookie@4
	add	esp, 20					; 00000014H
	ret	0
_saveState ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File c:\program files (x86)\windows kits\10\include\10.0.19041.0\ucrt\stdio.h
;	COMDAT _sprintf
_TEXT	SEGMENT
__Buffer$ = 8						; size = 4
__Format$ = 12						; size = 4
_sprintf PROC						; COMDAT

; 1392 :         int const _Result = __stdio_common_vsprintf(

	lea	eax, DWORD PTR __Format$[esp]
	push	eax
	push	0
	push	DWORD PTR __Format$[esp+4]
	push	-1
	push	DWORD PTR __Buffer$[esp+12]
	call	___local_stdio_printf_options
	mov	ecx, DWORD PTR [eax]
	push	DWORD PTR [eax+4]
	or	ecx, 1
	push	ecx
	call	___stdio_common_vsprintf

; 1393 :             _CRT_INTERNAL_LOCAL_PRINTF_OPTIONS | _CRT_INTERNAL_PRINTF_LEGACY_VSPRINTF_NULL_TERMINATION,
; 1394 :             _Buffer, _BufferCount, _Format, _Locale, _ArgList);
; 1395 : 
; 1396 :         return _Result < 0 ? -1 : _Result;

	or	ecx, -1
	add	esp, 28					; 0000001cH
	test	eax, eax
	cmovs	eax, ecx

; 1772 :         int _Result;
; 1773 :         va_list _ArgList;
; 1774 :         __crt_va_start(_ArgList, _Format);
; 1775 : 
; 1776 :         _Result = _vsprintf_l(_Buffer, _Format, NULL, _ArgList);
; 1777 : 
; 1778 :         __crt_va_end(_ArgList);
; 1779 :         return _Result;
; 1780 :     }

	ret	0
_sprintf ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File c:\program files (x86)\windows kits\10\include\10.0.19041.0\ucrt\stdio.h
;	COMDAT __vsprintf_l
_TEXT	SEGMENT
__Buffer$ = 8						; size = 4
__Format$ = 12						; size = 4
__Locale$ = 16						; size = 4
__ArgList$ = 20						; size = 4
__vsprintf_l PROC					; COMDAT

; 1392 :         int const _Result = __stdio_common_vsprintf(

	push	DWORD PTR __ArgList$[esp-4]
	push	DWORD PTR __Locale$[esp]
	push	DWORD PTR __Format$[esp+4]
	push	-1
	push	DWORD PTR __Buffer$[esp+12]
	call	___local_stdio_printf_options
	mov	ecx, DWORD PTR [eax]
	push	DWORD PTR [eax+4]
	or	ecx, 1
	push	ecx
	call	___stdio_common_vsprintf

; 1393 :             _CRT_INTERNAL_LOCAL_PRINTF_OPTIONS | _CRT_INTERNAL_PRINTF_LEGACY_VSPRINTF_NULL_TERMINATION,
; 1394 :             _Buffer, _BufferCount, _Format, _Locale, _ArgList);
; 1395 : 
; 1396 :         return _Result < 0 ? -1 : _Result;

	or	ecx, -1
	add	esp, 28					; 0000001cH
	test	eax, eax
	cmovs	eax, ecx

; 1459 :         return _vsnprintf_l(_Buffer, (size_t)-1, _Format, _Locale, _ArgList);
; 1460 :     }

	ret	0
__vsprintf_l ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File c:\program files (x86)\windows kits\10\include\10.0.19041.0\ucrt\stdio.h
;	COMDAT __vsnprintf_l
_TEXT	SEGMENT
__Buffer$ = 8						; size = 4
__BufferCount$ = 12					; size = 4
__Format$ = 16						; size = 4
__Locale$ = 20						; size = 4
__ArgList$ = 24						; size = 4
__vsnprintf_l PROC					; COMDAT

; 1392 :         int const _Result = __stdio_common_vsprintf(

	push	DWORD PTR __ArgList$[esp-4]
	push	DWORD PTR __Locale$[esp]
	push	DWORD PTR __Format$[esp+4]
	push	DWORD PTR __BufferCount$[esp+8]
	push	DWORD PTR __Buffer$[esp+12]
	call	___local_stdio_printf_options
	mov	ecx, DWORD PTR [eax]
	push	DWORD PTR [eax+4]
	or	ecx, 1
	push	ecx
	call	___stdio_common_vsprintf

; 1393 :             _CRT_INTERNAL_LOCAL_PRINTF_OPTIONS | _CRT_INTERNAL_PRINTF_LEGACY_VSPRINTF_NULL_TERMINATION,
; 1394 :             _Buffer, _BufferCount, _Format, _Locale, _ArgList);
; 1395 : 
; 1396 :         return _Result < 0 ? -1 : _Result;

	or	ecx, -1
	add	esp, 28					; 0000001cH
	test	eax, eax
	cmovs	eax, ecx

; 1397 :     }

	ret	0
__vsnprintf_l ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File c:\program files (x86)\windows kits\10\include\10.0.19041.0\ucrt\corecrt_stdio_config.h
;	COMDAT ___local_stdio_printf_options
_TEXT	SEGMENT
___local_stdio_printf_options PROC			; COMDAT

; 91   :         static unsigned __int64 _OptionsStorage;
; 92   :         return &_OptionsStorage;

	mov	eax, OFFSET ?_OptionsStorage@?1??__local_stdio_printf_options@@9@9 ; `__local_stdio_printf_options'::`2'::_OptionsStorage

; 93   :     }

	ret	0
___local_stdio_printf_options ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommapperkorean126.c
;	COMDAT _romMapperKorean126Create
_TEXT	SEGMENT
_callbacks$ = -16					; size = 16
_filename$ = 8						; size = 4
_romData$ = 12						; size = 4
_size$ = 16						; size = 4
_slot$ = 20						; size = 4
_sslot$ = 24						; size = 4
_startPage$ = 28					; size = 4
_romMapperKorean126Create PROC				; COMDAT

; 112  : {

	sub	esp, 16					; 00000010H

; 113  :     DeviceCallbacks callbacks = { destroy, NULL, saveState, loadState };
; 114  :     RomMapperKorean126* rm;
; 115  :     int i;
; 116  : 
; 117  :     if (size < 0x8000) {

	cmp	DWORD PTR _size$[esp+12], 32768		; 00008000H
	mov	DWORD PTR _callbacks$[esp+16], OFFSET _destroy
	mov	DWORD PTR _callbacks$[esp+20], 0
	mov	DWORD PTR _callbacks$[esp+24], OFFSET _saveState
	mov	DWORD PTR _callbacks$[esp+28], OFFSET _loadState
	jge	SHORT $LN5@romMapperK

; 118  :         return 0;

	xor	eax, eax

; 142  : }

	add	esp, 16					; 00000010H
	ret	0
$LN5@romMapperK:
	push	ebx
	push	ebp
	push	esi
	push	edi

; 119  :     }
; 120  : 
; 121  :     rm = malloc(sizeof(RomMapperKorean126));

	push	40					; 00000028H
	call	_malloc
	mov	esi, eax

; 122  : 
; 123  :     rm->deviceHandle = deviceManagerRegister(ROM_KOREAN126, &callbacks, rm);

	lea	eax, DWORD PTR _callbacks$[esp+36]
	push	esi
	push	eax
	push	14					; 0000000eH
	call	_deviceManagerRegister

; 124  :     slotRegister(slot, sslot, startPage, 4, NULL, NULL, write, destroy, rm);

	mov	ebp, DWORD PTR _startPage$[esp+44]
	mov	ebx, DWORD PTR _sslot$[esp+44]
	mov	edi, DWORD PTR _slot$[esp+44]
	push	esi
	push	OFFSET _destroy
	push	OFFSET _write
	push	0
	push	0
	push	4
	push	ebp
	push	ebx
	push	edi
	mov	DWORD PTR [esi], eax
	call	_slotRegister

; 125  : 
; 126  :     rm->romData = malloc(size);

	push	DWORD PTR _size$[esp+80]
	call	_malloc

; 127  :     memcpy(rm->romData, romData, size);

	push	DWORD PTR _size$[esp+84]
	mov	DWORD PTR [esi+4], eax
	push	DWORD PTR _romData$[esp+88]
	push	eax
	call	_memcpy

; 128  :     rm->size = size;

	mov	eax, DWORD PTR _size$[esp+96]
	add	esp, 68					; 00000044H

; 129  :     rm->slot  = slot;
; 130  :     rm->sslot = sslot;

	mov	DWORD PTR [esi+12], ebx

; 131  :     rm->startPage  = startPage;
; 132  : 
; 133  :     rm->romMapper[0] = 0;

	lea	ebx, DWORD PTR [esi+24]
	mov	DWORD PTR [esi+8], edi
	xor	edi, edi
	mov	DWORD PTR [esi+20], eax
	mov	DWORD PTR [esi+16], ebp
	mov	DWORD PTR [ebx], 0

; 134  :     rm->romMapper[2] = 0;

	mov	DWORD PTR [esi+32], 0
$LL4@romMapperK:

; 135  : 
; 136  :     for (i = 0; i < 4; i += 2) {   
; 137  :         slotMapPage(rm->slot, rm->sslot, rm->startPage + i,     rm->romData + rm->romMapper[i] * 0x2000, 1, 0);

	mov	eax, DWORD PTR [ebx]
	push	0
	shl	eax, 13					; 0000000dH
	add	eax, DWORD PTR [esi+4]
	push	1
	push	eax
	mov	eax, DWORD PTR [esi+16]
	add	eax, edi
	push	eax
	push	DWORD PTR [esi+12]
	push	DWORD PTR [esi+8]
	call	_slotMapPage

; 138  :         slotMapPage(rm->slot, rm->sslot, rm->startPage + i + 1, rm->romData + rm->romMapper[i] * 0x2000 + 0x2000, 1, 0);

	mov	eax, DWORD PTR [ebx]
	inc	eax
	push	0
	shl	eax, 13					; 0000000dH
	add	eax, DWORD PTR [esi+4]
	push	1
	push	eax
	mov	eax, DWORD PTR [esi+16]
	inc	eax
	add	eax, edi
	push	eax
	push	DWORD PTR [esi+12]
	push	DWORD PTR [esi+8]
	call	_slotMapPage
	add	edi, 2
	lea	ebx, DWORD PTR [ebx+8]
	add	esp, 48					; 00000030H
	cmp	edi, 4
	jl	SHORT $LL4@romMapperK

; 139  :     }
; 140  : 
; 141  :     return 1;

	pop	edi
	pop	esi
	pop	ebp
	mov	eax, 1
	pop	ebx

; 142  : }

	add	esp, 16					; 00000010H
	ret	0
_romMapperKorean126Create ENDP
_TEXT	ENDS
END
