; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27054.0 

	TITLE	D:\repo\MSX-master\MSX\blueMSX-DPI\Src\Memory\romMapperKonami4.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_romMapperKonami4Create
PUBLIC	___local_stdio_printf_options
PUBLIC	_sprintf
PUBLIC	??_C@_0O@FPDAHDBH@mapperKonami4@		; `string'
PUBLIC	??_C@_0M@NAELOINI@romMapper?$CFd@		; `string'
EXTRN	_slotRegister:PROC
EXTRN	_slotUnregister:PROC
EXTRN	_slotMapPage:PROC
EXTRN	_deviceManagerRegister:PROC
EXTRN	_deviceManagerUnregister:PROC
EXTRN	_saveStateOpenForRead:PROC
EXTRN	_saveStateOpenForWrite:PROC
EXTRN	_saveStateClose:PROC
EXTRN	_saveStateGet:PROC
EXTRN	_saveStateSet:PROC
EXTRN	_free:PROC
EXTRN	_malloc:PROC
EXTRN	___stdio_common_vsprintf:PROC
EXTRN	@__security_check_cookie@4:PROC
EXTRN	_memcpy:PROC
EXTRN	_memset:PROC
EXTRN	___security_cookie:DWORD
_DATA	SEGMENT
COMM	?_OptionsStorage@?1??__local_stdio_printf_options@@9@9:QWORD							; `__local_stdio_printf_options'::`2'::_OptionsStorage
_DATA	ENDS
;	COMDAT ??_C@_0M@NAELOINI@romMapper?$CFd@
CONST	SEGMENT
??_C@_0M@NAELOINI@romMapper?$CFd@ DB 'romMapper%d', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0O@FPDAHDBH@mapperKonami4@
CONST	SEGMENT
??_C@_0O@FPDAHDBH@mapperKonami4@ DB 'mapperKonami4', 00H ; `string'
CONST	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommapperkonami4.c
;	COMDAT _write
_TEXT	SEGMENT
_rm$ = 8						; size = 4
_address$ = 12						; size = 2
_value$ = 16						; size = 1
_write	PROC						; COMDAT

; 91   :     int bank;
; 92   : 
; 93   :     address += 0x4000;

	mov	ecx, DWORD PTR _address$[esp-4]

; 94   : 
; 95   :     /* Page at 4000h is fixed */
; 96   :     if (address < 0x6000 || address >= 0xc000) {

	mov	edx, 24575				; 00005fffH
	add	ecx, 16384				; 00004000H
	lea	eax, DWORD PTR [ecx-24576]
	cmp	ax, dx
	ja	SHORT $LN3@write

; 97   :         return;
; 98   :     }
; 99   : 
; 100  :     bank = (address - 0x4000) >> 13;

	push	esi

; 101  : 
; 102  :     value %= rm->size / 0x2000;
; 103  :     if (rm->romMapper[bank] != value) {

	mov	esi, DWORD PTR _rm$[esp]
	push	edi
	movzx	edi, cx
	sub	edi, 16384				; 00004000H
	mov	eax, DWORD PTR [esi+20]
	cdq
	and	edx, 8191				; 00001fffH
	sar	edi, 13					; 0000000dH
	lea	ecx, DWORD PTR [edx+eax]
	movzx	eax, BYTE PTR _value$[esp+4]
	sar	ecx, 13					; 0000000dH
	cdq
	idiv	ecx
	movzx	ecx, dl
	cmp	DWORD PTR [esi+edi*4+24], ecx
	je	SHORT $LN6@write

; 104  :         UInt8* bankData = rm->romData + ((int)value << 13);
; 105  : 
; 106  :         rm->romMapper[bank] = value;
; 107  :         
; 108  :         slotMapPage(rm->slot, rm->sslot, rm->startPage + bank, bankData, 1, 0);

	push	0
	mov	eax, ecx
	shl	eax, 13					; 0000000dH
	add	eax, DWORD PTR [esi+4]
	push	1
	push	eax
	mov	DWORD PTR [esi+edi*4+24], ecx
	mov	eax, DWORD PTR [esi+16]
	add	eax, edi
	push	eax
	push	DWORD PTR [esi+12]
	push	DWORD PTR [esi+8]
	call	_slotMapPage
	add	esp, 24					; 00000018H
$LN6@write:
	pop	edi
	pop	esi
$LN3@write:

; 109  :     }
; 110  : }

	ret	0
_write	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommapperkonami4.c
;	COMDAT _destroy
_TEXT	SEGMENT
_rm$ = 8						; size = 4
_destroy PROC						; COMDAT

; 81   : {

	push	esi

; 82   :     slotUnregister(rm->slot, rm->sslot, rm->startPage);

	mov	esi, DWORD PTR _rm$[esp]
	push	DWORD PTR [esi+16]
	push	DWORD PTR [esi+12]
	push	DWORD PTR [esi+8]
	call	_slotUnregister

; 83   :     deviceManagerUnregister(rm->deviceHandle);

	push	DWORD PTR [esi]
	call	_deviceManagerUnregister

; 84   : 
; 85   :     free(rm->romData);

	push	DWORD PTR [esi+4]
	call	_free

; 86   :     free(rm);

	push	esi
	call	_free
	add	esp, 24					; 00000018H
	pop	esi

; 87   : }

	ret	0
_destroy ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommapperkonami4.c
;	COMDAT _loadState
_TEXT	SEGMENT
_rm$GSCopy$1$ = -24					; size = 4
_tag$ = -20						; size = 16
__$ArrayPad$ = -4					; size = 4
_rm$ = 8						; size = 4
_loadState PROC						; COMDAT

; 63   : {

	sub	esp, 28					; 0000001cH
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, esp
	mov	DWORD PTR __$ArrayPad$[esp+28], eax
	push	ebx
	mov	ebx, DWORD PTR _rm$[esp+28]
	push	ebp
	push	esi
	push	edi

; 64   :     SaveState* state = saveStateOpenForRead("mapperKonami4");

	push	OFFSET ??_C@_0O@FPDAHDBH@mapperKonami4@
	mov	DWORD PTR _rm$GSCopy$1$[esp+48], ebx
	call	_saveStateOpenForRead
	lea	ebp, DWORD PTR [ebx+24]
	add	esp, 4
	xor	esi, esi
	mov	edi, ebp
	mov	ebx, eax
$LL4@loadState:

; 65   :     char tag[16];
; 66   :     int i;
; 67   : 
; 68   :     for (i = 0; i < 4; i++) {
; 69   :         sprintf(tag, "romMapper%d", i);

	push	esi
	lea	eax, DWORD PTR _tag$[esp+48]
	push	OFFSET ??_C@_0M@NAELOINI@romMapper?$CFd@
	push	eax
	call	_sprintf

; 70   :         rm->romMapper[i] = saveStateGet(state, tag, 0);

	push	0
	lea	eax, DWORD PTR _tag$[esp+60]
	push	eax
	push	ebx
	call	_saveStateGet
	inc	esi
	mov	DWORD PTR [edi], eax
	add	esp, 24					; 00000018H
	lea	edi, DWORD PTR [edi+4]
	cmp	esi, 4
	jl	SHORT $LL4@loadState

; 71   :     }
; 72   : 
; 73   :     saveStateClose(state);

	push	ebx
	call	_saveStateClose
	mov	ebx, DWORD PTR _rm$GSCopy$1$[esp+48]
	add	esp, 4
	xor	esi, esi
	npad	6
$LL7@loadState:

; 74   : 
; 75   :     for (i = 0; i < 4; i++) {   
; 76   :         slotMapPage(rm->slot, rm->sslot, rm->startPage + i, rm->romData + rm->romMapper[i] * 0x2000, 1, 0);

	mov	eax, DWORD PTR [ebp]
	push	0
	shl	eax, 13					; 0000000dH
	add	eax, DWORD PTR [ebx+4]
	push	1
	push	eax
	mov	eax, DWORD PTR [ebx+16]
	add	eax, esi
	push	eax
	push	DWORD PTR [ebx+12]
	push	DWORD PTR [ebx+8]
	call	_slotMapPage
	inc	esi
	lea	ebp, DWORD PTR [ebp+4]
	add	esp, 24					; 00000018H
	cmp	esi, 4
	jl	SHORT $LL7@loadState

; 77   :     }
; 78   : }

	mov	ecx, DWORD PTR __$ArrayPad$[esp+44]
	pop	edi
	pop	esi
	pop	ebp
	pop	ebx
	xor	ecx, esp
	call	@__security_check_cookie@4
	add	esp, 28					; 0000001cH
	ret	0
_loadState ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommapperkonami4.c
;	COMDAT _saveState
_TEXT	SEGMENT
_tag$ = -20						; size = 16
__$ArrayPad$ = -4					; size = 4
_rm$ = 8						; size = 4
_saveState PROC						; COMDAT

; 49   : {

	sub	esp, 20					; 00000014H
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, esp
	mov	DWORD PTR __$ArrayPad$[esp+20], eax
	push	ebx
	push	esi
	mov	esi, DWORD PTR _rm$[esp+24]
	push	edi

; 50   :     SaveState* state = saveStateOpenForWrite("mapperKonami4");

	push	OFFSET ??_C@_0O@FPDAHDBH@mapperKonami4@
	call	_saveStateOpenForWrite
	add	esp, 4
	xor	edi, edi
	mov	ebx, eax
	add	esi, 24					; 00000018H
	npad	7
$LL4@saveState:

; 51   :     char tag[16];
; 52   :     int i;
; 53   : 
; 54   :     for (i = 0; i < 4; i++) {
; 55   :         sprintf(tag, "romMapper%d", i);

	push	edi
	lea	eax, DWORD PTR _tag$[esp+36]
	push	OFFSET ??_C@_0M@NAELOINI@romMapper?$CFd@
	push	eax
	call	_sprintf

; 56   :         saveStateSet(state, tag, rm->romMapper[i]);

	push	DWORD PTR [esi]
	lea	eax, DWORD PTR _tag$[esp+48]
	push	eax
	push	ebx
	call	_saveStateSet
	inc	edi
	lea	esi, DWORD PTR [esi+4]
	add	esp, 24					; 00000018H
	cmp	edi, 4
	jl	SHORT $LL4@saveState

; 57   :     }
; 58   : 
; 59   :     saveStateClose(state);

	push	ebx
	call	_saveStateClose

; 60   : }

	mov	ecx, DWORD PTR __$ArrayPad$[esp+36]
	add	esp, 4
	pop	edi
	pop	esi
	pop	ebx
	xor	ecx, esp
	call	@__security_check_cookie@4
	add	esp, 20					; 00000014H
	ret	0
_saveState ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File c:\program files (x86)\windows kits\10\include\10.0.19041.0\ucrt\stdio.h
;	COMDAT _sprintf
_TEXT	SEGMENT
__Buffer$ = 8						; size = 4
__Format$ = 12						; size = 4
_sprintf PROC						; COMDAT

; 1392 :         int const _Result = __stdio_common_vsprintf(

	lea	eax, DWORD PTR __Format$[esp]
	push	eax
	push	0
	push	DWORD PTR __Format$[esp+4]
	push	-1
	push	DWORD PTR __Buffer$[esp+12]
	call	___local_stdio_printf_options
	mov	ecx, DWORD PTR [eax]
	push	DWORD PTR [eax+4]
	or	ecx, 1
	push	ecx
	call	___stdio_common_vsprintf

; 1393 :             _CRT_INTERNAL_LOCAL_PRINTF_OPTIONS | _CRT_INTERNAL_PRINTF_LEGACY_VSPRINTF_NULL_TERMINATION,
; 1394 :             _Buffer, _BufferCount, _Format, _Locale, _ArgList);
; 1395 : 
; 1396 :         return _Result < 0 ? -1 : _Result;

	or	ecx, -1
	add	esp, 28					; 0000001cH
	test	eax, eax
	cmovs	eax, ecx

; 1772 :         int _Result;
; 1773 :         va_list _ArgList;
; 1774 :         __crt_va_start(_ArgList, _Format);
; 1775 : 
; 1776 :         _Result = _vsprintf_l(_Buffer, _Format, NULL, _ArgList);
; 1777 : 
; 1778 :         __crt_va_end(_ArgList);
; 1779 :         return _Result;
; 1780 :     }

	ret	0
_sprintf ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File c:\program files (x86)\windows kits\10\include\10.0.19041.0\ucrt\stdio.h
;	COMDAT __vsprintf_l
_TEXT	SEGMENT
__Buffer$ = 8						; size = 4
__Format$ = 12						; size = 4
__Locale$ = 16						; size = 4
__ArgList$ = 20						; size = 4
__vsprintf_l PROC					; COMDAT

; 1392 :         int const _Result = __stdio_common_vsprintf(

	push	DWORD PTR __ArgList$[esp-4]
	push	DWORD PTR __Locale$[esp]
	push	DWORD PTR __Format$[esp+4]
	push	-1
	push	DWORD PTR __Buffer$[esp+12]
	call	___local_stdio_printf_options
	mov	ecx, DWORD PTR [eax]
	push	DWORD PTR [eax+4]
	or	ecx, 1
	push	ecx
	call	___stdio_common_vsprintf

; 1393 :             _CRT_INTERNAL_LOCAL_PRINTF_OPTIONS | _CRT_INTERNAL_PRINTF_LEGACY_VSPRINTF_NULL_TERMINATION,
; 1394 :             _Buffer, _BufferCount, _Format, _Locale, _ArgList);
; 1395 : 
; 1396 :         return _Result < 0 ? -1 : _Result;

	or	ecx, -1
	add	esp, 28					; 0000001cH
	test	eax, eax
	cmovs	eax, ecx

; 1459 :         return _vsnprintf_l(_Buffer, (size_t)-1, _Format, _Locale, _ArgList);
; 1460 :     }

	ret	0
__vsprintf_l ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File c:\program files (x86)\windows kits\10\include\10.0.19041.0\ucrt\stdio.h
;	COMDAT __vsnprintf_l
_TEXT	SEGMENT
__Buffer$ = 8						; size = 4
__BufferCount$ = 12					; size = 4
__Format$ = 16						; size = 4
__Locale$ = 20						; size = 4
__ArgList$ = 24						; size = 4
__vsnprintf_l PROC					; COMDAT

; 1392 :         int const _Result = __stdio_common_vsprintf(

	push	DWORD PTR __ArgList$[esp-4]
	push	DWORD PTR __Locale$[esp]
	push	DWORD PTR __Format$[esp+4]
	push	DWORD PTR __BufferCount$[esp+8]
	push	DWORD PTR __Buffer$[esp+12]
	call	___local_stdio_printf_options
	mov	ecx, DWORD PTR [eax]
	push	DWORD PTR [eax+4]
	or	ecx, 1
	push	ecx
	call	___stdio_common_vsprintf

; 1393 :             _CRT_INTERNAL_LOCAL_PRINTF_OPTIONS | _CRT_INTERNAL_PRINTF_LEGACY_VSPRINTF_NULL_TERMINATION,
; 1394 :             _Buffer, _BufferCount, _Format, _Locale, _ArgList);
; 1395 : 
; 1396 :         return _Result < 0 ? -1 : _Result;

	or	ecx, -1
	add	esp, 28					; 0000001cH
	test	eax, eax
	cmovs	eax, ecx

; 1397 :     }

	ret	0
__vsnprintf_l ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File c:\program files (x86)\windows kits\10\include\10.0.19041.0\ucrt\corecrt_stdio_config.h
;	COMDAT ___local_stdio_printf_options
_TEXT	SEGMENT
___local_stdio_printf_options PROC			; COMDAT

; 91   :         static unsigned __int64 _OptionsStorage;
; 92   :         return &_OptionsStorage;

	mov	eax, OFFSET ?_OptionsStorage@?1??__local_stdio_printf_options@@9@9 ; `__local_stdio_printf_options'::`2'::_OptionsStorage

; 93   :     }

	ret	0
___local_stdio_printf_options ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommapperkonami4.c
;	COMDAT _romMapperKonami4Create
_TEXT	SEGMENT
_callbacks$ = -16					; size = 16
_filename$ = 8						; size = 4
_romData$ = 12						; size = 4
_size$ = 16						; size = 4
_slot$ = 20						; size = 4
_sslot$ = 24						; size = 4
_startPage$ = 28					; size = 4
_romMapperKonami4Create PROC				; COMDAT

; 114  : {

	sub	esp, 16					; 00000010H
	push	edi

; 115  :     DeviceCallbacks callbacks = { destroy, NULL, saveState, loadState };
; 116  :     RomMapperKonami4* rm;
; 117  :     int romSize;
; 118  :     int i;
; 119  : 
; 120  :     if (size < 0x8000) {

	mov	edi, DWORD PTR _size$[esp+16]
	mov	DWORD PTR _callbacks$[esp+20], OFFSET _destroy
	mov	DWORD PTR _callbacks$[esp+24], 0
	mov	DWORD PTR _callbacks$[esp+28], OFFSET _saveState
	mov	DWORD PTR _callbacks$[esp+32], OFFSET _loadState
	cmp	edi, 32768				; 00008000H
	jge	SHORT $LN5@romMapperK

; 121  :         return 0;

	xor	eax, eax
	pop	edi

; 152  : }

	add	esp, 16					; 00000010H
	ret	0
$LN5@romMapperK:
	push	ebx
	push	ebp
	push	esi

; 122  :     }
; 123  : 
; 124  :     rm = malloc(sizeof(RomMapperKonami4));

	push	40					; 00000028H
	call	_malloc
	mov	esi, eax

; 125  : 
; 126  :     rm->deviceHandle = deviceManagerRegister(ROM_KONAMI4, &callbacks, rm);

	lea	eax, DWORD PTR _callbacks$[esp+36]
	push	esi
	push	eax
	push	4
	call	_deviceManagerRegister

; 127  :     slotRegister(slot, sslot, startPage, 4, NULL, NULL, write, destroy, rm);

	push	esi
	push	OFFSET _destroy
	push	OFFSET _write
	push	0
	push	0
	push	4
	push	DWORD PTR _startPage$[esp+68]
	mov	DWORD PTR [esi], eax
	push	DWORD PTR _sslot$[esp+72]
	push	DWORD PTR _slot$[esp+76]
	call	_slotRegister

; 128  : 
; 129  :     romSize = size > 0x40000 ? size : 0x40000;

	mov	ebx, 262144				; 00040000H
	cmp	edi, ebx
	mov	ebp, ebx
	cmovg	ebp, edi

; 130  :     rm->romData = malloc(romSize);

	push	ebp
	call	_malloc

; 131  :     memcpy(rm->romData, romData, size);

	push	edi
	push	DWORD PTR _romData$[esp+88]
	mov	DWORD PTR [esi+4], eax
	push	eax
	call	_memcpy
	add	esp, 68					; 00000044H

; 132  : 
; 133  :     if (size < 0x40000) {

	cmp	edi, ebx
	jge	SHORT $LN6@romMapperK

; 134  :         memset(rm->romData + size, 0xff, 0x40000 - size);

	mov	eax, DWORD PTR [esi+4]
	sub	ebx, edi
	push	ebx
	add	eax, edi
	push	255					; 000000ffH
	push	eax
	call	_memset
	add	esp, 12					; 0000000cH
$LN6@romMapperK:

; 135  :     }
; 136  : 
; 137  :     rm->size = romSize;
; 138  :     rm->slot  = slot;

	mov	eax, DWORD PTR _slot$[esp+28]

; 139  :     rm->sslot = sslot;
; 140  :     rm->startPage  = startPage;
; 141  : 
; 142  :     rm->romMapper[0] = 0;

	lea	ebx, DWORD PTR [esi+24]
	mov	DWORD PTR [esi+8], eax

; 143  :     rm->romMapper[1] = 1;
; 144  :     rm->romMapper[2] = 2;
; 145  :     rm->romMapper[3] = 3;
; 146  : 
; 147  :     for (i = 0; i < 4; i++) {   

	xor	edi, edi
	mov	eax, DWORD PTR _sslot$[esp+28]
	mov	DWORD PTR [esi+12], eax
	mov	eax, DWORD PTR _startPage$[esp+28]
	mov	DWORD PTR [esi+20], ebp
	mov	DWORD PTR [esi+16], eax
	mov	DWORD PTR [ebx], 0
	mov	DWORD PTR [esi+28], 1
	mov	DWORD PTR [esi+32], 2
	mov	DWORD PTR [esi+36], 3
	npad	7
$LL4@romMapperK:

; 148  :         slotMapPage(rm->slot, rm->sslot, rm->startPage + i, rm->romData + rm->romMapper[i] * 0x2000, 1, 0);

	mov	eax, DWORD PTR [ebx]
	push	0
	shl	eax, 13					; 0000000dH
	add	eax, DWORD PTR [esi+4]
	push	1
	push	eax
	mov	eax, DWORD PTR [esi+16]
	add	eax, edi
	push	eax
	push	DWORD PTR [esi+12]
	push	DWORD PTR [esi+8]
	call	_slotMapPage
	inc	edi
	lea	ebx, DWORD PTR [ebx+4]
	add	esp, 24					; 00000018H
	cmp	edi, 4
	jl	SHORT $LL4@romMapperK

; 149  :     }
; 150  : 
; 151  :     return 1;

	pop	esi
	pop	ebp
	pop	ebx
	mov	eax, 1
	pop	edi

; 152  : }

	add	esp, 16					; 00000010H
	ret	0
_romMapperKonami4Create ENDP
_TEXT	ENDS
END
