; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27054.0 

	TITLE	D:\repo\MSX-master\MSX\blueMSX-DPI\Src\Memory\romMapperSunriseIDE.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_romMapperSunriseIdeCreate
PUBLIC	??_C@_0BB@PBGKFGI@mapperSunriseIde@		; `string'
PUBLIC	??_C@_0L@NFMKGKHP@ideEnabled@			; `string'
PUBLIC	??_C@_09EEKFPJOD@readLatch@			; `string'
PUBLIC	??_C@_0L@GPKJKAOG@writeLatch@			; `string'
PUBLIC	??_C@_09BHBKDJJ@romMapper@			; `string'
EXTRN	_slotRegister:PROC
EXTRN	_slotUnregister:PROC
EXTRN	_slotMapPage:PROC
EXTRN	_deviceManagerRegister:PROC
EXTRN	_deviceManagerUnregister:PROC
EXTRN	_sunriseIdeCreate:PROC
EXTRN	_sunriseIdeDestroy:PROC
EXTRN	_sunriseIdeReset:PROC
EXTRN	_sunriseIdeRead:PROC
EXTRN	_sunriseIdePeek:PROC
EXTRN	_sunriseIdeWrite:PROC
EXTRN	_sunriseIdeReadRegister:PROC
EXTRN	_sunriseIdePeekRegister:PROC
EXTRN	_sunriseIdeWriteRegister:PROC
EXTRN	_sunriseIdeSaveState:PROC
EXTRN	_sunriseIdeLoadState:PROC
EXTRN	_saveStateOpenForRead:PROC
EXTRN	_saveStateOpenForWrite:PROC
EXTRN	_saveStateClose:PROC
EXTRN	_saveStateGet:PROC
EXTRN	_saveStateSet:PROC
EXTRN	_calloc:PROC
EXTRN	_free:PROC
EXTRN	_malloc:PROC
EXTRN	_memcpy:PROC
EXTRN	_memset:PROC
;	COMDAT ??_C@_09BHBKDJJ@romMapper@
CONST	SEGMENT
??_C@_09BHBKDJJ@romMapper@ DB 'romMapper', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_0L@GPKJKAOG@writeLatch@
CONST	SEGMENT
??_C@_0L@GPKJKAOG@writeLatch@ DB 'writeLatch', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_09EEKFPJOD@readLatch@
CONST	SEGMENT
??_C@_09EEKFPJOD@readLatch@ DB 'readLatch', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_0L@NFMKGKHP@ideEnabled@
CONST	SEGMENT
??_C@_0L@NFMKGKHP@ideEnabled@ DB 'ideEnabled', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0BB@PBGKFGI@mapperSunriseIde@
CONST	SEGMENT
??_C@_0BB@PBGKFGI@mapperSunriseIde@ DB 'mapperSunriseIde', 00H ; `string'
CONST	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommappersunriseide.c
;	COMDAT _reset
_TEXT	SEGMENT
_rm$ = 8						; size = 4
_reset	PROC						; COMDAT

; 166  : #if 0
; 167  :     rm->ideEnabled = 1;
; 168  :     rm->romMapper = rm->romMask * 0x4000;
; 169  :     rm->readLatch = 0;
; 170  :     rm->writeLatch = 0;
; 171  : #endif
; 172  :     sunriseIdeReset(rm->ide);

	mov	eax, DWORD PTR _rm$[esp-4]
	push	DWORD PTR [eax+24]
	call	_sunriseIdeReset
	pop	ecx

; 173  : }

	ret	0
_reset	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommappersunriseide.c
;	COMDAT _write
_TEXT	SEGMENT
_rm$ = 8						; size = 4
_address$ = 12						; size = 2
_value$ = 16						; size = 1
_write	PROC						; COMDAT

; 139  : 	if ((address & 0xbf04) == 0x0104) {

	mov	ecx, DWORD PTR _address$[esp-4]
	mov	eax, ecx
	and	eax, 48900				; 0000bf04H
	push	esi
	mov	esi, DWORD PTR _rm$[esp]
	cmp	eax, 260				; 00000104H
	jne	SHORT $LN2@write

; 140  :         rm->ideEnabled = value & 1;

	mov	cl, BYTE PTR _value$[esp]
	movzx	eax, cl

; 141  :             
; 142  : 	    value = ((value & 0xf0) >> 4) | ((value & 0x0f) << 4);

	rol	cl, 4
	and	eax, 1

; 143  : 	    value = ((value & 0xcc) >> 2) | ((value & 0x33) << 2);

	mov	dl, cl
	mov	DWORD PTR [esi+28], eax
	mov	al, cl
	shr	dl, 2
	shl	al, 2
	xor	dl, al
	shl	cl, 2
	and	dl, 51					; 00000033H
	xor	dl, cl

; 144  : 	    value = ((value & 0xaa) >> 1) | ((value & 0x55) << 1);

	mov	al, dl
	movzx	ecx, dl
	shr	ecx, 1
	add	al, al
	xor	ecx, eax
	add	dl, dl
	and	ecx, 85					; 00000055H
	movzx	eax, dl
	xor	ecx, eax

; 145  :         rm->romMapper = 0x4000 * (value & rm->romMask);

	and	ecx, DWORD PTR [esi+20]
	shl	ecx, 14					; 0000000eH
	mov	DWORD PTR [esi+36], ecx
	pop	esi

; 160  : 		return;
; 161  : 	}
; 162  : }

	ret	0
$LN2@write:

; 146  : 		return;
; 147  : 	}
; 148  : 
; 149  : 	if (rm->ideEnabled && (address & 0x3e00) == 0x3c00) {

	cmp	DWORD PTR [esi+28], 0
	je	SHORT $LN6@write
	mov	eax, ecx
	and	eax, 15872				; 00003e00H
	cmp	eax, 15360				; 00003c00H
	jne	SHORT $LN3@write

; 150  : 		if ((address & 1) == 0) {

	test	cl, 1
	jne	SHORT $LN4@write

; 151  :             rm->writeLatch = value;

	mov	al, BYTE PTR _value$[esp]
	mov	BYTE PTR [esi+33], al
	pop	esi

; 160  : 		return;
; 161  : 	}
; 162  : }

	ret	0
$LN4@write:

; 152  : 		} 
; 153  :         else {
; 154  :             sunriseIdeWrite(rm->ide, (value << 8) | rm->writeLatch);

	movzx	ecx, BYTE PTR _value$[esp]
	movzx	eax, BYTE PTR [esi+33]
	shl	cx, 8
	or	cx, ax
	movzx	eax, cx
	push	eax
	push	DWORD PTR [esi+24]
	call	_sunriseIdeWrite
	add	esp, 8
	pop	esi

; 160  : 		return;
; 161  : 	}
; 162  : }

	ret	0
$LN3@write:

; 155  : 		}
; 156  : 		return;
; 157  : 	}
; 158  : 	if (rm->ideEnabled && ((address & 0x3f00) == 0x3e00)) {

	mov	eax, ecx
	and	eax, 16128				; 00003f00H
	cmp	eax, 15872				; 00003e00H
	jne	SHORT $LN6@write

; 159  : 		sunriseIdeWriteRegister(rm->ide, address & 0x0f, value);

	push	DWORD PTR _value$[esp]
	and	cl, 15					; 0000000fH
	movzx	eax, cl
	push	eax
	push	DWORD PTR [esi+24]
	call	_sunriseIdeWriteRegister
	add	esp, 12					; 0000000cH
$LN6@write:

; 160  : 		return;
; 161  : 	}
; 162  : }

	pop	esi
	ret	0
_write	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommappersunriseide.c
;	COMDAT _peek
_TEXT	SEGMENT
_rm$ = 8						; size = 4
_address$ = 12						; size = 2
_peek	PROC						; COMDAT

; 118  : 	if (rm->ideEnabled && (address & 0x3e00) == 0x3c00) {

	mov	edx, DWORD PTR _address$[esp-4]
	push	esi
	mov	esi, DWORD PTR _rm$[esp]
	cmp	DWORD PTR [esi+28], 0
	je	SHORT $LN4@peek
	mov	eax, edx
	and	eax, 15872				; 00003e00H
	cmp	eax, 15360				; 00003c00H
	jne	SHORT $LN2@peek

; 119  : 		if ((address & 1) == 0) {

	test	dl, 1
	jne	SHORT $LN3@peek

; 120  : 	        UInt16 value = sunriseIdePeek(rm->ide);

	push	DWORD PTR [esi+24]
	call	_sunriseIdePeek
	add	esp, 4
	pop	esi

; 135  : }

	ret	0
$LN3@peek:

; 121  : 	        return value & 0xff;
; 122  :         }
; 123  : 		return rm->readLatch;

	mov	al, BYTE PTR [esi+32]
	pop	esi

; 135  : }

	ret	0
$LN2@peek:

; 124  : 	}
; 125  : 
; 126  : 	if (rm->ideEnabled && (address & 0x3f00) == 0x3e00) {

	mov	eax, edx
	and	eax, 16128				; 00003f00H
	cmp	eax, 15872				; 00003e00H
	jne	SHORT $LN4@peek

; 127  :         return sunriseIdePeekRegister(rm->ide, address & 0x0f);

	and	dl, 15					; 0000000fH
	movzx	eax, dl
	push	eax
	push	DWORD PTR [esi+24]
	call	_sunriseIdePeekRegister
	add	esp, 8
	pop	esi

; 135  : }

	ret	0
$LN4@peek:

; 128  : 	}
; 129  :     address -= 0x4000;

	add	edx, 49152				; 0000c000H

; 130  : 	if (address < 0x4000) {

	mov	eax, 16384				; 00004000H
	cmp	dx, ax
	jae	SHORT $LN5@peek

; 131  : 		return rm->romData[address + rm->romMapper];

	mov	ecx, DWORD PTR [esi+36]
	add	ecx, DWORD PTR [esi+4]
	movzx	eax, dx
	pop	esi
	mov	al, BYTE PTR [ecx+eax]

; 135  : }

	ret	0
$LN5@peek:

; 132  : 	}
; 133  : 
; 134  :     return 0xff;

	or	al, 255					; 000000ffH
	pop	esi

; 135  : }

	ret	0
_peek	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommappersunriseide.c
;	COMDAT _read
_TEXT	SEGMENT
_rm$ = 8						; size = 4
_address$ = 12						; size = 2
_read	PROC						; COMDAT

; 96   : 	if (rm->ideEnabled && (address & 0x3e00) == 0x3c00) {

	mov	edx, DWORD PTR _address$[esp-4]
	push	esi
	mov	esi, DWORD PTR _rm$[esp]
	cmp	DWORD PTR [esi+28], 0
	je	SHORT $LN4@read
	mov	eax, edx
	and	eax, 15872				; 00003e00H
	cmp	eax, 15360				; 00003c00H
	jne	SHORT $LN2@read

; 97   : 		if ((address & 1) == 0) {

	test	dl, 1
	jne	SHORT $LN3@read

; 98   : 	        UInt16 value = sunriseIdeRead(rm->ide);

	push	DWORD PTR [esi+24]
	call	_sunriseIdeRead
	movzx	eax, ax
	add	esp, 4

; 99   : 	        rm->readLatch = value >> 8;

	mov	ecx, eax
	shr	ecx, 8
	mov	BYTE PTR [esi+32], cl
	pop	esi

; 114  : }

	ret	0
$LN3@read:

; 100  : 	        return value & 0xff;
; 101  :         }
; 102  : 		return rm->readLatch;

	mov	al, BYTE PTR [esi+32]
	pop	esi

; 114  : }

	ret	0
$LN2@read:

; 103  : 	}
; 104  : 
; 105  : 	if (rm->ideEnabled && (address & 0x3f00) == 0x3e00) {

	mov	eax, edx
	and	eax, 16128				; 00003f00H
	cmp	eax, 15872				; 00003e00H
	jne	SHORT $LN4@read

; 106  :         return sunriseIdeReadRegister(rm->ide, address & 0x0f);

	and	dl, 15					; 0000000fH
	movzx	eax, dl
	push	eax
	push	DWORD PTR [esi+24]
	call	_sunriseIdeReadRegister
	add	esp, 8
	pop	esi

; 114  : }

	ret	0
$LN4@read:

; 107  : 	}
; 108  :     address -= 0x4000;

	add	edx, 49152				; 0000c000H

; 109  : 	if (address < 0x4000) {

	mov	eax, 16384				; 00004000H
	cmp	dx, ax
	jae	SHORT $LN5@read

; 110  : 		return rm->romData[address + rm->romMapper];

	mov	ecx, DWORD PTR [esi+36]
	add	ecx, DWORD PTR [esi+4]
	movzx	eax, dx
	pop	esi
	mov	al, BYTE PTR [ecx+eax]

; 114  : }

	ret	0
$LN5@read:

; 111  : 	}
; 112  : 
; 113  :     return 0xff;

	or	al, 255					; 000000ffH
	pop	esi

; 114  : }

	ret	0
_read	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommappersunriseide.c
;	COMDAT _destroy
_TEXT	SEGMENT
_rm$ = 8						; size = 4
_destroy PROC						; COMDAT

; 84   : {

	push	esi

; 85   :     slotUnregister(rm->slot, rm->sslot, rm->startPage);

	mov	esi, DWORD PTR _rm$[esp]
	push	DWORD PTR [esi+16]
	push	DWORD PTR [esi+12]
	push	DWORD PTR [esi+8]
	call	_slotUnregister

; 86   :     deviceManagerUnregister(rm->deviceHandle);

	push	DWORD PTR [esi]
	call	_deviceManagerUnregister

; 87   : 
; 88   :     sunriseIdeDestroy(rm->ide);

	push	DWORD PTR [esi+24]
	call	_sunriseIdeDestroy

; 89   : 
; 90   :     free(rm->romData);

	push	DWORD PTR [esi+4]
	call	_free

; 91   :     free(rm);

	push	esi
	call	_free
	add	esp, 28					; 0000001cH
	pop	esi

; 92   : }

	ret	0
_destroy ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommappersunriseide.c
;	COMDAT _loadState
_TEXT	SEGMENT
_rm$ = 8						; size = 4
_loadState PROC						; COMDAT

; 70   : {

	push	esi
	push	edi

; 71   :     SaveState* state = saveStateOpenForRead("mapperSunriseIde");

	push	OFFSET ??_C@_0BB@PBGKFGI@mapperSunriseIde@
	call	_saveStateOpenForRead

; 72   : 
; 73   :     rm->ideEnabled = saveStateGet(state, "ideEnabled", 0);

	push	0
	mov	edi, eax
	push	OFFSET ??_C@_0L@NFMKGKHP@ideEnabled@
	push	edi
	call	_saveStateGet
	mov	esi, DWORD PTR _rm$[esp+20]

; 74   :     rm->readLatch = (UInt8)saveStateGet(state, "readLatch", 0);

	push	0
	push	OFFSET ??_C@_09EEKFPJOD@readLatch@
	push	edi
	mov	DWORD PTR [esi+28], eax
	call	_saveStateGet

; 75   :     rm->writeLatch = (UInt8)saveStateGet(state, "writeLatch", 0);

	push	0
	push	OFFSET ??_C@_0L@GPKJKAOG@writeLatch@
	push	edi
	mov	BYTE PTR [esi+32], al
	call	_saveStateGet

; 76   :     rm->romMapper = saveStateGet(state, "romMapper", 0);

	push	0
	push	OFFSET ??_C@_09BHBKDJJ@romMapper@
	push	edi
	mov	BYTE PTR [esi+33], al
	call	_saveStateGet

; 77   : 
; 78   :     saveStateClose(state);

	push	edi
	mov	DWORD PTR [esi+36], eax
	call	_saveStateClose

; 79   :     
; 80   :     sunriseIdeLoadState(rm->ide);

	push	DWORD PTR [esi+24]
	call	_sunriseIdeLoadState
	add	esp, 60					; 0000003cH
	pop	edi
	pop	esi

; 81   : }

	ret	0
_loadState ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommappersunriseide.c
;	COMDAT _saveState
_TEXT	SEGMENT
_rm$ = 8						; size = 4
_saveState PROC						; COMDAT

; 56   : {

	push	esi
	push	edi

; 57   :     SaveState* state = saveStateOpenForWrite("mapperSunriseIde");

	push	OFFSET ??_C@_0BB@PBGKFGI@mapperSunriseIde@
	call	_saveStateOpenForWrite

; 58   : 
; 59   :     saveStateSet(state, "ideEnabled", rm->ideEnabled);

	mov	edi, DWORD PTR _rm$[esp+8]
	mov	esi, eax
	push	DWORD PTR [edi+28]
	push	OFFSET ??_C@_0L@NFMKGKHP@ideEnabled@
	push	esi
	call	_saveStateSet

; 60   :     saveStateSet(state, "readLatch", rm->readLatch);

	movzx	ecx, BYTE PTR [edi+32]
	push	ecx
	push	OFFSET ??_C@_09EEKFPJOD@readLatch@
	push	esi
	call	_saveStateSet

; 61   :     saveStateSet(state, "writeLatch", rm->writeLatch);

	movzx	eax, BYTE PTR [edi+33]
	push	eax
	push	OFFSET ??_C@_0L@GPKJKAOG@writeLatch@
	push	esi
	call	_saveStateSet

; 62   :     saveStateSet(state, "romMapper", rm->romMapper);

	push	DWORD PTR [edi+36]
	push	OFFSET ??_C@_09BHBKDJJ@romMapper@
	push	esi
	call	_saveStateSet

; 63   : 
; 64   :     saveStateClose(state);

	push	esi
	call	_saveStateClose

; 65   : 
; 66   :     sunriseIdeSaveState(rm->ide);

	push	DWORD PTR [edi+24]
	call	_sunriseIdeSaveState
	add	esp, 60					; 0000003cH
	pop	edi
	pop	esi

; 67   : }

	ret	0
_saveState ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommappersunriseide.c
;	COMDAT _romMapperSunriseIdeCreate
_TEXT	SEGMENT
_callbacks$ = -16					; size = 16
_hdId$ = 8						; size = 4
_filename$ = 12						; size = 4
_romData$ = 16						; size = 4
_size$ = 20						; size = 4
_slot$ = 24						; size = 4
_sslot$ = 28						; size = 4
_startPage$ = 32					; size = 4
_romMapperSunriseIdeCreate PROC				; COMDAT

; 178  : {

	sub	esp, 16					; 00000010H

; 179  :     DeviceCallbacks callbacks = { destroy, NULL, saveState, loadState };
; 180  :     RomMapperSunriseIde* rm;
; 181  :     int i;
; 182  :     int origSize = size;
; 183  : 
; 184  :     if (startPage != 0) {

	cmp	DWORD PTR _startPage$[esp+12], 0
	push	ebx
	mov	ebx, DWORD PTR _size$[esp+16]
	mov	DWORD PTR _callbacks$[esp+20], OFFSET _destroy
	mov	DWORD PTR _callbacks$[esp+24], 0
	mov	DWORD PTR _callbacks$[esp+28], OFFSET _saveState
	mov	DWORD PTR _callbacks$[esp+32], OFFSET _loadState
	je	SHORT $LN7@romMapperS

; 185  :         return 0;

	xor	eax, eax
	pop	ebx

; 229  : }

	add	esp, 16					; 00000010H
	ret	0
$LN7@romMapperS:
	push	esi

; 186  :     }
; 187  : 
; 188  :     
; 189  :     size = 0x4000;

	mov	esi, 16384				; 00004000H
	push	edi

; 190  :     while (size < origSize) {

	cmp	ebx, esi
	jle	SHORT $LN3@romMapperS
$LL2@romMapperS:

; 191  :         size *= 2;

	add	esi, esi
	cmp	esi, ebx
	jl	SHORT $LL2@romMapperS
$LN3@romMapperS:
	push	ebp

; 192  :     }
; 193  : 
; 194  :     if (romData == NULL) {

	mov	ebp, DWORD PTR _romData$[esp+28]
	mov	eax, 524288				; 00080000H
	test	ebp, ebp

; 195  :         size = 0x80000;
; 196  :     }
; 197  : 
; 198  :     rm = malloc(sizeof(RomMapperSunriseIde));

	push	40					; 00000028H
	cmove	esi, eax
	call	_malloc
	mov	edi, eax

; 199  : 
; 200  :     rm->deviceHandle = deviceManagerRegister(ROM_SUNRISEIDE, &callbacks, rm);

	lea	eax, DWORD PTR _callbacks$[esp+36]
	push	edi
	push	eax
	push	96					; 00000060H
	call	_deviceManagerRegister

; 201  :     slotRegister(slot, sslot, startPage, 8, read, peek, write, destroy, rm);

	push	edi
	push	OFFSET _destroy
	push	OFFSET _write
	push	OFFSET _peek
	push	OFFSET _read
	push	8
	push	0
	push	DWORD PTR _sslot$[esp+72]
	mov	DWORD PTR [edi], eax
	push	DWORD PTR _slot$[esp+76]
	call	_slotRegister

; 202  : 
; 203  :     rm->ide = sunriseIdeCreate(hdId);

	push	DWORD PTR _hdId$[esp+80]
	call	_sunriseIdeCreate

; 204  : 
; 205  :     rm->romData = calloc(1, size);

	push	esi
	push	1
	mov	DWORD PTR [edi+24], eax
	call	_calloc
	add	esp, 64					; 00000040H
	mov	DWORD PTR [edi+4], eax

; 206  :     if (romData != NULL) {

	test	ebp, ebp
	je	SHORT $LN9@romMapperS

; 207  :         memcpy(rm->romData, romData, origSize);

	push	ebx
	push	ebp
	push	eax
	call	_memcpy

; 208  :     }

	jmp	SHORT $LN22@romMapperS
$LN9@romMapperS:

; 209  :     else {
; 210  :         memset(rm->romData, 0xff, size);

	push	esi
	push	255					; 000000ffH
	push	eax
	call	_memset
$LN22@romMapperS:

; 211  :     }
; 212  :     rm->romMask = size / 0x4000 - 1;

	mov	eax, esi

; 213  :     rm->slot  = slot;
; 214  :     rm->sslot = sslot;
; 215  :     rm->startPage  = startPage;

	mov	DWORD PTR [edi+16], 0
	cdq
	add	esp, 12					; 0000000cH
	and	edx, 16383				; 00003fffH

; 216  : 
; 217  :     rm->romMapper = 0;

	mov	DWORD PTR [edi+36], 0
	add	eax, edx
	sar	eax, 14					; 0000000eH
	dec	eax
	xor	esi, esi
	mov	DWORD PTR [edi+20], eax
	mov	eax, DWORD PTR _slot$[esp+28]
	mov	DWORD PTR [edi+8], eax
	mov	eax, DWORD PTR _sslot$[esp+28]
	mov	DWORD PTR [edi+12], eax
	pop	ebp
	npad	4
$LL6@romMapperS:

; 218  : 
; 219  :     for (i = 0; i < 8; i++) {   
; 220  :         slotMapPage(rm->slot, rm->sslot, rm->startPage + i, NULL, 0, 0);

	mov	eax, DWORD PTR [edi+16]
	push	0
	push	0
	push	0
	add	eax, esi
	push	eax
	push	DWORD PTR [edi+12]
	push	DWORD PTR [edi+8]
	call	_slotMapPage
	inc	esi
	add	esp, 24					; 00000018H
	cmp	esi, 8
	jl	SHORT $LL6@romMapperS

; 172  :     sunriseIdeReset(rm->ide);

	push	DWORD PTR [edi+24]

; 221  :     }
; 222  : 
; 223  :     rm->ideEnabled = 1;

	mov	DWORD PTR [edi+28], 1

; 224  :     rm->romMapper = 0;

	mov	DWORD PTR [edi+36], 0

; 172  :     sunriseIdeReset(rm->ide);

	call	_sunriseIdeReset
	add	esp, 4

; 225  : 
; 226  :     reset(rm);
; 227  : 
; 228  :     return 1;

	mov	eax, 1
	pop	edi
	pop	esi
	pop	ebx

; 229  : }

	add	esp, 16					; 00000010H
	ret	0
_romMapperSunriseIdeCreate ENDP
_TEXT	ENDS
END
