; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27054.0 

	TITLE	D:\repo\MSX-master\MSX\blueMSX-DPI\Src\Memory\romMapperTurboRTimer.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	??_C@_05IEEKDPFI@V9938@				; `string'
PUBLIC	??_C@_05IAMHEDOK@V9958@				; `string'
PUBLIC	??_C@_08IBFDMDNO@TMS9929A@			; `string'
PUBLIC	??_C@_08HEDIBBLA@TMS99x8A@			; `string'
;	COMDAT ??_C@_08HEDIBBLA@TMS99x8A@
CONST	SEGMENT
??_C@_08HEDIBBLA@TMS99x8A@ DB 'TMS99x8A', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_08IBFDMDNO@TMS9929A@
CONST	SEGMENT
??_C@_08IBFDMDNO@TMS9929A@ DB 'TMS9929A', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_05IAMHEDOK@V9958@
CONST	SEGMENT
??_C@_05IAMHEDOK@V9958@ DB 'V9958', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_05IEEKDPFI@V9938@
CONST	SEGMENT
??_C@_05IEEKDPFI@V9938@ DB 'V9938', 00H			; `string'
CONST	ENDS
PUBLIC	_romMapperTurboRTimerCreate
PUBLIC	_romMapperTurboRTimerSync
PUBLIC	??_C@_0BC@GHOPKBAK@mapperTurboRTimer@		; `string'
PUBLIC	??_C@_07HDOCMLOI@counter@			; `string'
PUBLIC	??_C@_07KALDCPGN@refTime@			; `string'
PUBLIC	??_C@_07GKHKAPH@refFrag@			; `string'
EXTRN	_deviceManagerRegister:PROC
EXTRN	_deviceManagerUnregister:PROC
EXTRN	_saveStateOpenForRead:PROC
EXTRN	_saveStateOpenForWrite:PROC
EXTRN	_saveStateClose:PROC
EXTRN	_saveStateGet:PROC
EXTRN	_saveStateSet:PROC
EXTRN	_ioPortRegister:PROC
EXTRN	_ioPortUnregister:PROC
EXTRN	_free:PROC
EXTRN	_malloc:PROC
EXTRN	__aulldiv:PROC
EXTRN	_boardSysTime:DWORD
_BSS	SEGMENT
_theTimer DD	01H DUP (?)
_BSS	ENDS
;	COMDAT ??_C@_07GKHKAPH@refFrag@
CONST	SEGMENT
??_C@_07GKHKAPH@refFrag@ DB 'refFrag', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_07KALDCPGN@refTime@
CONST	SEGMENT
??_C@_07KALDCPGN@refTime@ DB 'refTime', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_07HDOCMLOI@counter@
CONST	SEGMENT
??_C@_07HDOCMLOI@counter@ DB 'counter', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_0BC@GHOPKBAK@mapperTurboRTimer@
CONST	SEGMENT
??_C@_0BC@GHOPKBAK@mapperTurboRTimer@ DB 'mapperTurboRTimer', 00H ; `string'
CONST	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommapperturbortimer.c
;	COMDAT _write
_TEXT	SEGMENT
_rm$ = 8						; size = 4
_ioPort$ = 12						; size = 2
_value$ = 16						; size = 1
_write	PROC						; COMDAT

; 109  :     theTimer->counter = 0;

	mov	eax, DWORD PTR _theTimer

; 110  :     rm->refTime = boardSystemTime();

	mov	ecx, DWORD PTR _rm$[esp-4]
	mov	DWORD PTR [eax+4], 0
	mov	eax, DWORD PTR _boardSysTime
	mov	eax, DWORD PTR [eax]
	mov	DWORD PTR [ecx+8], eax

; 111  :     rm->refFrag = 0;

	mov	DWORD PTR [ecx+12], 0

; 112  : }

	ret	0
_write	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommapperturbortimer.c
; File d:\repo\msx-master\msx\bluemsx-dpi\src\board\board.h
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommapperturbortimer.c
; File d:\repo\msx-master\msx\bluemsx-dpi\src\board\board.h
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommapperturbortimer.c
; File d:\repo\msx-master\msx\bluemsx-dpi\src\board\board.h
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommapperturbortimer.c
;	COMDAT _read
_TEXT	SEGMENT
_rm$ = 8						; size = 4
_ioPort$ = 12						; size = 2
_read	PROC						; COMDAT

; 94   : {

	push	edi

; 84   :     if (theTimer != NULL) {

	mov	edi, DWORD PTR _theTimer
	test	edi, edi
	je	SHORT $LN8@read
; File d:\repo\msx-master\msx\bluemsx-dpi\src\board\board.h

; 165  :     return *boardSysTime;

	mov	eax, DWORD PTR _boardSysTime
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommapperturbortimer.c

; 86   :         UInt64 elapsed = 255682 * (UInt64)(systemTime - theTimer->refTime) + theTimer->refFrag;

	mov	edx, 255682				; 0003e6c2H
; File d:\repo\msx-master\msx\bluemsx-dpi\src\board\board.h

; 165  :     return *boardSysTime;

	push	esi
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommapperturbortimer.c

; 88   :         theTimer->refFrag = (UInt32)(elapsed % boardFrequency());

	push	0
	push	21477270				; 0147b796H
; File d:\repo\msx-master\msx\bluemsx-dpi\src\board\board.h

; 165  :     return *boardSysTime;

	mov	ecx, DWORD PTR [eax]
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommapperturbortimer.c

; 86   :         UInt64 elapsed = 255682 * (UInt64)(systemTime - theTimer->refTime) + theTimer->refFrag;

	mov	eax, ecx
	sub	eax, DWORD PTR [edi+8]
	mul	edx

; 87   :         theTimer->refTime = systemTime;

	mov	DWORD PTR [edi+8], ecx
	mov	esi, eax
	add	esi, DWORD PTR [edi+12]
	adc	edx, 0

; 88   :         theTimer->refFrag = (UInt32)(elapsed % boardFrequency());

	push	edx
	push	esi
	call	__aulldiv
	imul	ecx, eax, 21477270
	sub	esi, ecx

; 89   :         theTimer->counter += (UInt32)(elapsed / boardFrequency());

	add	DWORD PTR [edi+4], eax
	mov	DWORD PTR [edi+12], esi
	pop	esi
$LN8@read:

; 95   :     romMapperTurboRTimerSync();
; 96   :     
; 97   :     switch (ioPort & 0x01) {

	mov	eax, DWORD PTR _ioPort$[esp]
	and	eax, 1
	pop	edi
	sub	eax, 0
	je	SHORT $LN4@read
	sub	eax, 1
	je	SHORT $LN5@read

; 102  :     }
; 103  : 
; 104  :     return 0xff;

	or	al, 255					; 000000ffH

; 105  : }

	ret	0
$LN5@read:

; 100  : 	case 1:
; 101  : 		return (UInt8)((rm->counter >> 8) & 0xff);

	mov	eax, DWORD PTR _rm$[esp-4]
	mov	al, BYTE PTR [eax+5]

; 105  : }

	ret	0
$LN4@read:

; 98   : 	case 0:
; 99   : 		return (UInt8)(rm->counter & 0xff);

	mov	eax, DWORD PTR _rm$[esp-4]
	mov	al, BYTE PTR [eax+4]

; 105  : }

	ret	0
_read	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommapperturbortimer.c
;	COMDAT _destroy
_TEXT	SEGMENT
_rm$ = 8						; size = 4
_destroy PROC						; COMDAT

; 71   : {

	push	esi

; 72   :     deviceManagerUnregister(rm->deviceHandle);

	mov	esi, DWORD PTR _rm$[esp]
	push	DWORD PTR [esi]
	call	_deviceManagerUnregister

; 73   : 
; 74   :     ioPortUnregister(0xe6);

	push	230					; 000000e6H
	call	_ioPortUnregister

; 75   :     ioPortUnregister(0xe7);

	push	231					; 000000e7H
	call	_ioPortUnregister

; 76   : 
; 77   :     free(rm);

	push	esi
	call	_free
	add	esp, 16					; 00000010H

; 78   : 
; 79   :     theTimer = NULL;

	mov	DWORD PTR _theTimer, 0
	pop	esi

; 80   : }

	ret	0
_destroy ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommapperturbortimer.c
; File d:\repo\msx-master\msx\bluemsx-dpi\src\board\board.h
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommapperturbortimer.c
;	COMDAT _loadState
_TEXT	SEGMENT
_rm$ = 8						; size = 4
_loadState PROC						; COMDAT

; 60   : {

	push	esi
	push	edi

; 61   :     SaveState* state = saveStateOpenForRead("mapperTurboRTimer");

	push	OFFSET ??_C@_0BC@GHOPKBAK@mapperTurboRTimer@
	call	_saveStateOpenForRead

; 62   : 
; 63   :     rm->counter = saveStateGet(state, "counter", 0);

	push	0
	mov	edi, eax
	push	OFFSET ??_C@_07HDOCMLOI@counter@
	push	edi
	call	_saveStateGet
	mov	esi, DWORD PTR _rm$[esp+20]
	mov	DWORD PTR [esi+4], eax
; File d:\repo\msx-master\msx\bluemsx-dpi\src\board\board.h

; 165  :     return *boardSysTime;

	mov	ecx, DWORD PTR _boardSysTime
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommapperturbortimer.c

; 64   :     rm->refTime = saveStateGet(state, "refTime", boardSystemTime());

	push	DWORD PTR [ecx]
	push	OFFSET ??_C@_07KALDCPGN@refTime@
	push	edi
	call	_saveStateGet

; 65   :     rm->refFrag = saveStateGet(state, "refFrag", 0);

	push	0
	push	OFFSET ??_C@_07GKHKAPH@refFrag@
	push	edi
	mov	DWORD PTR [esi+8], eax
	call	_saveStateGet

; 66   : 
; 67   :     saveStateClose(state);

	push	edi
	mov	DWORD PTR [esi+12], eax
	call	_saveStateClose
	add	esp, 44					; 0000002cH
	pop	edi
	pop	esi

; 68   : }

	ret	0
_loadState ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommapperturbortimer.c
;	COMDAT _saveState
_TEXT	SEGMENT
_rm$ = 8						; size = 4
_saveState PROC						; COMDAT

; 49   : {

	push	esi
	push	edi

; 50   :     SaveState* state = saveStateOpenForWrite("mapperTurboRTimer");

	push	OFFSET ??_C@_0BC@GHOPKBAK@mapperTurboRTimer@
	call	_saveStateOpenForWrite

; 51   : 
; 52   :     saveStateSet(state, "counter", rm->counter);

	mov	esi, DWORD PTR _rm$[esp+8]
	mov	edi, eax
	push	DWORD PTR [esi+4]
	push	OFFSET ??_C@_07HDOCMLOI@counter@
	push	edi
	call	_saveStateSet

; 53   :     saveStateSet(state, "refTime", rm->refTime);

	push	DWORD PTR [esi+8]
	push	OFFSET ??_C@_07KALDCPGN@refTime@
	push	edi
	call	_saveStateSet

; 54   :     saveStateSet(state, "refFrag", rm->refFrag);

	push	DWORD PTR [esi+12]
	push	OFFSET ??_C@_07GKHKAPH@refFrag@
	push	edi
	call	_saveStateSet

; 55   :     
; 56   :     saveStateClose(state);

	push	edi
	call	_saveStateClose
	add	esp, 44					; 0000002cH
	pop	edi
	pop	esi

; 57   : }

	ret	0
_saveState ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\board\board.h
;	COMDAT _boardSystemTime
_TEXT	SEGMENT
_boardSystemTime PROC					; COMDAT

; 164  :     extern UInt32* boardSysTime;
; 165  :     return *boardSysTime;

	mov	eax, DWORD PTR _boardSysTime
	mov	eax, DWORD PTR [eax]

; 166  : }

	ret	0
_boardSystemTime ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommapperturbortimer.c
; File d:\repo\msx-master\msx\bluemsx-dpi\src\board\board.h
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommapperturbortimer.c
; File d:\repo\msx-master\msx\bluemsx-dpi\src\board\board.h
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommapperturbortimer.c
; File d:\repo\msx-master\msx\bluemsx-dpi\src\board\board.h
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommapperturbortimer.c
;	COMDAT _romMapperTurboRTimerSync
_TEXT	SEGMENT
_romMapperTurboRTimerSync PROC				; COMDAT

; 83   : {

	push	edi

; 84   :     if (theTimer != NULL) {

	mov	edi, DWORD PTR _theTimer
	test	edi, edi
	je	SHORT $LN2@romMapperT
; File d:\repo\msx-master\msx\bluemsx-dpi\src\board\board.h

; 165  :     return *boardSysTime;

	mov	eax, DWORD PTR _boardSysTime
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommapperturbortimer.c

; 86   :         UInt64 elapsed = 255682 * (UInt64)(systemTime - theTimer->refTime) + theTimer->refFrag;

	mov	edx, 255682				; 0003e6c2H
; File d:\repo\msx-master\msx\bluemsx-dpi\src\board\board.h

; 165  :     return *boardSysTime;

	push	esi
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommapperturbortimer.c

; 88   :         theTimer->refFrag = (UInt32)(elapsed % boardFrequency());

	push	0
	push	21477270				; 0147b796H
; File d:\repo\msx-master\msx\bluemsx-dpi\src\board\board.h

; 165  :     return *boardSysTime;

	mov	ecx, DWORD PTR [eax]
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommapperturbortimer.c

; 86   :         UInt64 elapsed = 255682 * (UInt64)(systemTime - theTimer->refTime) + theTimer->refFrag;

	mov	eax, ecx
	sub	eax, DWORD PTR [edi+8]
	mul	edx

; 87   :         theTimer->refTime = systemTime;

	mov	DWORD PTR [edi+8], ecx
	mov	esi, eax
	add	esi, DWORD PTR [edi+12]
	adc	edx, 0

; 88   :         theTimer->refFrag = (UInt32)(elapsed % boardFrequency());

	push	edx
	push	esi
	call	__aulldiv
	imul	ecx, eax, 21477270
	sub	esi, ecx

; 89   :         theTimer->counter += (UInt32)(elapsed / boardFrequency());

	add	DWORD PTR [edi+4], eax
	mov	DWORD PTR [edi+12], esi
	pop	esi
$LN2@romMapperT:

; 90   :     }
; 91   : }

	pop	edi
	ret	0
_romMapperTurboRTimerSync ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\rommapperturbortimer.c
;	COMDAT _romMapperTurboRTimerCreate
_TEXT	SEGMENT
_callbacks$ = -16					; size = 16
_romMapperTurboRTimerCreate PROC			; COMDAT

; 115  : {

	sub	esp, 16					; 00000010H
	push	esi

; 116  :     DeviceCallbacks callbacks = { destroy, NULL, saveState, loadState };
; 117  :     RomMapperTurboRTimer* rm = malloc(sizeof(RomMapperTurboRTimer));

	push	16					; 00000010H
	mov	DWORD PTR _callbacks$[esp+24], OFFSET _destroy
	mov	DWORD PTR _callbacks$[esp+28], 0
	mov	DWORD PTR _callbacks$[esp+32], OFFSET _saveState
	mov	DWORD PTR _callbacks$[esp+36], OFFSET _loadState
	call	_malloc
	mov	esi, eax

; 118  : 
; 119  :     rm->deviceHandle = deviceManagerRegister(ROM_TURBORTIMER, &callbacks, rm);

	lea	eax, DWORD PTR _callbacks$[esp+24]
	push	esi
	push	eax
	push	59					; 0000003bH
	call	_deviceManagerRegister
	mov	DWORD PTR [esi], eax

; 120  : 
; 121  :     rm->refTime = boardSystemTime();

	mov	ecx, DWORD PTR _boardSysTime

; 122  :     rm->refFrag = 0;
; 123  :     rm->counter = 0;
; 124  : 
; 125  :     ioPortRegister(0xe6, read, write, rm);

	push	esi
	push	OFFSET _write
	push	OFFSET _read
	mov	ecx, DWORD PTR [ecx]
	push	230					; 000000e6H
	mov	DWORD PTR [esi+8], ecx
	mov	DWORD PTR [esi+12], 0
	mov	DWORD PTR [esi+4], 0
	call	_ioPortRegister

; 126  :     ioPortRegister(0xe7, read, write, rm);

	push	esi
	push	OFFSET _write
	push	OFFSET _read
	push	231					; 000000e7H
	call	_ioPortRegister
	add	esp, 48					; 00000030H

; 127  : 
; 128  :     theTimer = rm;

	mov	DWORD PTR _theTimer, esi

; 129  : 
; 130  :     return 1;

	mov	eax, 1
	pop	esi

; 131  : }

	add	esp, 16					; 00000010H
	ret	0
_romMapperTurboRTimerCreate ENDP
_TEXT	ENDS
END
