; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27054.0 

	TITLE	D:\repo\MSX-master\MSX\blueMSX-DPI\Src\Memory\sramLoader.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	??_C@_05IEEKDPFI@V9938@				; `string'
PUBLIC	??_C@_05IAMHEDOK@V9958@				; `string'
PUBLIC	??_C@_08IBFDMDNO@TMS9929A@			; `string'
PUBLIC	??_C@_08HEDIBBLA@TMS99x8A@			; `string'
;	COMDAT ??_C@_08HEDIBBLA@TMS99x8A@
CONST	SEGMENT
??_C@_08HEDIBBLA@TMS99x8A@ DB 'TMS99x8A', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_08IBFDMDNO@TMS9929A@
CONST	SEGMENT
??_C@_08IBFDMDNO@TMS9929A@ DB 'TMS9929A', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_05IAMHEDOK@V9958@
CONST	SEGMENT
??_C@_05IAMHEDOK@V9958@ DB 'V9958', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_05IEEKDPFI@V9938@
CONST	SEGMENT
??_C@_05IEEKDPFI@V9938@ DB 'V9938', 00H			; `string'
CONST	ENDS
PUBLIC	_sramCreateFilename
PUBLIC	_sramCreateFilenameWithSuffix
PUBLIC	_sramLoad
PUBLIC	_sramSave
PUBLIC	___local_stdio_printf_options
PUBLIC	_sprintf
PUBLIC	??_C@_05BMGBEOOC@?$CFs?2?$CFs@			; `string'
PUBLIC	??_C@_02JDPG@rb@				; `string'
PUBLIC	??_C@_02GMLFBBN@wb@				; `string'
EXTRN	_fclose:PROC
EXTRN	_fopen:PROC
EXTRN	_fread:PROC
EXTRN	_fwrite:PROC
EXTRN	___stdio_common_vsprintf:PROC
EXTRN	_boardGetBaseDirectory:PROC
EXTRN	@__security_check_cookie@4:PROC
EXTRN	_memcpy:PROC
EXTRN	___security_cookie:DWORD
_DATA	SEGMENT
COMM	?_OptionsStorage@?1??__local_stdio_printf_options@@9@9:QWORD							; `__local_stdio_printf_options'::`2'::_OptionsStorage
_DATA	ENDS
_BSS	SEGMENT
?SRAMfileName@?1??sramCreateFilenameWithSuffix@@9@9 DB 0200H DUP (?) ; `sramCreateFilenameWithSuffix'::`2'::SRAMfileName
_BSS	ENDS
;	COMDAT ??_C@_02GMLFBBN@wb@
CONST	SEGMENT
??_C@_02GMLFBBN@wb@ DB 'wb', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_02JDPG@rb@
CONST	SEGMENT
??_C@_02JDPG@rb@ DB 'rb', 00H				; `string'
CONST	ENDS
;	COMDAT ??_C@_05BMGBEOOC@?$CFs?2?$CFs@
CONST	SEGMENT
??_C@_05BMGBEOOC@?$CFs?2?$CFs@ DB '%s\%s', 00H		; `string'
CONST	ENDS
; Function compile flags: /Ogtpy
; File c:\program files (x86)\windows kits\10\include\10.0.19041.0\ucrt\stdio.h
;	COMDAT _sprintf
_TEXT	SEGMENT
__Buffer$ = 8						; size = 4
__Format$ = 12						; size = 4
_sprintf PROC						; COMDAT

; 1392 :         int const _Result = __stdio_common_vsprintf(

	lea	eax, DWORD PTR __Format$[esp]
	push	eax
	push	0
	push	DWORD PTR __Format$[esp+4]
	push	-1
	push	DWORD PTR __Buffer$[esp+12]
	call	___local_stdio_printf_options
	mov	ecx, DWORD PTR [eax]
	push	DWORD PTR [eax+4]
	or	ecx, 1
	push	ecx
	call	___stdio_common_vsprintf

; 1393 :             _CRT_INTERNAL_LOCAL_PRINTF_OPTIONS | _CRT_INTERNAL_PRINTF_LEGACY_VSPRINTF_NULL_TERMINATION,
; 1394 :             _Buffer, _BufferCount, _Format, _Locale, _ArgList);
; 1395 : 
; 1396 :         return _Result < 0 ? -1 : _Result;

	or	ecx, -1
	add	esp, 28					; 0000001cH
	test	eax, eax
	cmovs	eax, ecx

; 1772 :         int _Result;
; 1773 :         va_list _ArgList;
; 1774 :         __crt_va_start(_ArgList, _Format);
; 1775 : 
; 1776 :         _Result = _vsprintf_l(_Buffer, _Format, NULL, _ArgList);
; 1777 : 
; 1778 :         __crt_va_end(_ArgList);
; 1779 :         return _Result;
; 1780 :     }

	ret	0
_sprintf ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File c:\program files (x86)\windows kits\10\include\10.0.19041.0\ucrt\stdio.h
;	COMDAT __vsprintf_l
_TEXT	SEGMENT
__Buffer$ = 8						; size = 4
__Format$ = 12						; size = 4
__Locale$ = 16						; size = 4
__ArgList$ = 20						; size = 4
__vsprintf_l PROC					; COMDAT

; 1392 :         int const _Result = __stdio_common_vsprintf(

	push	DWORD PTR __ArgList$[esp-4]
	push	DWORD PTR __Locale$[esp]
	push	DWORD PTR __Format$[esp+4]
	push	-1
	push	DWORD PTR __Buffer$[esp+12]
	call	___local_stdio_printf_options
	mov	ecx, DWORD PTR [eax]
	push	DWORD PTR [eax+4]
	or	ecx, 1
	push	ecx
	call	___stdio_common_vsprintf

; 1393 :             _CRT_INTERNAL_LOCAL_PRINTF_OPTIONS | _CRT_INTERNAL_PRINTF_LEGACY_VSPRINTF_NULL_TERMINATION,
; 1394 :             _Buffer, _BufferCount, _Format, _Locale, _ArgList);
; 1395 : 
; 1396 :         return _Result < 0 ? -1 : _Result;

	or	ecx, -1
	add	esp, 28					; 0000001cH
	test	eax, eax
	cmovs	eax, ecx

; 1459 :         return _vsnprintf_l(_Buffer, (size_t)-1, _Format, _Locale, _ArgList);
; 1460 :     }

	ret	0
__vsprintf_l ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File c:\program files (x86)\windows kits\10\include\10.0.19041.0\ucrt\stdio.h
;	COMDAT __vsnprintf_l
_TEXT	SEGMENT
__Buffer$ = 8						; size = 4
__BufferCount$ = 12					; size = 4
__Format$ = 16						; size = 4
__Locale$ = 20						; size = 4
__ArgList$ = 24						; size = 4
__vsnprintf_l PROC					; COMDAT

; 1392 :         int const _Result = __stdio_common_vsprintf(

	push	DWORD PTR __ArgList$[esp-4]
	push	DWORD PTR __Locale$[esp]
	push	DWORD PTR __Format$[esp+4]
	push	DWORD PTR __BufferCount$[esp+8]
	push	DWORD PTR __Buffer$[esp+12]
	call	___local_stdio_printf_options
	mov	ecx, DWORD PTR [eax]
	push	DWORD PTR [eax+4]
	or	ecx, 1
	push	ecx
	call	___stdio_common_vsprintf

; 1393 :             _CRT_INTERNAL_LOCAL_PRINTF_OPTIONS | _CRT_INTERNAL_PRINTF_LEGACY_VSPRINTF_NULL_TERMINATION,
; 1394 :             _Buffer, _BufferCount, _Format, _Locale, _ArgList);
; 1395 : 
; 1396 :         return _Result < 0 ? -1 : _Result;

	or	ecx, -1
	add	esp, 28					; 0000001cH
	test	eax, eax
	cmovs	eax, ecx

; 1397 :     }

	ret	0
__vsnprintf_l ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File c:\program files (x86)\windows kits\10\include\10.0.19041.0\ucrt\corecrt_stdio_config.h
;	COMDAT ___local_stdio_printf_options
_TEXT	SEGMENT
___local_stdio_printf_options PROC			; COMDAT

; 91   :         static unsigned __int64 _OptionsStorage;
; 92   :         return &_OptionsStorage;

	mov	eax, OFFSET ?_OptionsStorage@?1??__local_stdio_printf_options@@9@9 ; `__local_stdio_printf_options'::`2'::_OptionsStorage

; 93   :     }

	ret	0
___local_stdio_printf_options ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\sramloader.c
;	COMDAT _sramSave
_TEXT	SEGMENT
_filename$ = 8						; size = 4
_sram$ = 12						; size = 4
_length$ = 16						; size = 4
_header$ = 20						; size = 4
_headerLength$ = 24					; size = 4
_sramSave PROC						; COMDAT

; 100  : void sramSave(const char* filename, UInt8* sram, int length, void* header, int headerLength) {

	push	esi

; 101  :     FILE* file;
; 102  : 
; 103  :     file = fopen(filename, "wb");

	push	OFFSET ??_C@_02GMLFBBN@wb@
	push	DWORD PTR _filename$[esp+4]
	call	_fopen
	mov	esi, eax
	add	esp, 8

; 104  :     if (file != NULL) {

	test	esi, esi
	je	SHORT $LN2@sramSave

; 105  :         if (headerLength > 0) {

	mov	eax, DWORD PTR _headerLength$[esp]
	test	eax, eax
	jle	SHORT $LN3@sramSave

; 106  :             fwrite(header, 1, headerLength, file);

	push	esi
	push	eax
	push	1
	push	DWORD PTR _header$[esp+12]
	call	_fwrite
	add	esp, 16					; 00000010H
$LN3@sramSave:

; 107  :         }
; 108  :         fwrite(sram, 1, length, file);

	push	esi
	push	DWORD PTR _length$[esp+4]
	push	1
	push	DWORD PTR _sram$[esp+12]
	call	_fwrite

; 109  :         fclose(file);

	push	esi
	call	_fclose
	add	esp, 20					; 00000014H
$LN2@sramSave:

; 110  :     }
; 111  : }

	pop	esi
	ret	0
_sramSave ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\sramloader.c
;	COMDAT _sramLoad
_TEXT	SEGMENT
_readHeader$1 = -1028					; size = 1024
__$ArrayPad$ = -4					; size = 4
_filename$ = 8						; size = 4
_sram$ = 12						; size = 4
_length$ = 16						; size = 4
_header$ = 20						; size = 4
_headerLength$ = 24					; size = 4
_sramLoad PROC						; COMDAT

; 81   : void sramLoad(const char* filename, UInt8* sram, int length, void* header, int headerLength) {

	sub	esp, 1028				; 00000404H
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, esp
	mov	DWORD PTR __$ArrayPad$[esp+1028], eax
	mov	eax, DWORD PTR _filename$[esp+1024]
	push	ebx
	mov	ebx, DWORD PTR _sram$[esp+1028]
	push	edi

; 82   :     FILE* file;
; 83   : 
; 84   :     file = fopen(filename, "rb");

	push	OFFSET ??_C@_02JDPG@rb@
	push	eax
	call	_fopen
	mov	edi, eax
	add	esp, 8

; 85   :     if (file != NULL) {

	test	edi, edi
	je	$LN2@sramLoad

; 86   :         if (headerLength > 0) {

	push	esi
	mov	esi, DWORD PTR _headerLength$[esp+1036]
	test	esi, esi
	jle	$LN6@sramLoad

; 87   :             char* readHeader[256];
; 88   : 
; 89   :             fread(readHeader, 1, headerLength, file);

	push	edi
	push	esi
	lea	eax, DWORD PTR _readHeader$1[esp+1048]
	push	1
	push	eax
	call	_fread

; 90   :             if (memcmp(readHeader, header, headerLength)) {

	mov	edx, DWORD PTR _header$[esp+1052]
	lea	ecx, DWORD PTR _readHeader$1[esp+1056]
	add	esp, 16					; 00000010H
	sub	esi, 4
	jb	SHORT $LN8@sramLoad
	npad	3
$LL9@sramLoad:
	mov	eax, DWORD PTR [ecx]
	cmp	eax, DWORD PTR [edx]
	jne	SHORT $LN7@sramLoad
	add	ecx, 4
	add	edx, 4
	sub	esi, 4
	jae	SHORT $LL9@sramLoad
$LN8@sramLoad:
	cmp	esi, -4					; fffffffcH
	je	SHORT $LN6@sramLoad
$LN7@sramLoad:
	mov	al, BYTE PTR [ecx]
	cmp	al, BYTE PTR [edx]
	jne	SHORT $LN10@sramLoad
	cmp	esi, -3					; fffffffdH
	je	SHORT $LN6@sramLoad
	mov	al, BYTE PTR [ecx+1]
	cmp	al, BYTE PTR [edx+1]
	jne	SHORT $LN10@sramLoad
	cmp	esi, -2					; fffffffeH
	je	SHORT $LN6@sramLoad
	mov	al, BYTE PTR [ecx+2]
	cmp	al, BYTE PTR [edx+2]
	jne	SHORT $LN10@sramLoad
	cmp	esi, -1
	je	SHORT $LN6@sramLoad
	mov	al, BYTE PTR [ecx+3]
	cmp	al, BYTE PTR [edx+3]
	je	SHORT $LN6@sramLoad
$LN10@sramLoad:

; 91   :                 fclose(file);

	push	edi
	call	_fclose
	add	esp, 4
	pop	esi
	pop	edi

; 97   :     }
; 98   : }

	pop	ebx
	mov	ecx, DWORD PTR __$ArrayPad$[esp+1028]
	xor	ecx, esp
	call	@__security_check_cookie@4
	add	esp, 1028				; 00000404H
	ret	0
$LN6@sramLoad:

; 92   :                 return;
; 93   :             }
; 94   :         }
; 95   :         fread(sram, 1, length, file);

	push	edi
	push	DWORD PTR _length$[esp+1040]
	push	1
	push	ebx
	call	_fread

; 96   :         fclose(file);

	push	edi
	call	_fclose
	add	esp, 20					; 00000014H
	pop	esi
$LN2@sramLoad:

; 97   :     }
; 98   : }

	mov	ecx, DWORD PTR __$ArrayPad$[esp+1036]
	pop	edi
	pop	ebx
	xor	ecx, esp
	call	@__security_check_cookie@4
	add	esp, 1028				; 00000404H
	ret	0
_sramLoad ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\sramloader.c
;	COMDAT _sramCreateFilenameWithSuffix
_TEXT	SEGMENT
_fileName$ = -516					; size = 512
__$ArrayPad$ = -4					; size = 4
_romFilename$ = 8					; size = 4
_suffix$ = 12						; size = 4
_ext$ = 16						; size = 4
_sramCreateFilenameWithSuffix PROC			; COMDAT

; 37   : {

	sub	esp, 516				; 00000204H
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, esp
	mov	DWORD PTR __$ArrayPad$[esp+516], eax

; 38   :     static char SRAMfileName[512];
; 39   :     char fileName[512];
; 40   :     char* dst = fileName + 512;
; 41   :     const char* src;
; 42   : 
; 43   :     *--dst = '\0';
; 44   :     if (ext == NULL) {

	mov	edx, DWORD PTR _ext$[esp+512]
	mov	BYTE PTR _fileName$[esp+1027], 0
	push	esi
	lea	esi, DWORD PTR _fileName$[esp+1031]
	push	edi
	mov	edi, DWORD PTR _suffix$[esp+520]
	test	edx, edx
	jne	SHORT $LN9@sramCreate

; 45   :         *--dst = 'm';
; 46   :         *--dst = 'a';
; 47   :         *--dst = 'r';
; 48   :         *--dst = 's';

	mov	DWORD PTR _fileName$[esp+1031], 1835102835 ; 6d617273H

; 49   :         *--dst = '.';

	lea	esi, DWORD PTR _fileName$[esp+1030]
	mov	BYTE PTR _fileName$[esp+1030], 46	; 0000002eH

; 50   :     }

	jmp	SHORT $LN3@sramCreate
$LN9@sramCreate:

; 51   :     else {
; 52   :         char* p = ext + strlen(ext);

	mov	ecx, edx
	push	ebx
	lea	ebx, DWORD PTR [ecx+1]
	npad	7
$LL25@sramCreate:
	mov	al, BYTE PTR [ecx]
	inc	ecx
	test	al, al
	jne	SHORT $LL25@sramCreate
	sub	ecx, ebx
	add	ecx, edx
	pop	ebx
	npad	4
$LL18@sramCreate:

; 53   :         do {
; 54   :             *--dst = *--p;

	mov	al, BYTE PTR [ecx-1]
	dec	ecx
	dec	esi
	mov	BYTE PTR [esi], al

; 55   :         } while (p != ext);

	cmp	ecx, edx
	jne	SHORT $LL18@sramCreate
$LN3@sramCreate:

; 56   :     }
; 57   : 
; 58   :     dst -= strlen(suffix);

	mov	ecx, edi
	lea	edx, DWORD PTR [ecx+1]
$LL26@sramCreate:
	mov	al, BYTE PTR [ecx]
	inc	ecx
	test	al, al
	jne	SHORT $LL26@sramCreate
	sub	ecx, edx
	sub	esi, ecx

; 59   :     memcpy(dst, suffix, strlen(suffix));

	mov	ecx, edi
	lea	edx, DWORD PTR [ecx+1]
$LL27@sramCreate:
	mov	al, BYTE PTR [ecx]
	inc	ecx
	test	al, al
	jne	SHORT $LL27@sramCreate
	sub	ecx, edx
	push	ecx
	push	edi
	push	esi
	call	_memcpy

; 60   :     
; 61   :     src = romFilename + strlen(romFilename);

	mov	edx, DWORD PTR _romFilename$[esp+532]
	add	esp, 12					; 0000000cH
	mov	ecx, edx
	lea	edi, DWORD PTR [ecx+1]
$LL28@sramCreate:
	mov	al, BYTE PTR [ecx]
	inc	ecx
	test	al, al
	jne	SHORT $LL28@sramCreate
	sub	ecx, edi

; 62   : 
; 63   :     while (*src != '.' && src > romFilename) {

	cmp	BYTE PTR [ecx+edx], 46			; 0000002eH
	lea	eax, DWORD PTR [ecx+edx]
	je	SHORT $LN29@sramCreate
$LL5@sramCreate:
	cmp	eax, edx
	jbe	SHORT $LN29@sramCreate

; 64   :         src--;

	dec	eax
	cmp	BYTE PTR [eax], 46			; 0000002eH
	jne	SHORT $LL5@sramCreate
$LN29@sramCreate:

; 65   :     }
; 66   :     src--;
; 67   : 
; 68   :     while (*src != '/' && *src != '\\' && src >= romFilename) {

	mov	cl, BYTE PTR [eax-1]
	dec	eax
	cmp	cl, 47					; 0000002fH
	je	SHORT $LN30@sramCreate
$LL7@sramCreate:
	cmp	cl, 92					; 0000005cH
	je	SHORT $LN30@sramCreate
	cmp	eax, edx
	jb	SHORT $LN30@sramCreate

; 69   :         *--dst = *src--;

	dec	esi
	dec	eax
	mov	BYTE PTR [esi], cl
	mov	cl, BYTE PTR [eax]
	cmp	cl, 47					; 0000002fH
	jne	SHORT $LL7@sramCreate
$LN30@sramCreate:

; 70   :     }
; 71   : 
; 72   :     sprintf(SRAMfileName, "%s" DIR_SEPARATOR "%s", boardGetBaseDirectory(), dst);

	push	esi
	call	_boardGetBaseDirectory
	push	eax
	push	OFFSET ??_C@_05BMGBEOOC@?$CFs?2?$CFs@
	push	OFFSET ?SRAMfileName@?1??sramCreateFilenameWithSuffix@@9@9
	call	_sprintf

; 73   : 
; 74   :     return SRAMfileName;
; 75   : }

	mov	ecx, DWORD PTR __$ArrayPad$[esp+540]
	add	esp, 16					; 00000010H
	mov	eax, OFFSET ?SRAMfileName@?1??sramCreateFilenameWithSuffix@@9@9
	pop	edi
	pop	esi
	xor	ecx, esp
	call	@__security_check_cookie@4
	add	esp, 516				; 00000204H
	ret	0
_sramCreateFilenameWithSuffix ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\memory\sramloader.c
;	COMDAT _sramCreateFilename
_TEXT	SEGMENT
_fileName$1 = -516					; size = 512
__$ArrayPad$ = -4					; size = 4
_romFilename$ = 8					; size = 4
_sramCreateFilename PROC				; COMDAT

; 78   : const char* sramCreateFilename(const char* romFilename) {

	sub	esp, 516				; 00000204H
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, esp
	mov	DWORD PTR __$ArrayPad$[esp+516], eax
	push	esi

; 61   :     src = romFilename + strlen(romFilename);

	mov	esi, DWORD PTR _romFilename$[esp+516]
	lea	edx, DWORD PTR _fileName$1[esp+1026]
	mov	ecx, esi
	mov	DWORD PTR _fileName$1[esp+1028], 7168370 ; 006d6172H

; 78   : const char* sramCreateFilename(const char* romFilename) {

	push	edi

; 49   :         *--dst = '.';

	mov	WORD PTR _fileName$1[esp+1030], 29486	; 0000732eH

; 50   :     }
; 51   :     else {
; 52   :         char* p = ext + strlen(ext);
; 53   :         do {
; 54   :             *--dst = *--p;
; 55   :         } while (p != ext);
; 56   :     }
; 57   : 
; 58   :     dst -= strlen(suffix);
; 59   :     memcpy(dst, suffix, strlen(suffix));
; 60   :     
; 61   :     src = romFilename + strlen(romFilename);

	lea	edi, DWORD PTR [ecx+1]
	npad	2
$LL22@sramCreate:
	mov	al, BYTE PTR [ecx]
	inc	ecx
	test	al, al
	jne	SHORT $LL22@sramCreate
	sub	ecx, edi

; 62   : 
; 63   :     while (*src != '.' && src > romFilename) {

	cmp	BYTE PTR [ecx+esi], 46			; 0000002eH
	lea	eax, DWORD PTR [ecx+esi]
	je	SHORT $LN23@sramCreate
$LL7@sramCreate:
	cmp	eax, esi
	jbe	SHORT $LN23@sramCreate

; 64   :         src--;

	dec	eax
	cmp	BYTE PTR [eax], 46			; 0000002eH
	jne	SHORT $LL7@sramCreate
$LN23@sramCreate:

; 65   :     }
; 66   :     src--;
; 67   : 
; 68   :     while (*src != '/' && *src != '\\' && src >= romFilename) {

	mov	cl, BYTE PTR [eax-1]
	dec	eax
	cmp	cl, 47					; 0000002fH
	je	SHORT $LN24@sramCreate
$LL9@sramCreate:
	cmp	cl, 92					; 0000005cH
	je	SHORT $LN24@sramCreate
	cmp	eax, esi
	jb	SHORT $LN24@sramCreate

; 69   :         *--dst = *src--;

	dec	edx
	dec	eax
	mov	BYTE PTR [edx], cl
	mov	cl, BYTE PTR [eax]
	cmp	cl, 47					; 0000002fH
	jne	SHORT $LL9@sramCreate
$LN24@sramCreate:

; 70   :     }
; 71   : 
; 72   :     sprintf(SRAMfileName, "%s" DIR_SEPARATOR "%s", boardGetBaseDirectory(), dst);

	push	edx
	call	_boardGetBaseDirectory
	push	eax
	push	OFFSET ??_C@_05BMGBEOOC@?$CFs?2?$CFs@
	push	OFFSET ?SRAMfileName@?1??sramCreateFilenameWithSuffix@@9@9
	call	_sprintf

; 80   : }

	mov	ecx, DWORD PTR __$ArrayPad$[esp+540]

; 72   :     sprintf(SRAMfileName, "%s" DIR_SEPARATOR "%s", boardGetBaseDirectory(), dst);

	add	esp, 16					; 00000010H

; 79   :     return sramCreateFilenameWithSuffix(romFilename, "", NULL);

	mov	eax, OFFSET ?SRAMfileName@?1??sramCreateFilenameWithSuffix@@9@9
	pop	edi
	pop	esi

; 80   : }

	xor	ecx, esp
	call	@__security_check_cookie@4
	add	esp, 516				; 00000204H
	ret	0
_sramCreateFilename ENDP
_TEXT	ENDS
END
