; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27054.0 

	TITLE	D:\repo\MSX-master\MSX\blueMSX-DPI\Src\Win32\Win32Midi.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_midiInitialize
PUBLIC	_midiShutdown
PUBLIC	_midiEnableMt32ToGmMapping
PUBLIC	_midiInSetChannelFilter
PUBLIC	_midiInGetDeviceCount
PUBLIC	_midiInGetDeviceName
PUBLIC	_midiInGetDeviceIdString
PUBLIC	_midiOutGetDeviceCount
PUBLIC	_midiOutGetDeviceName
PUBLIC	_midiOutGetDeviceIdString
PUBLIC	_archMidiEnable
PUBLIC	_archMidiGetNoteOn
PUBLIC	_archMidiUpdateVolume
PUBLIC	_archMidiLoadState
PUBLIC	_archMidiSaveState
PUBLIC	_archMidiInCreate
PUBLIC	_archMidiInDestroy
PUBLIC	_archMidiInGetNoteOn
PUBLIC	_archMidiOutCreate
PUBLIC	_archMidiOutDestroy
PUBLIC	_archMidiOutTransmit
PUBLIC	___local_stdio_printf_options
PUBLIC	_sprintf
PUBLIC	??_C@_08GIABBKPP@midi?9out@			; `string'
PUBLIC	??_C@_0M@EHCEIAJD@midi?9out?9?$CFu@		; `string'
PUBLIC	??_C@_0L@HFOEGABH@midi?9in?9?$CFu@		; `string'
PUBLIC	??_C@_08HNDPCGNE@ArchMidi@			; `string'
PUBLIC	??_C@_0L@NBAGFBIK@history_?$CFd@		; `string'
PUBLIC	??_C@_0N@INFLDEIM@history_head@			; `string'
PUBLIC	??_C@_0BA@JFHEPDHH@buffer_?$CFd_count@		; `string'
PUBLIC	??_C@_0BB@EJLFJOGP@buffer_?$CFd_remain@		; `string'
PUBLIC	??_C@_0P@EIHEJNDG@buffer_?$CFd_data@		; `string'
EXTRN	_propGetGlobalProperties:PROC
EXTRN	_saveStateOpenForRead:PROC
EXTRN	_saveStateOpenForWrite:PROC
EXTRN	_saveStateClose:PROC
EXTRN	_saveStateGet:PROC
EXTRN	_saveStateSet:PROC
EXTRN	_saveStateGetBuffer:PROC
EXTRN	_saveStateSetBuffer:PROC
EXTRN	_calloc:PROC
EXTRN	_free:PROC
EXTRN	___stdio_common_vsprintf:PROC
EXTRN	__imp__Sleep@4:PROC
EXTRN	__imp__midiOutGetNumDevs@0:PROC
EXTRN	__imp__midiOutGetDevCapsA@12:PROC
EXTRN	__imp__midiOutGetVolume@8:PROC
EXTRN	__imp__midiOutSetVolume@8:PROC
EXTRN	__imp__midiOutOpen@20:PROC
EXTRN	__imp__midiOutClose@4:PROC
EXTRN	__imp__midiOutPrepareHeader@12:PROC
EXTRN	__imp__midiOutUnprepareHeader@12:PROC
EXTRN	__imp__midiOutShortMsg@8:PROC
EXTRN	__imp__midiOutLongMsg@12:PROC
EXTRN	__imp__midiInGetNumDevs@0:PROC
EXTRN	__imp__midiInGetDevCapsA@12:PROC
EXTRN	__imp__midiInOpen@20:PROC
EXTRN	__imp__midiInClose@4:PROC
EXTRN	__imp__midiInStart@4:PROC
EXTRN	__imp__midiInStop@4:PROC
EXTRN	@__security_check_cookie@4:PROC
EXTRN	_memset:PROC
EXTRN	___security_cookie:DWORD
_DATA	SEGMENT
COMM	?_OptionsStorage@?1??__local_stdio_printf_options@@9@9:QWORD							; `__local_stdio_printf_options'::`2'::_OptionsStorage
_DATA	ENDS
_BSS	SEGMENT
_midi	DB	0434H DUP (?)
_BSS	ENDS
;	COMDAT ??_C@_0P@EIHEJNDG@buffer_?$CFd_data@
CONST	SEGMENT
??_C@_0P@EIHEJNDG@buffer_?$CFd_data@ DB 'buffer_%d_data', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BB@EJLFJOGP@buffer_?$CFd_remain@
CONST	SEGMENT
??_C@_0BB@EJLFJOGP@buffer_?$CFd_remain@ DB 'buffer_%d_remain', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BA@JFHEPDHH@buffer_?$CFd_count@
CONST	SEGMENT
??_C@_0BA@JFHEPDHH@buffer_?$CFd_count@ DB 'buffer_%d_count', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0N@INFLDEIM@history_head@
CONST	SEGMENT
??_C@_0N@INFLDEIM@history_head@ DB 'history_head', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0L@NBAGFBIK@history_?$CFd@
CONST	SEGMENT
??_C@_0L@NBAGFBIK@history_?$CFd@ DB 'history_%d', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_08HNDPCGNE@ArchMidi@
CONST	SEGMENT
??_C@_08HNDPCGNE@ArchMidi@ DB 'ArchMidi', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_0L@HFOEGABH@midi?9in?9?$CFu@
CONST	SEGMENT
??_C@_0L@HFOEGABH@midi?9in?9?$CFu@ DB 'midi-in-%u', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0M@EHCEIAJD@midi?9out?9?$CFu@
CONST	SEGMENT
??_C@_0M@EHCEIAJD@midi?9out?9?$CFu@ DB 'midi-out-%u', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_08GIABBKPP@midi?9out@
CONST	SEGMENT
??_C@_08GIABBKPP@midi?9out@ DB 'midi-out', 00H		; `string'
CONST	ENDS
_DATA	SEGMENT
_MT32toGM DB	00H
	DB	01H
	DB	02H
	DB	04H
	DB	04H
	DB	05H
	DB	05H
	DB	03H
	DB	010H
	DB	010H
	DB	010H
	DB	010H
	DB	013H
	DB	013H
	DB	013H
	DB	015H
	DB	06H
	DB	06H
	DB	06H
	DB	07H
	DB	07H
	DB	07H
	DB	08H
	DB	08H
	DB	03eH
	DB	039H
	DB	03fH
	DB	03aH
	DB	026H
	DB	026H
	DB	027H
	DB	027H
	DB	058H
	DB	021H
	DB	034H
	DB	023H
	DB	061H
	DB	064H
	DB	026H
	DB	027H
	DB	0eH
	DB	066H
	DB	044H
	DB	067H
	DB	02cH
	DB	05cH
	DB	02eH
	DB	050H
	DB	030H
	DB	031H
	DB	033H
	DB	02dH
	DB	028H
	DB	028H
	DB	02aH
	DB	02aH
	DB	02bH
	DB	02eH
	DB	02eH
	DB	018H
	DB	019H
	DB	01cH
	DB	01bH
	DB	068H
	DB	020H
	DB	020H
	DB	022H
	DB	021H
	DB	024H
	DB	025H
	DB	027H
	DB	023H
	DB	04fH
	DB	049H
	DB	04cH
	DB	048H
	DB	04aH
	DB	04bH
	DB	040H
	DB	041H
	DB	042H
	DB	043H
	DB	047H
	DB	047H
	DB	045H
	DB	046H
	DB	03cH
	DB	016H
	DB	038H
	DB	03bH
	DB	039H
	DB	03fH
	DB	03cH
	DB	03cH
	DB	03aH
	DB	03dH
	DB	03dH
	DB	0bH
	DB	0bH
	DB	063H
	DB	064H
	DB	09H
	DB	0eH
	DB	0dH
	DB	0cH
	DB	06bH
	DB	06aH
	DB	04dH
	DB	04eH
	DB	04eH
	DB	04cH
	DB	06fH
	DB	02fH
	DB	075H
	DB	07fH
	DB	073H
	DB	076H
	DB	074H
	DB	076H
	DB	07eH
	DB	079H
	DB	079H
	DB	037H
	DB	07cH
	DB	078H
	DB	07dH
	DB	07eH
	DB	07fH
_DATA	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\win32\win32midi.c
;	COMDAT _midiInCallback@20
_TEXT	SEGMENT
_hMidiIn$ = 8						; size = 4
_wMsg$ = 12						; size = 4
_dwInstance$ = 16					; size = 4
_buffer$ = 20						; size = 4
_dwParam1$ = 20						; size = 4
_dwParam2$ = 24						; size = 4
_midiInCallback@20 PROC					; COMDAT

; 536  :     DWORD id = dwInstance;
; 537  :     char buffer[4];
; 538  :     int length = 0;
; 539  :     MIDIHDR* hdr;
; 540  :     int i;
; 541  : 
; 542  :     switch (wMsg) {

	mov	eax, DWORD PTR _wMsg$[esp-4]
	push	ebx
	push	esi
	push	edi
	sub	eax, 963				; 000003c3H
	je	SHORT $LN17@midiInCall
	sub	eax, 1
	je	SHORT $LN33@midiInCall
	sub	eax, 8
	jne	$LN12@midiInCall
$LN17@midiInCall:

; 543  :     case MM_MIM_DATA:
; 544  : 	case MM_MIM_MOREDATA:
; 545  :         buffer[0] = (char)((dwParam1 >>  0) & 0xff);

	mov	ecx, DWORD PTR _dwParam1$[esp+8]

; 546  :         buffer[1] = (char)((dwParam1 >>  8) & 0xff);

	mov	ebx, ecx

; 547  :         buffer[2] = (char)((dwParam1 >> 16) & 0xff);

	mov	eax, ecx
	shr	ebx, 8
	shr	eax, 16					; 00000010H
	mov	BYTE PTR _buffer$[esp+10], al

; 548  :         buffer[3] = (char)((dwParam1 >> 24) & 0xff);

	mov	eax, ecx
	shr	eax, 24					; 00000018H
	mov	BYTE PTR _buffer$[esp+11], al

; 549  : 		switch (buffer[0] & 0x0f0) {

	movzx	eax, cl
	and	eax, 240				; 000000f0H
	mov	BYTE PTR _buffer$[esp+8], cl
	add	eax, -128				; ffffff80H
	mov	BYTE PTR _buffer$[esp+9], bl
	push	ebp
	mov	ebp, DWORD PTR _dwInstance$[esp+12]
	cmp	eax, 112				; 00000070H
	ja	$LN31@midiInCall
	movzx	eax, BYTE PTR $LN48@midiInCall[eax]
	jmp	DWORD PTR $LN51@midiInCall[eax*4]
$LN33@midiInCall:

; 597  :             }
; 598  :         }
; 599  :         break;
; 600  : 
; 601  :     case MM_MIM_LONGDATA:
; 602  :         hdr = (MIDIHDR*)dwParam1;

	mov	edi, DWORD PTR _dwParam1$[esp+8]
	mov	esi, OFFSET _midi+8
	mov	ebx, DWORD PTR _dwInstance$[esp+8]
$LL16@midiInCall:

; 604  :             DevInfo* di = midi.in.current[i];

	mov	eax, DWORD PTR [esi]

; 605  :             if (di != NULL && di->id == id && di->archMidi->callback != NULL) {

	test	eax, eax
	je	SHORT $LN14@midiInCall
	cmp	DWORD PTR [eax], ebx
	jne	SHORT $LN14@midiInCall
	mov	eax, DWORD PTR [eax+316]
	mov	ecx, DWORD PTR [eax+4]
	test	ecx, ecx
	je	SHORT $LN14@midiInCall

; 606  :                 di->archMidi->callback(di->archMidi->ref, hdr->lpData, hdr->dwBytesRecorded);

	push	DWORD PTR [edi+8]
	push	DWORD PTR [edi]
	push	DWORD PTR [eax+8]
	call	ecx
	add	esp, 12					; 0000000cH
$LN14@midiInCall:

; 603  :         for (i = 0; i < 2; i++) {

	add	esi, 4
	cmp	esi, OFFSET _midi+16
	jl	SHORT $LL16@midiInCall

; 607  :             }
; 608  :         }
; 609  :         break;
; 610  :     }
; 611  : }

	pop	edi
	pop	esi
	pop	ebx
	ret	20					; 00000014H
$LN18@midiInCall:

; 550  : 		case 0x090:	// Note On
; 551  : 		case 0x080:	// Note Off
; 552  :             if (midi.in.noteFilter == 0 || midi.in.noteFilter == (buffer[0] & 0x0f) + 1) {

	mov	edx, DWORD PTR _midi+16
	test	edx, edx
	je	SHORT $LN20@midiInCall
	movsx	eax, cl
	and	eax, 15					; 0000000fH
	inc	eax
	cmp	edx, eax
	jne	SHORT $LN7@midiInCall
$LN20@midiInCall:

; 553  :                 for (i = 0; i < 2; i++) {

	mov	edx, OFFSET _midi+8
$LL8@midiInCall:

; 554  :                     DevInfo* di = midi.in.current[i];

	mov	ecx, DWORD PTR [edx]

; 555  :                     if (di != NULL && di->id == id) {

	test	ecx, ecx
	je	SHORT $LN6@midiInCall
	cmp	DWORD PTR [ecx], ebp
	jne	SHORT $LN6@midiInCall

; 556  :                         if ((buffer[0] & 0x10) && buffer[2] > 0) {

	test	BYTE PTR _buffer$[esp+12], 16		; 00000010H
	je	SHORT $LN22@midiInCall
	cmp	BYTE PTR _buffer$[esp+14], 0
	jle	SHORT $LN22@midiInCall

; 557  :                             di->notes[buffer[1]]++;

	movsx	eax, bl
	inc	DWORD PTR [ecx+eax*4+320]

; 558  :                         }

	jmp	SHORT $LN49@midiInCall
$LN22@midiInCall:

; 559  :                         else if (di->notes[buffer[1]] > 0) {

	movsx	eax, bl
	lea	ecx, DWORD PTR [ecx+eax*4]
	mov	eax, DWORD PTR [ecx+320]
	test	eax, eax
	jle	SHORT $LN6@midiInCall

; 560  :                             di->notes[buffer[1]]--;

	dec	eax
	mov	DWORD PTR [ecx+320], eax
$LN49@midiInCall:

; 553  :                 for (i = 0; i < 2; i++) {

	mov	bl, BYTE PTR _buffer$[esp+13]
$LN6@midiInCall:
	add	edx, 4
	cmp	edx, OFFSET _midi+16
	jl	SHORT $LL8@midiInCall
$LN7@midiInCall:

; 576  : 			case 0x02:	// Song Position Pointer
; 577  :                 length = 3;
; 578  : 				break;
; 579  : 			case 0x01:	// Time Code
; 580  : 			case 0x03:	// Song Select
; 581  :                 length = 2;
; 582  :                 break;
; 583  :             default:
; 584  :                 length = 1;
; 585  :                 break;
; 586  :             }
; 587  :             break;
; 588  :         default:
; 589  :             length = 1;
; 590  :             break;
; 591  :         }
; 592  : 
; 593  :         for (i = 0; i < 2; i++) {

	mov	edi, 3
	jmp	SHORT $LN4@midiInCall
$LN26@midiInCall:
	mov	edi, 2
	jmp	SHORT $LN4@midiInCall
$LN27@midiInCall:

; 561  :                         }
; 562  :                     }
; 563  :                 }
; 564  :             }
; 565  : 		case 0x0a0:	// Key Pressure
; 566  : 		case 0x0b0:	// Control Change
; 567  : 		case 0x0e0:	// Pitch Wheel
; 568  :             length = 3;
; 569  :             break;
; 570  : 		case 0x0c0:	// Program Change
; 571  : 		case 0x0d0:	// After Touch
; 572  :             length = 2;
; 573  :             break;
; 574  : 		case 0x0f0:	// SYSTEM MESSAGE (other than "EXCLUSIVE")
; 575  : 			switch (buffer[0] & 0x0f) {

	movsx	eax, cl
	and	eax, 15					; 0000000fH
	sub	eax, 1
	je	SHORT $LN26@midiInCall
	sub	eax, 1
	je	SHORT $LN7@midiInCall
	sub	eax, 1
	je	SHORT $LN26@midiInCall
$LN31@midiInCall:

; 576  : 			case 0x02:	// Song Position Pointer
; 577  :                 length = 3;
; 578  : 				break;
; 579  : 			case 0x01:	// Time Code
; 580  : 			case 0x03:	// Song Select
; 581  :                 length = 2;
; 582  :                 break;
; 583  :             default:
; 584  :                 length = 1;
; 585  :                 break;
; 586  :             }
; 587  :             break;
; 588  :         default:
; 589  :             length = 1;
; 590  :             break;
; 591  :         }
; 592  : 
; 593  :         for (i = 0; i < 2; i++) {

	mov	edi, 1
$LN4@midiInCall:
	mov	esi, OFFSET _midi+8
	npad	7
$LL13@midiInCall:

; 594  :             DevInfo* di = midi.in.current[i];

	mov	eax, DWORD PTR [esi]

; 595  :             if (di != NULL && di->id == id && di->archMidi->callback != NULL) {

	test	eax, eax
	je	SHORT $LN11@midiInCall
	cmp	DWORD PTR [eax], ebp
	jne	SHORT $LN11@midiInCall
	mov	eax, DWORD PTR [eax+316]
	mov	ecx, DWORD PTR [eax+4]
	test	ecx, ecx
	je	SHORT $LN11@midiInCall

; 596  :                 di->archMidi->callback(di->archMidi->ref, buffer, length);

	push	edi
	lea	edx, DWORD PTR _buffer$[esp+16]
	push	edx
	push	DWORD PTR [eax+8]
	call	ecx
	add	esp, 12					; 0000000cH
$LN11@midiInCall:

; 576  : 			case 0x02:	// Song Position Pointer
; 577  :                 length = 3;
; 578  : 				break;
; 579  : 			case 0x01:	// Time Code
; 580  : 			case 0x03:	// Song Select
; 581  :                 length = 2;
; 582  :                 break;
; 583  :             default:
; 584  :                 length = 1;
; 585  :                 break;
; 586  :             }
; 587  :             break;
; 588  :         default:
; 589  :             length = 1;
; 590  :             break;
; 591  :         }
; 592  : 
; 593  :         for (i = 0; i < 2; i++) {

	add	esi, 4
	cmp	esi, OFFSET _midi+16
	jl	SHORT $LL13@midiInCall
	pop	ebp
$LN12@midiInCall:
	pop	edi

; 607  :             }
; 608  :         }
; 609  :         break;
; 610  :     }
; 611  : }

	pop	esi
	pop	ebx
	ret	20					; 00000014H
	npad	1
$LN51@midiInCall:
	DD	$LN18@midiInCall
	DD	$LN7@midiInCall
	DD	$LN26@midiInCall
	DD	$LN27@midiInCall
	DD	$LN31@midiInCall
$LN48@midiInCall:
	DB	0
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	0
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	1
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	1
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	2
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	2
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	1
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	3
_midiInCallback@20 ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File c:\program files (x86)\windows kits\10\include\10.0.19041.0\ucrt\stdio.h
;	COMDAT _sprintf
_TEXT	SEGMENT
__Buffer$ = 8						; size = 4
__Format$ = 12						; size = 4
_sprintf PROC						; COMDAT

; 1392 :         int const _Result = __stdio_common_vsprintf(

	lea	eax, DWORD PTR __Format$[esp]
	push	eax
	push	0
	push	DWORD PTR __Format$[esp+4]
	push	-1
	push	DWORD PTR __Buffer$[esp+12]
	call	___local_stdio_printf_options
	mov	ecx, DWORD PTR [eax]
	push	DWORD PTR [eax+4]
	or	ecx, 1
	push	ecx
	call	___stdio_common_vsprintf

; 1393 :             _CRT_INTERNAL_LOCAL_PRINTF_OPTIONS | _CRT_INTERNAL_PRINTF_LEGACY_VSPRINTF_NULL_TERMINATION,
; 1394 :             _Buffer, _BufferCount, _Format, _Locale, _ArgList);
; 1395 : 
; 1396 :         return _Result < 0 ? -1 : _Result;

	or	ecx, -1
	add	esp, 28					; 0000001cH
	test	eax, eax
	cmovs	eax, ecx

; 1772 :         int _Result;
; 1773 :         va_list _ArgList;
; 1774 :         __crt_va_start(_ArgList, _Format);
; 1775 : 
; 1776 :         _Result = _vsprintf_l(_Buffer, _Format, NULL, _ArgList);
; 1777 : 
; 1778 :         __crt_va_end(_ArgList);
; 1779 :         return _Result;
; 1780 :     }

	ret	0
_sprintf ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File c:\program files (x86)\windows kits\10\include\10.0.19041.0\ucrt\stdio.h
;	COMDAT __vsprintf_l
_TEXT	SEGMENT
__Buffer$ = 8						; size = 4
__Format$ = 12						; size = 4
__Locale$ = 16						; size = 4
__ArgList$ = 20						; size = 4
__vsprintf_l PROC					; COMDAT

; 1392 :         int const _Result = __stdio_common_vsprintf(

	push	DWORD PTR __ArgList$[esp-4]
	push	DWORD PTR __Locale$[esp]
	push	DWORD PTR __Format$[esp+4]
	push	-1
	push	DWORD PTR __Buffer$[esp+12]
	call	___local_stdio_printf_options
	mov	ecx, DWORD PTR [eax]
	push	DWORD PTR [eax+4]
	or	ecx, 1
	push	ecx
	call	___stdio_common_vsprintf

; 1393 :             _CRT_INTERNAL_LOCAL_PRINTF_OPTIONS | _CRT_INTERNAL_PRINTF_LEGACY_VSPRINTF_NULL_TERMINATION,
; 1394 :             _Buffer, _BufferCount, _Format, _Locale, _ArgList);
; 1395 : 
; 1396 :         return _Result < 0 ? -1 : _Result;

	or	ecx, -1
	add	esp, 28					; 0000001cH
	test	eax, eax
	cmovs	eax, ecx

; 1459 :         return _vsnprintf_l(_Buffer, (size_t)-1, _Format, _Locale, _ArgList);
; 1460 :     }

	ret	0
__vsprintf_l ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File c:\program files (x86)\windows kits\10\include\10.0.19041.0\ucrt\stdio.h
;	COMDAT __vsnprintf_l
_TEXT	SEGMENT
__Buffer$ = 8						; size = 4
__BufferCount$ = 12					; size = 4
__Format$ = 16						; size = 4
__Locale$ = 20						; size = 4
__ArgList$ = 24						; size = 4
__vsnprintf_l PROC					; COMDAT

; 1392 :         int const _Result = __stdio_common_vsprintf(

	push	DWORD PTR __ArgList$[esp-4]
	push	DWORD PTR __Locale$[esp]
	push	DWORD PTR __Format$[esp+4]
	push	DWORD PTR __BufferCount$[esp+8]
	push	DWORD PTR __Buffer$[esp+12]
	call	___local_stdio_printf_options
	mov	ecx, DWORD PTR [eax]
	push	DWORD PTR [eax+4]
	or	ecx, 1
	push	ecx
	call	___stdio_common_vsprintf

; 1393 :             _CRT_INTERNAL_LOCAL_PRINTF_OPTIONS | _CRT_INTERNAL_PRINTF_LEGACY_VSPRINTF_NULL_TERMINATION,
; 1394 :             _Buffer, _BufferCount, _Format, _Locale, _ArgList);
; 1395 : 
; 1396 :         return _Result < 0 ? -1 : _Result;

	or	ecx, -1
	add	esp, 28					; 0000001cH
	test	eax, eax
	cmovs	eax, ecx

; 1397 :     }

	ret	0
__vsnprintf_l ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File c:\program files (x86)\windows kits\10\include\10.0.19041.0\ucrt\corecrt_stdio_config.h
;	COMDAT ___local_stdio_printf_options
_TEXT	SEGMENT
___local_stdio_printf_options PROC			; COMDAT

; 91   :         static unsigned __int64 _OptionsStorage;
; 92   :         return &_OptionsStorage;

	mov	eax, OFFSET ?_OptionsStorage@?1??__local_stdio_printf_options@@9@9 ; `__local_stdio_printf_options'::`2'::_OptionsStorage

; 93   :     }

	ret	0
___local_stdio_printf_options ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\win32\win32midi.c
;	COMDAT _archMidiOutTransmit
_TEXT	SEGMENT
_header$1 = -68						; size = 64
__$ArrayPad$ = -4					; size = 4
_archMidi$ = 8						; size = 4
_value$ = 12						; size = 1
_archMidiOutTransmit PROC				; COMDAT

; 417  : {

	sub	esp, 68					; 00000044H
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, esp
	mov	DWORD PTR __$ArrayPad$[esp+68], eax
	mov	eax, DWORD PTR _archMidi$[esp+64]
	push	esi

; 418  :     DevInfo* di = archMidi->devInfo;

	mov	esi, DWORD PTR [eax]

; 419  : 
; 420  :     if (di == NULL) {

	test	esi, esi
	je	$LN27@archMidiOu

; 421  :         return;
; 422  :     }
; 423  : 
; 424  :     if (di->buffer.count == 0) {

	cmp	DWORD PTR [esi+1344], 0
	push	ebx
	mov	bl, BYTE PTR _value$[esp+72]
	jne	$LN21@archMidiOu

; 425  :         UInt8 status;
; 426  : 
; 427  :         if ((value & 0x080) != 0x00) {

	test	bl, bl
	jns	SHORT $LN10@archMidiOu

; 428  :             status = value;

	mov	al, bl

; 429  :         } else {

	jmp	SHORT $LN11@archMidiOu
$LN10@archMidiOu:

; 430  :             // running status
; 431  :             status = di->buffer.data[0];

	mov	al, BYTE PTR [esi+1356]

; 432  :             di->buffer.count++;

	mov	DWORD PTR [esi+1344], 1

; 433  :             di->buffer.runningStatus = 1;

	mov	DWORD PTR [esi+1352], 1
$LN11@archMidiOu:

; 434  :         }
; 435  : 
; 436  :         di->buffer.data[1] = 0;
; 437  :         di->buffer.data[2] = 0;
; 438  : 
; 439  : 		switch (status & 0x0f0) {

	movzx	eax, al
	and	eax, 240				; 000000f0H
	mov	WORD PTR [esi+1357], 0
	add	eax, -128				; ffffff80H
	cmp	eax, 112				; 00000070H
	ja	SHORT $LN20@archMidiOu
	movzx	eax, BYTE PTR $LN36@archMidiOu[eax]
	jmp	DWORD PTR $LN41@archMidiOu[eax*4]
$LN12@archMidiOu:

; 440  : 		case 0x090:	// Note On
; 441  :             di->noteOn = 1;

	mov	DWORD PTR [esi+312], 1
$LN13@archMidiOu:

; 457  : 			case 0x02:	// Song Position Pointer
; 458  :                 di->buffer.remain = 3;
; 459  : 				break;
; 460  : 			case 0x01:	// Time Code
; 461  : 			case 0x03:	// Song Select
; 462  :                 di->buffer.remain = 2;
; 463  :                 break;
; 464  :             default:
; 465  :                 di->buffer.remain = 1;
; 466  :                 break;
; 467  :             }
; 468  :             break;
; 469  :         default:
; 470  :             di->buffer.remain = 1;
; 471  :             break;
; 472  :         }
; 473  :         if (di->buffer.runningStatus) {

	mov	DWORD PTR [esi+1348], 3
	mov	eax, 3
	jmp	SHORT $LN2@archMidiOu
$LN14@archMidiOu:
	mov	DWORD PTR [esi+1348], 2
	mov	eax, 2
	jmp	SHORT $LN2@archMidiOu
$LN15@archMidiOu:

; 442  : 		case 0x080:	// Note Off
; 443  : 		case 0x0a0:	// Key Pressure
; 444  : 		case 0x0b0:	// Control Change
; 445  : 		case 0x0e0:	// Pitch Wheel
; 446  :             di->buffer.remain = 3;
; 447  :             break;
; 448  : 		case 0x0c0:	// Program Change
; 449  : 		case 0x0d0:	// After Touch
; 450  :             di->buffer.remain = 2;
; 451  :             break;
; 452  : 		case 0x0f0:	// SYSTEM MESSAGE
; 453  : 			switch (value & 0x0f) {

	movzx	eax, bl
	and	eax, 15					; 0000000fH
	cmp	eax, 3
	ja	SHORT $LN20@archMidiOu
	jmp	DWORD PTR $LN42@archMidiOu[eax*4]
$LN16@archMidiOu:

; 454  :             case 0x00:  // Exclusive
; 455  :                 di->buffer.remain = 0;

	mov	DWORD PTR [esi+1348], 0
	xor	eax, eax

; 456  :                 break;

	jmp	SHORT $LN2@archMidiOu
$LN20@archMidiOu:

; 457  : 			case 0x02:	// Song Position Pointer
; 458  :                 di->buffer.remain = 3;
; 459  : 				break;
; 460  : 			case 0x01:	// Time Code
; 461  : 			case 0x03:	// Song Select
; 462  :                 di->buffer.remain = 2;
; 463  :                 break;
; 464  :             default:
; 465  :                 di->buffer.remain = 1;
; 466  :                 break;
; 467  :             }
; 468  :             break;
; 469  :         default:
; 470  :             di->buffer.remain = 1;
; 471  :             break;
; 472  :         }
; 473  :         if (di->buffer.runningStatus) {

	mov	eax, 1
	mov	DWORD PTR [esi+1348], eax
$LN2@archMidiOu:
	cmp	DWORD PTR [esi+1352], 0
	je	SHORT $LN21@archMidiOu

; 474  :             di->buffer.remain--;

	dec	eax
	mov	DWORD PTR [esi+1348], eax
$LN21@archMidiOu:

; 475  :         }
; 476  :     }
; 477  : 
; 478  :     di->buffer.data[di->buffer.count] = value;

	mov	eax, DWORD PTR [esi+1344]
	mov	BYTE PTR [eax+esi+1356], bl

; 479  : 
; 480  :     if (di->buffer.count < MAX_MIDI_SYSMES_LENGTH) {

	mov	ecx, DWORD PTR [esi+1344]
	cmp	ecx, 4096				; 00001000H
	jge	SHORT $LN22@archMidiOu

; 481  :         di->buffer.count++;

	inc	ecx
	mov	DWORD PTR [esi+1344], ecx
$LN22@archMidiOu:

; 482  :     }
; 483  :     di->buffer.remain--;

	add	DWORD PTR [esi+1348], -1
	mov	eax, DWORD PTR [esi+1348]

; 484  : 
; 485  :     // End of short message
; 486  :     if (di->buffer.remain == 0) {

	jne	$LN23@archMidiOu

; 487  :         DWORD msg = (di->buffer.data[0] <<  0) | (di->buffer.data[1] <<  8) | (di->buffer.data[2] << 16);

	movzx	edx, BYTE PTR [esi+1358]
	movzx	eax, BYTE PTR [esi+1357]
	mov	cl, BYTE PTR [esi+1356]
	shl	edx, 8
	or	edx, eax
	movzx	eax, cl
	shl	edx, 8

; 488  : 
; 489  :         if ((di->buffer.data[0] & 0xf0) == 0xc0) {

	and	cl, 240					; 000000f0H
	or	edx, eax
	cmp	cl, 192					; 000000c0H
	jne	SHORT $LN25@archMidiOu

; 490  :             midi.out.history.data[midi.out.history.head] = msg;

	mov	eax, DWORD PTR _midi+1068
	mov	DWORD PTR _midi[eax*4+44], edx

; 491  :             midi.out.history.head = (midi.out.history.head + 1) & (HISTORY_SIZE - 1);

	mov	eax, DWORD PTR _midi+1068
	inc	eax

; 492  :             if (midi.out.mt32ToGm) {

	cmp	DWORD PTR _midi+28, 0
	movzx	eax, al
	mov	DWORD PTR _midi+1068, eax
	je	SHORT $LN25@archMidiOu

; 493  :                 msg = (msg & 0xffff80ff) | (MT32toGM[di->buffer.data[1] & 0x7f] << 8);

	movzx	eax, BYTE PTR [esi+1357]
	and	edx, -32513				; ffff80ffH
	and	eax, 127				; 0000007fH
	movzx	eax, BYTE PTR _MT32toGM[eax]
	shl	eax, 8
	or	edx, eax
$LN25@archMidiOu:

; 494  :             }
; 495  :         }
; 496  :         if (di->buffer.runningStatus) {

	cmp	DWORD PTR [esi+1352], 0
	je	SHORT $LN26@archMidiOu

; 497  :             // omit status byte
; 498  :             msg >>= 8;

	shr	edx, 8

; 499  :             di->buffer.runningStatus = 0;

	mov	DWORD PTR [esi+1352], 0
$LN26@archMidiOu:

; 500  :         }
; 501  :         midiOutShortMsg((HMIDIOUT)di->handle, msg);

	push	edx
	push	DWORD PTR [esi+36]
	call	DWORD PTR __imp__midiOutShortMsg@8

; 502  :         di->buffer.count = 0;

	mov	eax, DWORD PTR [esi+1348]
	xor	ecx, ecx
	mov	DWORD PTR [esi+1344], 0
$LN23@archMidiOu:

; 503  :     }
; 504  : 
; 505  :     // End of long message
; 506  :     if (di->buffer.remain < 0 && value == 0xf7) {

	test	eax, eax
	jns	$LN38@archMidiOu
	cmp	bl, 247					; 000000f7H
	jne	$LN38@archMidiOu

; 507  :         // Only send message if data was not truncated
; 508  :         if (di->buffer.count < MAX_MIDI_SYSMES_LENGTH) {

	cmp	ecx, 4096				; 00001000H
	jge	SHORT $LN30@archMidiOu

; 509  :             MIDIHDR header;
; 510  :             
; 511  : 	        header.lpData         = di->buffer.data;

	lea	eax, DWORD PTR [esi+1356]

; 512  : 	        header.dwBufferLength = di->buffer.count;

	mov	DWORD PTR _header$1[esp+80], ecx
	mov	DWORD PTR _header$1[esp+76], eax

; 513  : 	        header.dwFlags        = 0;
; 514  : 
; 515  :             if (midiOutPrepareHeader((HMIDIOUT)di->handle, &header, sizeof(header)) == MMSYSERR_NOERROR) {

	lea	eax, DWORD PTR _header$1[esp+76]
	push	64					; 00000040H
	push	eax
	push	DWORD PTR [esi+36]
	mov	DWORD PTR _header$1[esp+104], 0
	call	DWORD PTR __imp__midiOutPrepareHeader@12
	test	eax, eax
	jne	SHORT $LN30@archMidiOu

; 516  :                 int cnt = 10;

	push	edi
	lea	edi, DWORD PTR [eax+10]

; 517  :         	    if (midiOutLongMsg((HMIDIOUT)di->handle, &header, sizeof(header)) == MMSYSERR_NOERROR) {

	push	64					; 00000040H
	lea	eax, DWORD PTR _header$1[esp+84]
	push	eax
	push	DWORD PTR [esi+36]
	call	DWORD PTR __imp__midiOutLongMsg@12
	test	eax, eax
	jne	SHORT $LN39@archMidiOu

; 518  : 
; 519  : 	                while (!(header.dwFlags & MHDR_DONE) && --cnt) {

	test	BYTE PTR _header$1[esp+96], 1
	jne	SHORT $LN37@archMidiOu
	mov	ebx, DWORD PTR __imp__Sleep@4
$LL6@archMidiOu:
	sub	edi, 1
	je	SHORT $LN37@archMidiOu

; 520  : 		                Sleep(1);

	push	1
	call	ebx
	test	BYTE PTR _header$1[esp+96], 1
	je	SHORT $LL6@archMidiOu
$LN37@archMidiOu:

; 521  : 	                }
; 522  :                     midiOutUnprepareHeader((HMIDIOUT)di->handle, &header, sizeof(header));

	push	64					; 00000040H
	lea	eax, DWORD PTR _header$1[esp+84]
	push	eax
	push	DWORD PTR [esi+36]
	call	DWORD PTR __imp__midiOutUnprepareHeader@12
$LN39@archMidiOu:
	pop	edi
$LN30@archMidiOu:

; 523  :                 }
; 524  :             }
; 525  :         }
; 526  :         di->buffer.count = 0;

	mov	DWORD PTR [esi+1344], 0
$LN38@archMidiOu:
	pop	ebx
$LN27@archMidiOu:

; 527  :     }
; 528  : }

	mov	ecx, DWORD PTR __$ArrayPad$[esp+72]
	pop	esi
	xor	ecx, esp
	call	@__security_check_cookie@4
	add	esp, 68					; 00000044H
	ret	0
	npad	2
$LN41@archMidiOu:
	DD	$LN13@archMidiOu
	DD	$LN12@archMidiOu
	DD	$LN14@archMidiOu
	DD	$LN15@archMidiOu
	DD	$LN20@archMidiOu
$LN36@archMidiOu:
	DB	0
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	1
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	0
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	0
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	2
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	2
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	0
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	3
	npad	3
$LN42@archMidiOu:
	DD	$LN16@archMidiOu
	DD	$LN14@archMidiOu
	DD	$LN13@archMidiOu
	DD	$LN14@archMidiOu
_archMidiOutTransmit ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\win32\win32midi.c
;	COMDAT _archMidiOutDestroy
_TEXT	SEGMENT
_archMidi$ = 8						; size = 4
_archMidiOutDestroy PROC				; COMDAT

; 396  : {

	push	esi

; 397  :     if (archMidi->devInfo == NULL) {

	mov	esi, DWORD PTR _archMidi$[esp]
	mov	eax, DWORD PTR [esi]
	test	eax, eax
	je	SHORT $LN5@archMidiOu

; 398  :         free(archMidi);
; 399  :         return;
; 400  :     }
; 401  : 
; 402  :     if (--archMidi->devInfo->refCount > 0) {

	dec	DWORD PTR [eax+308]
	cmp	DWORD PTR [eax+308], 0
	jg	SHORT $LN5@archMidiOu

; 403  :         free(archMidi);
; 404  :         return;
; 405  :     }
; 406  :     
; 407  :     midiOutSetVolume((HMIDIOUT)archMidi->devInfo->handle, archMidi->devInfo->origVolume);

	mov	eax, DWORD PTR [esi]
	push	DWORD PTR [eax+304]
	push	DWORD PTR [eax+36]
	call	DWORD PTR __imp__midiOutSetVolume@8

; 408  :     midiOutClose((HMIDIOUT)archMidi->devInfo->handle);

	mov	eax, DWORD PTR [esi]
	push	DWORD PTR [eax+36]
	call	DWORD PTR __imp__midiOutClose@4

; 409  : 
; 410  :     if (archMidi->devInfo == midi.out.current[0]) midi.out.current[0] = NULL;

	mov	ecx, DWORD PTR [esi]
	cmp	ecx, DWORD PTR _midi+36
	jne	SHORT $LN4@archMidiOu
	mov	DWORD PTR _midi+36, 0
	mov	ecx, DWORD PTR [esi]
$LN4@archMidiOu:

; 411  :     if (archMidi->devInfo == midi.out.current[1]) midi.out.current[1] = NULL;

	mov	eax, DWORD PTR _midi+40
	xor	edx, edx
	cmp	ecx, eax
	cmove	eax, edx
	mov	DWORD PTR _midi+40, eax
$LN5@archMidiOu:

; 412  : 
; 413  :     free(archMidi);
; 414  : }

	push	esi
	call	_free
	add	esp, 4
	pop	esi
	ret	0
_archMidiOutDestroy ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\win32\win32midi.c
;	COMDAT _archMidiOutCreate
_TEXT	SEGMENT
_archMidi$1$ = -4					; size = 4
_device$ = 8						; size = 4
_archMidiOutCreate PROC					; COMDAT

; 351  : {

	push	ecx
	push	ebx
	push	esi

; 352  :     Properties* pProperties = propGetGlobalProperties();

	call	_propGetGlobalProperties

; 353  :     char* propName = device == 0 ? pProperties->sound.MidiOut.name : pProperties->sound.MidiOut.name;
; 354  :     ArchMidi* archMidi = (ArchMidi*)calloc(1, sizeof(ArchMidi));

	push	12					; 0000000cH
	push	1
	lea	esi, DWORD PTR [eax+6304]
	call	_calloc
	add	esp, 8
	mov	ebx, eax

; 355  : 
; 356  :     if (device != 0) {

	cmp	DWORD PTR _device$[esp+8], 0
	mov	DWORD PTR _archMidi$1$[esp+12], ebx
	jne	$LN1@archMidiOu

; 357  :         return archMidi;
; 358  :     }
; 359  : 
; 360  :     if (midi.out.current[device] == NULL) {

	mov	eax, DWORD PTR _midi+36
	test	eax, eax
	jne	$LN25@archMidiOu

; 361  :         int i;
; 362  :         for (i = 0; i < midi.out.count; i++) {

	push	ebp
	mov	ebp, DWORD PTR _midi+20
	push	edi
	xor	edi, edi
	test	ebp, ebp
	jle	$LN11@archMidiOu
	mov	ebx, DWORD PTR _midi+24
	add	ebx, 4
$LL4@archMidiOu:

; 363  :             if (strcmp(midi.out.dev[i].idString, propName) == 0) {

	mov	eax, esi
	mov	ecx, ebx
$LL28@archMidiOu:
	mov	dl, BYTE PTR [ecx]
	cmp	dl, BYTE PTR [eax]
	jne	SHORT $LN29@archMidiOu
	test	dl, dl
	je	SHORT $LN30@archMidiOu
	mov	dl, BYTE PTR [ecx+1]
	cmp	dl, BYTE PTR [eax+1]
	jne	SHORT $LN29@archMidiOu
	add	ecx, 2
	add	eax, 2
	test	dl, dl
	jne	SHORT $LL28@archMidiOu
$LN30@archMidiOu:
	xor	eax, eax
	jmp	SHORT $LN31@archMidiOu
$LN29@archMidiOu:
	sbb	eax, eax
	or	eax, 1
$LN31@archMidiOu:
	test	eax, eax
	je	SHORT $LN19@archMidiOu

; 361  :         int i;
; 362  :         for (i = 0; i < midi.out.count; i++) {

	inc	edi
	add	ebx, 5456				; 00001550H
	cmp	edi, ebp
	jl	SHORT $LL4@archMidiOu

; 363  :             if (strcmp(midi.out.dev[i].idString, propName) == 0) {

	jmp	SHORT $LN26@archMidiOu
$LN19@archMidiOu:

; 364  : 	            if (midiOutOpen((HMIDIOUT*)&midi.out.dev[i].handle, midi.out.dev[i].id, 0, 0 ,0) == MMSYSERR_NOERROR) {

	mov	eax, DWORD PTR _midi+24
	imul	edi, edi, 5456
	push	0
	push	0
	push	0
	push	DWORD PTR [edi+eax]
	add	eax, 36					; 00000024H
	add	eax, edi
	push	eax
	call	DWORD PTR __imp__midiOutOpen@20
	test	eax, eax
	jne	SHORT $LN32@archMidiOu

; 365  : 		            midi.out.current[device] = &midi.out.dev[i];

	mov	ecx, DWORD PTR _midi+24
	add	ecx, edi
	mov	DWORD PTR _midi+36, ecx
	jmp	SHORT $LN8@archMidiOu
$LN32@archMidiOu:

; 364  : 	            if (midiOutOpen((HMIDIOUT*)&midi.out.dev[i].handle, midi.out.dev[i].id, 0, 0 ,0) == MMSYSERR_NOERROR) {

	mov	ecx, DWORD PTR _midi+36
$LN8@archMidiOu:

; 366  : 	            }
; 367  :                 break;
; 368  :             }
; 369  :         }
; 370  :         if (midi.out.current[device] == NULL && midi.out.count > 0) {

	test	ecx, ecx
	jne	SHORT $LN27@archMidiOu
	mov	ebp, DWORD PTR _midi+20
$LN26@archMidiOu:
	test	ebp, ebp
	jle	SHORT $LN34@archMidiOu

; 371  : 	        if (midiOutOpen((HMIDIOUT*)&midi.out.dev[0].handle, midi.out.dev[0].id, 0, 0 ,0) == MMSYSERR_NOERROR) {

	mov	eax, DWORD PTR _midi+24
	push	0
	push	0
	push	0
	push	DWORD PTR [eax]
	add	eax, 36					; 00000024H
	push	eax
	call	DWORD PTR __imp__midiOutOpen@20
	mov	ecx, DWORD PTR _midi+36
	test	eax, eax
	mov	eax, DWORD PTR _midi+24
	cmove	ecx, eax
	mov	DWORD PTR _midi+36, ecx

; 372  : 		        midi.out.current[device] = &midi.out.dev[0];
; 373  : 	        }
; 374  :             strcpy(propName, midi.out.dev[0].idString);

	lea	ecx, DWORD PTR [eax+4]
$LL16@archMidiOu:
	mov	al, BYTE PTR [ecx]
	lea	ecx, DWORD PTR [ecx+1]
	mov	BYTE PTR [esi], al
	lea	esi, DWORD PTR [esi+1]
	test	al, al
	jne	SHORT $LL16@archMidiOu

; 375  :         }
; 376  : 
; 377  :         if (midi.out.current[device] != NULL) {

	mov	ecx, DWORD PTR _midi+36
	test	ecx, ecx
	je	SHORT $LN34@archMidiOu
$LN27@archMidiOu:

; 378  :             midiOutGetVolume((HMIDIOUT)midi.out.current[device]->handle, &midi.out.current[device]->origVolume);

	lea	eax, DWORD PTR [ecx+304]
	push	eax
	push	DWORD PTR [ecx+36]
	call	DWORD PTR __imp__midiOutGetVolume@8
$LN34@archMidiOu:

; 379  :         }
; 380  :         archMidiEnable(midi.enabled);

	mov	ebx, DWORD PTR _archMidi$1$[esp+20]
$LN11@archMidiOu:
	push	DWORD PTR _midi+1072
	call	_archMidiEnable

; 381  : 
; 382  :         // Clear history
; 383  :         memset(midi.out.history.data, 0, sizeof(midi.out.history.data));

	push	1024					; 00000400H
	push	0
	push	OFFSET _midi+44
	call	_memset

; 384  :     }
; 385  : 
; 386  :     if (midi.out.current[device] != NULL) {

	mov	eax, DWORD PTR _midi+36
	add	esp, 16					; 00000010H
	pop	edi
	pop	ebp
	test	eax, eax
	je	SHORT $LN12@archMidiOu
$LN25@archMidiOu:

; 387  :         midi.out.current[device]->refCount++;

	inc	DWORD PTR [eax+308]
	mov	eax, DWORD PTR _midi+36
$LN12@archMidiOu:

; 388  :     }
; 389  : 
; 390  :     archMidi->devInfo = midi.out.current[device];

	mov	DWORD PTR [ebx], eax

; 391  : 
; 392  :     return archMidi;

	mov	eax, ebx
$LN1@archMidiOu:

; 393  : }

	pop	esi
	pop	ebx
	pop	ecx
	ret	0
_archMidiOutCreate ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\win32\win32midi.c
;	COMDAT _archMidiInGetNoteOn
_TEXT	SEGMENT
_archMidi$ = 8						; size = 4
_note$ = 12						; size = 4
_archMidiInGetNoteOn PROC				; COMDAT

; 693  :     if (archMidi->devInfo == NULL) {

	mov	eax, DWORD PTR _archMidi$[esp-4]
	mov	ecx, DWORD PTR [eax]
	test	ecx, ecx
	je	SHORT $LN5@archMidiIn

; 694  :         return 0;
; 695  :     }
; 696  :     if (note >= 256) {

	mov	eax, DWORD PTR _note$[esp-4]
	cmp	eax, 256				; 00000100H
	jge	SHORT $LN5@archMidiIn

; 698  :     }
; 699  :     return archMidi->devInfo->notes[note];

	mov	eax, DWORD PTR [ecx+eax*4+320]

; 700  : }

	ret	0
$LN5@archMidiIn:

; 697  :         return 0;

	xor	eax, eax

; 700  : }

	ret	0
_archMidiInGetNoteOn ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\win32\win32midi.c
;	COMDAT _archMidiInDestroy
_TEXT	SEGMENT
_archMidi$ = 8						; size = 4
_archMidiInDestroy PROC					; COMDAT

; 666  : {

	push	esi

; 667  :     if (archMidi->devInfo == NULL) {

	mov	esi, DWORD PTR _archMidi$[esp]
	mov	eax, DWORD PTR [esi]
	test	eax, eax
	je	SHORT $LN6@archMidiIn

; 668  :         free(archMidi);
; 669  :         return;
; 670  :     }
; 671  : 
; 672  :     if (--archMidi->devInfo->refCount > 0) {

	dec	DWORD PTR [eax+308]
	cmp	DWORD PTR [eax+308], 0
	jg	SHORT $LN6@archMidiIn

; 673  :         free(archMidi);
; 674  :         return;
; 675  :     }
; 676  : 
; 677  :     if (archMidi->devInfo->recording) {

	mov	eax, DWORD PTR [esi]
	cmp	DWORD PTR [eax+300], 0
	je	SHORT $LN4@archMidiIn

; 678  :         midiInStop((HMIDIIN)archMidi->devInfo->handle);

	push	DWORD PTR [eax+36]
	call	DWORD PTR __imp__midiInStop@4

; 679  :         archMidi->devInfo->recording = 0;

	mov	eax, DWORD PTR [esi]
	mov	DWORD PTR [eax+300], 0
	mov	eax, DWORD PTR [esi]
$LN4@archMidiIn:

; 680  :     }
; 681  :     
; 682  :     midiInClose((HMIDIIN)archMidi->devInfo->handle);

	push	DWORD PTR [eax+36]
	call	DWORD PTR __imp__midiInClose@4

; 683  : 
; 684  :     if (archMidi->devInfo == midi.in.current[0]) midi.in.current[0] = NULL;

	mov	ecx, DWORD PTR [esi]
	cmp	ecx, DWORD PTR _midi+8
	jne	SHORT $LN5@archMidiIn
	mov	DWORD PTR _midi+8, 0
	mov	ecx, DWORD PTR [esi]
$LN5@archMidiIn:

; 685  :     if (archMidi->devInfo == midi.in.current[1]) midi.in.current[1] = NULL;

	mov	eax, DWORD PTR _midi+12
	xor	edx, edx
	cmp	ecx, eax
	cmove	eax, edx
	mov	DWORD PTR _midi+12, eax
$LN6@archMidiIn:

; 686  : 
; 687  :     free(archMidi);
; 688  : }

	push	esi
	call	_free
	add	esp, 4
	pop	esi
	ret	0
_archMidiInDestroy ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\win32\win32midi.c
;	COMDAT _archMidiInCreate
_TEXT	SEGMENT
_archMidi$1$ = -4					; size = 4
_device$ = 8						; size = 4
_cb$ = 12						; size = 4
_ref$ = 16						; size = 4
_archMidiInCreate PROC					; COMDAT

; 614  : {

	push	ecx
	push	ebp
	push	esi

; 615  :     Properties* pProperties = propGetGlobalProperties();

	call	_propGetGlobalProperties

; 616  :     char* propName = device == 1 ? pProperties->sound.YkIn.name : pProperties->sound.MidiIn.name;                        
; 617  :     ArchMidi* archMidi = (ArchMidi*)calloc(1, sizeof(ArchMidi));

	mov	ebp, DWORD PTR _device$[esp+8]
	mov	edx, 5276				; 0000149cH
	cmp	ebp, 1
	mov	esi, 4244				; 00001094H
	push	12					; 0000000cH
	cmovne	esi, edx
	push	1
	add	esi, eax
	call	_calloc

; 618  : 
; 619  :     archMidi->callback = cb;

	mov	ecx, DWORD PTR _cb$[esp+16]
	mov	edx, eax
	add	esp, 8
	mov	DWORD PTR _archMidi$1$[esp+12], edx
	mov	DWORD PTR [edx+4], ecx

; 620  :     archMidi->ref      = ref;

	mov	ecx, DWORD PTR _ref$[esp+8]
	mov	DWORD PTR [edx+8], ecx

; 621  : 
; 622  :     if (device != 0 && device != 1) {

	test	ebp, ebp
	je	SHORT $LN5@archMidiIn
	cmp	ebp, 1
	jne	$LN1@archMidiIn
$LN5@archMidiIn:

; 623  :         return archMidi;
; 624  :     }
; 625  : 
; 626  :     if (midi.in.current[device] == NULL) {

	cmp	DWORD PTR _midi[ebp*4+8], 0
	jne	$LN6@archMidiIn

; 627  :         int i;
; 628  :         for (i = 0; i < midi.in.count; i++) {

	mov	eax, DWORD PTR _midi
	push	ebx
	mov	ebx, DWORD PTR _midi+4
	push	edi
	xor	edi, edi
	test	eax, eax
	jle	$LN8@archMidiIn
	lea	ebp, DWORD PTR [ebx+4]
$LL4@archMidiIn:

; 629  :             if (strcmp(midi.in.dev[i].idString, propName) == 0) {

	mov	ecx, esi
	mov	eax, ebp
$LL27@archMidiIn:
	mov	dl, BYTE PTR [eax]
	cmp	dl, BYTE PTR [ecx]
	jne	SHORT $LN28@archMidiIn
	test	dl, dl
	je	SHORT $LN29@archMidiIn
	mov	dl, BYTE PTR [eax+1]
	cmp	dl, BYTE PTR [ecx+1]
	jne	SHORT $LN28@archMidiIn
	add	eax, 2
	add	ecx, 2
	test	dl, dl
	jne	SHORT $LL27@archMidiIn
$LN29@archMidiIn:
	xor	eax, eax
	jmp	SHORT $LN30@archMidiIn
$LN28@archMidiIn:
	sbb	eax, eax
	or	eax, 1
$LN30@archMidiIn:
	test	eax, eax
	je	SHORT $LN21@archMidiIn

; 627  :         int i;
; 628  :         for (i = 0; i < midi.in.count; i++) {

	mov	eax, DWORD PTR _midi
	inc	edi
	add	ebp, 5456				; 00001550H
	cmp	edi, eax
	jl	SHORT $LL4@archMidiIn

; 629  :             if (strcmp(midi.in.dev[i].idString, propName) == 0) {

	mov	ebp, DWORD PTR _device$[esp+16]
	jmp	SHORT $LN8@archMidiIn
$LN21@archMidiIn:

; 630  :                 if (midi.in.dev[i].refCount > 0 ||

	imul	edi, edi, 5456
	cmp	DWORD PTR [edi+ebx+308], 0
	jg	SHORT $LN9@archMidiIn
	mov	eax, DWORD PTR [edi+ebx]
	push	196608					; 00030000H
	push	eax
	push	OFFSET _midiInCallback@20
	push	eax
	lea	eax, DWORD PTR [ebx+36]
	add	eax, edi
	push	eax
	call	DWORD PTR __imp__midiInOpen@20
	mov	ebx, DWORD PTR _midi+4
	test	eax, eax
	je	SHORT $LN9@archMidiIn
	mov	ebp, DWORD PTR _device$[esp+16]
	jmp	SHORT $LN33@archMidiIn
$LN9@archMidiIn:

; 631  :                     midiInOpen((HMIDIIN*)&midi.in.dev[i].handle, midi.in.dev[i].id, 
; 632  :                                (DWORD_PTR)midiInCallback, midi.in.dev[i].id, CALLBACK_FUNCTION) == MMSYSERR_NOERROR) 
; 633  :                 {
; 634  : 		            midi.in.current[device] = &midi.in.dev[i];

	mov	ebp, DWORD PTR _device$[esp+16]
	lea	eax, DWORD PTR [edi+ebx]
	mov	DWORD PTR _midi[ebp*4+8], eax
	mov	ebx, DWORD PTR _midi+4
$LN33@archMidiIn:

; 635  : 	            }
; 636  :                 break;
; 637  :             }
; 638  :         }
; 639  :         if (midi.in.current[device] == NULL && midi.in.count > 0) {

	mov	eax, DWORD PTR _midi
$LN8@archMidiIn:
	cmp	DWORD PTR _midi[ebp*4+8], 0
	jne	SHORT $LN10@archMidiIn
	test	eax, eax
	jle	SHORT $LN10@archMidiIn

; 640  :             if (midi.in.dev[0].refCount > 0 ||

	cmp	DWORD PTR [ebx+308], 0
	jg	SHORT $LN12@archMidiIn
	mov	eax, DWORD PTR [ebx]
	push	196608					; 00030000H
	push	eax
	push	OFFSET _midiInCallback@20
	push	eax
	lea	eax, DWORD PTR [ebx+36]
	push	eax
	call	DWORD PTR __imp__midiInOpen@20
	test	eax, eax
	jne	SHORT $LN11@archMidiIn
	mov	ebx, DWORD PTR _midi+4
$LN12@archMidiIn:

; 641  : 	            midiInOpen((HMIDIIN*)&midi.in.dev[0].handle, midi.in.dev[0].id,
; 642  :                            (DWORD_PTR)midiInCallback, midi.in.dev[0].id, CALLBACK_FUNCTION) == MMSYSERR_NOERROR) 
; 643  :             {
; 644  : 		        midi.in.current[device] = &midi.in.dev[0];

	mov	DWORD PTR _midi[ebp*4+8], ebx
$LN11@archMidiIn:

; 645  : 	        }
; 646  :             strcpy(propName, midi.in.dev[0].idString);

	mov	ecx, DWORD PTR _midi+4
	add	ecx, 4
$LL18@archMidiIn:
	mov	al, BYTE PTR [ecx]
	lea	ecx, DWORD PTR [ecx+1]
	mov	BYTE PTR [esi], al
	lea	esi, DWORD PTR [esi+1]
	test	al, al
	jne	SHORT $LL18@archMidiIn
$LN10@archMidiIn:

; 647  :         }
; 648  : 
; 649  :         if (midi.in.current[device] != NULL) {

	mov	eax, DWORD PTR _midi[ebp*4+8]
	pop	edi
	pop	ebx
	test	eax, eax
	je	SHORT $LN13@archMidiIn

; 650  :             memset(midi.in.current[device]->notes, 0, sizeof(midi.in.current[device]->notes));

	push	1024					; 00000400H
	add	eax, 320				; 00000140H
	push	0
	push	eax
	call	_memset
	add	esp, 12					; 0000000cH
$LN13@archMidiIn:

; 651  :         }
; 652  :         archMidiEnable(midi.enabled);

	push	DWORD PTR _midi+1072
	call	_archMidiEnable
	mov	edx, DWORD PTR _archMidi$1$[esp+16]
	add	esp, 4
$LN6@archMidiIn:

; 653  :     }
; 654  : 
; 655  :     if (midi.in.current[device] != NULL) {

	mov	eax, DWORD PTR _midi[ebp*4+8]
	test	eax, eax
	je	SHORT $LN14@archMidiIn

; 656  :         midi.in.current[device]->refCount++;

	inc	DWORD PTR [eax+308]

; 657  :         midi.in.current[device]->archMidi = archMidi;

	mov	eax, DWORD PTR _midi[ebp*4+8]
	mov	DWORD PTR [eax+316], edx
	mov	eax, DWORD PTR _midi[ebp*4+8]
$LN14@archMidiIn:

; 658  :     }
; 659  : 
; 660  :     archMidi->devInfo = midi.in.current[device];

	mov	DWORD PTR [edx], eax

; 661  : 
; 662  :     return archMidi;

	mov	eax, edx
$LN1@archMidiIn:

; 663  : }

	pop	esi
	pop	ebp
	pop	ecx
	ret	0
_archMidiInCreate ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\win32\win32midi.c
;	COMDAT _archMidiSaveState
_TEXT	SEGMENT
_buf$ = -100						; size = 64
_buf$1 = -36						; size = 32
__$ArrayPad$ = -4					; size = 4
_archMidiSaveState PROC					; COMDAT

; 314  : {

	sub	esp, 100				; 00000064H
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, esp
	mov	DWORD PTR __$ArrayPad$[esp+100], eax
	push	ebx
	push	esi
	push	edi

; 315  :     SaveState* state = saveStateOpenForWrite("ArchMidi");

	push	OFFSET ??_C@_08HNDPCGNE@ArchMidi@
	call	_saveStateOpenForWrite
	add	esp, 4
	mov	edi, eax
	xor	esi, esi
$LL4@archMidiSa:

; 316  :     char buf[64];
; 317  :     int i;
; 318  : 
; 319  :     // Set history
; 320  :     for (i = 0; i < HISTORY_SIZE; i++) {
; 321  :         char buf[32];
; 322  :         sprintf(buf, "history_%d", i);

	push	esi
	lea	eax, DWORD PTR _buf$1[esp+116]
	push	OFFSET ??_C@_0L@NBAGFBIK@history_?$CFd@
	push	eax
	call	_sprintf

; 323  :         saveStateSet(state, buf, midi.out.history.data[i]);

	push	DWORD PTR _midi[esi*4+44]
	lea	eax, DWORD PTR _buf$1[esp+128]
	push	eax
	push	edi
	call	_saveStateSet
	inc	esi
	add	esp, 24					; 00000018H
	cmp	esi, 256				; 00000100H
	jl	SHORT $LL4@archMidiSa

; 324  :     }
; 325  :     saveStateSet(state, "history_head", midi.out.history.head);

	push	DWORD PTR _midi+1068
	push	OFFSET ??_C@_0N@INFLDEIM@history_head@
	push	edi
	call	_saveStateSet
	add	esp, 12					; 0000000cH

; 326  : 
; 327  :     for (i = 0; i < 4; i++) {

	xor	esi, esi
$LL7@archMidiSa:

; 328  :         DevInfo* di = NULL;
; 329  :         switch (i) {

	cmp	esi, 3
	ja	$LN5@archMidiSa
	jmp	DWORD PTR $LN25@archMidiSa[esi*4]
$LN10@archMidiSa:

; 330  :         case 0: di = midi.out.current[0]; break;

	mov	ebx, DWORD PTR _midi+36
	jmp	SHORT $LN8@archMidiSa
$LN11@archMidiSa:

; 331  :         case 1: di = midi.out.current[1]; break;

	mov	ebx, DWORD PTR _midi+40
	jmp	SHORT $LN8@archMidiSa
$LN12@archMidiSa:

; 332  :         case 2: di = midi.in.current[0]; break;

	mov	ebx, DWORD PTR _midi+8
	jmp	SHORT $LN8@archMidiSa
$LN13@archMidiSa:

; 333  :         case 3: di = midi.in.current[1]; break;

	mov	ebx, DWORD PTR _midi+12
$LN8@archMidiSa:

; 334  :         }
; 335  :         if (di != NULL) {

	test	ebx, ebx
	je	SHORT $LN5@archMidiSa

; 336  :             sprintf(buf, "buffer_%d_count", i);

	push	esi
	lea	eax, DWORD PTR _buf$[esp+116]
	push	OFFSET ??_C@_0BA@JFHEPDHH@buffer_?$CFd_count@
	push	eax
	call	_sprintf

; 337  :             saveStateSet(state, buf, di->buffer.count);

	push	DWORD PTR [ebx+1344]
	lea	eax, DWORD PTR _buf$[esp+128]
	push	eax
	push	edi
	call	_saveStateSet

; 338  :             sprintf(buf, "buffer_%d_remain", i);

	push	esi
	lea	eax, DWORD PTR _buf$[esp+140]
	push	OFFSET ??_C@_0BB@EJLFJOGP@buffer_?$CFd_remain@
	push	eax
	call	_sprintf

; 339  :             saveStateSet(state, buf, di->buffer.remain);

	push	DWORD PTR [ebx+1348]
	lea	eax, DWORD PTR _buf$[esp+152]
	push	eax
	push	edi
	call	_saveStateSet

; 340  :             // no need to save di->buffer.runningStatus
; 341  :             // (set 0 at archMidiLoadState())
; 342  :             sprintf(buf, "buffer_%d_data", i);

	push	esi
	lea	eax, DWORD PTR _buf$[esp+164]
	push	OFFSET ??_C@_0P@EIHEJNDG@buffer_?$CFd_data@
	push	eax
	call	_sprintf

; 343  :             saveStateSetBuffer(state, buf, di->buffer.data, sizeof(di->buffer.data));

	push	4097					; 00001001H
	lea	eax, DWORD PTR [ebx+1356]
	push	eax
	lea	eax, DWORD PTR _buf$[esp+180]
	push	eax
	push	edi
	call	_saveStateSetBuffer
	add	esp, 76					; 0000004cH
$LN5@archMidiSa:

; 326  : 
; 327  :     for (i = 0; i < 4; i++) {

	inc	esi
	cmp	esi, 4
	jl	$LL7@archMidiSa

; 344  :         }
; 345  :     }
; 346  :     
; 347  :     saveStateClose(state);

	push	edi
	call	_saveStateClose

; 348  : }

	mov	ecx, DWORD PTR __$ArrayPad$[esp+116]
	add	esp, 4
	pop	edi
	pop	esi
	pop	ebx
	xor	ecx, esp
	call	@__security_check_cookie@4
	add	esp, 100				; 00000064H
	ret	0
	npad	3
$LN25@archMidiSa:
	DD	$LN10@archMidiSa
	DD	$LN11@archMidiSa
	DD	$LN12@archMidiSa
	DD	$LN13@archMidiSa
_archMidiSaveState ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\win32\win32midi.c
;	COMDAT _archMidiLoadState
_TEXT	SEGMENT
_buf$ = -100						; size = 64
_buf$1 = -36						; size = 32
__$ArrayPad$ = -4					; size = 4
_archMidiLoadState PROC					; COMDAT

; 274  : {

	sub	esp, 100				; 00000064H
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, esp
	mov	DWORD PTR __$ArrayPad$[esp+100], eax
	push	ebx
	push	esi
	push	edi

; 275  :     SaveState* state = saveStateOpenForRead("ArchMidi");

	push	OFFSET ??_C@_08HNDPCGNE@ArchMidi@
	call	_saveStateOpenForRead
	add	esp, 4
	mov	edi, eax
	xor	esi, esi
$LL4@archMidiLo:

; 276  :     char buf[64];
; 277  :     int i;
; 278  : 
; 279  :     // Get history
; 280  :     for (i = 0; i < HISTORY_SIZE; i++) {
; 281  :         char buf[32];
; 282  :         sprintf(buf, "history_%d", i);

	push	esi
	lea	eax, DWORD PTR _buf$1[esp+116]
	push	OFFSET ??_C@_0L@NBAGFBIK@history_?$CFd@
	push	eax
	call	_sprintf

; 283  :         midi.out.history.data[i] = saveStateGet(state, buf, 0);

	push	0
	lea	eax, DWORD PTR _buf$1[esp+128]
	push	eax
	push	edi
	call	_saveStateGet
	mov	DWORD PTR _midi[esi*4+44], eax
	add	esp, 24					; 00000018H
	inc	esi
	cmp	esi, 256				; 00000100H
	jl	SHORT $LL4@archMidiLo

; 284  :     }
; 285  :     midi.out.history.head = saveStateGet(state, "history_head", 0);

	push	0
	push	OFFSET ??_C@_0N@INFLDEIM@history_head@
	push	edi
	call	_saveStateGet
	add	esp, 12					; 0000000cH
	mov	DWORD PTR _midi+1068, eax

; 286  : 
; 287  :     for (i = 0; i < 4; i++) {

	xor	esi, esi
	npad	7
$LL7@archMidiLo:

; 288  :         DevInfo* di = NULL;
; 289  :         switch (i) {

	cmp	esi, 3
	ja	$LN5@archMidiLo
	jmp	DWORD PTR $LN37@archMidiLo[esi*4]
$LN10@archMidiLo:

; 290  :         case 0: di = midi.out.current[0]; break;

	mov	ebx, DWORD PTR _midi+36
	jmp	SHORT $LN8@archMidiLo
$LN11@archMidiLo:

; 291  :         case 1: di = midi.out.current[1]; break;

	mov	ebx, DWORD PTR _midi+40
	jmp	SHORT $LN8@archMidiLo
$LN12@archMidiLo:

; 292  :         case 2: di = midi.in.current[0]; break;

	mov	ebx, DWORD PTR _midi+8
	jmp	SHORT $LN8@archMidiLo
$LN13@archMidiLo:

; 293  :         case 3: di = midi.in.current[1]; break;

	mov	ebx, DWORD PTR _midi+12
$LN8@archMidiLo:

; 294  :         }
; 295  :         if (di != NULL) {

	test	ebx, ebx
	je	SHORT $LN5@archMidiLo

; 296  :             sprintf(buf, "buffer_%d_count", i);

	push	esi
	lea	eax, DWORD PTR _buf$[esp+116]
	push	OFFSET ??_C@_0BA@JFHEPDHH@buffer_?$CFd_count@
	push	eax
	call	_sprintf

; 297  :             di->buffer.count = saveStateGet(state, buf, 0);

	push	0
	lea	eax, DWORD PTR _buf$[esp+128]
	push	eax
	push	edi
	call	_saveStateGet

; 298  :             sprintf(buf, "buffer_%d_remain", i);

	push	esi
	mov	DWORD PTR [ebx+1344], eax
	lea	eax, DWORD PTR _buf$[esp+140]
	push	OFFSET ??_C@_0BB@EJLFJOGP@buffer_?$CFd_remain@
	push	eax
	call	_sprintf

; 299  :             di->buffer.remain = saveStateGet(state, buf, 0);

	push	0
	lea	eax, DWORD PTR _buf$[esp+152]
	push	eax
	push	edi
	call	_saveStateGet

; 300  :             // status byte must be resent from di->buffer.data[0]
; 301  :             // even if di->buffer.runningStatus was 1 when state saved.
; 302  :             di->buffer.runningStatus = 0;
; 303  :             sprintf(buf, "buffer_%d_data", i);

	push	esi
	mov	DWORD PTR [ebx+1348], eax
	lea	eax, DWORD PTR _buf$[esp+164]
	push	OFFSET ??_C@_0P@EIHEJNDG@buffer_?$CFd_data@
	push	eax
	mov	DWORD PTR [ebx+1352], 0
	call	_sprintf

; 304  :             saveStateGetBuffer(state, buf, di->buffer.data, sizeof(di->buffer.data));

	push	4097					; 00001001H
	lea	eax, DWORD PTR [ebx+1356]
	push	eax
	lea	eax, DWORD PTR _buf$[esp+180]
	push	eax
	push	edi
	call	_saveStateGetBuffer
	add	esp, 76					; 0000004cH
$LN5@archMidiLo:

; 286  : 
; 287  :     for (i = 0; i < 4; i++) {

	inc	esi
	cmp	esi, 4
	jl	$LL7@archMidiLo

; 305  :         }
; 306  :     }
; 307  :     
; 308  :     saveStateClose(state);

	push	edi
	call	_saveStateClose

; 208  :     if (midi.out.current[0] != NULL) {

	mov	edi, DWORD PTR _midi+36

; 305  :         }
; 306  :     }
; 307  :     
; 308  :     saveStateClose(state);

	add	esp, 4

; 208  :     if (midi.out.current[0] != NULL) {

	test	edi, edi
	je	SHORT $LN18@archMidiLo

; 209  :         DevInfo* di = midi.out.current[0];

	mov	ebx, DWORD PTR __imp__midiOutShortMsg@8
	xor	esi, esi
$LL19@archMidiLo:

; 212  :             UInt32 msg = midi.out.history.data[(i + midi.out.history.head) & (HISTORY_SIZE - 1)];

	mov	eax, DWORD PTR _midi+1068
	add	eax, esi
	movzx	eax, al
	mov	ecx, DWORD PTR _midi[eax*4+44]

; 213  :             if ((msg & 0xf0) == 0xc0) {

	mov	eax, ecx
	and	eax, 240				; 000000f0H
	cmp	al, 192					; 000000c0H
	jne	SHORT $LN17@archMidiLo

; 214  :                 if (midi.out.mt32ToGm) {

	cmp	DWORD PTR _midi+28, 0
	je	SHORT $LN22@archMidiLo

; 215  :                     msg = (msg & 0xffff80ff) | (MT32toGM[di->buffer.data[1] & 0x7f] << 8);

	movzx	eax, BYTE PTR [edi+1357]
	and	ecx, -32513				; ffff80ffH
	and	eax, 127				; 0000007fH
	movzx	eax, BYTE PTR _MT32toGM[eax]
	shl	eax, 8
	or	ecx, eax
$LN22@archMidiLo:

; 216  :                 }
; 217  :                 midiOutShortMsg((HMIDIOUT)di->handle, msg);

	push	ecx
	push	DWORD PTR [edi+36]
	call	ebx
$LN17@archMidiLo:

; 210  :         UInt32 i;
; 211  :         for (i = 0; i < HISTORY_SIZE; i++) {

	inc	esi
	cmp	esi, 256				; 00000100H
	jb	SHORT $LL19@archMidiLo
$LN18@archMidiLo:

; 309  : 
; 310  :     midiEnableMt32ToGmMapping(midi.out.mt32ToGm);
; 311  : }

	mov	ecx, DWORD PTR __$ArrayPad$[esp+112]
	pop	edi
	pop	esi
	pop	ebx
	xor	ecx, esp
	call	@__security_check_cookie@4
	add	esp, 100				; 00000064H
	ret	0
	npad	1
$LN37@archMidiLo:
	DD	$LN10@archMidiLo
	DD	$LN11@archMidiLo
	DD	$LN12@archMidiLo
	DD	$LN13@archMidiLo
_archMidiLoadState ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\win32\win32midi.c
;	COMDAT _archMidiUpdateVolume
_TEXT	SEGMENT
_left$ = 8						; size = 4
_right$ = 12						; size = 4
_archMidiUpdateVolume PROC				; COMDAT

; 269  :     midi.out.volume = MIN(left * 100, 0xffff) | (MIN(right * 100, 0xffff) << 16);

	imul	eax, DWORD PTR _left$[esp-4], 100
	mov	edx, 65535				; 0000ffffH

; 270  :     archMidiEnable(midi.enabled);

	push	DWORD PTR _midi+1072
	mov	ecx, edx
	cmp	eax, edx
	cmovl	ecx, eax
	imul	eax, DWORD PTR _right$[esp], 100
	cmp	eax, edx
	cmovl	edx, eax
	shl	edx, 16					; 00000010H
	or	edx, ecx
	mov	DWORD PTR _midi+32, edx
	call	_archMidiEnable
	pop	ecx

; 271  : }

	ret	0
_archMidiUpdateVolume ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\win32\win32midi.c
;	COMDAT _archMidiGetNoteOn
_TEXT	SEGMENT
_archMidiGetNoteOn PROC					; COMDAT

; 237  :     int noteOn = 0;
; 238  :     if (midi.out.current[0] != NULL) {

	mov	ecx, DWORD PTR _midi+36
	test	ecx, ecx
	je	SHORT $LN4@archMidiGe

; 239  :         noteOn = midi.out.current[0]->noteOn;

	mov	eax, DWORD PTR [ecx+312]

; 240  :         midi.out.current[0]->noteOn = 0;

	mov	DWORD PTR [ecx+312], 0

; 243  : }

	ret	0
$LN4@archMidiGe:

; 241  :     }
; 242  :     return noteOn;

	xor	eax, eax

; 243  : }

	ret	0
_archMidiGetNoteOn ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\win32\win32midi.c
;	COMDAT _archMidiEnable
_TEXT	SEGMENT
_enable$ = 8						; size = 4
_archMidiEnable PROC					; COMDAT

; 247  :     int i;
; 248  : 
; 249  :     midi.enabled = enable;
; 250  :     if (midi.out.current[0] != NULL) {

	mov	ecx, DWORD PTR _midi+36
	push	ebx
	push	ebp
	push	esi
	push	edi
	mov	edi, DWORD PTR _enable$[esp+12]
	mov	DWORD PTR _midi+1072, edi
	test	ecx, ecx
	je	SHORT $LN5@archMidiEn

; 251  :         midiOutSetVolume((HMIDIOUT)midi.out.current[0]->handle, midi.out.volume * midi.enabled);

	mov	eax, DWORD PTR _midi+32
	imul	eax, edi
	push	eax
	push	DWORD PTR [ecx+36]
	call	DWORD PTR __imp__midiOutSetVolume@8
$LN5@archMidiEn:

; 252  :     }
; 253  :     for (i = 0; i < 2; i++) {

	mov	ebx, DWORD PTR __imp__midiInStart@4
	mov	esi, OFFSET _midi+8
	mov	ebp, DWORD PTR __imp__midiInStop@4
	npad	5
$LL4@archMidiEn:

; 254  :         if (midi.in.current[i] != NULL) {

	mov	eax, DWORD PTR [esi]
	test	eax, eax
	je	SHORT $LN2@archMidiEn

; 255  :             if (enable && !midi.in.current[i]->recording) {

	mov	ecx, DWORD PTR [eax+300]
	test	edi, edi
	je	SHORT $LN16@archMidiEn
	test	ecx, ecx
	jne	SHORT $LN2@archMidiEn

; 256  :                 midiInStart((HMIDIIN)midi.in.current[i]->handle);

	push	DWORD PTR [eax+36]
	call	ebx

; 257  :                 midi.in.current[i]->recording = 1;

	mov	eax, DWORD PTR [esi]
	mov	DWORD PTR [eax+300], 1

; 258  :             }

	jmp	SHORT $LN2@archMidiEn
$LN16@archMidiEn:

; 259  :             else if (!enable && midi.in.current[i]->recording) {

	test	ecx, ecx
	je	SHORT $LN2@archMidiEn

; 260  :                 midiInStop((HMIDIIN)midi.in.current[i]->handle);

	push	DWORD PTR [eax+36]
	call	ebp

; 261  :                 midi.in.current[i]->recording = 0;

	mov	eax, DWORD PTR [esi]
	mov	DWORD PTR [eax+300], 0
$LN2@archMidiEn:

; 252  :     }
; 253  :     for (i = 0; i < 2; i++) {

	add	esi, 4
	cmp	esi, OFFSET _midi+16
	jl	SHORT $LL4@archMidiEn

; 262  :             }
; 263  :         }
; 264  :     }
; 265  : }

	pop	edi
	pop	esi
	pop	ebp
	pop	ebx
	ret	0
_archMidiEnable ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\win32\win32midi.c
;	COMDAT _midiOutGetDeviceIdString
_TEXT	SEGMENT
_idx$ = 8						; size = 4
_midiOutGetDeviceIdString PROC				; COMDAT

; 202  :     return midi.out.dev[idx].idString;

	imul	ecx, DWORD PTR _idx$[esp-4], 5456
	mov	eax, DWORD PTR _midi+24
	add	eax, 4
	add	eax, ecx

; 203  : }

	ret	0
_midiOutGetDeviceIdString ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\win32\win32midi.c
;	COMDAT _midiOutGetDeviceName
_TEXT	SEGMENT
_idx$ = 8						; size = 4
_midiOutGetDeviceName PROC				; COMDAT

; 197  :     return midi.out.dev[idx].name;

	imul	ecx, DWORD PTR _idx$[esp-4], 5456
	mov	eax, DWORD PTR _midi+24
	add	eax, 40					; 00000028H
	add	eax, ecx

; 198  : }

	ret	0
_midiOutGetDeviceName ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\win32\win32midi.c
;	COMDAT _midiOutGetDeviceCount
_TEXT	SEGMENT
_midiOutGetDeviceCount PROC				; COMDAT

; 192  :     return midi.out.count;

	mov	eax, DWORD PTR _midi+20

; 193  : }

	ret	0
_midiOutGetDeviceCount ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\win32\win32midi.c
;	COMDAT _midiInGetDeviceIdString
_TEXT	SEGMENT
_idx$ = 8						; size = 4
_midiInGetDeviceIdString PROC				; COMDAT

; 187  :     return midi.in.dev[idx].idString;

	imul	ecx, DWORD PTR _idx$[esp-4], 5456
	mov	eax, DWORD PTR _midi+4
	add	eax, 4
	add	eax, ecx

; 188  : }

	ret	0
_midiInGetDeviceIdString ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\win32\win32midi.c
;	COMDAT _midiInGetDeviceName
_TEXT	SEGMENT
_idx$ = 8						; size = 4
_midiInGetDeviceName PROC				; COMDAT

; 182  :     return midi.in.dev[idx].name;

	imul	ecx, DWORD PTR _idx$[esp-4], 5456
	mov	eax, DWORD PTR _midi+4
	add	eax, 40					; 00000028H
	add	eax, ecx

; 183  : }

	ret	0
_midiInGetDeviceName ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\win32\win32midi.c
;	COMDAT _midiInGetDeviceCount
_TEXT	SEGMENT
_midiInGetDeviceCount PROC				; COMDAT

; 177  :     return midi.in.count;

	mov	eax, DWORD PTR _midi

; 178  : }

	ret	0
_midiInGetDeviceCount ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\win32\win32midi.c
;	COMDAT _midiInSetChannelFilter
_TEXT	SEGMENT
_filter$ = 8						; size = 4
_midiInSetChannelFilter PROC				; COMDAT

; 225  :     int i;
; 226  : 
; 227  :     midi.in.noteFilter = filter;

	mov	eax, DWORD PTR _filter$[esp-4]
	push	esi
	mov	DWORD PTR _midi+16, eax
	mov	esi, OFFSET _midi+8
	npad	1
$LL4@midiInSetC:

; 229  :         if (midi.in.current[i] != NULL) {

	mov	eax, DWORD PTR [esi]
	test	eax, eax
	je	SHORT $LN2@midiInSetC

; 230  :             memset(midi.in.current[i]->notes, 0, sizeof(midi.in.current[i]->notes));

	push	1024					; 00000400H
	add	eax, 320				; 00000140H
	push	0
	push	eax
	call	_memset
	add	esp, 12					; 0000000cH
$LN2@midiInSetC:

; 228  :     for (i = 0; i < 2; i++) {

	add	esi, 4
	cmp	esi, OFFSET _midi+16
	jl	SHORT $LL4@midiInSetC

; 231  :         }
; 232  :     }
; 233  : 
; 234  : }

	pop	esi
	ret	0
_midiInSetChannelFilter ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\win32\win32midi.c
;	COMDAT _midiEnableMt32ToGmMapping
_TEXT	SEGMENT
_enable$ = 8						; size = 4
_midiEnableMt32ToGmMapping PROC				; COMDAT

; 207  :     midi.out.mt32ToGm = enable;

	mov	edx, DWORD PTR _enable$[esp-4]
	push	edi

; 208  :     if (midi.out.current[0] != NULL) {

	mov	edi, DWORD PTR _midi+36
	mov	DWORD PTR _midi+28, edx
	test	edi, edi
	je	SHORT $LN3@midiEnable

; 209  :         DevInfo* di = midi.out.current[0];

	push	ebx
	mov	ebx, DWORD PTR __imp__midiOutShortMsg@8
	push	esi
	xor	esi, esi
	npad	1
$LL4@midiEnable:

; 212  :             UInt32 msg = midi.out.history.data[(i + midi.out.history.head) & (HISTORY_SIZE - 1)];

	mov	eax, DWORD PTR _midi+1068
	add	eax, esi
	movzx	eax, al
	mov	eax, DWORD PTR _midi[eax*4+44]

; 213  :             if ((msg & 0xf0) == 0xc0) {

	mov	ecx, eax
	and	ecx, 240				; 000000f0H
	cmp	cl, 192					; 000000c0H
	jne	SHORT $LN2@midiEnable

; 214  :                 if (midi.out.mt32ToGm) {

	test	edx, edx
	je	SHORT $LN7@midiEnable

; 215  :                     msg = (msg & 0xffff80ff) | (MT32toGM[di->buffer.data[1] & 0x7f] << 8);

	movzx	ecx, BYTE PTR [edi+1357]
	and	eax, -32513				; ffff80ffH
	and	ecx, 127				; 0000007fH
	movzx	ecx, BYTE PTR _MT32toGM[ecx]
	shl	ecx, 8
	or	eax, ecx
$LN7@midiEnable:

; 216  :                 }
; 217  :                 midiOutShortMsg((HMIDIOUT)di->handle, msg);

	push	eax
	push	DWORD PTR [edi+36]
	call	ebx
	mov	edx, DWORD PTR _midi+28
$LN2@midiEnable:

; 210  :         UInt32 i;
; 211  :         for (i = 0; i < HISTORY_SIZE; i++) {

	inc	esi
	cmp	esi, 256				; 00000100H
	jb	SHORT $LL4@midiEnable
	pop	esi
	pop	ebx
$LN3@midiEnable:
	pop	edi

; 218  :             }
; 219  :         }
; 220  :     }
; 221  : }

	ret	0
_midiEnableMt32ToGmMapping ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\win32\win32midi.c
;	COMDAT _midiShutdown
_TEXT	SEGMENT
_midiShutdown PROC					; COMDAT

; 169  :     free(midi.in.dev);

	push	DWORD PTR _midi+4
	call	_free

; 170  :     free(midi.out.dev);

	push	DWORD PTR _midi+24
	call	_free

; 171  : 
; 172  :     memset(&midi, 0, sizeof(midi));

	push	1076					; 00000434H
	push	0
	push	OFFSET _midi
	call	_memset
	add	esp, 20					; 00000014H

; 173  : }

	ret	0
_midiShutdown ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\win32\win32midi.c
;	COMDAT _midiInitialize
_TEXT	SEGMENT
_outCap$ = -100						; size = 52
_inCap$ = -48						; size = 44
__$ArrayPad$ = -4					; size = 4
_midiInitialize PROC					; COMDAT

; 121  : {

	sub	esp, 100				; 00000064H
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, esp
	mov	DWORD PTR __$ArrayPad$[esp+100], eax
	push	ebx
	push	esi
	push	edi

; 122  : 	MIDIINCAPSA  inCap;
; 123  : 	MIDIOUTCAPSA outCap;
; 124  :     int num;
; 125  : 
; 126  :     memset(&midi, 0, sizeof(midi));

	push	1072					; 00000430H
	push	0
	push	OFFSET _midi
	call	_memset
	add	esp, 12					; 0000000cH

; 127  :     midi.enabled = 1;

	mov	DWORD PTR _midi+1072, 1

; 128  : 
; 129  : 	num = midiOutGetNumDevs();

	call	DWORD PTR __imp__midiOutGetNumDevs@0
	mov	edi, eax

; 130  :     if (num > 0 && midiOutGetDevCapsA(MIDI_MAPPER, &outCap, sizeof(outCap)) == MMSYSERR_NOERROR) {

	test	edi, edi
	jle	$LN3@midiInitia
	mov	ebx, DWORD PTR __imp__midiOutGetDevCapsA@12
	lea	eax, DWORD PTR _outCap$[esp+112]
	push	52					; 00000034H
	push	eax
	push	-1
	call	ebx
	test	eax, eax
	jne	$LN3@midiInitia

; 131  :         int i;
; 132  : 
; 133  :         midi.out.dev = (DevInfo*)calloc(1, (num + 1) * sizeof(DevInfo));

	lea	eax, DWORD PTR [edi+1]
	imul	eax, eax, 5456
	push	eax
	push	1
	call	_calloc
	add	esp, 8
	mov	DWORD PTR _midi+24, eax

; 134  : 
; 135  :         strcpy(midi.out.dev[0].name, outCap.szPname);

	lea	ecx, DWORD PTR _outCap$[esp+120]
	lea	edx, DWORD PTR [eax+40]
$LL13@midiInitia:
	mov	al, BYTE PTR [ecx]
	lea	ecx, DWORD PTR [ecx+1]
	mov	BYTE PTR [edx], al
	lea	edx, DWORD PTR [edx+1]
	test	al, al
	jne	SHORT $LL13@midiInitia

; 136  :         midi.out.dev[0].id = MIDI_MAPPER;

	mov	eax, DWORD PTR _midi+24
	xor	esi, esi
	mov	DWORD PTR [eax], -1

; 137  : 	    strcpy(midi.out.dev[0].idString, "midi-out");

	mov	ecx, DWORD PTR _midi+24
	movq	xmm0, QWORD PTR ??_C@_08GIABBKPP@midi?9out@
	movq	QWORD PTR [ecx+4], xmm0
	mov	al, BYTE PTR ??_C@_08GIABBKPP@midi?9out@+8
	mov	BYTE PTR [ecx+12], al

; 138  :         midi.out.count++;

	inc	DWORD PTR _midi+20

; 139  : 
; 140  : 	    for (i = 0; i < num; i++) {

	test	edi, edi
	jle	SHORT $LN3@midiInitia
$LL4@midiInitia:

; 141  : 		    if (midiOutGetDevCapsA(i, &outCap, sizeof(outCap)) == MMSYSERR_NOERROR) {

	push	52					; 00000034H
	lea	eax, DWORD PTR _outCap$[esp+116]
	push	eax
	push	esi
	call	ebx
	test	eax, eax
	jne	SHORT $LN2@midiInitia

; 142  :                 strcpy(midi.out.dev[midi.out.count].name, outCap.szPname);

	imul	ecx, DWORD PTR _midi+20, 5456
	lea	edx, DWORD PTR _outCap$[esp+120]
	add	ecx, 40					; 00000028H
	add	ecx, DWORD PTR _midi+24
	npad	3
$LL14@midiInitia:
	mov	al, BYTE PTR [edx]
	lea	edx, DWORD PTR [edx+1]
	mov	BYTE PTR [ecx], al
	lea	ecx, DWORD PTR [ecx+1]
	test	al, al
	jne	SHORT $LL14@midiInitia

; 143  : 		        midi.out.dev[midi.out.count].id = i;

	imul	ecx, DWORD PTR _midi+20, 5456
	mov	eax, DWORD PTR _midi+24

; 144  : 		        sprintf(midi.out.dev[midi.out.count].idString, "midi-out-%u", i);

	push	esi
	push	OFFSET ??_C@_0M@EHCEIAJD@midi?9out?9?$CFu@
	mov	DWORD PTR [ecx+eax], esi
	imul	ecx, DWORD PTR _midi+20, 5456
	mov	eax, DWORD PTR _midi+24
	add	ecx, 4
	add	eax, ecx
	push	eax
	call	_sprintf
	add	esp, 12					; 0000000cH

; 145  :                 midi.out.count++;

	inc	DWORD PTR _midi+20
$LN2@midiInitia:

; 139  : 
; 140  : 	    for (i = 0; i < num; i++) {

	inc	esi
	cmp	esi, edi
	jl	SHORT $LL4@midiInitia
$LN3@midiInitia:

; 146  :             }
; 147  : 	    }
; 148  :     }
; 149  : 
; 150  : 	num = midiInGetNumDevs();

	call	DWORD PTR __imp__midiInGetNumDevs@0
	mov	edi, eax

; 151  :     if (num > 0) {

	test	edi, edi
	jle	$LN6@midiInitia

; 152  :         int i;
; 153  : 
; 154  :         midi.in.dev = (DevInfo*)calloc(1, num * sizeof(DevInfo));

	imul	ecx, edi, 5456
	push	ecx
	push	1
	call	_calloc
	mov	ebx, DWORD PTR __imp__midiInGetDevCapsA@12
	add	esp, 8
	mov	DWORD PTR _midi+4, eax
	xor	esi, esi
	npad	4
$LL7@midiInitia:

; 157  : 		    if (midiInGetDevCapsA(i, &inCap, sizeof(inCap)) == MMSYSERR_NOERROR) {

	push	44					; 0000002cH
	lea	eax, DWORD PTR _inCap$[esp+116]
	push	eax
	push	esi
	call	ebx
	test	eax, eax
	jne	SHORT $LN5@midiInitia

; 158  :                 strcpy(midi.in.dev[midi.in.count].name, inCap.szPname);

	imul	ecx, DWORD PTR _midi, 5456
	lea	edx, DWORD PTR _inCap$[esp+120]
	mov	eax, DWORD PTR _midi+4
	add	eax, 40					; 00000028H
	add	eax, ecx
$LL15@midiInitia:
	mov	cl, BYTE PTR [edx]
	lea	edx, DWORD PTR [edx+1]
	mov	BYTE PTR [eax], cl
	lea	eax, DWORD PTR [eax+1]
	test	cl, cl
	jne	SHORT $LL15@midiInitia

; 159  : 		        midi.in.dev[midi.in.count].id = i;

	imul	ecx, DWORD PTR _midi, 5456
	mov	eax, DWORD PTR _midi+4

; 160  : 		        sprintf(midi.in.dev[midi.in.count].idString, "midi-in-%u", i);

	push	esi
	push	OFFSET ??_C@_0L@HFOEGABH@midi?9in?9?$CFu@
	mov	DWORD PTR [ecx+eax], esi
	imul	ecx, DWORD PTR _midi, 5456
	mov	eax, DWORD PTR _midi+4
	add	ecx, 4
	add	eax, ecx
	push	eax
	call	_sprintf
	add	esp, 12					; 0000000cH

; 161  :                 midi.in.count++;

	inc	DWORD PTR _midi
$LN5@midiInitia:

; 155  : 
; 156  : 	    for (i = 0; i < num; ++i) {

	inc	esi
	cmp	esi, edi
	jl	SHORT $LL7@midiInitia
$LN6@midiInitia:

; 162  :             }
; 163  : 	    }
; 164  :     }
; 165  : }

	mov	ecx, DWORD PTR __$ArrayPad$[esp+112]
	pop	edi
	pop	esi
	pop	ebx
	xor	ecx, esp
	call	@__security_check_cookie@4
	add	esp, 100				; 00000064H
	ret	0
_midiInitialize ENDP
_TEXT	ENDS
END
