; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27054.0 

	TITLE	D:\repo\MSX-master\MSX\blueMSX-DPI\Src\Utils\ziphelper.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_memZipFileSystemCreate
PUBLIC	_memZipFileSystemDestroy
PUBLIC	_zipCacheReadOnlyZip
PUBLIC	_zipLoadFile
PUBLIC	_zipSaveFile
PUBLIC	_zipFileExists
PUBLIC	_zipGetFileList
PUBLIC	_zipHasFileType
PUBLIC	_zipExtractCurrentfile
PUBLIC	_zipExtract
PUBLIC	_zipCompress
PUBLIC	_zipUncompress
PUBLIC	___local_stdio_printf_options
PUBLIC	_printf
PUBLIC	_memZipFileDestroy
PUBLIC	_memZipFileFind
PUBLIC	_memZipFileCreate
PUBLIC	_memFileFindInZip
PUBLIC	_memFileLoad
PUBLIC	_memFileSave
PUBLIC	__zipLoadFile
PUBLIC	??_C@_03IJLIBDBM@mem@				; `string'
PUBLIC	??_C@_02JDPG@rb@				; `string'
PUBLIC	??_C@_0BO@HCBPGKCG@couldn?8t?5create?5directory?5?$CFs?6@ ; `string'
PUBLIC	??_C@_0DA@JKFADJED@error?5?$CFd?5with?5zipfile?5in?5unzGet@ ; `string'
PUBLIC	??_C@_0DF@EHJPKLOI@error?5?$CFd?5with?5zipfile?5in?5unzOpe@ ; `string'
PUBLIC	??_C@_02GMLFBBN@wb@				; `string'
PUBLIC	??_C@_0BC@CBHACCGB@error?5opening?5?$CFs?6@	; `string'
PUBLIC	??_C@_0BB@BKFCOHHC@?5extracting?3?5?$CFs?6@	; `string'
PUBLIC	??_C@_0CN@ENDBCDIB@error?5?$CFd?5with?5zipfile?5in?5unzRea@ ; `string'
PUBLIC	??_C@_0CB@EOJIBDBE@error?5in?5writing?5extracted?5file@ ; `string'
PUBLIC	??_C@_0CO@EMCAOMAG@error?5?$CFd?5with?5zipfile?5in?5unzClo@ ; `string'
PUBLIC	??_C@_0CM@EPAEMPIG@error?5?$CFd?5with?5zipfile?5in?5unzGet@ ; `string'
PUBLIC	??_C@_0CK@HCGKKBDJ@error?5?$CFd?5with?5zipfile?5in?5unzGoT@ ; `string'
EXTRN	_compress:PROC
EXTRN	_uncompress:PROC
EXTRN	_unzOpen:PROC
EXTRN	_unzOpen2:PROC
EXTRN	_unzClose:PROC
EXTRN	_unzGetGlobalInfo:PROC
EXTRN	_unzGoToFirstFile:PROC
EXTRN	_unzGoToNextFile:PROC
EXTRN	_unzLocateFile:PROC
EXTRN	_unzGetCurrentFileInfo:PROC
EXTRN	_unzOpenCurrentFile:PROC
EXTRN	_unzOpenCurrentFilePassword:PROC
EXTRN	_unzCloseCurrentFile:PROC
EXTRN	_unzReadCurrentFile:PROC
EXTRN	_zipOpen:PROC
EXTRN	_zipOpenNewFileInZip:PROC
EXTRN	_zipWriteInFileInZip:PROC
EXTRN	_zipClose:PROC
EXTRN	_tolower:PROC
EXTRN	_fill_fopen_memfunc:PROC
EXTRN	_free_fopen_memfunc:PROC
EXTRN	___acrt_iob_func:PROC
EXTRN	_fclose:PROC
EXTRN	_fopen:PROC
EXTRN	_fread:PROC
EXTRN	_fseek:PROC
EXTRN	_ftell:PROC
EXTRN	_fwrite:PROC
EXTRN	___stdio_common_vfprintf:PROC
EXTRN	_calloc:PROC
EXTRN	_free:PROC
EXTRN	_malloc:PROC
EXTRN	_realloc:PROC
EXTRN	__errno:PROC
EXTRN	_strstr:PROC
EXTRN	_strncmp:PROC
EXTRN	__mkdir:PROC
EXTRN	@__security_check_cookie@4:PROC
EXTRN	_memcpy:PROC
EXTRN	___security_cookie:DWORD
_DATA	SEGMENT
COMM	?_OptionsStorage@?1??__local_stdio_printf_options@@9@9:QWORD							; `__local_stdio_printf_options'::`2'::_OptionsStorage
_DATA	ENDS
_BSS	SEGMENT
_memZipFiles DD	01H DUP (?)
_memZipFileCount DD 01H DUP (?)
_cacheData DD	01H DUP (?)
_cacheFile DB	0200H DUP (?)
_cacheFilefunc DB 020H DUP (?)
_BSS	ENDS
;	COMDAT ??_C@_0CK@HCGKKBDJ@error?5?$CFd?5with?5zipfile?5in?5unzGoT@
CONST	SEGMENT
??_C@_0CK@HCGKKBDJ@error?5?$CFd?5with?5zipfile?5in?5unzGoT@ DB 'error %d '
	DB	'with zipfile in unzGoToNextFile', 0aH, 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0CM@EPAEMPIG@error?5?$CFd?5with?5zipfile?5in?5unzGet@
CONST	SEGMENT
??_C@_0CM@EPAEMPIG@error?5?$CFd?5with?5zipfile?5in?5unzGet@ DB 'error %d '
	DB	'with zipfile in unzGetGlobalInfo ', 0aH, 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0CO@EMCAOMAG@error?5?$CFd?5with?5zipfile?5in?5unzClo@
CONST	SEGMENT
??_C@_0CO@EMCAOMAG@error?5?$CFd?5with?5zipfile?5in?5unzClo@ DB 'error %d '
	DB	'with zipfile in unzCloseCurrentFile', 0aH, 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0CB@EOJIBDBE@error?5in?5writing?5extracted?5file@
CONST	SEGMENT
??_C@_0CB@EOJIBDBE@error?5in?5writing?5extracted?5file@ DB 'error in writ'
	DB	'ing extracted file', 0aH, 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_0CN@ENDBCDIB@error?5?$CFd?5with?5zipfile?5in?5unzRea@
CONST	SEGMENT
??_C@_0CN@ENDBCDIB@error?5?$CFd?5with?5zipfile?5in?5unzRea@ DB 'error %d '
	DB	'with zipfile in unzReadCurrentFile', 0aH, 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BB@BKFCOHHC@?5extracting?3?5?$CFs?6@
CONST	SEGMENT
??_C@_0BB@BKFCOHHC@?5extracting?3?5?$CFs?6@ DB ' extracting: %s', 0aH, 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BC@CBHACCGB@error?5opening?5?$CFs?6@
CONST	SEGMENT
??_C@_0BC@CBHACCGB@error?5opening?5?$CFs?6@ DB 'error opening %s', 0aH, 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_02GMLFBBN@wb@
CONST	SEGMENT
??_C@_02GMLFBBN@wb@ DB 'wb', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_0DF@EHJPKLOI@error?5?$CFd?5with?5zipfile?5in?5unzOpe@
CONST	SEGMENT
??_C@_0DF@EHJPKLOI@error?5?$CFd?5with?5zipfile?5in?5unzOpe@ DB 'error %d '
	DB	'with zipfile in unzOpenCurrentFilePassword', 0aH, 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0DA@JKFADJED@error?5?$CFd?5with?5zipfile?5in?5unzGet@
CONST	SEGMENT
??_C@_0DA@JKFADJED@error?5?$CFd?5with?5zipfile?5in?5unzGet@ DB 'error %d '
	DB	'with zipfile in unzGetCurrentFileInfo', 0aH, 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BO@HCBPGKCG@couldn?8t?5create?5directory?5?$CFs?6@
CONST	SEGMENT
??_C@_0BO@HCBPGKCG@couldn?8t?5create?5directory?5?$CFs?6@ DB 'couldn''t c'
	DB	'reate directory %s', 0aH, 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_02JDPG@rb@
CONST	SEGMENT
??_C@_02JDPG@rb@ DB 'rb', 00H				; `string'
CONST	ENDS
;	COMDAT ??_C@_03IJLIBDBM@mem@
CONST	SEGMENT
??_C@_03IJLIBDBM@mem@ DB 'mem', 00H			; `string'
CONST	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\utils\ziphelper.c
;	COMDAT _makedir
_TEXT	SEGMENT
_newdir$ = 8						; size = 4
_makedir PROC						; COMDAT

; 744  : {

	push	esi

; 745  :     char *buffer;
; 746  :     char *p;
; 747  :     int len = (int)strlen(newdir);

	mov	esi, DWORD PTR _newdir$[esp]
	push	edi
	mov	edi, esi
	lea	ecx, DWORD PTR [edi+1]
	npad	5
$LL26@makedir:
	mov	al, BYTE PTR [edi]
	inc	edi
	test	al, al
	jne	SHORT $LL26@makedir
	sub	edi, ecx

; 748  : 
; 749  :     if (len <= 0) return 0;

	test	edi, edi
	jg	SHORT $LN6@makedir
	pop	edi
	xor	eax, eax

; 780  : }

	pop	esi
	ret	0
$LN6@makedir:

; 750  : 
; 751  :     buffer = (char*)malloc(len+1);

	lea	eax, DWORD PTR [edi+1]
	push	ebp
	push	eax
	call	_malloc
	add	esp, 4
	mov	ebp, eax
	sub	eax, esi
$LL12@makedir:

; 752  :     strcpy(buffer,newdir);

	mov	cl, BYTE PTR [esi]
	lea	esi, DWORD PTR [esi+1]
	mov	BYTE PTR [eax+esi-1], cl
	test	cl, cl
	jne	SHORT $LL12@makedir

; 753  : 
; 754  :     if (buffer[len-1] == '/') {

	cmp	BYTE PTR [edi+ebp-1], 47		; 0000002fH
	jne	SHORT $LN7@makedir

; 755  :         buffer[len-1] = '\0';

	mov	BYTE PTR [edi+ebp-1], cl
$LN7@makedir:
	push	ebx

; 756  :     }
; 757  :     if (MKDIR(buffer) == 0) {

	push	ebp
	call	__mkdir
	add	esp, 4
	test	eax, eax
	je	SHORT $LN18@makedir

; 758  :         free(buffer);
; 759  :         return 1;
; 760  :     }
; 761  : 
; 762  :     p = buffer+1;

	lea	esi, DWORD PTR [ebp+1]
	npad	4
$LL2@makedir:

; 763  :     while (1) {
; 764  :         char hold;
; 765  : 
; 766  :         while(*p && *p != '\\' && *p != '/') p++;

	mov	bl, BYTE PTR [esi]
	test	bl, bl
	je	SHORT $LN27@makedir
	mov	al, bl
$LL4@makedir:
	mov	bl, al
	cmp	al, 92					; 0000005cH
	je	SHORT $LN27@makedir
	cmp	al, 47					; 0000002fH
	je	SHORT $LN27@makedir
	mov	bl, BYTE PTR [esi+1]
	inc	esi
	mov	al, bl
	test	bl, bl
	jne	SHORT $LL4@makedir
$LN27@makedir:

; 767  :         hold = *p;
; 768  :         *p = 0;
; 769  :         if ((MKDIR(buffer) == -1) && (errno == ENOENT))

	push	ebp
	mov	BYTE PTR [esi], 0
	call	__mkdir
	add	esp, 4
	cmp	eax, -1
	jne	SHORT $LN9@makedir
	call	__errno
	cmp	DWORD PTR [eax], 2
	je	SHORT $LN17@makedir
$LN9@makedir:

; 774  :         }
; 775  :         if (hold == 0) break;

	test	bl, bl
	je	SHORT $LN18@makedir

; 776  :         *p++ = hold;

	mov	BYTE PTR [esi], bl
	inc	esi

; 777  :     }

	jmp	SHORT $LL2@makedir
$LN17@makedir:

; 770  :         {
; 771  :             printf("couldn't create directory %s\n",buffer);

	push	ebp
	push	OFFSET ??_C@_0BO@HCBPGKCG@couldn?8t?5create?5directory?5?$CFs?6@
	call	_printf

; 772  :             free(buffer);

	push	ebp
	call	_free
	add	esp, 12					; 0000000cH

; 773  :             return 0;

	xor	eax, eax
	pop	ebx
	pop	ebp
	pop	edi

; 780  : }

	pop	esi
	ret	0
$LN18@makedir:

; 778  :     free(buffer);

	push	ebp
	call	_free
	add	esp, 4

; 779  :     return 1;

	mov	eax, 1
	pop	ebx
	pop	ebp
	pop	edi

; 780  : }

	pop	esi
	ret	0
_makedir ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\utils\ziphelper.c
;	COMDAT __zipLoadFile
_TEXT	SEGMENT
_filefunc$GSCopy$1$ = -344				; size = 4
_info$ = -340						; size = 80
_name$ = -260						; size = 256
__$ArrayPad$ = -4					; size = 4
_zipName$ = 8						; size = 4
_fileName$ = 12						; size = 4
_size$ = 16						; size = 4
_filefunc$ = 20						; size = 4
__zipLoadFile PROC					; COMDAT

; 425  : {

	sub	esp, 344				; 00000158H
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, esp
	mov	DWORD PTR __$ArrayPad$[esp+344], eax

; 426  :     void* buf;
; 427  :     char name[256];
; 428  :     unzFile zip;
; 429  :     unz_file_info info;
; 430  : 
; 431  :     *size = 0;
; 432  : 
; 433  :     if (fileName[0] == '*') {

	mov	ecx, DWORD PTR _fileName$[esp+340]
	mov	eax, DWORD PTR _filefunc$[esp+340]
	push	ebp
	mov	ebp, DWORD PTR _size$[esp+344]
	push	esi
	push	edi
	mov	edi, DWORD PTR _zipName$[esp+352]
	mov	DWORD PTR [ebp], 0
	cmp	BYTE PTR [ecx], 42			; 0000002aH
	mov	DWORD PTR _filefunc$GSCopy$1$[esp+356], eax
	jne	$LN2@zipLoadFil

; 434  :         strcpy(name, zipName);

	lea	esi, DWORD PTR _name$[esp+356]
	mov	edx, edi
	sub	esi, edi
	npad	1
$LL9@zipLoadFil:
	mov	al, BYTE PTR [edx]
	lea	edx, DWORD PTR [edx+1]
	mov	BYTE PTR [esi+edx-1], al
	test	al, al
	jne	SHORT $LL9@zipLoadFil

; 435  :         name[strlen(zipName) - 3] = fileName[strlen(fileName) - 3];

	mov	edx, ecx
	lea	esi, DWORD PTR [edx+1]
$LL18@zipLoadFil:
	mov	al, BYTE PTR [edx]
	inc	edx
	test	al, al
	jne	SHORT $LL18@zipLoadFil
	sub	edx, esi
	mov	esi, edi
	push	ebx
	lea	ebx, DWORD PTR [esi+1]
$LL19@zipLoadFil:
	mov	al, BYTE PTR [esi]
	inc	esi
	test	al, al
	jne	SHORT $LL19@zipLoadFil
	mov	al, BYTE PTR [edx+ecx-3]
	sub	esi, ebx

; 436  :         name[strlen(zipName) - 2] = fileName[strlen(fileName) - 2];

	mov	edx, ecx
	mov	BYTE PTR _name$[esp+esi+357], al
	lea	esi, DWORD PTR [edx+1]
$LL20@zipLoadFil:
	mov	al, BYTE PTR [edx]
	inc	edx
	test	al, al
	jne	SHORT $LL20@zipLoadFil
	sub	edx, esi
	mov	esi, edi
	lea	ebx, DWORD PTR [esi+1]
$LL21@zipLoadFil:
	mov	al, BYTE PTR [esi]
	inc	esi
	test	al, al
	jne	SHORT $LL21@zipLoadFil
	mov	al, BYTE PTR [edx+ecx-2]
	sub	esi, ebx
	mov	BYTE PTR _name$[esp+esi+358], al

; 437  :         name[strlen(zipName) - 1] = fileName[strlen(fileName) - 1];

	mov	esi, ecx
	lea	edx, DWORD PTR [esi+1]
	npad	5
$LL22@zipLoadFil:
	mov	al, BYTE PTR [esi]
	inc	esi
	test	al, al
	jne	SHORT $LL22@zipLoadFil
	sub	esi, edx
	mov	edx, edi
	lea	ebx, DWORD PTR [edx+1]
	npad	2
$LL23@zipLoadFil:
	mov	al, BYTE PTR [edx]
	inc	edx
	test	al, al
	jne	SHORT $LL23@zipLoadFil
	mov	al, BYTE PTR [esi+ecx-1]
	sub	edx, ebx
	pop	ebx
	mov	BYTE PTR _name$[esp+edx+355], al

; 438  :     }

	jmp	SHORT $LN3@zipLoadFil
$LN2@zipLoadFil:

; 439  :     else {
; 440  :         strcpy(name, fileName);

	lea	edx, DWORD PTR _name$[esp+356]
	sub	edx, ecx
	npad	6
$LL10@zipLoadFil:
	mov	al, BYTE PTR [ecx]
	lea	ecx, DWORD PTR [ecx+1]
	mov	BYTE PTR [edx+ecx-1], al
	test	al, al
	jne	SHORT $LL10@zipLoadFil
$LN3@zipLoadFil:

; 441  :     }
; 442  : 
; 443  :     zip = unzOpen2(zipName, filefunc);

	push	DWORD PTR _filefunc$GSCopy$1$[esp+356]
	push	edi
	call	_unzOpen2
	mov	esi, eax
	add	esp, 8

; 444  :     if (!zip) {

	test	esi, esi
	je	SHORT $LN17@zipLoadFil

; 445  :         return NULL;
; 446  :     }
; 447  : 
; 448  : #ifdef __APPLE__
; 449  :     // Most OS X installs are on a case-insensitive FS
; 450  :     if (unzLocateFile(zip, name, 2) == UNZ_END_OF_LIST_OF_FILE) {
; 451  : #else
; 452  :     if (unzLocateFile(zip, name, 1) == UNZ_END_OF_LIST_OF_FILE) {

	push	1
	lea	eax, DWORD PTR _name$[esp+360]
	push	eax
	push	esi
	call	_unzLocateFile
	add	esp, 12					; 0000000cH
	push	esi
	cmp	eax, -100				; ffffff9cH
	jne	SHORT $LN5@zipLoadFil

; 453  : #endif
; 454  :         unzClose(zip);

	call	_unzClose
	add	esp, 4
$LN17@zipLoadFil:

; 476  : 
; 477  :     return buf;
; 478  : }

	pop	edi
	pop	esi
	xor	eax, eax
	pop	ebp
	mov	ecx, DWORD PTR __$ArrayPad$[esp+344]
	xor	ecx, esp
	call	@__security_check_cookie@4
	add	esp, 344				; 00000158H
	ret	0
$LN5@zipLoadFil:

; 455  :         return NULL;
; 456  :     }
; 457  : 
; 458  :     if (unzOpenCurrentFile(zip) != UNZ_OK) {

	call	_unzOpenCurrentFile
	add	esp, 4
	test	eax, eax
	jne	SHORT $LN17@zipLoadFil

; 459  :         return NULL;
; 460  :     }
; 461  : 
; 462  :     unzGetCurrentFileInfo(zip,&info,NULL,0,NULL,0,NULL,0);

	push	eax
	push	eax
	push	eax
	push	eax
	push	eax
	push	eax
	lea	eax, DWORD PTR _info$[esp+380]
	push	eax
	push	esi
	call	_unzGetCurrentFileInfo

; 463  : 
; 464  :     buf = malloc(info.uncompressed_size);

	push	DWORD PTR _info$[esp+416]
	call	_malloc
	mov	edi, eax
	add	esp, 36					; 00000024H

; 465  :     *size = info.uncompressed_size;

	mov	eax, DWORD PTR _info$[esp+384]
	mov	DWORD PTR [ebp], eax

; 466  : 
; 467  :     if (!buf) {

	test	edi, edi
	jne	SHORT $LN7@zipLoadFil

; 468  :         unzCloseCurrentFile(zip);

	push	esi
	call	_unzCloseCurrentFile

; 469  :         unzClose(zip);

	push	esi
	call	_unzClose
	add	esp, 8

; 470  :         return NULL;

	jmp	SHORT $LN17@zipLoadFil
$LN7@zipLoadFil:

; 471  :     }
; 472  : 
; 473  :     unzReadCurrentFile(zip, buf, info.uncompressed_size);

	push	eax
	push	edi
	push	esi
	call	_unzReadCurrentFile

; 474  :     unzCloseCurrentFile(zip);

	push	esi
	call	_unzCloseCurrentFile

; 475  :     unzClose(zip);

	push	esi
	call	_unzClose

; 476  : 
; 477  :     return buf;
; 478  : }

	mov	ecx, DWORD PTR __$ArrayPad$[esp+376]
	add	esp, 20					; 00000014H
	mov	eax, edi
	pop	edi
	pop	esi
	pop	ebp
	xor	ecx, esp
	call	@__security_check_cookie@4
	add	esp, 344				; 00000158H
	ret	0
__zipLoadFile ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\utils\ziphelper.c
;	COMDAT _memFileSave
_TEXT	SEGMENT
_zipName$ = 8						; size = 4
_filename$ = 12						; size = 4
_append$ = 16						; size = 4
_buffer$ = 20						; size = 4
_size$ = 24						; size = 4
_memFileSave PROC					; COMDAT

; 195  : {

	push	ebx
	push	esi
	push	edi

; 196  :     MemZipFile* memZipFile = memZipFileFind(zipName);

	mov	edi, DWORD PTR _zipName$[esp+8]
	push	edi
	call	_memZipFileFind
	add	esp, 4
	mov	esi, eax

; 197  :     MemFile* memFile;
; 198  : 
; 199  :     if (!append)

	cmp	DWORD PTR _append$[esp+8], 0
	jne	SHORT $LN2@memFileSav

; 200  :     {
; 201  :         memZipFileDestroy(memZipFile);

	push	esi
	call	_memZipFileDestroy
	add	esp, 4
$LN2@memFileSav:

; 202  :         memZipFile = NULL;
; 203  :     }
; 204  : 
; 205  :     if (memZipFile == NULL)

	xor	ebx, ebx
	cmp	DWORD PTR _append$[esp+8], ebx
	cmovne	ebx, esi
	test	ebx, ebx
	jne	SHORT $LN27@memFileSav

; 151  :     for (i = 0; i < memZipFileCount; i++)

	mov	eax, DWORD PTR _memZipFileCount
	xor	esi, esi
	test	eax, eax
	jle	SHORT $LN5@memFileSav
	mov	ecx, DWORD PTR _memZipFiles
$LL11@memFileSav:

; 152  :     {
; 153  :         if (memZipFiles[i] == NULL)

	cmp	DWORD PTR [ecx+esi*4], 0
	je	SHORT $LN18@memFileSav

; 151  :     for (i = 0; i < memZipFileCount; i++)

	inc	esi
	cmp	esi, eax
	jl	SHORT $LL11@memFileSav
$LN5@memFileSav:
	pop	edi

; 224  : }

	pop	esi
	xor	eax, eax
	pop	ebx
	ret	0
$LN18@memFileSav:

; 155  :             memZipFiles[i] = malloc(sizeof(MemZipFile));

	push	292					; 00000124H
	call	_malloc
	mov	ecx, DWORD PTR _memZipFiles
	add	esp, 4
	lea	ebx, DWORD PTR [ecx+esi*4]
	mov	DWORD PTR [ebx], eax
	npad	7
$LL14@memFileSav:

; 156  :             strcpy(memZipFiles[i]->zipName, zipName);

	mov	cl, BYTE PTR [edi]
	lea	edi, DWORD PTR [edi+1]
	mov	BYTE PTR [eax], cl
	lea	eax, DWORD PTR [eax+1]
	test	cl, cl
	jne	SHORT $LL14@memFileSav

; 157  :             memZipFiles[i]->count = 0;

	mov	eax, DWORD PTR [ebx]
	mov	DWORD PTR [eax+288], 0

; 158  :             return memZipFiles[i];

	mov	ebx, DWORD PTR [ebx]

; 206  :     {
; 207  :         memZipFile = memZipFileCreate(zipName);
; 208  :     }
; 209  : 
; 210  :     if (memZipFile == NULL || memZipFile->count == MAX_FILES_IN_ZIP)

	test	ebx, ebx
	je	SHORT $LN5@memFileSav
$LN27@memFileSav:
	cmp	DWORD PTR [ebx+288], 64			; 00000040H
	je	SHORT $LN5@memFileSav

; 211  :     {
; 212  :         return 0;
; 213  :     }
; 214  :     
; 215  :     memFile = malloc(sizeof(MemFile));

	push	40					; 00000028H
	call	_malloc

; 216  :     memFile->buffer = malloc(size);

	mov	esi, DWORD PTR _size$[esp+12]
	mov	edi, eax
	push	esi
	call	_malloc

; 217  :     memcpy(memFile->buffer, buffer, size);

	push	esi
	push	DWORD PTR _buffer$[esp+20]
	mov	DWORD PTR [edi+36], eax
	push	eax
	call	_memcpy

; 218  :     memFile->size = size;
; 219  :     strcpy(memFile->filename, filename);

	mov	ecx, DWORD PTR _filename$[esp+28]
	mov	edx, edi
	add	esp, 20					; 00000014H
	mov	DWORD PTR [edi+32], esi
	sub	edx, ecx
	npad	8
$LL7@memFileSav:
	mov	al, BYTE PTR [ecx]
	lea	ecx, DWORD PTR [ecx+1]
	mov	BYTE PTR [edx+ecx-1], al
	test	al, al
	jne	SHORT $LL7@memFileSav

; 220  : 
; 221  :     memZipFile->memFiles[memZipFile->count++] = memFile;

	mov	eax, DWORD PTR [ebx+288]
	mov	DWORD PTR [ebx+eax*4+32], edi

; 222  : 
; 223  :     return 1;

	mov	eax, 1
	inc	DWORD PTR [ebx+288]
	pop	edi

; 224  : }

	pop	esi
	pop	ebx
	ret	0
_memFileSave ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\utils\ziphelper.c
;	COMDAT _memFileLoad
_TEXT	SEGMENT
_zipName$ = 8						; size = 4
_filename$ = 12						; size = 4
_size$ = 16						; size = 4
_memFileLoad PROC					; COMDAT

; 181  : {

	push	ebx
	push	ebp
	push	esi
	push	edi

; 182  :     MemFile* memFile = memFileFindInZip(memZipFileFind(zipName), filename);

	push	DWORD PTR _zipName$[esp+12]
	call	_memZipFileFind
	add	esp, 4

; 166  :     if (memZipFile != NULL)

	test	eax, eax
	je	SHORT $LN2@memFileLoa

; 167  :     {
; 168  :         int i;
; 169  :         for (i = 0; i < memZipFile->count; i++)

	mov	ebp, DWORD PTR [eax+288]
	xor	esi, esi
	test	ebp, ebp
	jle	SHORT $LN2@memFileLoa
	lea	edi, DWORD PTR [eax+32]
$LL7@memFileLoa:

; 170  :         {
; 171  :             if (strcmp(memZipFile->memFiles[i]->filename, filename) == 0)

	mov	ebx, DWORD PTR [edi]
	mov	ecx, ebx
	mov	eax, DWORD PTR _filename$[esp+12]
	npad	5
$LL16@memFileLoa:
	mov	dl, BYTE PTR [ecx]
	cmp	dl, BYTE PTR [eax]
	jne	SHORT $LN17@memFileLoa
	test	dl, dl
	je	SHORT $LN18@memFileLoa
	mov	dl, BYTE PTR [ecx+1]
	cmp	dl, BYTE PTR [eax+1]
	jne	SHORT $LN17@memFileLoa
	add	ecx, 2
	add	eax, 2
	test	dl, dl
	jne	SHORT $LL16@memFileLoa
$LN18@memFileLoa:
	xor	eax, eax
	jmp	SHORT $LN19@memFileLoa
$LN17@memFileLoa:
	sbb	eax, eax
	or	eax, 1
$LN19@memFileLoa:
	test	eax, eax
	je	SHORT $LN12@memFileLoa

; 167  :     {
; 168  :         int i;
; 169  :         for (i = 0; i < memZipFile->count; i++)

	inc	esi
	add	edi, 4
	cmp	esi, ebp
	jl	SHORT $LL7@memFileLoa
$LN2@memFileLoa:

; 189  :     }
; 190  :     *size = 0;

	mov	eax, DWORD PTR _size$[esp+12]
	pop	edi

; 191  :     return NULL;
; 192  : }

	pop	esi
	pop	ebp
	mov	DWORD PTR [eax], 0
	xor	eax, eax
	pop	ebx
	ret	0
$LN12@memFileLoa:

; 183  :     if (memFile != NULL && memFile->size > 0)

	test	ebx, ebx
	je	SHORT $LN2@memFileLoa
	mov	eax, DWORD PTR [ebx+32]
	test	eax, eax
	jle	SHORT $LN2@memFileLoa

; 184  :     {
; 185  :         void* buffer = malloc(memFile->size);

	push	eax
	call	_malloc

; 186  :         memcpy(buffer, memFile->buffer, memFile->size);

	mov	esi, DWORD PTR [ebx+32]
	mov	edi, eax
	push	esi
	push	DWORD PTR [ebx+36]
	push	edi
	call	_memcpy

; 187  :         *size = memFile->size;

	mov	ecx, DWORD PTR _size$[esp+28]
	add	esp, 16					; 00000010H

; 188  :         return buffer;

	mov	eax, edi
	pop	edi
	mov	DWORD PTR [ecx], esi

; 191  :     return NULL;
; 192  : }

	pop	esi
	pop	ebp
	pop	ebx
	ret	0
_memFileLoad ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\utils\ziphelper.c
;	COMDAT _memFileFindInZip
_TEXT	SEGMENT
_memZipFile$ = 8					; size = 4
_filename$ = 12						; size = 4
_memFileFindInZip PROC					; COMDAT

; 166  :     if (memZipFile != NULL)

	mov	eax, DWORD PTR _memZipFile$[esp-4]
	push	ebx
	push	ebp
	push	esi
	push	edi
	test	eax, eax
	je	SHORT $LN3@memFileFin

; 167  :     {
; 168  :         int i;
; 169  :         for (i = 0; i < memZipFile->count; i++)

	mov	ebp, DWORD PTR [eax+288]
	xor	esi, esi
	test	ebp, ebp
	jle	SHORT $LN3@memFileFin
	lea	edi, DWORD PTR [eax+32]
	npad	5
$LL4@memFileFin:

; 170  :         {
; 171  :             if (strcmp(memZipFile->memFiles[i]->filename, filename) == 0)

	mov	ebx, DWORD PTR [edi]
	mov	ecx, ebx
	mov	eax, DWORD PTR _filename$[esp+12]
$LL13@memFileFin:
	mov	dl, BYTE PTR [ecx]
	cmp	dl, BYTE PTR [eax]
	jne	SHORT $LN14@memFileFin
	test	dl, dl
	je	SHORT $LN15@memFileFin
	mov	dl, BYTE PTR [ecx+1]
	cmp	dl, BYTE PTR [eax+1]
	jne	SHORT $LN14@memFileFin
	add	ecx, 2
	add	eax, 2
	test	dl, dl
	jne	SHORT $LL13@memFileFin
$LN15@memFileFin:
	xor	eax, eax
	jmp	SHORT $LN16@memFileFin
$LN14@memFileFin:
	sbb	eax, eax
	or	eax, 1
$LN16@memFileFin:
	test	eax, eax
	je	SHORT $LN9@memFileFin

; 167  :     {
; 168  :         int i;
; 169  :         for (i = 0; i < memZipFile->count; i++)

	inc	esi
	add	edi, 4
	cmp	esi, ebp
	jl	SHORT $LL4@memFileFin
$LN3@memFileFin:
	pop	edi

; 172  :             {
; 173  :                 return memZipFile->memFiles[i];
; 174  :             }
; 175  :         }
; 176  :     }
; 177  :     return NULL;
; 178  : }

	pop	esi
	pop	ebp
	xor	eax, eax
	pop	ebx
	ret	0
$LN9@memFileFin:
	pop	edi
	pop	esi
	pop	ebp
	mov	eax, ebx
	pop	ebx
	ret	0
_memFileFindInZip ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\utils\ziphelper.c
;	COMDAT _memZipFileCreate
_TEXT	SEGMENT
_zipName$ = 8						; size = 4
_memZipFileCreate PROC					; COMDAT

; 149  :     int i;
; 150  : 
; 151  :     for (i = 0; i < memZipFileCount; i++)

	mov	eax, DWORD PTR _memZipFileCount
	push	esi
	xor	esi, esi
	test	eax, eax
	jle	SHORT $LN3@memZipFile
	mov	ecx, DWORD PTR _memZipFiles
$LL4@memZipFile:

; 152  :     {
; 153  :         if (memZipFiles[i] == NULL)

	cmp	DWORD PTR [ecx+esi*4], 0
	je	SHORT $LN10@memZipFile

; 149  :     int i;
; 150  : 
; 151  :     for (i = 0; i < memZipFileCount; i++)

	inc	esi
	cmp	esi, eax
	jl	SHORT $LL4@memZipFile
$LN3@memZipFile:

; 159  :         }
; 160  :     }
; 161  :     return NULL;

	xor	eax, eax
	pop	esi

; 162  : }

	ret	0
$LN10@memZipFile:

; 154  :         {
; 155  :             memZipFiles[i] = malloc(sizeof(MemZipFile));

	push	292					; 00000124H
	call	_malloc
	mov	edx, eax
	add	esp, 4
	mov	eax, DWORD PTR _memZipFiles
	lea	eax, DWORD PTR [eax+esi*4]

; 156  :             strcpy(memZipFiles[i]->zipName, zipName);

	mov	esi, DWORD PTR _zipName$[esp]
	mov	DWORD PTR [eax], edx
	npad	2
$LL7@memZipFile:
	mov	cl, BYTE PTR [esi]
	lea	esi, DWORD PTR [esi+1]
	mov	BYTE PTR [edx], cl
	lea	edx, DWORD PTR [edx+1]
	test	cl, cl
	jne	SHORT $LL7@memZipFile

; 157  :             memZipFiles[i]->count = 0;

	mov	ecx, DWORD PTR [eax]
	pop	esi
	mov	DWORD PTR [ecx+288], 0

; 158  :             return memZipFiles[i];

	mov	eax, DWORD PTR [eax]

; 162  : }

	ret	0
_memZipFileCreate ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\utils\ziphelper.c
;	COMDAT _memZipFileFind
_TEXT	SEGMENT
_zipName$ = 8						; size = 4
_memZipFileFind PROC					; COMDAT

; 134  : {

	push	ebx

; 135  :     int i;
; 136  :     for (i = 0; i < memZipFileCount; i++)

	mov	ebx, DWORD PTR _memZipFileCount
	push	ebp
	push	esi
	xor	esi, esi
	push	edi
	test	ebx, ebx
	jle	SHORT $LN13@memZipFile
	mov	ebp, DWORD PTR _memZipFiles
$LL4@memZipFile:

; 137  :     {
; 138  :         if (memZipFiles[i] != NULL && 

	mov	edi, DWORD PTR [ebp+esi*4]
	test	edi, edi
	je	SHORT $LN2@memZipFile
	mov	eax, DWORD PTR _zipName$[esp+12]
	mov	ecx, edi
$LL14@memZipFile:
	mov	dl, BYTE PTR [ecx]
	cmp	dl, BYTE PTR [eax]
	jne	SHORT $LN15@memZipFile
	test	dl, dl
	je	SHORT $LN16@memZipFile
	mov	dl, BYTE PTR [ecx+1]
	cmp	dl, BYTE PTR [eax+1]
	jne	SHORT $LN15@memZipFile
	add	ecx, 2
	add	eax, 2
	test	dl, dl
	jne	SHORT $LL14@memZipFile
$LN16@memZipFile:
	xor	eax, eax
	jmp	SHORT $LN17@memZipFile
$LN15@memZipFile:
	sbb	eax, eax
	or	eax, 1
$LN17@memZipFile:
	test	eax, eax
	je	SHORT $LN8@memZipFile
$LN2@memZipFile:

; 135  :     int i;
; 136  :     for (i = 0; i < memZipFileCount; i++)

	inc	esi
	cmp	esi, ebx
	jl	SHORT $LL4@memZipFile
$LN13@memZipFile:
	pop	edi

; 142  :         }
; 143  :     }
; 144  :     return NULL;
; 145  : }

	pop	esi
	pop	ebp
	xor	eax, eax
	pop	ebx
	ret	0
$LN8@memZipFile:

; 139  :             strcmp(memZipFiles[i]->zipName, zipName) == 0)
; 140  :         {
; 141  :             return memZipFiles[i];

	mov	eax, edi
	pop	edi

; 142  :         }
; 143  :     }
; 144  :     return NULL;
; 145  : }

	pop	esi
	pop	ebp
	pop	ebx
	ret	0
_memZipFileFind ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\utils\ziphelper.c
;	COMDAT _memZipFileDestroy
_TEXT	SEGMENT
_memZipFile$ = 8					; size = 4
_memZipFileDestroy PROC					; COMDAT

; 80   : {

	push	edi

; 81   :     int i;
; 82   : 
; 83   :     if (memZipFile == NULL)

	mov	edi, DWORD PTR _memZipFile$[esp]
	test	edi, edi
	je	SHORT $LN1@memZipFile

; 84   :     {
; 85   :         return;
; 86   :     }
; 87   : 
; 88   :     // Remove node
; 89   :     for (i = 0; i < memZipFileCount; i++)

	mov	ecx, DWORD PTR _memZipFileCount
	xor	eax, eax
	test	ecx, ecx
	jle	SHORT $LN3@memZipFile
	mov	edx, DWORD PTR _memZipFiles
	npad	5
$LL16@memZipFile:

; 90   :     {
; 91   :         if (memZipFiles[i] == memZipFile)

	cmp	DWORD PTR [edx+eax*4], edi
	jne	SHORT $LN24@memZipFile

; 92   :         {
; 93   :             memZipFiles[i] = NULL;

	mov	DWORD PTR [edx+eax*4], 0
$LN24@memZipFile:

; 84   :     {
; 85   :         return;
; 86   :     }
; 87   : 
; 88   :     // Remove node
; 89   :     for (i = 0; i < memZipFileCount; i++)

	inc	eax
	cmp	eax, ecx
	jl	SHORT $LL16@memZipFile
$LN3@memZipFile:
	push	ebx

; 94   :         }
; 95   :     }
; 96   : 
; 97   :     // Delete file contents
; 98   :     for (i = 0; i < memZipFile->count; i++)

	xor	ebx, ebx
	cmp	DWORD PTR [edi+288], ebx
	jle	SHORT $LN6@memZipFile
	push	esi
	lea	esi, DWORD PTR [edi+32]
$LL7@memZipFile:

; 99   :     {
; 100  :         if (memZipFile->memFiles[i]->buffer != NULL)

	mov	eax, DWORD PTR [esi]
	mov	ecx, DWORD PTR [eax+36]
	test	ecx, ecx
	je	SHORT $LN10@memZipFile

; 101  :         {
; 102  :             free(memZipFile->memFiles[i]->buffer);

	push	ecx
	call	_free
	mov	eax, DWORD PTR [esi]
	add	esp, 4
$LN10@memZipFile:

; 103  :         }
; 104  :         free(memZipFile->memFiles[i]);

	push	eax
	call	_free
	inc	ebx
	add	esp, 4
	add	esi, 4
	cmp	ebx, DWORD PTR [edi+288]
	jl	SHORT $LL7@memZipFile
	pop	esi
$LN6@memZipFile:

; 105  :     }
; 106  :     free(memZipFile);

	push	edi
	call	_free
	add	esp, 4
	pop	ebx
$LN1@memZipFile:

; 107  : }

	pop	edi
	ret	0
_memZipFileDestroy ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\utils\ziphelper.c
;	COMDAT _toLower
_TEXT	SEGMENT
_str$ = 8						; size = 4
_toLower PROC						; COMDAT

; 51   : static void toLower(char* str) {

	push	esi

; 52   :     while (*str) {

	mov	esi, DWORD PTR _str$[esp]
	mov	al, BYTE PTR [esi]
	test	al, al
	je	SHORT $LN3@toLower
	npad	5
$LL2@toLower:

; 53   :         *str = tolower(*str);

	movsx	eax, al
	push	eax
	call	_tolower
	mov	BYTE PTR [esi], al

; 54   :         str++;

	lea	esi, DWORD PTR [esi+1]
	mov	al, BYTE PTR [esi]
	add	esp, 4
	test	al, al
	jne	SHORT $LL2@toLower
$LN3@toLower:
	pop	esi

; 55   :     }
; 56   : }

	ret	0
_toLower ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File c:\program files (x86)\windows kits\10\include\10.0.19041.0\ucrt\stdio.h
;	COMDAT _printf
_TEXT	SEGMENT
__Format$ = 8						; size = 4
_printf	PROC						; COMDAT

; 956  :     {

	push	esi

; 957  :         int _Result;
; 958  :         va_list _ArgList;
; 959  :         __crt_va_start(_ArgList, _Format);
; 960  :         _Result = _vfprintf_l(stdout, _Format, NULL, _ArgList);

	mov	esi, DWORD PTR __Format$[esp]
	push	1
	call	___acrt_iob_func
	add	esp, 4

; 645  :         return __stdio_common_vfprintf(_CRT_INTERNAL_LOCAL_PRINTF_OPTIONS, _Stream, _Format, _Locale, _ArgList);

	lea	ecx, DWORD PTR __Format$[esp+4]
	push	ecx
	push	0
	push	esi
	push	eax
	call	___local_stdio_printf_options
	push	DWORD PTR [eax+4]
	push	DWORD PTR [eax]
	call	___stdio_common_vfprintf
	add	esp, 24					; 00000018H

; 961  :         __crt_va_end(_ArgList);
; 962  :         return _Result;

	pop	esi

; 963  :     }

	ret	0
_printf	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File c:\program files (x86)\windows kits\10\include\10.0.19041.0\ucrt\stdio.h
;	COMDAT __vfprintf_l
_TEXT	SEGMENT
__Stream$ = 8						; size = 4
__Format$ = 12						; size = 4
__Locale$ = 16						; size = 4
__ArgList$ = 20						; size = 4
__vfprintf_l PROC					; COMDAT

; 645  :         return __stdio_common_vfprintf(_CRT_INTERNAL_LOCAL_PRINTF_OPTIONS, _Stream, _Format, _Locale, _ArgList);

	push	DWORD PTR __ArgList$[esp-4]
	push	DWORD PTR __Locale$[esp]
	push	DWORD PTR __Format$[esp+4]
	push	DWORD PTR __Stream$[esp+8]
	call	___local_stdio_printf_options
	push	DWORD PTR [eax+4]
	push	DWORD PTR [eax]
	call	___stdio_common_vfprintf
	add	esp, 24					; 00000018H

; 646  :     }

	ret	0
__vfprintf_l ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File c:\program files (x86)\windows kits\10\include\10.0.19041.0\ucrt\corecrt_stdio_config.h
;	COMDAT ___local_stdio_printf_options
_TEXT	SEGMENT
___local_stdio_printf_options PROC			; COMDAT

; 91   :         static unsigned __int64 _OptionsStorage;
; 92   :         return &_OptionsStorage;

	mov	eax, OFFSET ?_OptionsStorage@?1??__local_stdio_printf_options@@9@9 ; `__local_stdio_printf_options'::`2'::_OptionsStorage

; 93   :     }

	ret	0
___local_stdio_printf_options ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\utils\ziphelper.c
;	COMDAT _zipUncompress
_TEXT	SEGMENT
_buffer$ = 8						; size = 4
_size$ = 12						; size = 4
_retSize$ = 16						; size = 4
_zipUncompress PROC					; COMDAT

; 933  : {

	push	esi

; 934  :     void* retBuf = malloc(*retSize);

	mov	esi, DWORD PTR _retSize$[esp]
	push	edi
	push	DWORD PTR [esi]
	call	_malloc

; 935  : 
; 936  :     if (uncompress(retBuf, retSize, buffer, size) != Z_OK) {

	push	DWORD PTR _size$[esp+8]
	mov	edi, eax
	push	DWORD PTR _buffer$[esp+12]
	push	esi
	push	edi
	call	_uncompress
	add	esp, 20					; 00000014H
	test	eax, eax
	je	SHORT $LN4@zipUncompr

; 937  :         free(retBuf);

	push	edi
	call	_free
	add	esp, 4

; 938  :         retBuf = NULL;
; 939  :     }
; 940  : 
; 941  :     return retBuf;

	xor	eax, eax
	pop	edi

; 942  : }

	pop	esi
	ret	0
$LN4@zipUncompr:

; 938  :         retBuf = NULL;
; 939  :     }
; 940  : 
; 941  :     return retBuf;

	mov	eax, edi
	pop	edi

; 942  : }

	pop	esi
	ret	0
_zipUncompress ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\utils\ziphelper.c
;	COMDAT _zipCompress
_TEXT	SEGMENT
_buffer$ = 8						; size = 4
_size$ = 12						; size = 4
_retSize$ = 16						; size = 4
_zipCompress PROC					; COMDAT

; 918  : {

	push	ebx
	push	esi

; 919  :     void* retBuf;
; 920  : 
; 921  :     *retSize = (size * 1001) / 1000 + 12;

	mov	esi, DWORD PTR _retSize$[esp+4]
	mov	eax, 274877907				; 10624dd3H
	push	edi
	mov	edi, DWORD PTR _size$[esp+8]
	imul	ecx, edi, 1001
	imul	ecx
	sar	edx, 6
	mov	eax, edx
	add	edx, 12					; 0000000cH
	shr	eax, 31					; 0000001fH
	add	eax, edx

; 922  :     retBuf = malloc(*retSize);

	push	eax
	mov	DWORD PTR [esi], eax
	call	_malloc

; 923  : 
; 924  :     if (compress(retBuf, retSize, buffer, size) != Z_OK) {

	push	edi
	push	DWORD PTR _buffer$[esp+16]
	mov	ebx, eax
	push	esi
	push	ebx
	call	_compress
	add	esp, 20					; 00000014H
	test	eax, eax
	je	SHORT $LN4@zipCompres

; 925  :         free(retBuf);

	push	ebx
	call	_free
	add	esp, 4

; 926  :         retBuf = NULL;
; 927  :     }
; 928  : 
; 929  :     return retBuf;

	xor	eax, eax
	pop	edi

; 930  : }

	pop	esi
	pop	ebx
	ret	0
$LN4@zipCompres:
	pop	edi
	pop	esi
	mov	eax, ebx
	pop	ebx
	ret	0
_zipCompress ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\utils\ziphelper.c
;	COMDAT _zipExtract
_TEXT	SEGMENT
_c$1$ = -373						; size = 1
_i$1$ = -372						; size = 4
_uf$GSCopy$1$ = -368					; size = 4
_buf$1$ = -364						; size = 4
_filename_withoutpath$1$ = -360				; size = 4
_password$GSCopy$1$ = -356				; size = 4
_progress_callback$GSCopy$1$ = -352			; size = 4
_gi$ = -348						; size = 8
_file_info$1 = -340					; size = 80
_filename_inzip$2 = -260				; size = 256
__$ArrayPad$ = -4					; size = 4
_uf$ = 8						; size = 4
_overwrite$ = 12					; size = 4
_password$ = 16						; size = 4
_progress_callback$ = 20				; size = 4
_zipExtract PROC					; COMDAT

; 884  : {

	sub	esp, 376				; 00000178H
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, esp
	mov	DWORD PTR __$ArrayPad$[esp+376], eax
	mov	eax, DWORD PTR _password$[esp+372]
	push	ebx
	mov	ebx, DWORD PTR _progress_callback$[esp+376]
	push	esi
	mov	esi, DWORD PTR _uf$[esp+380]
	mov	DWORD PTR _password$GSCopy$1$[esp+384], eax

; 885  :     uLong i;
; 886  :     unz_global_info gi;
; 887  :     int err;
; 888  : 
; 889  :     err = unzGetGlobalInfo(uf,&gi);

	lea	eax, DWORD PTR _gi$[esp+384]
	push	eax
	push	esi
	mov	DWORD PTR _uf$GSCopy$1$[esp+392], esi
	mov	DWORD PTR _progress_callback$GSCopy$1$[esp+392], ebx
	call	_unzGetGlobalInfo
	add	esp, 8

; 890  :     if (err!=UNZ_OK) {

	test	eax, eax
	je	SHORT $LN5@zipExtract

; 891  :         printf("error %d with zipfile in unzGetGlobalInfo \n",err);

	push	eax
	push	OFFSET ??_C@_0CM@EPAEMPIG@error?5?$CFd?5with?5zipfile?5in?5unzGet@
	call	_printf
	add	esp, 8

; 892  :         return 0;

	xor	eax, eax
	pop	esi

; 915  : }

	pop	ebx
	mov	ecx, DWORD PTR __$ArrayPad$[esp+376]
	xor	ecx, esp
	call	@__security_check_cookie@4
	add	esp, 376				; 00000178H
	ret	0
$LN5@zipExtract:

; 893  :     }
; 894  : 
; 895  :     for (i = 0; i < gi.number_entry; i++)

	mov	eax, DWORD PTR _gi$[esp+384]
	push	ebp
	push	edi
	xor	edi, edi
	mov	DWORD PTR _i$1$[esp+392], edi
	test	eax, eax
	je	$LN3@zipExtract
$LL4@zipExtract:

; 896  :     {
; 897  :         if( progress_callback ) {

	test	ebx, ebx
	je	SHORT $LN6@zipExtract

; 898  :             progress_callback(gi.number_entry, i);

	push	edi
	push	eax
	call	ebx
	add	esp, 8
$LN6@zipExtract:

; 793  :     err = unzGetCurrentFileInfo(uf,&file_info,filename_inzip,sizeof(filename_inzip),NULL,0,NULL,0);

	push	0
	push	0
	push	0
	push	0
	push	256					; 00000100H
	lea	eax, DWORD PTR _filename_inzip$2[esp+412]
	push	eax
	lea	eax, DWORD PTR _file_info$1[esp+416]
	push	eax
	push	esi
	call	_unzGetCurrentFileInfo
	add	esp, 32					; 00000020H

; 794  : 
; 795  :     if( err != UNZ_OK ) {

	test	eax, eax
	jne	$LN84@zipExtract

; 797  :         return 0;
; 798  :     }
; 799  : 
; 800  :     size_buf = WRITEBUFFERSIZE;
; 801  :     buf = (void*)malloc(size_buf);

	push	8192					; 00002000H
	call	_malloc

; 802  : 
; 803  :     p = filename_withoutpath = filename_inzip;
; 804  :     while ((*p) != '\0') {

	mov	cl, BYTE PTR _filename_inzip$2[esp+396]
	lea	ebx, DWORD PTR _filename_inzip$2[esp+396]
	add	esp, 4
	mov	ebp, eax
	mov	DWORD PTR _buf$1$[esp+392], ebp
	mov	edx, ebx
	test	cl, cl
	je	$LN80@zipExtract
$LL12@zipExtract:

; 805  :         if (((*p)=='/') || ((*p)=='\\'))

	cmp	cl, 47					; 0000002fH
	je	SHORT $LN70@zipExtract
	cmp	cl, 92					; 0000005cH
	jne	SHORT $LN18@zipExtract
$LN70@zipExtract:

; 806  :             filename_withoutpath = p+1;

	lea	ebx, DWORD PTR [edx+1]
$LN18@zipExtract:

; 802  : 
; 803  :     p = filename_withoutpath = filename_inzip;
; 804  :     while ((*p) != '\0') {

	mov	cl, BYTE PTR [edx+1]

; 807  :         p++;

	inc	edx
	test	cl, cl
	jne	SHORT $LL12@zipExtract
	mov	DWORD PTR _filename_withoutpath$1$[esp+392], ebx

; 808  :     }
; 809  : 
; 810  :     if ((*filename_withoutpath)=='\0') {

	cmp	BYTE PTR [ebx], cl
	je	$LN80@zipExtract

; 812  :     }else{
; 813  :         const char* write_filename;
; 814  :         int skip=0;
; 815  : 
; 816  :         write_filename = filename_inzip;
; 817  : 
; 818  :         err = unzOpenCurrentFilePassword(uf,password);

	push	DWORD PTR _password$GSCopy$1$[esp+392]
	push	esi
	call	_unzOpenCurrentFilePassword
	mov	esi, eax
	add	esp, 8

; 819  :         if (err!=UNZ_OK) {

	test	esi, esi
	je	SHORT $LN92@zipExtract

; 820  :             printf("error %d with zipfile in unzOpenCurrentFilePassword\n",err);

	push	esi
	push	OFFSET ??_C@_0DF@EHJPKLOI@error?5?$CFd?5with?5zipfile?5in?5unzOpe@
	call	_printf
	add	esp, 8

; 821  :         }
; 822  : 
; 823  :         if ((overwrite==0) && (err==UNZ_OK)) {

	test	esi, esi
	jne	$LN33@zipExtract
$LN92@zipExtract:
	cmp	DWORD PTR _overwrite$[esp+388], 0
	jne	SHORT $LN81@zipExtract

; 824  :             FILE* ftestexist = fopen(write_filename,"rb");

	lea	eax, DWORD PTR _filename_inzip$2[esp+392]
	push	OFFSET ??_C@_02JDPG@rb@
	push	eax
	call	_fopen
	add	esp, 8

; 825  :             if (ftestexist!=NULL) {

	test	eax, eax
	je	SHORT $LN81@zipExtract

; 826  :                 fclose(ftestexist);

	push	eax
	call	_fclose
	add	esp, 4

; 827  :                 skip = 1;
; 828  :             }
; 829  :         }
; 830  : 
; 831  :         if ((skip==0) && (err==UNZ_OK)) {

	jmp	$LN79@zipExtract
$LN81@zipExtract:

; 832  :             fout=fopen(write_filename,"wb");

	lea	eax, DWORD PTR _filename_inzip$2[esp+392]
	push	OFFSET ??_C@_02GMLFBBN@wb@
	push	eax
	call	_fopen
	mov	edi, eax
	add	esp, 8

; 833  : 
; 834  :             /* some zipfile don't contain directory alone before file */
; 835  :             if( (fout==NULL) && (filename_withoutpath!=(char*)filename_inzip) ) {

	test	edi, edi
	jne	$LN77@zipExtract
	lea	eax, DWORD PTR _filename_inzip$2[esp+392]
	cmp	ebx, eax
	je	$LN78@zipExtract

; 836  :                 char c=*(filename_withoutpath-1);

	mov	al, BYTE PTR [ebx-1]

; 747  :     int len = (int)strlen(newdir);

	lea	esi, DWORD PTR _filename_inzip$2[esp+392]

; 836  :                 char c=*(filename_withoutpath-1);

	mov	BYTE PTR _c$1$[esp+392], al

; 747  :     int len = (int)strlen(newdir);

	lea	ecx, DWORD PTR [esi+1]

; 837  :                 *(filename_withoutpath-1)='\0';

	mov	BYTE PTR [ebx-1], 0
$LL86@zipExtract:

; 747  :     int len = (int)strlen(newdir);

	mov	al, BYTE PTR [esi]
	inc	esi
	test	al, al
	jne	SHORT $LL86@zipExtract
	sub	esi, ecx

; 748  : 
; 749  :     if (len <= 0) return 0;

	test	esi, esi
	jle	$LN37@zipExtract

; 750  : 
; 751  :     buffer = (char*)malloc(len+1);

	lea	eax, DWORD PTR [esi+1]
	push	eax
	call	_malloc
	mov	ebp, eax

; 752  :     strcpy(buffer,newdir);

	lea	edx, DWORD PTR _filename_inzip$2[esp+396]
	mov	edi, ebp
	mov	eax, edx
	add	esp, 4
	sub	edi, eax
	npad	1
$LL48@zipExtract:
	mov	cl, BYTE PTR [edx]
	lea	edx, DWORD PTR [edx+1]
	mov	BYTE PTR [edi+edx-1], cl
	test	cl, cl
	jne	SHORT $LL48@zipExtract

; 753  : 
; 754  :     if (buffer[len-1] == '/') {

	cmp	BYTE PTR [esi+ebp-1], 47		; 0000002fH
	jne	SHORT $LN43@zipExtract

; 755  :         buffer[len-1] = '\0';

	mov	BYTE PTR [esi+ebp-1], cl
$LN43@zipExtract:

; 756  :     }
; 757  :     if (MKDIR(buffer) == 0) {

	push	ebp
	call	__mkdir
	add	esp, 4
	test	eax, eax
	je	SHORT $LN56@zipExtract

; 758  :         free(buffer);
; 759  :         return 1;
; 760  :     }
; 761  : 
; 762  :     p = buffer+1;

	lea	esi, DWORD PTR [ebp+1]
$LL38@zipExtract:

; 763  :     while (1) {
; 764  :         char hold;
; 765  : 
; 766  :         while(*p && *p != '\\' && *p != '/') p++;

	mov	bl, BYTE PTR [esi]
	test	bl, bl
	je	SHORT $LN87@zipExtract

; 805  :         if (((*p)=='/') || ((*p)=='\\'))

	mov	al, bl
$LL40@zipExtract:

; 766  :         while(*p && *p != '\\' && *p != '/') p++;

	mov	bl, al
	cmp	al, 92					; 0000005cH
	je	SHORT $LN87@zipExtract
	cmp	al, 47					; 0000002fH
	je	SHORT $LN87@zipExtract
	mov	bl, BYTE PTR [esi+1]
	inc	esi
	mov	al, bl
	test	bl, bl
	jne	SHORT $LL40@zipExtract
$LN87@zipExtract:

; 767  :         hold = *p;
; 768  :         *p = 0;
; 769  :         if ((MKDIR(buffer) == -1) && (errno == ENOENT))

	push	ebp
	mov	BYTE PTR [esi], 0
	call	__mkdir
	add	esp, 4
	cmp	eax, -1
	jne	SHORT $LN45@zipExtract
	call	__errno
	cmp	DWORD PTR [eax], 2
	je	SHORT $LN55@zipExtract
$LN45@zipExtract:

; 774  :         }
; 775  :         if (hold == 0) break;

	test	bl, bl
	je	SHORT $LN56@zipExtract

; 776  :         *p++ = hold;

	mov	BYTE PTR [esi], bl
	inc	esi

; 777  :     }

	jmp	SHORT $LL38@zipExtract
$LN55@zipExtract:

; 770  :         {
; 771  :             printf("couldn't create directory %s\n",buffer);

	push	ebp
	push	OFFSET ??_C@_0BO@HCBPGKCG@couldn?8t?5create?5directory?5?$CFs?6@
	call	_printf

; 772  :             free(buffer);

	push	ebp
	call	_free
	add	esp, 12					; 0000000cH

; 773  :             return 0;

	jmp	SHORT $LN93@zipExtract
$LN56@zipExtract:

; 778  :     free(buffer);

	push	ebp
	call	_free
	add	esp, 4
$LN93@zipExtract:

; 839  :                 *(filename_withoutpath-1)=c;

	mov	ebp, DWORD PTR _buf$1$[esp+392]
$LN37@zipExtract:
	mov	eax, DWORD PTR _filename_withoutpath$1$[esp+392]
	mov	cl, BYTE PTR _c$1$[esp+392]

; 840  :                 fout=fopen(write_filename,"wb");

	push	OFFSET ??_C@_02GMLFBBN@wb@
	mov	BYTE PTR [eax-1], cl
	lea	eax, DWORD PTR _filename_inzip$2[esp+396]
	push	eax
	call	_fopen
	mov	edi, eax
	add	esp, 8

; 841  :             }
; 842  : 
; 843  :             if( fout == NULL ) {

	test	edi, edi
	jne	SHORT $LN77@zipExtract
$LN78@zipExtract:

; 844  :                 printf("error opening %s\n",write_filename);

	lea	eax, DWORD PTR _filename_inzip$2[esp+392]
	push	eax
	push	OFFSET ??_C@_0BC@CBHACCGB@error?5opening?5?$CFs?6@
	call	_printf
	add	esp, 8

; 845  :             }
; 846  :         }
; 847  : 
; 848  :         if (fout!=NULL)

	jmp	$LN94@zipExtract
$LN77@zipExtract:

; 849  :         {
; 850  :             printf(" extracting: %s\n",write_filename);

	lea	eax, DWORD PTR _filename_inzip$2[esp+392]
	push	eax
	push	OFFSET ??_C@_0BB@BKFCOHHC@?5extracting?3?5?$CFs?6@
	call	_printf
	mov	ebx, DWORD PTR _uf$GSCopy$1$[esp+400]
	add	esp, 8
$LL16@zipExtract:

; 851  :             do {
; 852  :                 err = unzReadCurrentFile(uf,buf,size_buf);

	push	8192					; 00002000H
	push	ebp
	push	ebx
	call	_unzReadCurrentFile
	mov	esi, eax
	add	esp, 12					; 0000000cH

; 853  :                 if( err < 0 ) {

	test	esi, esi
	js	SHORT $LN57@zipExtract

; 855  :                     break;
; 856  :                 }
; 857  :                 if( err > 0 ) {

	jle	SHORT $LN15@zipExtract

; 858  :                     if (fwrite(buf,err,1,fout)!=1) {

	push	edi
	push	1
	push	esi
	push	ebp
	call	_fwrite
	add	esp, 16					; 00000010H
	cmp	eax, 1
	je	SHORT $LL16@zipExtract

; 859  :                         printf("error in writing extracted file\n");

	push	OFFSET ??_C@_0CB@EOJIBDBE@error?5in?5writing?5extracted?5file@
	call	_printf
	add	esp, 4

; 860  :                         err=UNZ_ERRNO;

	or	esi, -1
	jmp	SHORT $LN15@zipExtract
$LN57@zipExtract:

; 854  :                     printf("error %d with zipfile in unzReadCurrentFile\n",err);

	push	esi
	push	OFFSET ??_C@_0CN@ENDBCDIB@error?5?$CFd?5with?5zipfile?5in?5unzRea@
	call	_printf
	add	esp, 8
$LN15@zipExtract:

; 861  :                         break;
; 862  :                     }
; 863  :                 }
; 864  :             }while( err > 0 );
; 865  :             if( fout ) fclose(fout);

	test	edi, edi
	je	SHORT $LN32@zipExtract
	push	edi
	call	_fclose
	add	esp, 4
$LN32@zipExtract:

; 866  :         }
; 867  : 
; 868  :         if(err == UNZ_OK) {

	test	esi, esi
	jne	SHORT $LN88@zipExtract
$LN94@zipExtract:

; 869  :             err = unzCloseCurrentFile (uf);

	mov	edi, DWORD PTR _i$1$[esp+392]
$LN79@zipExtract:
	mov	esi, DWORD PTR _uf$GSCopy$1$[esp+392]
	push	esi
	call	_unzCloseCurrentFile
	add	esp, 4

; 870  :             if( err != UNZ_OK ) {

	test	eax, eax
	je	SHORT $LN34@zipExtract

; 871  :                 printf("error %d with zipfile in unzCloseCurrentFile\n",err);

	push	eax
	push	OFFSET ??_C@_0CO@EMCAOMAG@error?5?$CFd?5with?5zipfile?5in?5unzClo@
	call	_printf
	add	esp, 8

; 872  :             }
; 873  :         }else{

	jmp	SHORT $LN34@zipExtract
$LN88@zipExtract:

; 866  :         }
; 867  : 
; 868  :         if(err == UNZ_OK) {

	mov	edi, DWORD PTR _i$1$[esp+392]
$LN33@zipExtract:

; 874  :             unzCloseCurrentFile(uf); /* don't lose the error */

	mov	esi, DWORD PTR _uf$GSCopy$1$[esp+392]
	push	esi
	call	_unzCloseCurrentFile
	jmp	SHORT $LN95@zipExtract
$LN80@zipExtract:

; 811  :         MKDIR(filename_inzip);

	lea	eax, DWORD PTR _filename_inzip$2[esp+392]
	push	eax
	call	__mkdir
$LN95@zipExtract:

; 875  :         }
; 876  :     }
; 877  : 
; 878  :     free(buf);

	add	esp, 4
$LN34@zipExtract:
	push	ebp
	call	_free

; 902  :         }
; 903  :         if ((i+1) < gi.number_entry)

	mov	eax, DWORD PTR _gi$[esp+396]
	inc	edi

; 878  :     free(buf);

	add	esp, 4

; 902  :         }
; 903  :         if ((i+1) < gi.number_entry)

	mov	DWORD PTR _i$1$[esp+392], edi
	cmp	edi, eax
	jae	SHORT $LN3@zipExtract

; 904  :         {
; 905  :             err = unzGoToNextFile(uf);

	push	esi
	call	_unzGoToNextFile
	add	esp, 4

; 906  :             if (err!=UNZ_OK)

	test	eax, eax
	jne	SHORT $LN60@zipExtract

; 893  :     }
; 894  : 
; 895  :     for (i = 0; i < gi.number_entry; i++)

	mov	eax, DWORD PTR _gi$[esp+392]
	cmp	edi, eax
	jae	SHORT $LN3@zipExtract
	mov	ebx, DWORD PTR _progress_callback$GSCopy$1$[esp+392]
	jmp	$LL4@zipExtract
$LN60@zipExtract:

; 907  :             {
; 908  :                 printf("error %d with zipfile in unzGoToNextFile\n",err);

	push	eax
	push	OFFSET ??_C@_0CK@HCGKKBDJ@error?5?$CFd?5with?5zipfile?5in?5unzGoT@
	call	_printf
	add	esp, 8

; 909  :                 return 0;

	xor	eax, eax
	jmp	SHORT $LN89@zipExtract
$LN84@zipExtract:

; 796  :         printf("error %d with zipfile in unzGetCurrentFileInfo\n",err);

	push	eax
	push	OFFSET ??_C@_0DA@JKFADJED@error?5?$CFd?5with?5zipfile?5in?5unzGet@
	call	_printf
	add	esp, 8

; 899  :         }
; 900  :         if( !zipExtractCurrentfile(uf, overwrite, password) ) {
; 901  :             return 0;

	xor	eax, eax
	jmp	SHORT $LN89@zipExtract
$LN3@zipExtract:

; 910  :             }
; 911  :         }
; 912  :     }
; 913  : 
; 914  :     return 1;

	mov	eax, 1
$LN89@zipExtract:

; 915  : }

	mov	ecx, DWORD PTR __$ArrayPad$[esp+392]
	pop	edi
	pop	ebp
	pop	esi
	pop	ebx
	xor	ecx, esp
	call	@__security_check_cookie@4
	add	esp, 376				; 00000178H
	ret	0
_zipExtract ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\utils\ziphelper.c
;	COMDAT _zipExtractCurrentfile
_TEXT	SEGMENT
_uf$GSCopy$1$ = -352					; size = 4
_filename_withoutpath$1$ = -348				; size = 4
_buf$1$ = -344						; size = 4
_file_info$ = -340					; size = 80
_filename_inzip$ = -260					; size = 256
__$ArrayPad$ = -4					; size = 4
_uf$ = 8						; size = 4
_overwrite$ = 12					; size = 4
_password$ = 16						; size = 4
_zipExtractCurrentfile PROC				; COMDAT

; 783  : {

	sub	esp, 352				; 00000160H
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, esp
	mov	DWORD PTR __$ArrayPad$[esp+352], eax
	mov	eax, DWORD PTR _uf$[esp+348]

; 784  :     char filename_inzip[256];
; 785  :     char* filename_withoutpath;
; 786  :     char* p;
; 787  :     int err=UNZ_OK;
; 788  :     FILE *fout=NULL;
; 789  :     void* buf;
; 790  :     uInt size_buf;
; 791  : 
; 792  :     unz_file_info file_info;
; 793  :     err = unzGetCurrentFileInfo(uf,&file_info,filename_inzip,sizeof(filename_inzip),NULL,0,NULL,0);

	lea	ecx, DWORD PTR _filename_inzip$[esp+352]
	push	esi
	mov	esi, DWORD PTR _password$[esp+352]
	push	0
	push	0
	push	0
	push	0
	push	256					; 00000100H
	push	ecx
	lea	ecx, DWORD PTR _file_info$[esp+380]
	mov	DWORD PTR _uf$GSCopy$1$[esp+380], eax
	push	ecx
	push	eax
	call	_unzGetCurrentFileInfo
	add	esp, 32					; 00000020H

; 794  : 
; 795  :     if( err != UNZ_OK ) {

	test	eax, eax
	je	SHORT $LN7@zipExtract

; 796  :         printf("error %d with zipfile in unzGetCurrentFileInfo\n",err);

	push	eax
	push	OFFSET ??_C@_0DA@JKFADJED@error?5?$CFd?5with?5zipfile?5in?5unzGet@
	call	_printf
	add	esp, 8

; 797  :         return 0;

	xor	eax, eax
	pop	esi

; 879  :     return 1;
; 880  : }

	mov	ecx, DWORD PTR __$ArrayPad$[esp+352]
	xor	ecx, esp
	call	@__security_check_cookie@4
	add	esp, 352				; 00000160H
	ret	0
$LN7@zipExtract:
	push	ebx
	push	ebp
	push	edi

; 798  :     }
; 799  : 
; 800  :     size_buf = WRITEBUFFERSIZE;
; 801  :     buf = (void*)malloc(size_buf);

	push	8192					; 00002000H
	call	_malloc

; 802  : 
; 803  :     p = filename_withoutpath = filename_inzip;
; 804  :     while ((*p) != '\0') {

	mov	cl, BYTE PTR _filename_inzip$[esp+372]
	lea	ebp, DWORD PTR _filename_inzip$[esp+372]
	add	esp, 4
	mov	ebx, eax
	mov	DWORD PTR _buf$1$[esp+368], ebx
	mov	edx, ebp
	test	cl, cl
	je	$LN64@zipExtract
	npad	7
$LL2@zipExtract:

; 805  :         if (((*p)=='/') || ((*p)=='\\'))

	cmp	cl, 47					; 0000002fH
	je	SHORT $LN55@zipExtract
	cmp	cl, 92					; 0000005cH
	jne	SHORT $LN8@zipExtract
$LN55@zipExtract:

; 806  :             filename_withoutpath = p+1;

	lea	ebp, DWORD PTR [edx+1]
$LN8@zipExtract:

; 802  : 
; 803  :     p = filename_withoutpath = filename_inzip;
; 804  :     while ((*p) != '\0') {

	mov	cl, BYTE PTR [edx+1]

; 807  :         p++;

	inc	edx
	test	cl, cl
	jne	SHORT $LL2@zipExtract

; 808  :     }
; 809  : 
; 810  :     if ((*filename_withoutpath)=='\0') {

	mov	DWORD PTR _filename_withoutpath$1$[esp+368], ebp
	cmp	BYTE PTR [ebp], cl
	je	$LN64@zipExtract

; 812  :     }else{
; 813  :         const char* write_filename;
; 814  :         int skip=0;
; 815  : 
; 816  :         write_filename = filename_inzip;
; 817  : 
; 818  :         err = unzOpenCurrentFilePassword(uf,password);

	push	esi
	push	DWORD PTR _uf$GSCopy$1$[esp+372]
	call	_unzOpenCurrentFilePassword
	mov	esi, eax
	add	esp, 8

; 819  :         if (err!=UNZ_OK) {

	test	esi, esi
	je	SHORT $LN71@zipExtract

; 820  :             printf("error %d with zipfile in unzOpenCurrentFilePassword\n",err);

	push	esi
	push	OFFSET ??_C@_0DF@EHJPKLOI@error?5?$CFd?5with?5zipfile?5in?5unzOpe@
	call	_printf
	add	esp, 8

; 821  :         }
; 822  : 
; 823  :         if ((overwrite==0) && (err==UNZ_OK)) {

	test	esi, esi
	jne	$LN23@zipExtract
$LN71@zipExtract:
	cmp	DWORD PTR _overwrite$[esp+364], 0
	jne	SHORT $LN65@zipExtract

; 824  :             FILE* ftestexist = fopen(write_filename,"rb");

	lea	eax, DWORD PTR _filename_inzip$[esp+368]
	push	OFFSET ??_C@_02JDPG@rb@
	push	eax
	call	_fopen
	add	esp, 8

; 825  :             if (ftestexist!=NULL) {

	test	eax, eax
	je	SHORT $LN65@zipExtract

; 826  :                 fclose(ftestexist);

	push	eax
	call	_fclose
	add	esp, 4

; 827  :                 skip = 1;
; 828  :             }
; 829  :         }
; 830  : 
; 831  :         if ((skip==0) && (err==UNZ_OK)) {

	jmp	$LN63@zipExtract
$LN65@zipExtract:

; 832  :             fout=fopen(write_filename,"wb");

	lea	eax, DWORD PTR _filename_inzip$[esp+368]
	push	OFFSET ??_C@_02GMLFBBN@wb@
	push	eax
	call	_fopen
	mov	edi, eax
	add	esp, 8

; 833  : 
; 834  :             /* some zipfile don't contain directory alone before file */
; 835  :             if( (fout==NULL) && (filename_withoutpath!=(char*)filename_inzip) ) {

	test	edi, edi
	jne	$LN61@zipExtract
	lea	eax, DWORD PTR _filename_inzip$[esp+368]
	cmp	ebp, eax
	je	$LN62@zipExtract

; 836  :                 char c=*(filename_withoutpath-1);

	mov	bh, BYTE PTR [ebp-1]

; 747  :     int len = (int)strlen(newdir);

	mov	esi, eax

; 837  :                 *(filename_withoutpath-1)='\0';

	mov	BYTE PTR [ebp-1], 0

; 747  :     int len = (int)strlen(newdir);

	lea	ecx, DWORD PTR [esi+1]
	npad	3
$LL67@zipExtract:
	mov	al, BYTE PTR [esi]
	inc	esi
	test	al, al
	jne	SHORT $LL67@zipExtract
	sub	esi, ecx

; 748  : 
; 749  :     if (len <= 0) return 0;

	test	esi, esi
	jle	$LN27@zipExtract

; 750  : 
; 751  :     buffer = (char*)malloc(len+1);

	lea	eax, DWORD PTR [esi+1]
	push	eax
	call	_malloc
	mov	ebp, eax

; 752  :     strcpy(buffer,newdir);

	lea	edx, DWORD PTR _filename_inzip$[esp+372]
	mov	edi, ebp
	mov	eax, edx
	add	esp, 4
	sub	edi, eax
	npad	7
$LL38@zipExtract:
	mov	cl, BYTE PTR [edx]
	lea	edx, DWORD PTR [edx+1]
	mov	BYTE PTR [edi+edx-1], cl
	test	cl, cl
	jne	SHORT $LL38@zipExtract

; 753  : 
; 754  :     if (buffer[len-1] == '/') {

	cmp	BYTE PTR [esi+ebp-1], 47		; 0000002fH
	jne	SHORT $LN33@zipExtract

; 755  :         buffer[len-1] = '\0';

	mov	BYTE PTR [esi+ebp-1], cl
$LN33@zipExtract:

; 756  :     }
; 757  :     if (MKDIR(buffer) == 0) {

	push	ebp
	call	__mkdir
	add	esp, 4
	test	eax, eax
	je	SHORT $LN45@zipExtract

; 758  :         free(buffer);
; 759  :         return 1;
; 760  :     }
; 761  : 
; 762  :     p = buffer+1;

	lea	esi, DWORD PTR [ebp+1]
$LL28@zipExtract:

; 763  :     while (1) {
; 764  :         char hold;
; 765  : 
; 766  :         while(*p && *p != '\\' && *p != '/') p++;

	mov	bl, BYTE PTR [esi]
	test	bl, bl
	je	SHORT $LN68@zipExtract

; 805  :         if (((*p)=='/') || ((*p)=='\\'))

	mov	al, bl
$LL30@zipExtract:

; 766  :         while(*p && *p != '\\' && *p != '/') p++;

	mov	bl, al
	cmp	al, 92					; 0000005cH
	je	SHORT $LN68@zipExtract
	cmp	al, 47					; 0000002fH
	je	SHORT $LN68@zipExtract
	mov	bl, BYTE PTR [esi+1]
	inc	esi
	mov	al, bl
	test	bl, bl
	jne	SHORT $LL30@zipExtract
$LN68@zipExtract:

; 767  :         hold = *p;
; 768  :         *p = 0;
; 769  :         if ((MKDIR(buffer) == -1) && (errno == ENOENT))

	push	ebp
	mov	BYTE PTR [esi], 0
	call	__mkdir
	add	esp, 4
	cmp	eax, -1
	jne	SHORT $LN35@zipExtract
	call	__errno
	cmp	DWORD PTR [eax], 2
	je	SHORT $LN44@zipExtract
$LN35@zipExtract:

; 774  :         }
; 775  :         if (hold == 0) break;

	test	bl, bl
	je	SHORT $LN45@zipExtract

; 776  :         *p++ = hold;

	mov	BYTE PTR [esi], bl
	inc	esi

; 777  :     }

	jmp	SHORT $LL28@zipExtract
$LN44@zipExtract:

; 770  :         {
; 771  :             printf("couldn't create directory %s\n",buffer);

	push	ebp
	push	OFFSET ??_C@_0BO@HCBPGKCG@couldn?8t?5create?5directory?5?$CFs?6@
	call	_printf

; 772  :             free(buffer);

	push	ebp
	call	_free
	add	esp, 12					; 0000000cH

; 773  :             return 0;

	jmp	SHORT $LN72@zipExtract
$LN45@zipExtract:

; 778  :     free(buffer);

	push	ebp
	call	_free
	add	esp, 4
$LN72@zipExtract:

; 838  :                 makedir(write_filename);
; 839  :                 *(filename_withoutpath-1)=c;

	mov	ebp, DWORD PTR _filename_withoutpath$1$[esp+368]
$LN27@zipExtract:

; 840  :                 fout=fopen(write_filename,"wb");

	lea	eax, DWORD PTR _filename_inzip$[esp+368]
	mov	BYTE PTR [ebp-1], bh
	push	OFFSET ??_C@_02GMLFBBN@wb@
	push	eax
	call	_fopen

; 841  :             }
; 842  : 
; 843  :             if( fout == NULL ) {

	mov	ebx, DWORD PTR _buf$1$[esp+376]
	mov	edi, eax
	add	esp, 8
	test	edi, edi
	jne	SHORT $LN61@zipExtract
$LN62@zipExtract:

; 844  :                 printf("error opening %s\n",write_filename);

	lea	eax, DWORD PTR _filename_inzip$[esp+368]
	push	eax
	push	OFFSET ??_C@_0BC@CBHACCGB@error?5opening?5?$CFs?6@
	call	_printf
	add	esp, 8

; 845  :             }
; 846  :         }
; 847  : 
; 848  :         if (fout!=NULL)

	jmp	SHORT $LN63@zipExtract
$LN61@zipExtract:

; 849  :         {
; 850  :             printf(" extracting: %s\n",write_filename);

	lea	eax, DWORD PTR _filename_inzip$[esp+368]
	push	eax
	push	OFFSET ??_C@_0BB@BKFCOHHC@?5extracting?3?5?$CFs?6@
	call	_printf
	add	esp, 8
$LL6@zipExtract:

; 851  :             do {
; 852  :                 err = unzReadCurrentFile(uf,buf,size_buf);

	push	8192					; 00002000H
	push	ebx
	push	DWORD PTR _uf$GSCopy$1$[esp+376]
	call	_unzReadCurrentFile
	mov	esi, eax
	add	esp, 12					; 0000000cH

; 853  :                 if( err < 0 ) {

	test	esi, esi
	js	SHORT $LN46@zipExtract

; 855  :                     break;
; 856  :                 }
; 857  :                 if( err > 0 ) {

	jle	SHORT $LN5@zipExtract

; 858  :                     if (fwrite(buf,err,1,fout)!=1) {

	push	edi
	push	1
	push	esi
	push	ebx
	call	_fwrite
	add	esp, 16					; 00000010H
	cmp	eax, 1
	je	SHORT $LL6@zipExtract

; 859  :                         printf("error in writing extracted file\n");

	push	OFFSET ??_C@_0CB@EOJIBDBE@error?5in?5writing?5extracted?5file@
	call	_printf
	add	esp, 4

; 860  :                         err=UNZ_ERRNO;

	or	esi, -1
	jmp	SHORT $LN5@zipExtract
$LN46@zipExtract:

; 854  :                     printf("error %d with zipfile in unzReadCurrentFile\n",err);

	push	esi
	push	OFFSET ??_C@_0CN@ENDBCDIB@error?5?$CFd?5with?5zipfile?5in?5unzRea@
	call	_printf
	add	esp, 8
$LN5@zipExtract:

; 861  :                         break;
; 862  :                     }
; 863  :                 }
; 864  :             }while( err > 0 );
; 865  :             if( fout ) fclose(fout);

	test	edi, edi
	je	SHORT $LN22@zipExtract
	push	edi
	call	_fclose
	add	esp, 4
$LN22@zipExtract:

; 866  :         }
; 867  : 
; 868  :         if(err == UNZ_OK) {

	test	esi, esi
	jne	SHORT $LN23@zipExtract
$LN63@zipExtract:

; 869  :             err = unzCloseCurrentFile (uf);

	push	DWORD PTR _uf$GSCopy$1$[esp+368]
	call	_unzCloseCurrentFile
	add	esp, 4

; 870  :             if( err != UNZ_OK ) {

	test	eax, eax
	je	SHORT $LN24@zipExtract

; 871  :                 printf("error %d with zipfile in unzCloseCurrentFile\n",err);

	push	eax
	push	OFFSET ??_C@_0CO@EMCAOMAG@error?5?$CFd?5with?5zipfile?5in?5unzClo@
	call	_printf
	add	esp, 8

; 872  :             }
; 873  :         }else{

	jmp	SHORT $LN24@zipExtract
$LN23@zipExtract:

; 874  :             unzCloseCurrentFile(uf); /* don't lose the error */

	push	DWORD PTR _uf$GSCopy$1$[esp+368]
	call	_unzCloseCurrentFile
	jmp	SHORT $LN73@zipExtract
$LN64@zipExtract:

; 811  :         MKDIR(filename_inzip);

	lea	eax, DWORD PTR _filename_inzip$[esp+368]
	push	eax
	call	__mkdir
$LN73@zipExtract:

; 875  :         }
; 876  :     }
; 877  : 
; 878  :     free(buf);

	add	esp, 4
$LN24@zipExtract:
	push	ebx
	call	_free

; 879  :     return 1;
; 880  : }

	mov	ecx, DWORD PTR __$ArrayPad$[esp+372]
	add	esp, 4
	mov	eax, 1
	pop	edi
	pop	ebp
	pop	ebx
	pop	esi
	xor	ecx, esp
	call	@__security_check_cookie@4
	add	esp, 352				; 00000160H
	ret	0
_zipExtractCurrentfile ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\utils\ziphelper.c
;	COMDAT _zipHasFileType
_TEXT	SEGMENT
_info$ = -348						; size = 80
_extension$ = -268					; size = 8
_tempName$ = -260					; size = 256
__$ArrayPad$ = -4					; size = 4
_zipName$ = 8						; size = 4
_ext$ = 12						; size = 4
_zipHasFileType PROC					; COMDAT

; 577  : int zipHasFileType(char* zipName, char* ext) {

	sub	esp, 348				; 0000015cH
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, esp
	mov	DWORD PTR __$ArrayPad$[esp+348], eax
	mov	eax, DWORD PTR _zipName$[esp+344]
	push	ebx
	push	edi

; 578  :     char tempName[256];
; 579  :     char extension[8];
; 580  :     unzFile zip;
; 581  :     unz_file_info info;
; 582  :     int found = 0;
; 583  :     int status;
; 584  : 
; 585  :     zip = unzOpen(zipName);

	push	eax
	xor	ebx, ebx
	call	_unzOpen
	mov	edi, eax
	add	esp, 4

; 586  :     if (!zip) {

	test	edi, edi
	jne	SHORT $LN4@zipHasFile

; 609  : 
; 610  :     return found;
; 611  : }

	pop	edi
	pop	ebx
	mov	ecx, DWORD PTR __$ArrayPad$[esp+348]
	xor	ecx, esp
	call	@__security_check_cookie@4
	add	esp, 348				; 0000015cH
	ret	0
$LN4@zipHasFile:

; 587  :         return 0;
; 588  :     }
; 589  : 
; 590  :     strcpy(extension, ext);

	mov	ecx, DWORD PTR _ext$[esp+352]
	lea	edx, DWORD PTR _extension$[esp+356]
	sub	edx, ecx
$LL7@zipHasFile:
	mov	al, BYTE PTR [ecx]
	lea	ecx, DWORD PTR [ecx+1]
	mov	BYTE PTR [edx+ecx-1], al
	test	al, al
	jne	SHORT $LL7@zipHasFile

; 52   :     while (*str) {

	mov	al, BYTE PTR _extension$[esp+356]

; 591  :     toLower(extension);

	push	esi
	lea	esi, DWORD PTR _extension$[esp+360]

; 52   :     while (*str) {

	test	al, al
	je	SHORT $LN10@zipHasFile
	npad	4
$LL9@zipHasFile:

; 53   :         *str = tolower(*str);

	movsx	eax, al
	push	eax
	call	_tolower
	mov	BYTE PTR [esi], al

; 54   :         str++;

	lea	esi, DWORD PTR [esi+1]
	mov	al, BYTE PTR [esi]
	add	esp, 4
	test	al, al
	jne	SHORT $LL9@zipHasFile
$LN10@zipHasFile:

; 592  : 
; 593  :     status = unzGoToFirstFile(zip);

	push	edi
	call	_unzGoToFirstFile

; 594  :     unzGetCurrentFileInfo(zip,&info,tempName,256,NULL,0,NULL,0);

	push	0
	push	0
	push	0
	push	0
	mov	esi, eax
	lea	eax, DWORD PTR _tempName$[esp+380]
	push	256					; 00000100H
	push	eax
	lea	eax, DWORD PTR _info$[esp+388]
	push	eax
	push	edi
	call	_unzGetCurrentFileInfo
	add	esp, 36					; 00000024H

; 595  : 
; 596  :     while (status == UNZ_OK) {

	test	esi, esi
	jne	SHORT $LN3@zipHasFile
$LL2@zipHasFile:

; 597  :         unzGetCurrentFileInfo(zip, &info, tempName, 256, NULL, 0, NULL, 0);

	push	0
	push	0
	push	0
	push	0
	push	256					; 00000100H
	lea	eax, DWORD PTR _tempName$[esp+380]
	push	eax
	lea	eax, DWORD PTR _info$[esp+384]
	push	eax
	push	edi
	call	_unzGetCurrentFileInfo

; 52   :     while (*str) {

	mov	al, BYTE PTR _tempName$[esp+392]

; 598  : 
; 599  :         toLower(tempName);

	lea	esi, DWORD PTR _tempName$[esp+392]
	add	esp, 32					; 00000020H

; 52   :     while (*str) {

	test	al, al
	je	SHORT $LN14@zipHasFile
$LL13@zipHasFile:

; 53   :         *str = tolower(*str);

	movsx	eax, al
	push	eax
	call	_tolower
	mov	BYTE PTR [esi], al

; 54   :         str++;

	lea	esi, DWORD PTR [esi+1]
	mov	al, BYTE PTR [esi]
	add	esp, 4
	test	al, al
	jne	SHORT $LL13@zipHasFile
$LN14@zipHasFile:

; 600  :         if (strstr(tempName, extension) != NULL) {

	lea	eax, DWORD PTR _extension$[esp+360]
	push	eax
	lea	eax, DWORD PTR _tempName$[esp+364]
	push	eax
	call	_strstr
	add	esp, 8
	test	eax, eax
	jne	SHORT $LN20@zipHasFile

; 602  :             break;
; 603  :         }
; 604  : 
; 605  :         status = unzGoToNextFile(zip);

	push	edi
	call	_unzGoToNextFile
	add	esp, 4
	test	eax, eax
	je	SHORT $LL2@zipHasFile

; 600  :         if (strstr(tempName, extension) != NULL) {

	jmp	SHORT $LN3@zipHasFile
$LN20@zipHasFile:

; 601  :             found = 1;

	mov	ebx, 1
$LN3@zipHasFile:

; 606  :     }
; 607  : 
; 608  :     unzClose(zip);

	push	edi
	call	_unzClose

; 609  : 
; 610  :     return found;
; 611  : }

	mov	ecx, DWORD PTR __$ArrayPad$[esp+364]
	add	esp, 4
	mov	eax, ebx
	pop	esi
	pop	edi
	pop	ebx
	xor	ecx, esp
	call	@__security_check_cookie@4
	add	esp, 348				; 0000015cH
	ret	0
_zipHasFileType ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\utils\ziphelper.c
;	COMDAT _zipGetFileList
_TEXT	SEGMENT
_fileArray$1$ = -612					; size = 4
_count$GSCopy$1$ = -608					; size = 4
_info$ = -604						; size = 80
_extension$ = -524					; size = 8
_tempName$ = -516					; size = 256
_tmp$1 = -260						; size = 256
__$ArrayPad$ = -4					; size = 4
_zipName$ = 8						; size = 4
_ext$ = 12						; size = 4
_count$ = 16						; size = 4
_zipGetFileList PROC					; COMDAT

; 677  : char* zipGetFileList(const char* zipName, const char* ext, int* count) {

	sub	esp, 612				; 00000264H
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, esp
	mov	DWORD PTR __$ArrayPad$[esp+612], eax
	mov	ecx, DWORD PTR _count$[esp+608]
	mov	eax, DWORD PTR _zipName$[esp+608]
	push	ebx
	push	ebp
	push	edi

; 678  :     char tempName[256];
; 679  :     char extension[8];
; 680  :     unzFile zip;
; 681  :     unz_file_info info;
; 682  :     char* fileArray = NULL;

	xor	ebx, ebx
	mov	DWORD PTR _count$GSCopy$1$[esp+624], ecx

; 683  :     int totalLen = 0;
; 684  :     int status;
; 685  : 
; 686  :     *count = 0;
; 687  : 
; 688  :     zip = unzOpen(zipName);

	push	eax
	mov	DWORD PTR _fileArray$1$[esp+628], ebx
	xor	edi, edi
	mov	DWORD PTR [ecx], ebx
	call	_unzOpen
	mov	ebp, eax
	add	esp, 4

; 689  :     if (!zip) {

	test	ebp, ebp
	jne	SHORT $LN4@zipGetFile

; 721  : 
; 722  :     return fileArray;
; 723  : }

	pop	edi
	pop	ebp
	pop	ebx
	mov	ecx, DWORD PTR __$ArrayPad$[esp+612]
	xor	ecx, esp
	call	@__security_check_cookie@4
	add	esp, 612				; 00000264H
	ret	0
$LN4@zipGetFile:

; 690  :         return 0;
; 691  :     }
; 692  : 
; 693  :     strcpy(extension, ext);

	mov	ecx, DWORD PTR _ext$[esp+620]
	lea	edx, DWORD PTR _extension$[esp+624]
	sub	edx, ecx
$LL7@zipGetFile:
	mov	al, BYTE PTR [ecx]
	lea	ecx, DWORD PTR [ecx+1]
	mov	BYTE PTR [edx+ecx-1], al
	test	al, al
	jne	SHORT $LL7@zipGetFile

; 52   :     while (*str) {

	mov	al, BYTE PTR _extension$[esp+624]

; 694  :     toLower(extension);

	push	esi
	lea	esi, DWORD PTR _extension$[esp+628]

; 52   :     while (*str) {

	test	al, al
	je	SHORT $LN12@zipGetFile
$LL11@zipGetFile:

; 53   :         *str = tolower(*str);

	movsx	eax, al
	push	eax
	call	_tolower
	mov	BYTE PTR [esi], al

; 54   :         str++;

	lea	esi, DWORD PTR [esi+1]
	mov	al, BYTE PTR [esi]
	add	esp, 4
	test	al, al
	jne	SHORT $LL11@zipGetFile
$LN12@zipGetFile:

; 695  : 
; 696  :     status = unzGoToFirstFile(zip);

	push	ebp
	call	_unzGoToFirstFile

; 697  :     unzGetCurrentFileInfo(zip,&info,tempName,256,NULL,0,NULL,0);

	push	0
	push	0
	push	0
	push	0
	mov	esi, eax
	lea	eax, DWORD PTR _tempName$[esp+648]
	push	256					; 00000100H
	push	eax
	lea	eax, DWORD PTR _info$[esp+656]
	push	eax
	push	ebp
	call	_unzGetCurrentFileInfo
	add	esp, 36					; 00000024H

; 698  : 
; 699  :     while (status == UNZ_OK) {

	test	esi, esi
	jne	$LN3@zipGetFile
	npad	5
$LL2@zipGetFile:

; 700  :         char tmp[256];
; 701  : 
; 702  :         unzGetCurrentFileInfo(zip, &info, tempName, 256, NULL, 0, NULL, 0);

	push	0
	push	0
	push	0
	push	0
	push	256					; 00000100H
	lea	eax, DWORD PTR _tempName$[esp+648]
	push	eax
	lea	eax, DWORD PTR _info$[esp+652]
	push	eax
	push	ebp
	call	_unzGetCurrentFileInfo
	add	esp, 32					; 00000020H
	xor	eax, eax
	npad	11
$LL8@zipGetFile:

; 703  : 
; 704  :         strcpy(tmp, tempName);

	mov	cl, BYTE PTR _tempName$[esp+eax+628]
	mov	BYTE PTR _tmp$1[esp+eax+628], cl
	inc	eax
	test	cl, cl
	jne	SHORT $LL8@zipGetFile

; 52   :     while (*str) {

	mov	al, BYTE PTR _tmp$1[esp+628]

; 705  : 
; 706  :         toLower(tmp);

	lea	esi, DWORD PTR _tmp$1[esp+628]

; 52   :     while (*str) {

	test	al, al
	je	SHORT $LN16@zipGetFile
$LL15@zipGetFile:

; 53   :         *str = tolower(*str);

	movsx	eax, al
	push	eax
	call	_tolower
	mov	BYTE PTR [esi], al

; 54   :         str++;

	lea	esi, DWORD PTR [esi+1]
	mov	al, BYTE PTR [esi]
	add	esp, 4
	test	al, al
	jne	SHORT $LL15@zipGetFile
$LN16@zipGetFile:

; 707  :         if (strstr(tmp, extension) != NULL) {

	lea	eax, DWORD PTR _extension$[esp+628]
	push	eax
	lea	eax, DWORD PTR _tmp$1[esp+632]
	push	eax
	call	_strstr
	add	esp, 8
	test	eax, eax
	je	SHORT $LN5@zipGetFile

; 708  :             int entryLen = strlen(tempName) + 1;

	lea	ecx, DWORD PTR _tempName$[esp+628]
	lea	edx, DWORD PTR [ecx+1]
	npad	7
$LL39@zipGetFile:
	mov	al, BYTE PTR [ecx]
	inc	ecx
	test	al, al
	jne	SHORT $LL39@zipGetFile
	sub	ecx, edx

; 709  :             fileArray = realloc(fileArray, totalLen +  entryLen + 1);

	lea	ebx, DWORD PTR [ecx+edi]
	lea	eax, DWORD PTR [ebx+2]
	push	eax
	push	DWORD PTR _fileArray$1$[esp+632]
	call	_realloc

; 710  :             strcpy(fileArray + totalLen, tempName);

	lea	edx, DWORD PTR _tempName$[esp+636]
	mov	DWORD PTR _fileArray$1$[esp+636], eax
	mov	ecx, edx
	add	esp, 8
	sub	edi, ecx
	lea	esi, DWORD PTR [edi+eax]
	npad	5
$LL9@zipGetFile:
	mov	cl, BYTE PTR [edx]
	lea	edx, DWORD PTR [edx+1]
	mov	BYTE PTR [esi+edx-1], cl
	test	cl, cl
	jne	SHORT $LL9@zipGetFile

; 711  :             totalLen += entryLen;

	lea	edi, DWORD PTR [ebx+1]

; 712  :             fileArray[totalLen] = '\0'; // double null termination at end
; 713  : 
; 714  :             *count = *count + 1;

	mov	ebx, DWORD PTR _count$GSCopy$1$[esp+628]
	mov	BYTE PTR [edi+eax], cl
	inc	DWORD PTR [ebx]
$LN5@zipGetFile:

; 715  :         }
; 716  : 
; 717  :         status = unzGoToNextFile(zip);

	push	ebp
	call	_unzGoToNextFile
	add	esp, 4
	test	eax, eax
	je	$LL2@zipGetFile
	mov	ebx, DWORD PTR _fileArray$1$[esp+628]
$LN3@zipGetFile:

; 718  :     }
; 719  : 
; 720  :     unzClose(zip);

	push	ebp
	call	_unzClose

; 721  : 
; 722  :     return fileArray;
; 723  : }

	mov	ecx, DWORD PTR __$ArrayPad$[esp+632]
	add	esp, 4
	mov	eax, ebx
	pop	esi
	pop	edi
	pop	ebp
	pop	ebx
	xor	ecx, esp
	call	@__security_check_cookie@4
	add	esp, 612				; 00000264H
	ret	0
_zipGetFileList ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\utils\ziphelper.c
;	COMDAT _zipFileExists
_TEXT	SEGMENT
_name$ = -260						; size = 256
__$ArrayPad$ = -4					; size = 4
_zipName$ = 8						; size = 4
_fileName$ = 12						; size = 4
_zipFileExists PROC					; COMDAT

; 628  : {

	sub	esp, 260				; 00000104H
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, esp
	mov	DWORD PTR __$ArrayPad$[esp+260], eax

; 629  :     char name[256];
; 630  :     unzFile zip;
; 631  : 
; 632  :     if (fileName[0] == '*') {

	mov	ecx, DWORD PTR _fileName$[esp+256]
	push	esi
	push	edi
	mov	edi, DWORD PTR _zipName$[esp+264]
	cmp	BYTE PTR [ecx], 42			; 0000002aH
	jne	$LN2@zipFileExi

; 633  :         strcpy(name, zipName);

	lea	esi, DWORD PTR _name$[esp+268]
	mov	edx, edi
	sub	esi, edi
$LL8@zipFileExi:
	mov	al, BYTE PTR [edx]
	lea	edx, DWORD PTR [edx+1]
	mov	BYTE PTR [esi+edx-1], al
	test	al, al
	jne	SHORT $LL8@zipFileExi

; 634  :         name[strlen(zipName) - 3] = fileName[strlen(fileName) - 3];

	mov	edx, ecx
	lea	esi, DWORD PTR [edx+1]
$LL17@zipFileExi:
	mov	al, BYTE PTR [edx]
	inc	edx
	test	al, al
	jne	SHORT $LL17@zipFileExi
	sub	edx, esi
	mov	esi, edi
	push	ebx
	lea	ebx, DWORD PTR [esi+1]
$LL18@zipFileExi:
	mov	al, BYTE PTR [esi]
	inc	esi
	test	al, al
	jne	SHORT $LL18@zipFileExi
	mov	al, BYTE PTR [edx+ecx-3]
	sub	esi, ebx

; 635  :         name[strlen(zipName) - 2] = fileName[strlen(fileName) - 2];

	mov	edx, ecx
	mov	BYTE PTR _name$[esp+esi+269], al
	lea	esi, DWORD PTR [edx+1]
	npad	4
$LL19@zipFileExi:
	mov	al, BYTE PTR [edx]
	inc	edx
	test	al, al
	jne	SHORT $LL19@zipFileExi
	sub	edx, esi
	mov	esi, edi
	lea	ebx, DWORD PTR [esi+1]
	npad	2
$LL20@zipFileExi:
	mov	al, BYTE PTR [esi]
	inc	esi
	test	al, al
	jne	SHORT $LL20@zipFileExi
	mov	al, BYTE PTR [edx+ecx-2]
	sub	esi, ebx
	mov	BYTE PTR _name$[esp+esi+270], al

; 636  :         name[strlen(zipName) - 1] = fileName[strlen(fileName) - 1];

	mov	esi, ecx
	lea	edx, DWORD PTR [esi+1]
$LL21@zipFileExi:
	mov	al, BYTE PTR [esi]
	inc	esi
	test	al, al
	jne	SHORT $LL21@zipFileExi
	sub	esi, edx
	mov	edx, edi
	lea	ebx, DWORD PTR [edx+1]
$LL22@zipFileExi:
	mov	al, BYTE PTR [edx]
	inc	edx
	test	al, al
	jne	SHORT $LL22@zipFileExi
	mov	al, BYTE PTR [esi+ecx-1]
	sub	edx, ebx
	pop	ebx
	mov	BYTE PTR _name$[esp+edx+267], al

; 637  :     }

	jmp	SHORT $LN3@zipFileExi
$LN2@zipFileExi:

; 638  :     else {
; 639  :         strcpy(name, fileName);

	lea	edx, DWORD PTR _name$[esp+268]
	sub	edx, ecx
	npad	2
$LL9@zipFileExi:
	mov	al, BYTE PTR [ecx]
	lea	ecx, DWORD PTR [ecx+1]
	mov	BYTE PTR [edx+ecx-1], al
	test	al, al
	jne	SHORT $LL9@zipFileExi
$LN3@zipFileExi:

; 640  :     }
; 641  : 
; 642  :     zip = unzOpen(zipName);

	push	edi
	call	_unzOpen
	mov	edi, eax
	add	esp, 4

; 643  :     if (!zip) {

	test	edi, edi
	je	SHORT $LN16@zipFileExi

; 644  :         return 0;
; 645  :     }
; 646  : 
; 647  : #ifdef __APPLE__
; 648  :     // Most OS X installs are on a case-insensitive FS
; 649  :     if (unzLocateFile(zip, name, 2) == UNZ_END_OF_LIST_OF_FILE) {
; 650  : #else
; 651  :     if (unzLocateFile(zip, name, 1) == UNZ_END_OF_LIST_OF_FILE) {

	push	1
	lea	eax, DWORD PTR _name$[esp+272]
	push	eax
	push	edi
	call	_unzLocateFile
	push	edi
	mov	esi, eax
	call	_unzClose
	add	esp, 16					; 00000010H
	cmp	esi, -100				; ffffff9cH
	je	SHORT $LN16@zipFileExi

; 652  : #endif
; 653  :         unzClose(zip);
; 654  :         return 0;
; 655  :     }else{
; 656  :         unzClose(zip);
; 657  :         return 1;

	pop	edi
	mov	eax, 1

; 658  :     }
; 659  : }

	pop	esi
	mov	ecx, DWORD PTR __$ArrayPad$[esp+260]
	xor	ecx, esp
	call	@__security_check_cookie@4
	add	esp, 260				; 00000104H
	ret	0
$LN16@zipFileExi:
	mov	ecx, DWORD PTR __$ArrayPad$[esp+268]
	xor	eax, eax
	pop	edi
	pop	esi
	xor	ecx, esp
	call	@__security_check_cookie@4
	add	esp, 260				; 00000104H
	ret	0
_zipFileExists ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\utils\ziphelper.c
;	COMDAT _zipSaveFile
_TEXT	SEGMENT
tv392 = -48						; size = 4
_buffer$GSCopy$1$ = -44					; size = 4
_zi$ = -40						; size = 36
__$ArrayPad$ = -4					; size = 4
_zipName$ = 8						; size = 4
_fileName$ = 12						; size = 4
_append$ = 16						; size = 4
_buffer$ = 20						; size = 4
_size$ = 24						; size = 4
_zipSaveFile PROC					; COMDAT

; 549  : {

	sub	esp, 48					; 00000030H
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, esp
	mov	DWORD PTR __$ArrayPad$[esp+48], eax
	push	ebx
	mov	ebx, DWORD PTR _zipName$[esp+48]
	push	ebp
	mov	ebp, DWORD PTR _buffer$[esp+52]
	push	esi
	mov	esi, DWORD PTR _append$[esp+56]
	push	edi
	mov	edi, DWORD PTR _fileName$[esp+60]

; 550  :     zipFile zip;
; 551  :     zip_fileinfo zi;
; 552  :     int err;
; 553  : 
; 554  :     if (strncmp(zipName, "mem", 3) == 0) {

	push	3
	push	OFFSET ??_C@_03IJLIBDBM@mem@
	push	ebx
	mov	DWORD PTR _buffer$GSCopy$1$[esp+76], ebp
	call	_strncmp
	add	esp, 12					; 0000000cH
	test	eax, eax
	jne	$LN2@zipSaveFil

; 196  :     MemZipFile* memZipFile = memZipFileFind(zipName);

	push	ebx
	call	_memZipFileFind
	add	esp, 4
	mov	DWORD PTR tv392[esp+64], eax

; 197  :     MemFile* memFile;
; 198  : 
; 199  :     if (!append)

	test	esi, esi
	jne	SHORT $LN7@zipSaveFil

; 200  :     {
; 201  :         memZipFileDestroy(memZipFile);

	push	eax
	call	_memZipFileDestroy
	mov	eax, DWORD PTR tv392[esp+68]
	add	esp, 4
$LN7@zipSaveFil:

; 202  :         memZipFile = NULL;
; 203  :     }
; 204  : 
; 205  :     if (memZipFile == NULL)

	xor	ebp, ebp
	test	esi, esi
	cmovne	ebp, eax
	test	ebp, ebp
	jne	SHORT $LN32@zipSaveFil

; 151  :     for (i = 0; i < memZipFileCount; i++)

	mov	eax, DWORD PTR _memZipFileCount
	xor	esi, esi
	test	eax, eax
	jle	SHORT $LN10@zipSaveFil
	mov	ecx, DWORD PTR _memZipFiles
$LL16@zipSaveFil:

; 152  :     {
; 153  :         if (memZipFiles[i] == NULL)

	cmp	DWORD PTR [ecx+esi*4], 0
	je	SHORT $LN23@zipSaveFil

; 151  :     for (i = 0; i < memZipFileCount; i++)

	inc	esi
	cmp	esi, eax
	jl	SHORT $LL16@zipSaveFil
$LN10@zipSaveFil:
	pop	edi

; 573  : 
; 574  :     return err >= 0;
; 575  : }

	pop	esi
	pop	ebp
	xor	eax, eax
	pop	ebx
	mov	ecx, DWORD PTR __$ArrayPad$[esp+48]
	xor	ecx, esp
	call	@__security_check_cookie@4
	add	esp, 48					; 00000030H
	ret	0
$LN23@zipSaveFil:

; 155  :             memZipFiles[i] = malloc(sizeof(MemZipFile));

	push	292					; 00000124H
	call	_malloc
	mov	ecx, DWORD PTR _memZipFiles
	add	esp, 4
	lea	ebp, DWORD PTR [ecx+esi*4]
	mov	DWORD PTR [ebp], eax
$LL19@zipSaveFil:

; 156  :             strcpy(memZipFiles[i]->zipName, zipName);

	mov	cl, BYTE PTR [ebx]
	lea	ebx, DWORD PTR [ebx+1]
	mov	BYTE PTR [eax], cl
	lea	eax, DWORD PTR [eax+1]
	test	cl, cl
	jne	SHORT $LL19@zipSaveFil

; 157  :             memZipFiles[i]->count = 0;

	mov	eax, DWORD PTR [ebp]
	mov	DWORD PTR [eax+288], 0

; 158  :             return memZipFiles[i];

	mov	ebp, DWORD PTR [ebp]

; 210  :     if (memZipFile == NULL || memZipFile->count == MAX_FILES_IN_ZIP)

	test	ebp, ebp
	je	SHORT $LN10@zipSaveFil
$LN32@zipSaveFil:
	cmp	DWORD PTR [ebp+288], 64			; 00000040H
	je	SHORT $LN10@zipSaveFil

; 211  :     {
; 212  :         return 0;
; 213  :     }
; 214  :     
; 215  :     memFile = malloc(sizeof(MemFile));

	push	40					; 00000028H
	call	_malloc

; 216  :     memFile->buffer = malloc(size);

	mov	esi, DWORD PTR _size$[esp+64]
	mov	ebx, eax
	push	esi
	call	_malloc

; 217  :     memcpy(memFile->buffer, buffer, size);

	push	esi
	push	DWORD PTR _buffer$GSCopy$1$[esp+76]
	mov	DWORD PTR [ebx+36], eax
	push	eax
	call	_memcpy
	mov	ecx, ebx

; 218  :     memFile->size = size;

	mov	DWORD PTR [ebx+32], esi
	add	esp, 20					; 00000014H
	sub	ecx, edi
$LL12@zipSaveFil:

; 219  :     strcpy(memFile->filename, filename);

	mov	al, BYTE PTR [edi]
	lea	edi, DWORD PTR [edi+1]
	mov	BYTE PTR [ecx+edi-1], al
	test	al, al
	jne	SHORT $LL12@zipSaveFil

; 220  : 
; 221  :     memZipFile->memFiles[memZipFile->count++] = memFile;

	mov	eax, DWORD PTR [ebp+288]
	pop	edi

; 573  : 
; 574  :     return err >= 0;
; 575  : }

	pop	esi

; 221  :     memZipFile->memFiles[memZipFile->count++] = memFile;

	mov	DWORD PTR [ebp+eax*4+32], ebx

; 222  : 
; 223  :     return 1;

	mov	eax, 1
	inc	DWORD PTR [ebp+288]

; 573  : 
; 574  :     return err >= 0;
; 575  : }

	pop	ebp
	pop	ebx
	mov	ecx, DWORD PTR __$ArrayPad$[esp+48]
	xor	ecx, esp
	call	@__security_check_cookie@4
	add	esp, 48					; 00000030H
	ret	0
$LN2@zipSaveFil:

; 555  :         return memFileSave(zipName, fileName, append, buffer, size);
; 556  :     }
; 557  : 
; 558  :     zip = zipOpen(zipName, append ? 2 : 0);

	neg	esi
	sbb	esi, esi
	and	esi, 2
	push	esi
	push	ebx
	call	_zipOpen
	mov	ebx, eax
	add	esp, 8

; 559  :     if (zip == NULL) {

	test	ebx, ebx
	je	$LN10@zipSaveFil

; 560  :         return 0;
; 561  :     }
; 562  : 
; 563  :     memset(&zi, 0, sizeof(zi));
; 564  : 
; 565  :     err = zipOpenNewFileInZip(zip, fileName, &zi,

	push	-1
	push	8
	push	0
	push	0
	push	0
	push	0
	push	0
	lea	eax, DWORD PTR _zi$[esp+92]
	mov	DWORD PTR _zi$[esp+124], 0
	push	eax
	xorps	xmm0, xmm0
	push	edi
	push	ebx
	movups	XMMWORD PTR _zi$[esp+104], xmm0
	movups	XMMWORD PTR _zi$[esp+120], xmm0
	call	_zipOpenNewFileInZip
	mov	esi, eax
	add	esp, 40					; 00000028H

; 566  :                               NULL, 0, NULL, 0, NULL,
; 567  :                               Z_DEFLATED, Z_DEFAULT_COMPRESSION);
; 568  :     if (err == ZIP_OK) {

	test	esi, esi
	jne	SHORT $LN4@zipSaveFil

; 569  :         err = zipWriteInFileInZip(zip, buffer, size);

	push	DWORD PTR _size$[esp+60]
	push	ebp
	push	ebx
	call	_zipWriteInFileInZip
	add	esp, 12					; 0000000cH
	mov	esi, eax
$LN4@zipSaveFil:

; 570  :     }
; 571  : 
; 572  :     zipClose(zip, NULL);

	push	0
	push	ebx
	call	_zipClose

; 573  : 
; 574  :     return err >= 0;
; 575  : }

	mov	ecx, DWORD PTR __$ArrayPad$[esp+72]
	add	esp, 8
	not	esi
	shr	esi, 31					; 0000001fH
	mov	eax, esi
	pop	edi
	pop	esi
	pop	ebp
	pop	ebx
	xor	ecx, esp
	call	@__security_check_cookie@4
	add	esp, 48					; 00000030H
	ret	0
_zipSaveFile ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\utils\ziphelper.c
;	COMDAT _zipLoadFile
_TEXT	SEGMENT
_zipName$ = 8						; size = 4
_fileName$ = 12						; size = 4
_size$ = 16						; size = 4
_zipLoadFile PROC					; COMDAT

; 491  : {

	push	esi

; 492  :     if (strncmp(zipName, "mem", 3) == 0) {

	mov	esi, DWORD PTR _zipName$[esp]
	push	edi
	push	3
	push	OFFSET ??_C@_03IJLIBDBM@mem@
	push	esi
	call	_strncmp
	add	esp, 12					; 0000000cH
	test	eax, eax
	jne	$LN2@zipLoadFil

; 182  :     MemFile* memFile = memFileFindInZip(memZipFileFind(zipName), filename);

	push	ebx
	push	ebp
	push	esi
	call	_memZipFileFind
	add	esp, 4

; 166  :     if (memZipFile != NULL)

	test	eax, eax
	je	SHORT $LN7@zipLoadFil

; 167  :     {
; 168  :         int i;
; 169  :         for (i = 0; i < memZipFile->count; i++)

	mov	ebp, DWORD PTR [eax+288]
	xor	esi, esi
	test	ebp, ebp
	jle	SHORT $LN7@zipLoadFil
	lea	edi, DWORD PTR [eax+32]
	npad	4
$LL12@zipLoadFil:

; 170  :         {
; 171  :             if (strcmp(memZipFile->memFiles[i]->filename, filename) == 0)

	mov	ebx, DWORD PTR [edi]
	mov	eax, ebx
	mov	ecx, DWORD PTR _fileName$[esp+12]
$LL21@zipLoadFil:
	mov	dl, BYTE PTR [eax]
	cmp	dl, BYTE PTR [ecx]
	jne	SHORT $LN22@zipLoadFil
	test	dl, dl
	je	SHORT $LN23@zipLoadFil
	mov	dl, BYTE PTR [eax+1]
	cmp	dl, BYTE PTR [ecx+1]
	jne	SHORT $LN22@zipLoadFil
	add	eax, 2
	add	ecx, 2
	test	dl, dl
	jne	SHORT $LL21@zipLoadFil
$LN23@zipLoadFil:
	xor	eax, eax
	jmp	SHORT $LN24@zipLoadFil
$LN22@zipLoadFil:
	sbb	eax, eax
	or	eax, 1
$LN24@zipLoadFil:
	test	eax, eax
	je	SHORT $LN17@zipLoadFil

; 167  :     {
; 168  :         int i;
; 169  :         for (i = 0; i < memZipFile->count; i++)

	inc	esi
	add	edi, 4
	cmp	esi, ebp
	jl	SHORT $LL12@zipLoadFil
$LN7@zipLoadFil:

; 493  :         return memFileLoad(zipName, fileName, size);

	mov	ecx, DWORD PTR _size$[esp+12]

; 191  :     return NULL;

	xor	esi, esi

; 493  :         return memFileLoad(zipName, fileName, size);

	pop	ebp

; 191  :     return NULL;

	xor	eax, eax

; 493  :         return memFileLoad(zipName, fileName, size);

	pop	ebx
	mov	DWORD PTR [ecx], eax
	mov	eax, esi
	pop	edi

; 499  :     }
; 500  : }

	pop	esi
	ret	0
$LN17@zipLoadFil:

; 183  :     if (memFile != NULL && memFile->size > 0)

	test	ebx, ebx
	je	SHORT $LN7@zipLoadFil
	mov	eax, DWORD PTR [ebx+32]
	test	eax, eax
	jle	SHORT $LN7@zipLoadFil

; 184  :     {
; 185  :         void* buffer = malloc(memFile->size);

	push	eax
	call	_malloc

; 186  :         memcpy(buffer, memFile->buffer, memFile->size);

	push	DWORD PTR [ebx+32]
	mov	esi, eax
	push	DWORD PTR [ebx+36]
	push	esi
	call	_memcpy

; 187  :         *size = memFile->size;
; 188  :         return buffer;

	mov	eax, DWORD PTR [ebx+32]
	add	esp, 16					; 00000010H

; 493  :         return memFileLoad(zipName, fileName, size);

	mov	ecx, DWORD PTR _size$[esp+12]
	pop	ebp
	pop	ebx
	mov	DWORD PTR [ecx], eax
	mov	eax, esi
	pop	edi

; 499  :     }
; 500  : }

	pop	esi
	ret	0
$LN2@zipLoadFil:

; 494  :     }
; 495  :     if( cacheData != NULL && *cacheFile != '\0' && 0==strcmp(cacheFile, zipName) ) {

	mov	edi, DWORD PTR _cacheData
	test	edi, edi
	je	SHORT $LN3@zipLoadFil
	cmp	BYTE PTR _cacheFile, 0
	je	SHORT $LN3@zipLoadFil
	mov	ecx, esi
	mov	eax, OFFSET _cacheFile
$LL25@zipLoadFil:
	mov	dl, BYTE PTR [eax]
	cmp	dl, BYTE PTR [ecx]
	jne	SHORT $LN26@zipLoadFil
	test	dl, dl
	je	SHORT $LN27@zipLoadFil
	mov	dl, BYTE PTR [eax+1]
	cmp	dl, BYTE PTR [ecx+1]
	jne	SHORT $LN26@zipLoadFil
	add	eax, 2
	add	ecx, 2
	test	dl, dl
	jne	SHORT $LL25@zipLoadFil
$LN27@zipLoadFil:
	xor	eax, eax
	jmp	SHORT $LN28@zipLoadFil
$LN26@zipLoadFil:
	sbb	eax, eax
	or	eax, 1
$LN28@zipLoadFil:
	test	eax, eax
	jne	SHORT $LN3@zipLoadFil

; 496  :         return _zipLoadFile(cacheData, fileName, size, &cacheFilefunc);

	push	OFFSET _cacheFilefunc
	push	DWORD PTR _size$[esp+8]
	push	DWORD PTR _fileName$[esp+12]
	push	edi

; 499  :     }
; 500  : }

	call	__zipLoadFile
	add	esp, 16					; 00000010H
	pop	edi
	pop	esi
	ret	0
$LN3@zipLoadFil:

; 497  :     }else{
; 498  :         return _zipLoadFile(zipName, fileName, size, NULL);

	push	0
	push	DWORD PTR _size$[esp+8]
	push	DWORD PTR _fileName$[esp+12]
	push	esi

; 499  :     }
; 500  : }

	call	__zipLoadFile
	add	esp, 16					; 00000010H
	pop	edi
	pop	esi
	ret	0
_zipLoadFile ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\utils\ziphelper.c
;	COMDAT _zipCacheReadOnlyZip
_TEXT	SEGMENT
_zipName$ = 8						; size = 4
_zipCacheReadOnlyZip PROC				; COMDAT

; 503  : {

	push	esi

; 504  :     if (zipName != NULL && strncmp(zipName, "mem", 3) == 0) {

	mov	esi, DWORD PTR _zipName$[esp]
	test	esi, esi
	je	SHORT $LN2@zipCacheRe
	push	3
	push	OFFSET ??_C@_03IJLIBDBM@mem@
	push	esi
	call	_strncmp
	add	esp, 12					; 0000000cH
	test	eax, eax
	je	$LN5@zipCacheRe
$LN2@zipCacheRe:

; 505  :         return;
; 506  :     }
; 507  : 
; 508  :     *cacheFile = '\0';
; 509  :     if( cacheData != NULL ) {

	mov	eax, DWORD PTR _cacheData
	mov	BYTE PTR _cacheFile, 0
	test	eax, eax
	je	SHORT $LN3@zipCacheRe

; 510  :         free(cacheData);

	push	eax
	call	_free

; 511  :         cacheData = NULL;
; 512  :         free_fopen_memfunc(&cacheFilefunc);

	push	OFFSET _cacheFilefunc
	mov	DWORD PTR _cacheData, 0
	call	_free_fopen_memfunc
	add	esp, 8
$LN3@zipCacheRe:

; 513  :     }
; 514  :     if( zipName != NULL ) {

	test	esi, esi
	je	$LN5@zipCacheRe

; 515  :         FILE *file;
; 516  :         file = fopen(zipName, "rb");

	push	edi
	push	OFFSET ??_C@_02JDPG@rb@
	push	esi
	call	_fopen
	mov	edi, eax
	add	esp, 8

; 517  :         if( file != NULL ) {

	test	edi, edi
	je	SHORT $LN15@zipCacheRe

; 518  :             unsigned int filesize;
; 519  :             fseek(file, 0, SEEK_END);

	push	ebx
	push	2
	push	0
	push	edi
	call	_fseek

; 520  :             filesize = ftell(file);

	push	edi
	call	_ftell
	mov	ebx, eax

; 521  :             fill_fopen_memfunc(&cacheFilefunc, filesize);

	push	ebx
	push	OFFSET _cacheFilefunc
	call	_fill_fopen_memfunc

; 522  :             fseek(file, 0, SEEK_SET);

	push	0
	push	0
	push	edi
	call	_fseek

; 523  :             cacheData = malloc(filesize);

	push	ebx
	call	_malloc
	add	esp, 40					; 00000028H
	mov	DWORD PTR _cacheData, eax

; 524  :             if( cacheData != NULL ) {

	test	eax, eax
	je	SHORT $LN7@zipCacheRe

; 525  :                 size_t size = fread(cacheData, 1, filesize, file);

	push	edi
	push	ebx
	push	1
	push	eax
	call	_fread
	add	esp, 16					; 00000010H

; 526  :                 if( size == filesize ) {

	cmp	eax, ebx
	jne	SHORT $LN7@zipCacheRe

; 527  :                     strcpy(cacheFile, zipName);

	mov	ecx, OFFSET _cacheFile
	sub	ecx, esi
	npad	3
$LL11@zipCacheRe:
	mov	al, BYTE PTR [esi]
	lea	esi, DWORD PTR [esi+1]
	mov	BYTE PTR [ecx+esi-1], al
	test	al, al
	jne	SHORT $LL11@zipCacheRe
$LN7@zipCacheRe:

; 528  :                 }
; 529  :             }
; 530  :             fclose(file);

	push	edi
	call	_fclose
	add	esp, 4
	pop	ebx
$LN15@zipCacheRe:
	pop	edi
$LN5@zipCacheRe:
	pop	esi

; 531  :         }
; 532  :     }
; 533  : }

	ret	0
_zipCacheReadOnlyZip ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\utils\ziphelper.c
;	COMDAT _memZipFileSystemDestroy
_TEXT	SEGMENT
_memZipFileSystemDestroy PROC				; COMDAT

; 117  :     int i;
; 118  : 
; 119  :     if (memZipFileCount == 0)

	mov	ecx, DWORD PTR _memZipFileCount
	test	ecx, ecx
	je	$LN1@memZipFile

; 120  :     {
; 121  :         return;
; 122  :     }
; 123  : 
; 124  :     for (i = 0; i < memZipFileCount; i++)

	mov	edx, DWORD PTR _memZipFiles
	push	ebp
	xor	ebp, ebp
	test	ecx, ecx
	jle	SHORT $LN3@memZipFile
	push	ebx
	push	esi
	push	edi
	npad	2
$LL4@memZipFile:

; 125  :     {
; 126  :         memZipFileDestroy(memZipFiles[i]);

	mov	ebx, DWORD PTR [edx+ebp*4]

; 83   :     if (memZipFile == NULL)

	test	ebx, ebx
	je	SHORT $LN2@memZipFile

; 84   :     {
; 85   :         return;
; 86   :     }
; 87   : 
; 88   :     // Remove node
; 89   :     for (i = 0; i < memZipFileCount; i++)

	xor	eax, eax
	test	ecx, ecx
	jle	SHORT $LN9@memZipFile
	npad	3
$LL24@memZipFile:

; 90   :     {
; 91   :         if (memZipFiles[i] == memZipFile)

	cmp	DWORD PTR [edx+eax*4], ebx
	jne	SHORT $LN34@memZipFile

; 92   :         {
; 93   :             memZipFiles[i] = NULL;

	mov	DWORD PTR [edx+eax*4], 0
$LN34@memZipFile:

; 84   :     {
; 85   :         return;
; 86   :     }
; 87   : 
; 88   :     // Remove node
; 89   :     for (i = 0; i < memZipFileCount; i++)

	inc	eax
	cmp	eax, ecx
	jl	SHORT $LL24@memZipFile
$LN9@memZipFile:

; 94   :         }
; 95   :     }
; 96   : 
; 97   :     // Delete file contents
; 98   :     for (i = 0; i < memZipFile->count; i++)

	xor	edi, edi
	cmp	DWORD PTR [ebx+288], edi
	jle	SHORT $LN12@memZipFile
	lea	esi, DWORD PTR [ebx+32]
	npad	2
$LL13@memZipFile:

; 99   :     {
; 100  :         if (memZipFile->memFiles[i]->buffer != NULL)

	mov	eax, DWORD PTR [esi]
	mov	ecx, DWORD PTR [eax+36]
	test	ecx, ecx
	je	SHORT $LN16@memZipFile

; 101  :         {
; 102  :             free(memZipFile->memFiles[i]->buffer);

	push	ecx
	call	_free
	mov	eax, DWORD PTR [esi]
	add	esp, 4
$LN16@memZipFile:

; 103  :         }
; 104  :         free(memZipFile->memFiles[i]);

	push	eax
	call	_free
	inc	edi
	add	esp, 4
	add	esi, 4
	cmp	edi, DWORD PTR [ebx+288]
	jl	SHORT $LL13@memZipFile
$LN12@memZipFile:

; 105  :     }
; 106  :     free(memZipFile);

	push	ebx
	call	_free
	mov	ecx, DWORD PTR _memZipFileCount
	add	esp, 4
	mov	edx, DWORD PTR _memZipFiles
$LN2@memZipFile:

; 120  :     {
; 121  :         return;
; 122  :     }
; 123  : 
; 124  :     for (i = 0; i < memZipFileCount; i++)

	inc	ebp
	cmp	ebp, ecx
	jl	SHORT $LL4@memZipFile
	pop	edi
	pop	esi
	pop	ebx
$LN3@memZipFile:

; 127  :     }
; 128  :     free(memZipFiles);

	push	edx
	call	_free
	add	esp, 4

; 129  : 
; 130  :     memZipFileCount = 0;

	mov	DWORD PTR _memZipFileCount, 0
	pop	ebp
$LN1@memZipFile:

; 131  : }

	ret	0
_memZipFileSystemDestroy ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\repo\msx-master\msx\bluemsx-dpi\src\utils\ziphelper.c
;	COMDAT _memZipFileSystemCreate
_TEXT	SEGMENT
_maxFiles$ = 8						; size = 4
_memZipFileSystemCreate PROC				; COMDAT

; 111  :     memZipFileCount = maxFiles;

	mov	eax, DWORD PTR _maxFiles$[esp-4]

; 112  :     memZipFiles = (MemZipFile**) calloc(memZipFileCount, sizeof(MemZipFile*));

	push	4
	push	eax
	mov	DWORD PTR _memZipFileCount, eax
	call	_calloc
	add	esp, 8
	mov	DWORD PTR _memZipFiles, eax

; 113  : }

	ret	0
_memZipFileSystemCreate ENDP
_TEXT	ENDS
END
